quarkus-qe/quarkus-test-suite

- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/DevModeOpenTelemetryIT.java
backports https://github.com/quarkus-qe/quarkus-test-suite/pull/1437
> [3.2] Fix flaky DevModeOpenTelemetryIT especially on Windows with waiting till live reload has finished

- build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/AbstractAnalyticsIT.java
On Windows, any test that runs after `io.quarkus.ts.buildtimeanalytics.AbstractAnalyticsIT#getPomDependencies` failes for `pom.xml` is used by other process. We need to close the reader properly. Tested, for failure please see respective Jenkins job.
> Fix some build-time analytics failures on Windows by closing file reader

- lifecycle-application/src/test/java/io/quarkus/ts/lifecycle/HelloMainTest.java
AFAICT this is only issue with Cygwin - https://github.com/quarkusio/quarkus/issues/31765, which we are not using anymore to run TS.
> Enable HelloMainTest on Windows as we dont use Cygwin

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
Things are slower on Windows, I can see logged `Caused by: java.net.ConnectException: Connection refused: connect` right after restart before app is ready, I think it also has implication as it is never stopped even though tests already finished.
> `QuarkusCliCreateJvmApplicationIT#shouldAddAndRemoveExtensions` needs to wait till app is ready after restart

- security/oidc-client-mutual-tls/src/test/java/io/quarkus/ts/security/oidcclient/mtls/JksOidcMtlsIT.java
- security/oidc-client-mutual-tls/src/test/java/io/quarkus/ts/security/oidcclient/mtls/LocalHostKeycloakContainerManagedResourceBuilder.java
- security/oidc-client-mutual-tls/src/test/java/io/quarkus/ts/security/oidcclient/mtls/MutualTlsKeycloakService.java
- security/oidc-client-mutual-tls/src/test/java/io/quarkus/ts/security/oidcclient/mtls/Pkcs12OidcMtlsIT.java
I wrote README how to re-generated these certificates, but I am not sure how good one, as couldn't automate it precisely yet. It will take little effort to every time regenerate all the certificates, while this port forwarding is quick and straightforward. Let's take it as a hotfix and come back if we have a time in the future.
> Forward OIDC mTLS container on Windows to localhost as certificates are generated for localhost

- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/OpenApiStoreSchemaIT.java
- security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/OpenApiStoreSchemaIT.java
I didn't see failing test for this, but we should close closeable and `IOUtils` are not doing it.
> Close FileReader when we are done in OpenAPI tests

- pom.xml
Backports https://github.com/quarkus-qe/quarkus-test-suite/pull/1450, I need this for Infinispan fixes that will come after this (but it will only run one module instead of all of them, so quicker). Fixes issue with loading resources to Infinispan container.
> [3.2] Backport 'Bump quarkus.qe.framework.version from 1.3.0.Beta27 to 1.3.0.Beta28'

- external-applications/pom.xml
This change fixes execution of External app module on Windows, I still can see maven plugin skipped
```
[INFO] --- quarkus:3.2.6.Final-redhat-00001:build (build) @ external-applications ---
[INFO] Skipping Quarkus build
```
However I won't see it failed as before:
```
Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:3.3.0:jar (default-jar) on project external-applications: You have to use a classifier to attach supplemental artifacts to the project instead of replacing them.
```
Previously, if you run command like this 
```
mvn clean validate compile test package verify -V -B -fae -Dlog.nocolor=true -P root-modules -Dquarkus-plugin.version=3.2.6.Final-redhat-00001 -Dquarkus.platform.version=3.2.6.Final-redhat-00001 -Dquarkus.platform.artifact-id="quarkus-bom" …
```
> Fix External apps module execution on Windows

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliVersionIT.java
Not sure how to create 999-SNAPSHOT CLI on Windows and I don't want to investigate it now. Let's disable failing test and work on opened issue when priorities decide so.
> Disable QuarkusCLIVersionIT on Windows when tested with Quarkus snapshot as we don't have snapshot CLI on Windows

- properties/src/test/java/io/quarkus/ts/properties/bulk/ConfigValueIT.java
Switch to DefaultValuesConfigSource after quarkusio/quarkus#35322
> Switch to DefaultValuesConfigSource after quarkusio/quarkus#35322

- env-info/src/main/java/io/quarkus/ts/envinfo/OsJvmEnvInfoLogger.java
- http/http-static/src/test/java/io/quarkus/ts/httpstatic/LargeStaticResourceIT.java
- qute/reactive/src/main/java/io/quarkus/ts/qute/Application.java
- qute/synchronous/src/main/java/io/quarkus/ts/qute/Application.java
Hi, this PR updating some deprecated method. To be prepared to JDK 21.
URL constructors was deprecated in JDK 20. Now is possible to create URL from URI.
`Runtime.getRuntime().exec(String)` was deprecated in JDK 18 and is recommended to use `Runtime.getRuntime().exec(String[])`.
> Update deprecated URL and Runtime methods

- messaging/infinispan-grpc-kafka/src/main/resources/application.properties
SNI is now required by default when SSL is used, see https://github.com/quarkusio/quarkus/pull/36445. Fixes one daily failure.
> Fix gRPC Infinispan tests by setting SNI as it is required when SSL is used after the latest Infinispan bump

- .github/workflows/daily.yaml
Change CI definition from latest mandrel version to specific version (23.0.1.2-Final) as the newest one was built only by JDK 21.
> Change mandrel version in CI

- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DevModeKafkaStreamIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DevModeRedPandaDevServiceUserExperienceIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DevModeStrimziKafkaStreamIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DisabledOnWindowsWithRhbqCondition.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/KafkaGratefulShutdownIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/SslAlertMonitorIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/StrimziKafkaStreamIT.java
Please see https://issues.redhat.com/browse/QUARKUS-3434.
This commit is not intended for the main branch.
> [3.2] Disable Kafka Streams tests when running on Windows with RHBQ due to QUARKUS-3434

- messaging/kafka-confluent-avro-reactive-messaging/pom.xml
- pom.xml
Bump kafka-avro-serializer to 7.5.1, add jackson-dataformat-csv dependency
See https://github.com/quarkusio/quarkus/issues/36372 for details
> Bump kafka-avro-serializer to 7.5.1, add jackson-dataformat-csv dependency

- build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/CliDevModeIT.java
- http/http-advanced-reactive/src/main/resources/application.properties
- http/http-advanced/src/main/resources/application.properties
- monitoring/opentelemetry-reactive/src/main/resources/application.properties
- monitoring/opentelemetry/src/main/resources/application.properties
- monitoring/opentracing-reactive-grpc/src/main/resources/application.properties
Solves issue https://github.com/quarkus-qe/quarkus-test-suite/issues/1373
> Use single HTTP server for gRPC services

- build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/CliDevModeIT.java
- http/http-advanced-reactive/src/main/resources/application.properties
- http/http-advanced/src/main/resources/application.properties
- monitoring/opentelemetry-reactive/src/main/resources/application.properties
- monitoring/opentelemetry/src/main/resources/application.properties
- monitoring/opentracing-reactive-grpc/src/main/resources/application.properties
backports https://github.com/quarkus-qe/quarkus-test-suite/pull/1472
> [3.2] Backports 'Use single HTTP server for gRPC services'

- infinispan-client/src/main/resources/application.properties
- infinispan-client/src/test/java/io/quarkus/ts/infinispan/client/OperatorOpenShiftInfinispanCountersIT.java
- infinispan-client/src/test/java/io/quarkus/ts/infinispan/client/OperatorOpenShiftInfinispanErrorSvcListener.java
- infinispan-client/src/test/resources/META-INF/services/io.quarkus.test.bootstrap.ServiceListener
- disables Infinispan client SNI host name validation as I didn't manage from test host to find out correct hostname that will be resolved inside cluster. Test with Infinispan client runs in different namespace then where operator is installed. We already test validation here https://github.com/quarkus-qe/quarkus-test-suite/pull/1473. I'm happy to try again if there are suggestions (or time)
- we had problem that when service failed to start as when validation is enabled, cluster is never deleted, now I'm adding listener that will take care of it together with https://github.com/quarkus-qe/quarkus-test-framework/pull/936
- service `one` is restarted and yamls that create cluster are re-applied again. AFAICT it is not causing issue, but at least it is whole lot of unnecessary commands. …
> Fix Infinispan client operator tests - disable hostname SNI validation and ensure cluster deleted on error

- http/vertx-web-client/src/test/java/io/quarkus/ts/http/vertx/webclient/PureVertxHttpClientTest.java
- http/vertx/src/test/java/io/quarkus/ts/vertx/AbstractVertxIT.java
- security/vertx-jwt/src/test/java/io/quarkus/ts/security/vertx/AbstractCommonIT.java
closes : [Leaking Vertx and HttpClient](https://github.com/quarkus-qe/quarkus-test-suite/issues/1408)
> bug-fix : Closed Vert.x to Prevent Resource Leaks

- http/vertx-web-client/src/test/java/io/quarkus/ts/http/vertx/webclient/PureVertxHttpClientTest.java
- http/vertx-web-client/src/test/java/io/quarkus/ts/http/vertx/webclient/VertxWebClientIT.java
I was trying to find out why is `PureVertxHttpClientTest` suddenly failing https://github.com/quarkus-qe/quarkus-test-suite/pull/1489 on Windows as today there were changes https://github.com/quarkus-qe/quarkus-test-suite/pull/1474, however I can't see anything wrong about it. Most likely it seems like something related to OTEL exported implementation as sometimes I can see exceptions like these:
```
2023-10-26 16:51:02,325 ERROR [io.qua.ver.cor.run.VertxCoreRecorder] (vert.x-eventloop-thread-10) Uncaught exception received by Vert.x [Error Occurred After Shutdown]: java.lang.IllegalStateException: Client is closed
at io.vertx.core.http.impl.HttpClientImpl.checkClosed(HttpClientImpl.java:696)
at io.vertx.core.http.impl.HttpClientImpl.doRequest(HttpClientImpl.java:597)
at …
```
> Refactor PureVertxHttpClientTest

- http/rest-client-reactive/pom.xml
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/MalformedClient.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/MalformedClientResource.java
- http/rest-client-reactive/src/main/resources/modern.properties
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientIT.java
https://github.com/quarkusio/quarkus/issues/36257
https://issues.redhat.com/browse/QQE-254
> Cover bug with rest client hanging on malformed chunks

- http/rest-client-reactive/pom.xml
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/MalformedClient.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/MalformedClientResource.java
- http/rest-client-reactive/src/main/resources/modern.properties
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientIT.java
- lifecycle-application/pom.xml
Backports:
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1482
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1495 + disable the test for 3.2.6 and 3.2.7
> [3.2] Backports

- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/KafkaGratefulShutdownIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/LocalHostKafkaContainerManagedResourceBuilder.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/SslAlertMonitorIT.java
- messaging/kafka-streams-reactive-messaging/src/test/resources/kafka.grateful.shutdown.application.properties
Fixes failing tests on Windows. 
- Kafka SSL fix is of same sort as we did in other modules (certificate issue).
- Processing of incoming topics during graceful shutdown just seems slower on Windows, I can't explain it. I've refactored it to avoid restart before testing graceful shutdown because amount of time needed to wait before app was accepting incoming topics was enormous. I spent hours trying to findout some timeout or other reasons (tried readyness checks calling etc.) and I can't find a reason why is it slower.
> Fix Kafka Reactive Streams tests on Windows

- .github/mvn-settings.xml
Only use Google Mirror as mirror
We used to have other repositories but it is counter productive nowadays.
Also switch to the American mirror.
There's a good chance GitHub Actions are run in America.
> Only use Google Mirror as mirror

- http/vertx/src/test/java/io/quarkus/ts/vertx/OpenShiftUsingExtensionDockerBuildStrategyVertxIT.java
- sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/AbstractDatabaseHibernateReactiveIT.java
As Quarkus QuickStarts migrated to Quarkus 3 I see no problem to enable them.
For the databases, issue is not closed but apparently it solved by itself or somebody forget to link issue in PR. Didn't dig deeper to look when this was solved.
> Enable some disabled tests

- nosql-db/mongodb-reactive/src/test/resources/mongo-openshift-deployment-template.yml
- nosql-db/mongodb-reactive/src/test/resources/test.properties
- nosql-db/mongodb/src/test/resources/mongo-openshift-deployment-template.yml
- nosql-db/mongodb/src/test/resources/test.properties
- pom.xml
Official MongoDB Docker image requires read / write on `/data/db` directory and because it is not adapted to work with random user ID, this user doesn't have permission to edit `/data/db` by default and startup in OCP fails with `"DBException in initAndListen, terminating","attr":{"error":"IllegalOperation: Attempted to create a lock file on a read-only directory: /data/db"}}`.
I've considered using `pre` lifecycle hook to grant permissions to this file, but it also means to handle `entrypoint` ourselves. This PR proposes to use `emptyDir` volume to store `/data/db`. Storing this data on mounted volume is legit strategy explained https://hub.docker.com/_/mongo in the _Where to Store Data_ section.
Please note that in next PR I'll allow run MongoDB tests on Aarch64, I didn't forget about …
> Adapt OpenShift MongoDB tests to work with official Docker image

- nosql-db/mongodb-reactive/src/test/java/io/quarkus/ts/nosqldb/mongodb/reactive/OpenShiftMongoClientReactiveIT.java
- nosql-db/mongodb/src/test/java/io/quarkus/ts/nosqldb/mongodb/OpenShiftMongoClientIT.java
- pom.xml
closes: #1146
OSD ARM64 should use MongoDB image for platform ARM64, OS Linux and variant v8. I didn't find a way to specify platform in Pod object definition https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#Container and even though OSD is running on ARM64, I checked digest from `oc describe pod ...` and inspected it with 
`docker inspect manifest docker.io/library/mongo@sha256:0d8482aef8d58e787fcf8e5e4aa81440f0ff1d9017c63958584b22312da10937` - it was still amd64. Stuff like `docker pull arm64v8/mongo` suggested here https://hub.docker.com/r/arm64v8/mongo doesn't even work for me locally, let alone in OCP (you need to specify --platform).
Fun fact, it works on AMD64 architecture image anyway, but requirement is to use ARM64 specific image.
Please select the …
> Use Arm64 specific MongoDB image for OSD ARM

- spring/spring-web-reactive/src/test/resources/request-types.csv
- spring/spring-web/src/test/resources/request-types.csv
Enable checks that were disabled because of quarkusio/quarkus#36297
> Enable checks that were disabled because of quarkusio/quarkus/#36297

- security/keycloak-oidc-client-extended/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/ping/clients/TokenPropagationPongClient.java
- security/keycloak-oidc-client-extended/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/ping/filters/CustomTokenRequestFilter.java
- security/keycloak-oidc-client-extended/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/ping/filters/DefaultTokenRequestFilter.java
- security/keycloak-oidc-client-extended/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/principal/FilteredTokenResource.java
- security/keycloak-oidc-client-extended/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/principal/PrincipalResource.java
- security/keycloak-oidc-client-extended/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/principal/clients/TokenPropagationFilteredClient.java
- security/keycloak-oidc-client-extended/src/main/resources/application.properties
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/TokenPropagationFilterIT.java
- security/keycloak-oidc-client-reactive-extended/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/ping/clients/TokenPropagationPongClient.java
- security/keycloak-oidc-client-reactive-extended/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/ping/filters/CustomTokenRequestFilter.java
- security/keycloak-oidc-client-reactive-extended/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/ping/filters/DefaultTokenRequestFilter.java
- security/keycloak-oidc-client-reactive-extended/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/principal/FilteredTokenResource.java
- security/keycloak-oidc-client-reactive-extended/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/principal/PrincipalResource.java
- security/keycloak-oidc-client-reactive-extended/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/principal/clients/TokenPropagationFilteredClient.java
- security/keycloak-oidc-client-reactive-extended/src/main/resources/application.properties
- security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/TokenPropagationFilterIT.java
Test for https://github.com/quarkusio/quarkus/pull/36459 and https://github.com/quarkusio/quarkus/pull/36501
Implement test for selection of exchange OIDC client from multiple clients setup in one app.
> Implement test for OIDC filtered client

- .github/workflows/ci.yml
- monitoring/opentracing-reactive-grpc/src/test/java/io/quarkus/ts/monitoring/opentracing/reactive/grpc/ServerSentEventsTraceOpentracingIT.java
- pom.xml
> [3.2] Bump Quarkus to 3.2.8.Final

- http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/CookiesResource.java
- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/CookiesIT.java
Hi, this PR adding coverage for https://github.com/quarkusio/quarkus/issues/35582. Which fail jakarta cookies serialization when using native.
> Add test coverage for cookie serialization

- security/basic/src/test/java/io/quarkus/ts/openshift/security/basic/callback/AbstractSecurityCallbackTest.java
- security/basic/src/test/java/io/quarkus/ts/openshift/security/basic/callback/TestSecurityDisabledTest.java
- security/basic/src/test/java/io/quarkus/ts/openshift/security/basic/callback/TestSecurityEnabledTest.java
Related to issue https://github.com/quarkusio/quarkus/issues/36601.
Create test that tests when QuarkusSecurityTestExtension.beforeEach and afterEach executes `@TestSecurity` related behaviour.
> Add tests for QuarkusSecurityTestExtension callbacks

- pom.xml
Extensions are moved https://github.com/quarkusio/quarkus/pull/36602 but as for now, not released: 
- https://github.com/quarkiverse/quarkus-jaeger
- https://github.com/quarkiverse/quarkus-smallrye-opentracing
Usage in Build Time Analytics won't cause compilation failure for whole TS and I'll handle it in a separate PR - https://github.com/quarkus-qe/quarkus-test-suite/blob/main/build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/AnalyticsUtils.java#L95 as there it will be replacement with OTEL.
See: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.6
> Disable OpenTracing modules due to unreleased extensions in Quarkiverse

- build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/AnalyticsUtils.java
Fixes CI. https://github.com/quarkus-qe/quarkus-test-suite/pull/1519 follow-up
https://docs.quarkiverse.io/quarkus-smallrye-opentracing/dev/index.html says we should use OpenTelemetry. There is no deeper logic why this module used OpenTracing extension (like product requirement or RH ticket etc.), so here we can safely replace it with preferred version.
> Use OpenTelemetry extension in Build-tiime Analytics module as OpenTracing is deprecated and not released yet

- http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/SseEventUpdateResource.java
- http/http-advanced-reactive/src/main/resources/application.properties
- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/BaseHttpAdvancedReactiveIT.java
Adding the test based on scenario from https://github.com/quarkusio/quarkus/issues/35966. When developing it there are some issues so for now it's disabled (https://github.com/quarkusio/quarkus/issues/37033 and https://github.com/quarkusio/quarkus/issues/36986). 
Test should run on ocp as well but as it it disable I don't see much point to run it now.
Maybe it would be nice to add this scenario (with empty request) to http-advanced (non-reactive)? There is recent test for SSE but with this there will need be some small adjustment to it. WDYT?
> Add test for check SSE reactive empty response data

- README.md
- http/vertx-web-validation/pom.xml
- http/vertx-web-validation/src/main/java/io/quarkus/ts/vertx/web/validation/ShopResource.java
- http/vertx-web-validation/src/main/java/io/quarkus/ts/vertx/web/validation/ShoppingList.java
- http/vertx-web-validation/src/main/java/io/quarkus/ts/vertx/web/validation/ValidationHandlerOnRoutes.java
- http/vertx-web-validation/src/test/java/io/quarkus/ts/vertx/web/validation/OpenShiftVertxWebValidationIT.java
- http/vertx-web-validation/src/test/java/io/quarkus/ts/vertx/web/validation/VertxWebValidationIT.java
- pom.xml
This module covers the functionality of Vert.x web validation (https://vertx.io/docs/vertx-web-validation/java/), basically provides an API to build a handler that performs parsing and validation of the requests.
> Implement Vert.x web validation module

- .github/workflows/daily.yaml
- Currently native analytics daily build fails over OOM during native executable build, it started to happen after #1520 but I don't expect there is something wrong about OpenTelemetry, it might be larger than OpenTracing extension, but we definitely had problemw with memory in this module before: https://github.com/quarkus-qe/quarkus-test-suite/pull/1349
- I checked and Security profile takes least on average (~ 1 h 20 min) and root modules with spring takes up to for 4 h https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/6765196692/job/18392571155 but it jumps heavily with hours in difference). IMO we should spread load by moving Spring modules to Security modules
```
2023-11-16T03:28:34.0733613Z 03:28:34,030 INFO   - 4.44GB of memory (28.5% of 15.61GB system memory, set via …
```
> Fix daily native build by limiting Java heap used and spread load in matrix

- .github/workflows/daily.yaml
I thought the best way to mitigate Daily native image workflow running out of memory was to limit maximum Java heap used during the native image generation, but you can see that it didn't really help and I'm thinking GC just needs more. In both cases, we saw that we only allow GC small part of system memory. So either something else is using the memory (in which case we need to find it, like purge Docker images), or we simply don't use all that is at our disposal. The minimum memory suggested by Quarkus guide is 4 GB, so we can't go any lower.
See #1523
```
2023-11-19T03:40:09.2040280Z  - 3.56GB of memory (22.8% of 15.61GB system memory, set via '-Xmx4g')
2023-11-19T03:40:09.2040567Z  - 4 thread(s) (100.0% of 4 available processor(s), determined at start)
2023-11-19T03:40:09.2040833Z …
```
> Raise maximum Java heap used in Daily native image generation

- .github/workflows/ci.yml
- .github/workflows/daily.yaml
- .github/workflows/quarkus-snapshot.yaml
- README.md
- pom.xml
I don't know what to do about dailys - https://github.com/quarkus-qe/quarkus-test-suite/actions/workflows/daily.yaml it seems to me like either we need to introduce some cleaning of resources, or we need to spread load to other runners. I already had 2 experimental attempts #1529 and #1523 without success.
But what is worse, new addition is coming right into root modules where we fight resources: #1524
I propose to separate cache modules as that way we can easily couple them with other profiles in matrix. Native executable build time is very volatile, but building HTTP modules still takes less than root-modules. Sometimes significantly less, see https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/6819612674/job/18547594454 2 hours less.
I'll follow-up with Jenkins updates if …
> Move cache extensions from root modules to spread load evenly in matrix (especially as way to mitigate native build OOM in dailys)

- README.md
- cache/redis/pom.xml
- cache/redis/src/main/java/io/quarkus/ts/cache/redis/ApplicationScopeService.java
- cache/redis/src/main/java/io/quarkus/ts/cache/redis/BaseServiceWithCache.java
- cache/redis/src/main/java/io/quarkus/ts/cache/redis/RequestScopeService.java
- cache/redis/src/main/java/io/quarkus/ts/cache/redis/ServiceWithCacheResource.java
- cache/redis/src/main/java/io/quarkus/ts/cache/redis/TemplateCacheResource.java
- cache/redis/src/main/resources/templates/cached.html
- cache/redis/src/test/java/io/quarkus/ts/cache/redis/OpenShiftRedisCacheIT.java
- cache/redis/src/test/java/io/quarkus/ts/cache/redis/RedisCacheIT.java
- cache/redis/src/test/resources/test.properties
- pom.xml
Hi, this PR main objective was cover https://github.com/quarkusio/quarkus/issues/35680. As it was need standalone module I added some test which was overlapping between caffeine cache and spring cache.  Test to cover 35680 is `quteShouldThrowError`. Tested manually the redis cache with rest of the api and I saw it cached in Redis (used `redis-cli keys "*"`).
In standalone commit is update of Redis version (Quarkus dev mode using latest).  
> Add Redis cache tests and bump Redis version

- .github/workflows/daily.yaml
here I was wrong #1529, the issue is https://github.com/quarkusio/quarkus/issues/37142
> Lower maximum Java heap size in GH native daily to 5g

- http/http-advanced/src/main/java/io/quarkus/ts/http/advanced/GrpcClientInterceptors.java
- http/http-advanced/src/main/java/io/quarkus/ts/http/advanced/GrpcInterceptorsService.java
- http/http-advanced/src/main/java/io/quarkus/ts/http/advanced/GrpcResource.java
- http/http-advanced/src/main/java/io/quarkus/ts/http/advanced/GrpcServerInterceptors.java
- http/http-advanced/src/main/proto/helloworld.proto
- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/BaseHttpAdvancedIT.java
Add test coverage for https://github.com/quarkusio/quarkus/issues/21358. Testing both server and client interceptor. 
> Add test coverage for grpc GlobalInterceptor method annotation

- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/BaseHttpAdvancedReactiveIT.java
- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/BaseHttpAdvancedIT.java
- security/basic/src/test/java/io/quarkus/ts/openshift/security/basic/callback/TestSecurityDisabledTest.java
- security/basic/src/test/java/io/quarkus/ts/openshift/security/basic/callback/TestSecurityEnabledTest.java
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/TokenPropagationFilterIT.java
- security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/TokenPropagationFilterIT.java
Add tags for:
- TD: https://github.com/quarkus-qe/quarkus-test-suite/pull/1508 Ticket: https://issues.redhat.com/browse/QUARKUS-3685
- TD: https://github.com/quarkusio/quarkus/pull/36664 Ticket: https://issues.redhat.com/browse/QUARKUS-3672
- TD: https://github.com/quarkus-qe/quarkus-test-suite/pull/1515 Ticket: https://issues.redhat.com/browse/QUARKUS-3674
- TD: https://github.com/quarkus-qe/quarkus-test-suite/pull/1513 Ticket: https://issues.redhat.com/browse/QUARKUS-3680
> Add tag with JIRA ticket to 3.2.9 test coverage

- build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/CliProdModeNativeIT.java
- funqy/knative-events/pom.xml
- funqy/knative-events/src/test/java/io/quarkus/ts/funqy/knativeevents/FunqyKnEventsIT.java
see https://github.com/quarkusio/quarkus/issues/37142 for details
> Disable native tests for funqy due to upstream issue

- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/BaseHttpAdvancedReactiveIT.java
- http/http-advanced/src/main/java/io/quarkus/ts/http/advanced/GrpcClientInterceptors.java
- http/http-advanced/src/main/java/io/quarkus/ts/http/advanced/GrpcInterceptorsService.java
- http/http-advanced/src/main/java/io/quarkus/ts/http/advanced/GrpcResource.java
- http/http-advanced/src/main/java/io/quarkus/ts/http/advanced/GrpcServerInterceptors.java
- http/http-advanced/src/main/proto/helloworld.proto
- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/BaseHttpAdvancedIT.java
- security/basic/src/test/java/io/quarkus/ts/openshift/security/basic/callback/TestSecurityDisabledTest.java
- security/basic/src/test/java/io/quarkus/ts/openshift/security/basic/callback/TestSecurityEnabledTest.java
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/TokenPropagationFilterIT.java
- security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/TokenPropagationFilterIT.java
Backports:
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1538
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1531
> [3.2] Backport gRPC interceptor test coverage and tagging tests with JIRAs

- build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/AbstractAnalyticsIT.java
- pom.xml
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
- Bumps test framework to 1.3.0.Beta32.
- Works around https://github.com/quarkusio/quarkus/issues/37307 as now we have fixed version https://github.com/quarkus-qe/quarkus-test-framework/commit/f0cdc1f4d76489171fce234685b59bc05e64ddb5
> [3.2] Bump QE Test Framework to 1.3.0.Beta32 and workaround Quarkus CLI issues

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
[QUARKUS-3439](https://issues.redhat.com/browse/QUARKUS-3439) was resolved, so this PR enable the test for gradle with Quarkus cli. 
Tested it locally with RHBQ. The test are passing.
> [3.2] Enable disabled test for gradle building app by Quarkus cli

- service-binding/postgresql-crunchy-classic/src/test/java/io/quarkus/ts/sb/postgresql/OpenShiftPostgreSqlSbIT.java
- service-binding/postgresql-crunchy-reactive/src/test/java/io/quarkus/ts/sb/reactive/OpenShiftPostgreSqlReactiveSbIT.java
Behavior between OCP 4.11 and OCP 4.14 differs in that cluster service versions are added to newly created project one by one (not at once) and it takes longer.
> [2.13] Fix service binding PostgreSQL tests on OpenShift 4.14 as cluster service versions are loaded lazily

- service-binding/postgresql-crunchy-classic/src/test/java/io/quarkus/ts/sb/postgresql/OpenShiftPostgreSqlSbIT.java
- service-binding/postgresql-crunchy-reactive/src/test/java/io/quarkus/ts/sb/reactive/OpenShiftPostgreSqlReactiveSbIT.java
Behavior between OCP 4.11 and OCP 4.14 differs in that cluster service versions are added to newly created project one by one (not at once) and it takes longer.
**Native OCP failure is very much as what I see on main (but there even in JVM mode), I'll get back to it, but it is not related to changes here.**
> [3.2] Fix service binding PostgreSQL tests on OpenShift 4.14 as cluster service versions are loaded lazily

- sql-db/hibernate/src/main/java/io/quarkus/qe/hibernate/analyze/AnalyzeResource.java
- sql-db/hibernate/src/main/java/io/quarkus/qe/hibernate/items/ItemsResource.java
- sql-db/hibernate/src/main/java/io/quarkus/qe/hibernate/validator/JakartaPersistenceAndHibernateValidatorResource.java
- sql-db/hibernate/src/main/resources/application.properties
- sql-db/hibernate/src/test/java/io/quarkus/qe/hibernate/BaseHibernateIT.java
verifies: https://github.com/quarkusio/quarkus/pull/35635
Plenty of other modules still uses default Hibernate persistence unit (sql-app, sql-app-compatibility; almost all others uses it as well together named pu)
`mvn clean verify` => pass
`mvn clean verify -Dquarkus.platform.version=3.2.7.Final` => fail
> [3.2] Verify Hibernate ORM config mapping for named persistence units

- nosql-db/mongodb/src/test/java/io/quarkus/ts/nosqldb/mongodb/OpenShiftMongoClientIT.java
- pom.xml
Due to the test suite no longer using `bitnami/mongodb`, we can use the community version of MongoDB from DockerHub that is available on s390x. The test is passing now instead of being previously skipped. I will cherry-pick this into `main` after.
https://master-jenkins-csb-runtimes-ibmzqe.apps.ocp-c1.prod.psi.redhat.com/view/RHOAR/job/rhbq-3.x-ocp4-rhel8-jdk11/lastCompletedBuild/jdk=openjdk11,label=quarkus,scenario=databases-modules/testReport/io.quarkus.ts.nosqldb.mongodb/
> [3.2] Re-enable mongodb tests on s390x

- .github/workflows/ci.yml
- .github/workflows/daily.yaml
- .github/workflows/quarkus-snapshot.yaml
- README.md
- docker-build/src/main/docker/Dockerfile.jvm
- helm/helm-minimum/src/main/docker/Dockerfile.jvm
- http/vertx-web-client/README.md
- pom.xml
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
- security/oidc-client-mutual-tls/src/test/java/io/quarkus/ts/security/oidcclient/mtls/Pkcs12OidcMtlsIT.java
- spring/spring-web-reactive/README.md
- sql-db/vertx-sql/README.md
- Both Quarkus and QE FW are moving to Java 17 - https://github.com/quarkus-qe/quarkus-test-framework/pull/970
- Builder images are mirroring Quarkus upstream defaults as these are most likely to be used by users - https://github.com/quarkusio/quarkus/blob/main/core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java#L23
> Move Java baseline to 17

- external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftTodoDemoIT.java
- external-applications/src/test/java/io/quarkus/ts/external/applications/TodoDemoIT.java
- TODO Application with Quarkus is now based on Quarkus 3 - https://github.com/quarkusio/todo-demo-app/pull/32
- we already support running git repository OpenShift tests with 999-SNAPSHOT
- TODO Application is now using database. I refactored test so that we use it and don't start database for nothing.
> Enable and refactor TodoDemoIT on baremetal and OpenShift as TODO Application with Quarkus is now based on Quarkus 3

- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/OracleTransactionGeneralUsageIT.java
Dailys are failing. I can't connect this change to any concerete PR in Quarkus or TS between 25.11 and 29.11 https://github.com/quarkusio/quarkus/pulls?q=is%3Apr+is%3Aclosed+merged%3A2023-11-25..2023-11-29+base%3Amain+sort%3Aupdated-desc+. I don't want to invest more of my time into it. I suppose this can be also related to Docker image (some change in minor version that caused change of driver interaction). It is possible to find out, but it will cost more time. FWIW it's change for better, thought it would be nice to know what changed.
> Fix Narayana OTEL operation name in Oracle test used for SELECT query to dual table

- external-applications/src/test/java/io/quarkus/ts/external/applications/TodoDemoIT.java
* Testing todo-demo-app has finally been updated to Quarkus 3, so we
need to pin this branch to use quarkus2 branch of the application.
> [2.13] Pin todo-demo-app to quarkus2 branch

- http/http-minimum-reactive/src/main/java/io/quarkus/ts/http/minimum/reactive/HelloResource.java
- http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/HttpMinimumReactiveIT.java
- http/http-minimum/src/main/java/io/quarkus/ts/http/minimum/HelloResource.java
- http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/HttpMinimumIT.java
- pom.xml
Test coverage for records returned in response from REST endpoint
maven.compiler.release property is required by impsort - https://github.com/revelc/impsort-maven-plugin/issues/60#issuecomment-1136464103
Motivation: Java 17 is base now + I have noticed issues related to records on other products/solutions
> Test coverage for records returned in response from REST endpoint

- .github/workflows/ci.yml
- .github/workflows/daily.yaml
Bumps [actions/upload-artifact](https://github.com/actions/upload-artifact) and [actions/download-artifact](https://github.com/actions/download-artifact) from 3 to 4. 
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/actions/upload-artifact/releases">actions/upload-artifact's releases</a>.</em></p>
> Bump actions/upload and actions/download artifact from 3 to 4

- security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/OidcRestClientIT.java
I bet with my luck https://github.com/quarkusio/quarkus/pull/37788 will get merged anytime now, but our daily build has been failing for more than a week now and other testing is cancelled as this is failing, we need to run full test coverage. So I suggest to disable the test even though upstream PR can be merged in an hour or so.
> Disable OidcRestClientIT due to upstream bug

- super-size/many-extensions/src/test/java/io/quarkus/ts/many/extensions/OpenShiftUsingExtensionDockerBuildStrategyManyExtensionsIT.java
- super-size/many-extensions/src/test/java/io/quarkus/ts/many/extensions/OpenShiftUsingExtensionManyExtensionsIT.java
- super-size/many-extensions/src/test/java/io/quarkus/ts/many/extensions/ServerlessExtensionDockerBuildStrategyOpenShiftManyExtensionsIT.java
- super-size/many-extensions/src/test/java/io/quarkus/ts/many/extensions/ServerlessExtensionOpenShiftManyExtensionsIT.java
See https://github.com/quarkusio/quarkus/issues/37855.
> Disable failing OCP test using OpenShift extension in Many-extensions project due to upstream bug

- security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/OidcRestClientIT.java
Reverts quarkus-qe/quarkus-test-suite#1586 as https://github.com/quarkusio/quarkus/pull/37788 is merged.
> Revert "Disable OidcRestClientIT due to upstream bug"

- service-discovery/stork/src/test/java/io/quarkus/ts/stork/StorkLoadBalancerIT.java
Stork changed property name, and load-balancer property now requires a ".type" suffix.
> Update stork property for new version

- .github/workflows/daily.yaml
Removing component: 'native_image' from windows daily pipeline, as it is no longer required. Pipeline itself throws a warning about this:
https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/7455477415/job/20284865839#step:6:20
I checked that this pipeline works without this.
> remove 'native-image' component from daily pipeline

- http/http-advanced-reactive/pom.xml
- http/http-advanced/pom.xml
Remove okhttp dependency from http-advanced and http-advanced-reactive.
This dependency was recently removed from upstream BOM - https://github.com/quarkusio/quarkus/pull/38066 and it's missing version is causing failures.
It is unclear to me, why was this dependency even added. PR that added it does not provide any clue - https://github.com/quarkus-qe/quarkus-test-suite/pull/715
Both modules seems to work even without it.
> Remove okhttp dependency

- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeOracleDevServiceUserExperienceIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeOracleIT.java
Tests, affected by issue https://github.com/quarkusio/quarkus/issues/38003 does not work on podman. Marking these as podman-incompatible, before it is fixed.
> Disable tests affected by issue 38003

- http/servlet-undertow/src/test/java/io/quarkus/ts/http/undertow/HttpServletWithSessionListenerIT.java
Old code check equality, while checking for "true" value. This provides limited info for investigation in case of failure.
Checking using "assertEquals" logs actual values in case of failure.
> Refactor to check equality using relevant assert

- http/servlet-undertow/src/main/java/io/quarkus/ts/http/undertow/listener/SessionListener.java
servlet-undertow test is failing for a long time in github daily. Issue is, that sessions are stored in a LinkedList, which is not thread safe. Sessions are inserted into it, remain active for some time and then get evicted, all at about a same time. Although all sessions are actually deleted/ended, theye are not correctly removed from the collection and collection turns into inconsistent state (some sessions remain in it, even though were destroyed), which results in test failures.
This PR changes it to using thread safe collection, which correctly removes all sessions, even if they are destroyed all at once.
> Use thread safe collection in servlet-undertow

- monitoring/opentelemetry/pom.xml
- monitoring/opentelemetry/src/test/java/io/quarkus/ts/opentelemetry/OpenTelemetryManagementIT.java
Adds test coverage for https://github.com/quarkusio/quarkus/pull/37218. PR changes that management endpoints (like endpoints from smallrye-health) should not be stored as traces. Before this PR they were.
> Add test coverage for openTelemetry management endpoint traces

- http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/OpenShiftUsingExtensionDockerBuildStrategyHttpMinimumReactiveIT.java
- http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/OpenShiftUsingExtensionHttpMinimumReactiveIT.java
- http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/OpenShiftUsingExtensionDockerBuildStrategyHttpMinimumIT.java
- http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/OpenShiftUsingExtensionHttpMinimumIT.java
- http/jakarta-rest-reactive/src/test/java/io/quarkus/ts/http/jakartarest/reactive/OpenShiftCompressionHandlerIT.java
- http/jakarta-rest-reactive/src/test/java/io/quarkus/ts/http/jakartarest/reactive/OpenShiftHttpCachingIT.java
- http/management/src/test/java/io/quarkus/qe/extension/OpenShiftDockerBuildIT.java
- http/management/src/test/java/io/quarkus/qe/extension/OpenShiftExtensionIT.java
- http/vertx/src/test/java/io/quarkus/ts/vertx/OpenShiftUsingExtensionDockerBuildStrategyVertxIT.java
- http/vertx/src/test/java/io/quarkus/ts/vertx/OpenShiftUsingExtensionVertxIT.java
- http/vertx/src/test/java/io/quarkus/ts/vertx/ServerlessExtensionDockerBuildStrategyOpenShiftVertxIT.java
- http/vertx/src/test/java/io/quarkus/ts/vertx/ServerlessExtensionOpenShiftVertxIT.java
Disabling tests that fail due to https://github.com/quarkusio/quarkus/issues/38018. Same was done last week for FW https://github.com/quarkus-qe/quarkus-test-framework/pull/1007. See weekly runs for examples, I can reproduce it from my workstation.
> Disable OCP tests using OpenShift extension due to upstream bug

- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/HeaderClient.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/filter/VersionHeaderFilter.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/HeadersReflectionResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/HeadersResource.java
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientIT.java
Add test coverage for https://github.com/quarkusio/quarkus/pull/37268 and issue described in it.
Issue is that ClientRequestFilter is not applied, if ContainerResponseFilter is also present in the same class, because of https://github.com/quarkusio/quarkus/pull/37006.
This PR is similar to https://github.com/quarkus-qe/quarkus-test-suite/pull/1616 but this test requires the restClient to actually do a request for the client filter to be invoked. For that reason, this new tests is in `rest-client-reactive` module, where is can do actual requests.
> Add test coverage for issue in PR 37268.

- pom.xml
Re-runs baremetal failures twice and OCP failures once. There is minimal cost of doing that on baremetal as JVM build takes little while and native build will be re-used when I make adjustments in the Test Framework (right now custom build is not re-used, but there is little point of testing Quarkus build indempotency).
This is part of efforts to limit false failures. After that must come way to detect flaky tests that were re-run and report it so that we address flakyness.
This is how logs will look like (OCP will be only re-run once though):
```
[ERROR] io.quarkus.ts.http.minimum.reactive.OpenShiftHttpMinimumReactiveIT.fail -- Time elapsed: 5.265 s <<< FAILURE!
org.opentest4j.AssertionFailedError
at io.quarkus.ts.http.minimum.reactive.HttpMinimumReactiveIT.fail(HttpMinimumReactiveIT.java …
```
> Re-run failing tests to limit flakiness

- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/CookiesIT.java
As https://github.com/quarkusio/quarkus/pull/38466 change how the cookies are handled this PR update it as well.
JFYI this should be correct form (at least the standard define it as "Lax" etc.) and not all uppercase as the RestEasy do it. That's the reason why the `toUpperCase` is remaining when the body is checked.
> Fix cookie sameSite tests as quarkus change the handling

- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/OpenShiftHttpAdvancedReactiveIT.java
- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/OpenShiftHttpAdvancedIT.java
- http/management/src/test/java/io/quarkus/qe/extension/OpenShiftRegistryIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftAmqStreamsKafkaStreamIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftStrimziKafkaStreamIT.java
- messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/OpenShiftAmqStreamsKafkaAvroIT.java
- messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/OpenShiftStrimziKafkaAvroIT.java
- messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/StrimziKafkaAvroIT.java
- monitoring/micrometer-prometheus-kafka-reactive/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/reactive/OpenShiftAmqStreamsAlertEventsReactiveIT.java
- monitoring/micrometer-prometheus-kafka-reactive/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/reactive/OpenShiftKafkaAlertEventsReactiveIT.java
- monitoring/micrometer-prometheus-kafka/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/OpenShiftAmqStreamsAlertEventsIT.java
- monitoring/micrometer-prometheus-kafka/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/OpenShiftKafkaAlertEventsIT.java
- nosql-db/mongodb-reactive/src/test/java/io/quarkus/ts/nosqldb/mongodb/reactive/OpenShiftMongoClientReactiveIT.java
- pom.xml
- properties/src/test/java/io/quarkus/ts/properties/consul/OpenShiftConsulConfigSourceIT.java
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/OpenShiftOidcRestClientIT.java
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/OpenShiftOidcSinglePageAppLogoutFlowIT.java
- security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/OpenShiftOidcRestClientIT.java
- security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/OpenShiftOidcSinglePageAppLogoutFlowIT.java
- service-binding/postgresql-crunchy-classic/src/test/java/io/quarkus/ts/sb/postgresql/OpenShiftPostgreSqlSbIT.java
- service-binding/postgresql-crunchy-reactive/src/test/java/io/quarkus/ts/sb/reactive/OpenShiftPostgreSqlReactiveSbIT.java
- sql-db/hibernate-fulltext-search/src/test/java/io/quarkus/ts/hibernate/search/OpenShiftMysqlMultitenantHibernateSearchIT.java
- sql-db/hibernate-fulltext-search/src/test/java/io/quarkus/ts/hibernate/search/OpenShiftPostgresqlMultitenantHibernateSearchIT.java
The previous PR to create a s390x testing profile and exclude some tests should have included Power PC (ppc64le) as both archs are similar. [Link to s390x PR](https://github.com/quarkus-qe/quarkus-test-suite/pull/1431)
These changes should also be cherry picked into main and 3.8 branches.
Latest test runs with new profile:
[Quarkus 3.2.10 JDK17 Run](https://master-jenkins-csb-runtimesppcqe.apps.ocp-c1.prod.psi.redhat.com/job/Cloud-Native-Runtimes/job/Quarkus/job/rhbq-3.x-jdk-11-17/)
> Disable the same testing for IBM ppc64le as IBM s390x

- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/OpenShiftHttpAdvancedReactiveIT.java
- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/OpenShiftHttpAdvancedIT.java
- http/management/src/test/java/io/quarkus/qe/extension/OpenShiftRegistryIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftAmqStreamsKafkaStreamIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftStrimziKafkaStreamIT.java
- messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/OpenShiftAmqStreamsKafkaAvroIT.java
- messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/OpenShiftStrimziKafkaAvroIT.java
- messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/StrimziKafkaAvroIT.java
- monitoring/micrometer-prometheus-kafka-reactive/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/reactive/OpenShiftAmqStreamsAlertEventsReactiveIT.java
- monitoring/micrometer-prometheus-kafka-reactive/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/reactive/OpenShiftKafkaAlertEventsReactiveIT.java
- monitoring/micrometer-prometheus-kafka/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/OpenShiftAmqStreamsAlertEventsIT.java
- monitoring/micrometer-prometheus-kafka/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/OpenShiftKafkaAlertEventsIT.java
- nosql-db/mongodb-reactive/src/test/java/io/quarkus/ts/nosqldb/mongodb/reactive/OpenShiftMongoClientReactiveIT.java
- pom.xml
- properties/src/test/java/io/quarkus/ts/properties/consul/OpenShiftConsulConfigSourceIT.java
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/OpenShiftOidcRestClientIT.java
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/OpenShiftOidcSinglePageAppLogoutFlowIT.java
- security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/OpenShiftOidcRestClientIT.java
- security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/OpenShiftOidcSinglePageAppLogoutFlowIT.java
- sql-db/hibernate-fulltext-search/src/test/java/io/quarkus/ts/hibernate/search/OpenShiftMysqlMultitenantHibernateSearchIT.java
- sql-db/hibernate-fulltext-search/src/test/java/io/quarkus/ts/hibernate/search/OpenShiftPostgresqlMultitenantHibernateSearchIT.java
The previous PR to create a s390x testing profile and exclude some tests should have included Power PC (ppc64le) as both archs are similar. [Link to s390x PR](https://github.com/quarkus-qe/quarkus-test-suite/pull/1431)
These changes should also be cherry picked into main and 3.8 branches.
Latest test runs with new profile:
[Quarkus 3.2.10 JDK17 Run](https://master-jenkins-csb-runtimesppcqe.apps.ocp-c1.prod.psi.redhat.com/job/Cloud-Native-Runtimes/job/Quarkus/job/rhbq-3.x-jdk-11-17/)
> [3.8] Disable the same testing for IBM ppc64le as IBM s390x

- pom.xml
> Bump framework version to 1.4.0.Beta8

- README.md
- pom.xml
Fixes my fault from [images bump PR](https://github.com/quarkus-qe/quarkus-test-suite/pull/1651)
Images from `registry.redhat.io` cannot be pushed without access token, that we have only in OC tests jobs in Jenkins
Should fix daily build failures
> Use public Red Hat registry images for non OC scenarios

- service-discovery/stork/src/test/java/io/quarkus/ts/stork/OpenShiftStorkServiceDiscoveryIT.java
It is disabled for 2.x, 999-SNAPSHOT and on 3.2 branch already
Required for https://github.com/quarkus-qe/quarkus-test-suite/pull/1668
> Fully disable service discovery test

- pom.xml
I'm reverting postgres image to use "library" version as it back with the version 15.
Problem is, that postgres has different tags on docker and podman. On docker image "docker.io/postgres" works OK. On podman it does not.
In current version (prior to this PR):
Docker pulls the image and tags it as "postgres:16.1-bullseye". When our TS is searching for this image, it searches for "docker.io/postgres:16.1" and finds it.
Podman pulls the very same image (same hash sum) and tags it as "docker.io/library/postgres:16.1-bullseye". And then, when searching for "docker.io/postgres:16.1" it fails to find it, even though image is there.
Changing the image name to "docker.io/library/postgres:16.1-bullseye" makes both docker and podman able of pulling it and then successfully searching for it.
Please …
> Use "library" version of postgresql image

- .github/workflows/add-flaky-test-label.yml
- .github/workflows/ci.yml
- pom.xml
- Generate flaky run report when flaky tests are detected during SureFire and FailSafe test runs (by Maven extension https://github.com/quarkus-qe/flaky-run-reporter); this report is going to be consumed by our Jenkins jobs and GitHub application and the report will be visualized
- I've tested it here https://github.com/quarkus-qe/quarkus-test-suite/pull/1678 with flaky test and artifact were generated; I don't think it is possible to test listening workflow from PR, it probably needs to be merged and if there is an issue then adjusted...
> Detect and report flaky tests

- .github/workflows/add-flaky-test-label.yml
I don't think this CI tests this PR anyway, so no need to wait.
- when expected flaky report artifact is not there, gh command throws error (see https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/7992635005/job/21826584746), sorry, but docs https://cli.github.com/manual/gh_run_download does not say what will happen so I didn't know (if artifact is not there, it is standard state for the workflow, we just don't run other job steps)
- PR_NUMBER environment variable is empty https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/7992439157/job/21825925418 which is hilarious because I copied that line from here https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#using-data-from-the-triggering-workflow Now I am taking advices from …
> Fix workflow that comments and add flaky test label

- .github/workflows/add-flaky-test-label.yml
Explained in https://github.com/quarkus-qe/quarkus-test-suite/pull/1684, third time is the charm.
- [x Bug fix (non-breaking change which fixes an issue)
> Fix Flaky workflow by getting PR from downloaded artifact instead of empty event object

- README.md
- pom.xml
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/MysqlTransactionGeneralUsageIT.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/TransactionCommons.java
- sql-db/reactive-rest-data-panache/src/test/java/io/quarkus/ts/reactive/rest/data/panache/MySqlPanacheResourceIT.java
- sql-db/sql-app-compatibility/src/test/java/io/quarkus/ts/sqldb/compatibility/MySqlDatabaseIT.java
- sql-db/sql-app-compatibility/src/test/resources/mysql.properties
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/MySqlDatabaseIT.java
Update docker image of MySQL as 5.7 reach EOL in October
> Switch MySQL 5.7 to 8 as 5.7 is EOL

- sql-db/hibernate-reactive/src/main/resources/application.properties
This should fix daily failure.
After https://github.com/quarkusio/quarkus/pull/39005 the Quarkus need specify datasource type in build time. We doing it others modules but missing it here.
> Add datasource type in hibernate reactive application.properties

- http/http-advanced-reactive/src/main/resources/application.properties
- http/http-advanced/src/main/resources/application.properties
Sets keystore file type as tests are now failing. See https://github.com/quarkusio/quarkus/pull/39106 and https://github.com/quarkusio/quarkus/issues/39151 for explanation what changed and why it is okay.
> Set keystore file type as required due to upstream changes the type can't be inferred anymore

- http/management/src/test/java/io/quarkus/qe/LocalOptionsIT.java
It's the same problem as https://github.com/quarkus-qe/quarkus-test-suite/pull/1700 
> Add keystore file type as it's now required

- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/BaseOidcIT.java
- security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/BaseOidcIT.java
Our `OidcRestClientIT`s tests in OpenShift are randomly failing. It's not reproducible, but it happens for some time now and re-run doesn't seem to help (not flaky :-/), exception looks like this:
```
java.lang.RuntimeException: Error executing http method [POST]. Response : null
at org.keycloak.authorization.client.util.HttpMethod.execute(HttpMethod.java:114)
at org.keycloak.authorization.client.util.HttpMethodResponse$2.execute(HttpMethodResponse.java:50)
at org.keycloak.authorization.client.AuthzClient.obtainAccessToken(AuthzClient.java:213)
at io.quarkus.ts.security.keycloak.oidcclient.extended.restclient.BaseOidcIT.createToken(BaseOidcIT.java:39)
at io.quarkus.ts.security.keycloak.oidcclient.extended.restclient.OidcRestClientIT.assertPingPongWithPathParam(OidcRestClientIT.java:127) …
```
> Workaround Keycloak Authoriz Client network connection issues in OpenShift

- service-binding/postgresql-crunchy-classic/src/test/java/io/quarkus/ts/sb/postgresql/OpenShiftPostgreSqlSbIT.java
- service-binding/postgresql-crunchy-reactive/src/test/java/io/quarkus/ts/sb/reactive/OpenShiftPostgreSqlReactiveSbIT.java
These tests wait for operators to be ready.
Earlier, they used Thread.sleep, which sometimes was not enough. These tests fail several times on OCP 4-15, so now they use awaitility
> Change waiting rules for operators

- env-info/pom.xml
- qute/multimodule/qute-api/pom.xml
Native build now fails https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/8371702125/job/22922072961. See https://github.com/quarkusio/quarkus/pull/39295#issuecomment-2011857784 for explanation why.
The `quarkus.native.enabled=true` disabled native executable build, however there is no point to even start, therefore this PR is disabling build on Plugin level, which is sooner, therefore less processing.
> Properly disable Env info and Qute API modules native build as native build is failing over this

- README.md
- external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftWorkshopHeroesIT.java
- external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftWorkshopVillainsIT.java
- external-applications/src/test/java/io/quarkus/ts/external/applications/TodoDemoIT.java
- pom.xml
- sql-db/reactive-rest-data-panache/src/test/java/io/quarkus/ts/reactive/rest/data/panache/H2SqlPanacheResourceIT.java
As a follow up of the https://github.com/quarkusio/quarkus/pull/39295 we should adapt our tests. While fallback config interceptors are in place, we need to sync properties set with how the framework detects them and works with them.
> Fix daily / CI failures by bumping the Test Framework to 1.4.2.Beta9 and migrating package type configuration property

- monitoring/opentelemetry-reactive/src/test/java/io/quarkus/ts/opentelemetry/reactive/OpentelemetryReactiveIT.java
- monitoring/opentelemetry/src/test/java/io/quarkus/ts/opentelemetry/OpenTelemetryIT.java
REST CLient operation names were changed here https://github.com/quarkusio/quarkus/pull/39534. Changes is intentional.
> Fix OpenTelemetry REST client operation names as they changed upstream

- infinispan-client/src/main/java/io/quarkus/ts/infinispan/client/serialized/ShopItemResource.java
Now `OperatorOpenShiftInfinispanObjectsIT` fails due to https://github.com/quarkusio/quarkus/pull/39302, that PR documents what should be done, just isn't properly marked or noted in a migration guide ATM.
> Fix OperatorOpenShiftInfinispanObjectsIT after upstream change of bean scope from Singleton to ApplicationScoped

- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/SaslSslAlertMonitorIT.java
- messaging/kafkaSSL/src/main/java/io/quarkus/qe/messaging/ssl/providers/SaslSslKafkaProvider.java
- messaging/kafkaSSL/src/main/java/io/quarkus/qe/messaging/ssl/quickstart/SaslSslKafkaEndpoint.java
- messaging/kafkaSSL/src/test/java/io/quarkus/qe/messaging/ssl/KafkaSaslSslIT.java
Add test support for Kafka authentication with SASL_SSL protocols
Tests `kafka.security.protocol=SASL_SSL` property
> Add tests to cover Kafka authentication with SASL_SSL

- http/management/src/test/java/io/quarkus/qe/extension/OpenShiftRegistryIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OperatorOpenShiftAmqStreamsKafkaStreamIT.java
Skipping an additional Kafka test on both IBM Z/Power due to specific image not being available on these platforms.
> [3.2] Skip Kafka test on IBM Z/Power due to missing image

- http/management/src/test/java/io/quarkus/qe/extension/OpenShiftRegistryIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OperatorOpenShiftAmqStreamsKafkaStreamIT.java
Similar to https://github.com/quarkus-qe/quarkus-test-suite/pull/1729.
Skipping an additional Kafka test on both IBM Z/Power due to specific image not being available on these platforms.
> [3.8] Skip Kafka test on IBM Z/Power due to missing image

- http/management/src/test/java/io/quarkus/qe/extension/OpenShiftRegistryIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OperatorOpenShiftAmqStreamsKafkaStreamIT.java
Similar to https://github.com/quarkus-qe/quarkus-test-suite/pull/1729.
Skipping an additional Kafka test on both IBM Z/Power due to specific image not being available on these platforms.
> Skip Kafka test on IBM Z/Power due to missing image

- service-binding/postgresql-crunchy-classic/src/test/java/io/quarkus/ts/sb/postgresql/OpenShiftPostgreSqlSbIT.java
- service-binding/postgresql-crunchy-reactive/src/test/java/io/quarkus/ts/sb/reactive/OpenShiftPostgreSqlReactiveSbIT.java
Skipping the 2 Postgres tests in the service-binding module on IBM ppc64le and IBM s390x due to Crunchy Postgres Operator not being available on IBM ppc64le and IBM s390x.
Example run showing that the test is skipped: https://master-jenkins-csb-runtimes-ibmzqe.apps.ocp-c1.prod.psi.redhat.com/job/rhbq-project_test/6/
> [3.8] Skip service-binding Postgres test on IBM ppc64le and IBM s390x

- service-binding/postgresql-crunchy-classic/src/test/java/io/quarkus/ts/sb/postgresql/OpenShiftPostgreSqlSbIT.java
- service-binding/postgresql-crunchy-reactive/src/test/java/io/quarkus/ts/sb/reactive/OpenShiftPostgreSqlReactiveSbIT.java
Skipping the 2 Postgres tests in the service-binding module on IBM ppc64le and IBM s390x due to Crunchy Postgres Operator not being available on IBM ppc64le and IBM s390x.
Cherry-picking the change from 3.8
> Skip service-binding Postgres test on IBM ppc64le and IBM s390x.

- external-applications/src/test/java/io/quarkus/ts/external/applications/TodoDemoIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
- Use quarkus3 branch in todo app to avoid 3.9-specific bugs
- Temporarly disable gradle test
> [3.8] Adapt to changes in CR2

- service-binding/postgresql-crunchy-classic/src/test/java/io/quarkus/ts/sb/postgresql/OpenShiftPostgreSqlSbIT.java
- service-binding/postgresql-crunchy-reactive/src/test/java/io/quarkus/ts/sb/reactive/OpenShiftPostgreSqlReactiveSbIT.java
* Disabling service binding tests on aarch64 as the CrunchyDB operator is not yet supported there.
Tracking issue: https://github.com/quarkus-qe/quarkus-test-suite/issues/1755
> [3.8] Disable tests on aarch64 due to no CrunchyDB there

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
The check in question returns 404 on Windows due to https://github.com/quarkusio/quarkus/issues/39909#issuecomment-2070739091. It seems like it's related to the CLI version installed on our Windows runners with a Docker. I didn't look further into cause of this behavior because I do not consider this very important as long as there is opened known issue marked as won't f i x https://github.com/quarkusio/quarkus/issues/39909.
> [3.8] Do not expect index page in DEV mode on Windows

- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DisabledOnRHBQAarch64Native.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DisabledOnRHBQAarch64NativeConditions.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftStrimziKafkaStreamIT.java
* Disabling Kafka Streams test on native product due to https://issues.redhat.com/browse/QUARKUS-4321.
> Disabling Kafka Streams test on native product

- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DisabledOnRHBQAarch64Native.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DisabledOnRHBQAarch64NativeConditions.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftStrimziKafkaStreamIT.java
* Disabling Kafka Streams test on native product due to https://issues.redhat.com/browse/QUARKUS-4321.
Test run: https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/job/rhbq-3.8-rhel8-jdk21-openshift-ts-native-ocp-4-stable-aarch64-mj/label=RHEL8_aarch64%20&&%20xlarge%20&&%20docker,scenario=messaging-modules/9/
> [3.8] QUARKUS-4321 Disabling Kafka Streams test on native product 

- service-binding/postgresql-crunchy-classic/src/test/java/io/quarkus/ts/sb/postgresql/OpenShiftPostgreSqlSbIT.java
- service-binding/postgresql-crunchy-reactive/src/test/java/io/quarkus/ts/sb/reactive/OpenShiftPostgreSqlReactiveSbIT.java
* Increasing the maximum timeout to 300 seconds for CSVs to be injected into the namespace in service binding tests. The reason is that on OSD, there's considerably more operators installed on the cluster and it takes more than a minute quite a lot of times.
Backport of #1767 
> [3.8] Increase wait time to 300 seconds for CSVs in SB

- service-binding/postgresql-crunchy-classic/src/test/java/io/quarkus/ts/sb/postgresql/OpenShiftPostgreSqlSbIT.java
- service-binding/postgresql-crunchy-reactive/src/test/java/io/quarkus/ts/sb/reactive/OpenShiftPostgreSqlReactiveSbIT.java
* Increasing the maximum timeout to 300 seconds for CSVs to be injected into the namespace in service binding tests. The reason is that on OSD, there's considerably more operators installed on the cluster and it takes more than a minute quite a lot of times.
> Increase wait time to 300 seconds for CSVs in SB

- messaging/amqp-reactive/pom.xml
- messaging/amqp-reactive/src/test/java/io/quarkus/ts/messaging/amqpreactive/ProdAmqpReactiveIT.java
- monitoring/opentelemetry-reactive/pom.xml
- monitoring/opentelemetry-reactive/src/main/java/io/quarkus/ts/opentelemetry/reactive/AdminResource.java
- monitoring/opentelemetry-reactive/src/main/resources/application.properties
- monitoring/opentelemetry-reactive/src/test/java/io/quarkus/ts/opentelemetry/reactive/OpentelemetryReactiveIT.java
- monitoring/opentelemetry/src/main/resources/application.properties
- monitoring/opentelemetry/src/test/java/io/quarkus/ts/opentelemetry/DevModeOpenTelemetryIT.java
- pom.xml
As was described in the Jira task : [QUARKUS-2391 Promote the OpenTelemetry extension from TP to full support](https://issues.redhat.com/browse/QQE-540), the OpenTelemetry extension will be fully supported then the plan is to increase the test coverage for Quarkus Opentelemetry, according with the test plan created here:
[OpenTelemetry extension test plan](https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-2391.md)
> Increase Opentelemetry test coverage

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
Disable gradle test as it failing for 3rd RHBQ release
> Disable shouldCreateApplicationWithGradleOnJvm test

- pom.xml
* Bumping version of quarkus-test-framework to first stable release of 1.4 stream meant for Quarkus 3.8.
> [3.8] Bump quarkus-test-framework to 1.4.4

- security/webauthn/src/test/java/io/quarkus/ts/security/webauthn/MySqlWebAuthnIT.java
I have created both RHBQ JIRA QUARKUS-4387 and upstream https://github.com/eclipse-vertx/vertx-sql-client/issues/1436. We need to disable this as our FIPS tests are failing.
> Disable MySQL WebAuth test in FIPS-enabled environment due to upstream bug

- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/MssqlTransactionGeneralUsageIT.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/OracleTransactionGeneralUsageIT.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/TransactionCommons.java
After https://github.com/quarkusio/quarkus/pull/40102 actual DB query changes as now, during the UPDATE with JDBC MSSQL, the alias is used. The DB statement now looks like this: `update ae1_0 set amount=?,updatedAt=? from account ae1_0 where ae1_0.accountNumber=?` which results in alias being used instead of database name.
I could not find anything in OTel specs in this regards, the closes I got is the first link https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7821, but it seems like a grey area and I don't think it's a bug.
> Adjust expectations regarding OpenTelemetry JDBC operation names after Hibernate ORM bump to 6.5

- sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/OracleDatabaseIT.java
- sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/PostgresqlDatabaseHibernateReactiveIT.java
Right now, it doesn't seem like we will get quick fix of the https://github.com/quarkusio/quarkus/issues/40425.
> Disable failing Hiberante Reactive Oracle and PostgreSQL tests after bump to 2.3

- sql-db/vertx-sql/src/main/java/io/quarkus/ts/vertx/sql/Application.java
The module compilation fails due to https://github.com/quarkusio/quarkus/pull/39194.
> Fix Vert.X SQL module compilation after ProfileManager removal from Quarkus

- security/oidc-client-mutual-tls/src/test/java/io/quarkus/ts/security/oidcclient/mtls/IncorrectKsFileTypeOidcMtlsIT.java
- security/oidc-client-mutual-tls/src/test/java/io/quarkus/ts/security/oidcclient/mtls/JksOidcMtlsIT.java
I run all the tests in native and JVM with RH OpenJDK 17 & 21 and they work.
> Run OIDC client mTLS tests in FIPS-enabled environment

- sql-db/reactive-vanilla/src/test/java/io/quarkus/ts/reactive/db/clients/DevModeReactiveMysqlDevServiceUserExperienceIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMysqlDevServiceUserExperienceIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMysqlIT.java
Our MySQL Dev Mode tests run with RHBQ 3.8.4 in FIPS-enabled failed. I have reported issue here https://github.com/quarkusio/quarkus/issues/40526 but we need to disable them for now and backport it to the 3.8 branch.
> Disable MySQL Dev Svc in FIPS due to upstream issue

- security/vertx-jwt/src/main/java/io/quarkus/ts/security/vertx/auth/AuthN.java
- security/vertx-jwt/src/main/java/io/quarkus/ts/security/vertx/auth/CertUtils.java
- security/vertx-jwt/src/main/java/io/quarkus/ts/security/vertx/config/AuthNConfig.java
- security/vertx-jwt/src/main/resources/application.properties
- security/vertx-jwt/src/test/java/io/quarkus/ts/security/vertx/AbstractCommonIT.java
- security/vertx-jwt/src/test/java/io/quarkus/ts/security/vertx/BladeRunnerHandlerIT.java
- security/vertx-jwt/src/test/java/io/quarkus/ts/security/vertx/NoSecuredResourceIT.java
- security/vertx-jwt/src/test/java/io/quarkus/ts/security/vertx/ReplicantHandlerIT.java
- security/vertx-jwt/src/test/java/io/quarkus/ts/security/vertx/SecuredResourceIT.java
- security/vertx-jwt/src/test/java/io/quarkus/ts/security/vertx/jwt/JwtTest.java
- algorithm `HS256` doesn't work in FIPS-enabled environment, so I replaced it with `RS256`
- `JwtIT` started Quarkus application for no reason, because it didn't test it, so I made it a plain unit test
> Fix Vert.x JWT tests in FIPS-enabled environment

- security/bouncycastle-fips/bcFipsJsse/src/test/java/io/quarkus/ts/security/bouncycastle/fips/jsse/BouncyCastleFipsJsseTest.java
- security/bouncycastle-fips/bcfips/src/test/java/io/quarkus/ts/security/bouncycastle/fips/BouncyCastleFipsIT.java
- BouncyCastleFipsIT just works, let's run it in FIPS-enabled environment
- BouncyCastleFipsJsseTest is disabled due to the https://github.com/quarkusio/quarkus/issues/40659
> Enable BouncyCastleFipsIT in FIPS-enabled environment and link upstream issue to BouncyCastleFipsJsseTest "fips-incompatible" tag

- security/bouncycastle-fips/bcFipsJsse/src/test/java/io/quarkus/ts/security/bouncycastle/fips/jsse/BouncyCastleFipsJsseTest.java
https://github.com/quarkusio/quarkus/issues/40659 is fixed, therefore we can run BouncyCastleFipsJsseTest in FIPS-enabled environment. This PR is not backportable to 3.8 as the upstream fix wasn't backported.
> Enable BouncyCastleFipsJsseTest in FIPS-enabled environment as upstream issue got fixed

- sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/MsSQLDatabaseHibernateReactiveIT.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/MssqlTransactionGeneralUsageIT.java
- sql-db/reactive-rest-data-panache/src/test/java/io/quarkus/ts/reactive/rest/data/panache/MssqlPanacheResourceIT.java
- sql-db/reactive-vanilla/src/test/java/io/quarkus/ts/reactive/db/clients/DevModeReactiveMssqlDevServiceUserExperienceIT.java
- sql-db/sql-app-compatibility/src/test/java/io/quarkus/ts/sqldb/compatibility/MssqlDatabaseIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMssqlDevServicesUserExperienceIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/MssqlDatabaseIT.java
- sql-db/sql-app/src/test/resources/mssql.properties
- sql-db/vertx-sql/src/test/java/io/quarkus/ts/vertx/sql/handlers/MssqlHandlerIT.java
- run at least one of JDBC MSSQL extension tests with encrypted communication without trusting server certs as documented in Microsoft SQL Server 2022 documentation: https://learn.microsoft.com/en-us/sql/connect/jdbc/fips-mode?view=sql-server-ver16
- do not run MSSQL tests with OpenJDK 17 in FIPS-enabled environment due to the https://github.com/quarkusio/quarkus/issues/40813 (that works with our Jenkins jobs as they expect `FIPS=fips` exported environment variable)
All the SQL Server tests are disabled in OpenShift, so running only GitHub CI.
> Add encrypted communication between Quarkus app and SQL Server 2022 and disable SQL Server tests when run in FIPS-enabled environment with OpenJDK 17

- pom.xml
- sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/MsSQLDatabaseHibernateReactiveIT.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/MssqlTransactionGeneralUsageIT.java
- sql-db/reactive-rest-data-panache/src/test/java/io/quarkus/ts/reactive/rest/data/panache/MssqlPanacheResourceIT.java
- sql-db/reactive-vanilla/src/test/java/io/quarkus/ts/reactive/db/clients/DevModeReactiveMssqlDevServiceUserExperienceIT.java
- sql-db/sql-app-compatibility/src/test/java/io/quarkus/ts/sqldb/compatibility/MssqlDatabaseIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMssqlDevServicesUserExperienceIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/MssqlDatabaseIT.java
- sql-db/sql-app/src/test/resources/mssql.properties
- sql-db/vertx-sql/src/test/java/io/quarkus/ts/vertx/sql/handlers/MssqlHandlerIT.java
- bump QE Test Framework to 1.4.6 (required for MSSQL changes)
- backport https://github.com/quarkus-qe/quarkus-test-suite/pull/1807
> [3.8] Bump Quarkus QE Test Framework to 1.4.6 and backport SQL Server FIPS fixes

- security/keycloak-oidc-client-extended/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/principal/JsonTokenResource.java
- security/keycloak-oidc-client-extended/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/principal/clients/JsonTokenClient.java
- security/keycloak-oidc-client-extended/src/main/resources/application.properties
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/TokenPropagationFilterIT.java
Adds missing coverage for token propagation
No changes in Reactive due to https://github.com/quarkusio/quarkus/issues/40884
https://issues.redhat.com/browse/QUARKUS-4179
> Coverage for JSON tokens

- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/BaseHttpAdvancedReactiveIT.java
- http/http-advanced/src/main/java/io/quarkus/ts/http/advanced/GzipResource.java
- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/GzipMaxInputIT.java
- http/http-advanced/src/test/resources/gzip.properties
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliPomIntegrityIT.java
Adding TD for the next backports:
- [Make max parameters of multipart handling configurable](https://github.com/quarkusio/quarkus/pull/40663/commits/8b683ee24fdeea6978156dd889f7ee8c3fee6f0c)
- [Preserve POM format when extensions are added/removed](https://github.com/quarkusio/quarkus/pull/40663/commits/2bb40f94ac518a45a092054f42b06f4e60680b24)
- [Properly convert MemorySize to RESTEasy configuration](https://github.com/quarkusio/quarkus/pull/40663/commits/7562534cdd8a9d4fc8092a0b8812b80be76b0063)
> Add test coverage for some 3.8.5 backports 2 #40663

- .github/workflows/ci.yml
When there are changes outside of specific modules like in the `POM.xml` or `.github` workflow, one run (with security and db modules) run very roughly about 2 hours and the other one about 1 hours. I am talking about times from here https://github.com/quarkus-qe/quarkus-test-suite/pull/1824. I'd like to spread out the load a bit. I'm sure it's not going to be perfect as it's dynamic matter (for example tests are added, I am going to remove some modules etc.).
After this PR (see CI) one run is 1h 15m 6s and the other run is 1h 0m 39s. Please keep in mind that some security modules are disabled, and so is the CLI one.
> Spread PR CI workload when "full" CI is run little bit better between work runners

- http/http-advanced-reactive/pom.xml
- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/DevModeGrpcIntegrationReactiveIT.java
- http/http-advanced/pom.xml
- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/DevModeGrpcIntegrationIT.java
Enables disabled gRPC DEV UI tests. The test differs because the new DEV UI is SPA and cannot be tested in a same way as static pages. It's bit hard to test it as there are no hooks we could use for selectors, so I reimplemented gRPC service assertion and opened https://github.com/quarkus-qe/quarkus-test-suite/issues/1832 for gRPC communication (follow-up). Another thing that has changed is that we use gRPC server on a same HTTP server (not a separate port as in past), but our FW is not adapted to this, so I only worked around it for now. I'll address it later in FW.
> Fix and enable DEV UI gRPC tests

- http/http-advanced-reactive/src/test/resources/keycloak-realm.json
- http/http-advanced/src/test/resources/keycloak-realm.json
- monitoring/micrometer-prometheus-oidc/src/test/resources/keycloak-realm.json
- pom.xml
- security/keycloak-authz-classic/src/test/resources/keycloak-realm.json
- security/keycloak-authz-reactive/src/test/resources/keycloak-realm.json
- security/keycloak-jwt/src/test/resources/keycloak-realm.json
- security/keycloak-multitenant/src/test/resources/keycloak-realm.json
- security/keycloak-oauth2/src/test/resources/keycloak-realm.json
- security/keycloak-oidc-client-basic/src/test/resources/keycloak-realm.json
- security/keycloak-oidc-client-extended/src/test/resources/keycloak-realm.json
- security/keycloak-oidc-client-reactive-basic/src/test/resources/keycloak-realm.json
- security/keycloak-oidc-client-reactive-extended/src/test/resources/keycloak-realm.json
- security/keycloak-webapp/src/test/resources/keycloak-realm.json
- security/keycloak/src/test/resources/keycloak-realm.json
- security/oidc-client-mutual-tls/src/test/resources/keycloak-realm.json
Bumping the Keycloak images + updating the Keycloak files with email, first and last name parameters.
Enable the disabled Keycloak modules.
Not changing OIDC client mutal TLS email as it's used in test and it's make more sense to check with more "realistic" email address
> Enable Keycloak modules and bump the Keycloak images

- .github/workflows/ci.yml
- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/BaseHttpAdvancedReactiveIT.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/failures/FailingClientResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/failures/FailingResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/failures/FailureClient.java
- http/rest-client-reactive/src/main/resources/modern.properties
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientIT.java
- pom.xml
- security/basic/pom.xml
- security/basic/src/main/java/io/quarkus/ts/openshift/security/basic/SecurityFilter.java
- security/keycloak-oidc-client-extended/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/principal/JsonTokenResource.java
- security/keycloak-oidc-client-extended/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/principal/clients/JsonTokenClient.java
- security/keycloak-oidc-client-extended/src/main/resources/application.properties
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/TokenPropagationFilterIT.java
Backports:
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1813
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1802 (only max parameters part)
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1818
Also updates Quarkus version to 3.8.5 in POM and CI
> [3.8] Backports for 3.8.5+Update to 3.8.5

- README.md
- monitoring/opentelemetry/pom.xml
- monitoring/opentelemetry/src/test/java/io/quarkus/ts/opentelemetry/DevModeOpenTelemetryIT.java
- monitoring/opentelemetry/src/test/java/io/quarkus/ts/opentelemetry/OpenTelemetryIT.java
- monitoring/opentelemetry/src/test/java/io/quarkus/ts/opentelemetry/OpenTelemetryProxyIT.java
test coverage for https://github.com/quarkusio/quarkus/issues/39519
TP: https://github.com/quarkus-qe/quarkus-test-plans/pull/178
> Test OpenTelemetry OTLP Exporter proxy

- http/http-advanced-reactive/src/test/resources/keycloak-realm.json
- http/http-advanced/src/test/resources/keycloak-realm.json
- monitoring/micrometer-prometheus-oidc/src/test/resources/keycloak-realm.json
- pom.xml
- security/keycloak-authz-classic/src/test/resources/keycloak-realm.json
- security/keycloak-authz-reactive/src/test/resources/keycloak-realm.json
- security/keycloak-jwt/src/test/resources/keycloak-realm.json
- security/keycloak-multitenant/src/test/resources/keycloak-realm.json
- security/keycloak-oauth2/src/test/resources/keycloak-realm.json
- security/keycloak-oidc-client-basic/src/test/resources/keycloak-realm.json
- security/keycloak-oidc-client-extended/src/test/resources/keycloak-realm.json
- security/keycloak-oidc-client-reactive-basic/src/test/resources/keycloak-realm.json
- security/keycloak-oidc-client-reactive-extended/src/test/resources/keycloak-realm.json
- security/keycloak-webapp/src/test/resources/keycloak-realm.json
- security/keycloak/src/test/resources/keycloak-realm.json
- security/oidc-client-mutual-tls/src/test/resources/keycloak-realm.json
Bumping framework as it contains image for Keycloak 24.
With this bump the fix for Keycloak 24 is backported (commit 29b0ee12f517a9fe5705d4080202a2de6fa55ca5 from https://github.com/quarkus-qe/quarkus-test-suite/pull/1829) 
> [3.8] Bump Framework + keycloak

- monitoring/micrometer-prometheus/src/main/java/io/quarkus/ts/micrometer/prometheus/PathPatternResource.java
- monitoring/micrometer-prometheus/src/test/java/io/quarkus/ts/micrometer/prometheus/HttpPathMetricsPatternIT.java
Test coverage for QUARKUS-4430  https://github.com/quarkusio/quarkus/pull/39583
TP: https://github.com/quarkus-qe/quarkus-test-plans/pull/177 
> Test coverage for Keep the URIs in the metrics tag with 302 and 404 patterns

- README.md
- logging/thirdparty/pom.xml
- logging/thirdparty/src/main/java/io/quarkus/ts/logging/jboss/LogResource.java
- logging/thirdparty/src/main/resources/application.properties
- logging/thirdparty/src/test/java/io/quarkus/ts/logging/jboss/SyslogIT.java
- logging/thirdparty/src/test/resources/syslog-ng.conf
- pom.xml
Adds new module for working with syslogs, since jboss uses json logs which have less predictable size.
Uses official image of sylog-ng. Syslog-ng was chose over rsyslog and logstash because it supports syslog input and stdout output out of the box, without additional plugins.
Required for https://issues.redhat.com/browse/QUARKUS-4531
> QQE-673 | Cover max-length option for syslog logs

- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/Brotli4JHttpIT.java
I realized that our quarkus test suite was failing on our CI because the test Brotli4JHttpIT failure :
https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/9509280971
After investigate a bit what had changed (because previosly our tests worked properly) I discovered that these changes https://github.com/quarkusio/quarkus/pull/40750/files affected our test failing.
In shorts, currently gzip compression works by default if we have set `quarkus.http.enable-compression=true` and we are not specifying any encoding in the request.
> Fix Brotli4JHttpIT.checkTextPlainDefaultWithoutBrotli4JEncoding test

- README.md
- logging/thirdparty/pom.xml
- logging/thirdparty/src/main/java/io/quarkus/ts/logging/jboss/LogResource.java
- logging/thirdparty/src/main/resources/application.properties
- logging/thirdparty/src/test/java/io/quarkus/ts/logging/jboss/SyslogIT.java
- logging/thirdparty/src/test/resources/syslog-ng.conf
- monitoring/micrometer-prometheus/src/main/java/io/quarkus/ts/micrometer/prometheus/PathPatternResource.java
- monitoring/micrometer-prometheus/src/test/java/io/quarkus/ts/micrometer/prometheus/HttpPathMetricsPatternIT.java
- monitoring/opentelemetry/pom.xml
- monitoring/opentelemetry/src/test/java/io/quarkus/ts/opentelemetry/DevModeOpenTelemetryIT.java
- monitoring/opentelemetry/src/test/java/io/quarkus/ts/opentelemetry/OpenTelemetryIT.java
- monitoring/opentelemetry/src/test/java/io/quarkus/ts/opentelemetry/OpenTelemetryProxyIT.java
- pom.xml
Backport of:
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1834
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1838
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1839 + change from rest to resteasy-reactive
> [3.8] Backport for 3.8 branch 20.6.2024

- http/http-advanced/src/main/java/io/quarkus/ts/http/advanced/GzipResource.java
- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/GzipMaxInputIT.java
- http/http-advanced/src/test/resources/gzip.properties
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliPomIntegrityIT.java
- quarkus-cli/src/test/resources/test.properties
Adding TD for the next backports for 3.8 branch:
- [Preserve POM format when extensions are added/removed](https://github.com/quarkusio/quarkus/pull/40663/commits/2bb40f94ac518a45a092054f42b06f4e60680b24)
- [Properly convert MemorySize to RESTEasy configuration](https://github.com/quarkusio/quarkus/pull/40663/commits/7562534cdd8a9d4fc8092a0b8812b80be76b0063)
These backports changes have been done also in main branch ---> https://github.com/quarkus-qe/quarkus-test-suite/pull/1802
> Add backports-3.8.5 coverage for QuarkusCliPomIntegrity and GzipMaxInput

- messaging/kafka-producer/src/test/java/io/quarkus/ts/messaging/kafka/producer/DevModeKafkaSnappyIT.java
- messaging/kafka-producer/src/test/java/io/quarkus/ts/messaging/kafka/producer/OpenShiftKafkaSnappyIT.java
- messaging/kafka-producer/src/test/java/io/quarkus/ts/messaging/kafka/producer/SnappyCompressionIT.java
- daily build is failing as SnappyCompressionIT is failing in native, Kafka reference https://quarkus.io/version/main/guides/kafka#using-snappy-for-message-compression says use `quarkus.kafka.snappy.enabled=true`
- `OpenShiftKafkaSnappyIT` was disabled in OpenShift in native mode, enabling it
- `KafkaConsumer` was not closed
- `DevModeKafkaSnappyIT` started: dev mode app, redpanda, prod mode app and kafka container (4 things), then tested:
- exactly same thing as was already tested by `SnappyCompressionIT` also in prod mode, not in the DEV mode!
- in the DEV mode, it tested that Redpanda was started, nothing else
- the `DevModeKafkaSnappyIT` is wrong name for test that does one thing related to DEV mode: test `kafkaContainerShouldBeStarted`
- there is no test plan matched or JIRA ticket …
> Fix Snappy tests in native, disable invalid DEV mode test and enable OpenShift native snappy test

- spring/spring-web/src/test/java/io/quarkus/ts/spring/web/bootstrap/OpenShiftSpringWebQuteIT.java
- spring/spring-web/src/test/java/io/quarkus/ts/spring/web/bootstrap/OpenShiftSpringWebRestIT.java
- spring/spring-web/src/test/java/io/quarkus/ts/spring/web/openapi/OpenShiftSpringWebOpenApiIT.java
- sql-db/hibernate-fulltext-search/src/test/java/io/quarkus/ts/hibernate/search/OpenShiftPostgresqlMultitenantHibernateSearchIT.java
- sql-db/multiple-pus/src/test/java/io/quarkus/ts/sqldb/multiplepus/OpenShiftMultiplePersistenceIT.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/OpenShiftMariaDbTransactionGeneralUsageIT.java
- sql-db/reactive-rest-data-panache/src/test/java/io/quarkus/ts/reactive/rest/data/panache/OpenShiftMariaDBPanacheResourceIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/OpenShiftMariaDB103DatabaseIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/OpenShiftMariaDBDatabaseIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/OpenShiftPostgresql10DatabaseIT.java
OpenShift tests are failing as Red Hat MariaDB and PostgreSQL images are using older versions than defaults configured at the build time. This is expected failure as it is explained in the migration guide https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.12#hibernate-orm.
We use:
- MariaDB 10.5 and 10.3
- PostgreSQL 10.23.0 (but image is `registry.redhat.io/rhel8/postgresql-10` so it's 10)
While defaults are:
- MariaDB 10.6.0
- PostgreSQL 12.0.0
> Set minimum database version to inform Hibernate our RH images are older than defaults which will fix failing OpenShift tests

- build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/AnalyticsUtils.java
Fix RHBQ version regex as dash `-` was used after the `Final` word. Now as the `Final` word is droped the delimeter from version and `redhat` keyword is dot `.`.
Tested it localy with `mvn clean validate compile test package verify -V -B -fae -P root-modules -Dmaven.repo.local=/home/jjedlick/work/3.8/rh-quarkus-platform-3.8.5.GA-maven-repository/maven-repository/ -Dinclude.quarkus-cli-tests -Dquarkus-plugin.version=3.8.5.redhat-00002 -Dquarkus.platform.version=3.8.5.redhat-00002 -Dquarkus.platform.artifact-id=quarkus-bom -Dquarkus.platform.group-id=com.redhat.quarkus.platform -pl build-time-analytics -Dit.test="*CliProdModeJvmIT#noExtensions"` which affected test
> Fix RHBQ version regex as dash was used after Final

- build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/AnalyticsUtils.java
Fixing same thing as #1856 just targeting 3.8 branch
> [3.8] Fix RHBQ version regex as dash was used after Final which was droped

- pom.xml
We use `openshift` system property to detect that OpenShift test is run here:
https://github.com/quarkus-qe/quarkus-test-framework/blob/f5c973082d109579fa1df09138ddc6d5fcdd496d/quarkus-test-core/src/main/java/io/quarkus/test/utils/TestExecutionProperties.java#L40
However IBM Z/PE and ARM64 don't have set this property, which means we don't detect OpenShift test execution in some contexts. For example, certificates are not mounted as we don't know about OpenShift.
Later, this needs to be ported to the main branch.
> [3.8] Detect that OpenShift test is run when OpenShift IBM Z/PE and ARM64 profiles are used

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
Reverts quarkus-qe/quarkus-test-suite#1759
As landing page on windows is fixed in RHBQ 3.8.5, it is no longer necessary to have this exception in 3.8 branch.
> Revert "[3.8] Do not expect index page in DEV mode on Windows"

- pom.xml
ports https://github.com/quarkus-qe/quarkus-test-suite/pull/1855
> Detect that OpenShift test is run when OpenShift IBM Z/PE and ARM64 profiles are used

- http/rest-client-reactive/pom.xml
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/multipart/EncoderModeRestClient.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/multipart/Html5EncoderModeRestClient.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/multipart/Item.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/multipart/MyMultipartDTO.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/multipart/Rfc1738EncoderModeRestClient.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/multipart/Rfc3986EncoderModeRestClient.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/MultipartPostEncoderModeResource.java
- http/rest-client-reactive/src/main/resources/application.properties
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/HttpMultipartEncodeModeAndContentIT.java
- http/rest-client-reactive/src/test/resources/sampl'eñ.txt
- http/rest-client-reactive/src/test/resources/sample.txt
Adding TD for the next backport:
[Improve the multipart encoded mode handling in the rest client](https://github.com/quarkusio/quarkus/pull/39770)
This PR adds test coverage for the improved multipart encoder mode handling in the REST client. 
The tests cover the encoder modes (HTML5, RFC1738, RFC3986), verifying the correct encoding of multipart requests and successful parsing by a Vert.x server. Data integrity checks, including file content verification via size and headers, are performed.
Note: Direct verification of the specific encoder mode used during the transmission is not directly feasible, but 
the tests ensure that the resulting content is correctly parsed and interpreted by the server, providing confidence that the appropriate encoder mode was applied.
Please select the …
> Add test coverage for improvement multipart encoded mode in rest-client

- sql-db/reactive-vanilla/src/test/java/io/quarkus/ts/reactive/db/clients/DevModeMultipleReactiveSqlClientsIT.java
Disabling as it's failing during 3.8.5 processing in FIPS-enabled environment.
Failures are due to known issue https://github.com/quarkusio/quarkus/issues/40526.
Test plan for FIPS expects this test to be disabled https://github.com/quarkus-qe/quarkus-test-plans/blob/d1a665ed050a3cbbc02ab7996ea494a0eec442b6/QUARKUS-3225.md?plain=1#L48.
> Disable DevModeMultipleReactiveSqlClientsIT on FIPS-enabled env

- sql-db/reactive-vanilla/src/test/java/io/quarkus/ts/reactive/db/clients/DevModeMultipleReactiveSqlClientsIT.java
- sql-db/sql-app-compatibility/src/test/java/io/quarkus/ts/sqldb/compatibility/MySqlDatabaseIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/MySqlDatabaseIT.java
- backports https://github.com/quarkus-qe/quarkus-test-suite/pull/1867
- MySqlDatabaseIT is disabled in FIPS-enabled environment as it only works in 3.9+
> [3.8] Disable MysqlDatabaseIT and DevModeMultipleReactiveSqlClientsIT in FIPS-enabled environment

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
* Re-enabling test that's fixed in Quarkus 3.8.5.
> [3.8] [QUARKUS-4184] Re-enable CLI Gradle test

- cache/caffeine/src/main/java/io/quarkus/ts/cache/caffeine/ReactiveWithCacheResource.java
- cache/caffeine/src/test/java/io/quarkus/ts/cache/caffeine/cache/caffeine/CaffeineCacheIT.java
Add test  to verify that failed unis are not cached according this fix:
https://github.com/quarkusio/quarkus/pull/39762 
> Test to verify that failed unis are not cached

- cache/caffeine/src/main/java/io/quarkus/ts/cache/caffeine/ReactiveWithCacheResource.java
- cache/caffeine/src/test/java/io/quarkus/ts/cache/caffeine/cache/caffeine/CaffeineCacheIT.java
Add test to verify that failed unis are not cached according the backport fix in 3.8.:
https://github.com/quarkusio/quarkus/pull/39762
> Add test to verify failed unis are not cached

- cache/caffeine/src/main/java/io/quarkus/ts/cache/caffeine/ReactiveWithCacheResource.java
- cache/caffeine/src/test/java/io/quarkus/ts/cache/caffeine/cache/caffeine/CaffeineCacheIT.java
Fix logic test to verify that failed unis are not cached according this fix:
https://github.com/quarkusio/quarkus/pull/39762
It's backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/1873#pullrequestreview-2165906696
> [3.8] [QUARKUS-4541] Fix test to verify that failed unis are not cached

- pom.xml
- websockets/quarkus-websockets/pom.xml
Update framework to the 1.3.1 and fix weird compilation failure in websockets, where java was not able to find io.quarkus.vertx.web.RouteFilter
> [3.2] Update framework to the latest version

- sql-db/panache-flyway/src/test/java/io/quarkus/ts/sqldb/panacheflyway/dbpool/MySqlDatabaseTestResource.java
We cannot rely on `localhost`. This is consequence of my PR https://github.com/quarkus-qe/quarkus-test-suite/pull/1782 but it only demonstrates when run on our Windows runners that rely on Minikube.
> Fix MySQL container host used in AgroalPoolTest as Windows tests are using remote Docker client

- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/DevModeGrpcIntegrationReactiveIT.java
- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/DevModeGrpcIntegrationIT.java
These tests were long disabled, I enabled and refactored them lately https://github.com/quarkus-qe/quarkus-test-suite/pull/1833 but it turns out that Playwright doesn't return same content of shadow DOMs. I think gRPC service implementations needs to be accessed directly as they are in visible DOM.
For context, the check I am changing here wasn't part of original test development, I included it as it seems right that implementation class signatures should be displayed.
Tested this PR both on Windows and Linux and works. Original failures can only be reproduced on Windows runners with Docker as we don't run DEV mode tests on GitHub runners. Reason for this is that we cannot detect automatically if Dev Service requiring Linux containers is started.
> Fix gRPC DEV UI tests on Windows as Vaadin grid is formed differently and we cannot see shadow DOM content

- javaee-like-getting-started/src/test/java/io/quarkus/ts/javaee/gettingstarted/OpenAPITracingIT.java
The Quarkus bumped Otel https://github.com/quarkusio/quarkus/pull/41521. This update have some breaking changes in [HTTP semantic conventions](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/migration-guide.md#summary-of-changes). 
I also look through the codebase and didn't find any occurencies of changed attributes. It's possible that there will be another fail because of the Otel bump.
> Update otel properties the Quarkus bumped the otel

- .github/workflows/ci.yml
This is port from https://github.com/quarkus-qe/quarkus-test-suite/pull/1866 because the name of [file](https://github.com/quarkus-qe/quarkus-test-suite/pull/1866/files#diff-4b63f5a6e9db4df956e6009a8113f592e5b43ffe603949d060255ad90bcb216e) contains special character. This wasn't caught on main because of some wierd bug with CI where it sometimes don't detecting files.
Don't expect this happend much often but it's better to have it in main also
> Fix possible CI (detect modules) failure because of the special characters in filename

- build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/AbstractAnalyticsIT.java
Fix platform and core version assumption for buildtimeanalytics tests
An example of problematic failure from RHBQ run
```
All extensions versions must match pattern: '3.8.5.SP1-redhat-00001'. Offending extensions: 
[io.quarkus:quarkus-arc:3.8.5.redhat-00004] ==> expected: <0> but was: <1>
```
> Fix platform and core version assumption for buildtimeanalytics tests

- funqy/knative-events/src/test/java/io/quarkus/ts/funqy/knativeevents/ServerlessExtensionOpenShiftFunqyKnEventsIT.java
- http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/ServerlessExtensionDockerBuildStrategyOpenShiftHttpMinimumReactiveIT.java
- http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/ServerlessExtensionOpenShiftHttpMinimumReactiveIT.java
- http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/ServerlessExtensionDockerBuildStrategyOpenShiftHttpMinimumIT.java
- http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/ServerlessExtensionOpenShiftHttpMinimumIT.java
- http/vertx/src/test/java/io/quarkus/ts/vertx/ServerlessExtensionDockerBuildStrategyOpenShiftVertxIT.java
- http/vertx/src/test/java/io/quarkus/ts/vertx/ServerlessExtensionOpenShiftVertxIT.java
- messaging/amqp-reactive/src/test/java/io/quarkus/ts/messaging/amqpreactive/OpenShiftProdAmqpReactiveIT.java
- messaging/cloud-events/amqp-binary/src/test/java/io/quarkus/ts/messaging/cloudevents/amqpbinary/OpenShiftBinaryCloudEventsOverProdAmqpIT.java
- messaging/cloud-events/amqp-json/src/test/java/io/quarkus/ts/messaging/cloudevents/amqpjson/OpenShiftJSONCloudEventsOverProdAmqpIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftAmqStreamsKafkaStreamIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OperatorOpenShiftAmqStreamsKafkaStreamIT.java
- messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/OpenShiftAmqStreamsKafkaAvroIT.java
- messaging/qpid/src/test/java/io/quarkus/ts/messaging/qpid/OpenShiftQpidIT.java
- monitoring/micrometer-prometheus-kafka-reactive/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/reactive/OpenShiftAmqStreamsAlertEventsReactiveIT.java
- monitoring/micrometer-prometheus-kafka/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/OpenShiftAmqStreamsAlertEventsIT.java
- pom.xml
- super-size/many-extensions/src/test/java/io/quarkus/ts/many/extensions/ServerlessExtensionDockerBuildStrategyOpenShiftManyExtensionsIT.java
- super-size/many-extensions/src/test/java/io/quarkus/ts/many/extensions/ServerlessExtensionOpenShiftManyExtensionsIT.java
* Now that Red Hat Serverless is shipped for OCP on aarch64, the tests should be re-enabled. (fixes #1142)
* The AMQ streams operator is now delivered for OCP on aarch64, so the tests need to be enabled. (fixes #1147)
* Bumping AMQ broker container to 7.12 which supports all Quarkus  supported platforms, as opposed to the 7.1 that we used released from 2019.
* Enabling AMQ stream tests on aarch64 as the test container is now multi-arch. (fixes #1144)
* Since library/mongodb is multiarch image, pinning it to tag is not needed or useful - this way we won't get fixes for Mongo container. So this commit removes the tag and re-uses the one used in all the other profiles.
> Draft: Enable tests for test services now available on aarch64

- pom.xml
Upstream did it some time ago: https://github.com/quarkusio/quarkus/pull/39389
> Update Infinispan to version 15

- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/MssqlTransactionGeneralUsageIT.java
Adding `-C` argument to automaticaly trust server certificate (docs [here](https://learn.microsoft.com/en-us/sql/tools/sqlcmd/sqlcmd-utility?view=sql-server-ver16&tabs=go%2Clinux&pivots=cs1-bash#-c)). It seems that latest update change now need trusted certificate by default. 
Also for some unknow reason the `mssql-tools` dir change the name to `mssql-tools18`.
> Fix MSSQL setup for narayana XA transactions

- quarkus-cli/pom.xml
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliConfigEncryptIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliConfigRemoveIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliConfigSetIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliHelpIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/config/surefire/EncryptPropertyTest.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/config/surefire/RemovePropertyTest.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/config/surefire/SetPropertyTest.java
Implements TP: https://github.com/quarkus-qe/quarkus-test-plans/pull/180
> Test Quarkus CLI Config subcommands for creating, updating, removing and encrypting configuration properties

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliConfigEncryptIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliConfigRemoveIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliConfigSetIT.java
Disabling tests introduced in https://github.com/quarkus-qe/quarkus-test-suite/pull/1902 to fix Windows failures and make it possible to run Quarkus CLI module with older versions.
- https://github.com/quarkusio/quarkus/pull/41203 introduced breaking changes that I didn't mention
- ATM our Windows runners use the latest released Quarkus 3.12
- if anyone want to run Quarkus CLI module with older version to debug older versions, the test would fail
> Disable Quarkus CLI config tests on Quarkus version older than 3.13 due to breaking changes between 3.13 and 3.12

- external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftTodoDemoIT.java
webbundler does not have supported for s390x & ppc64le. OpenShiftTodoDemoIT for p/z
> [3.8] Disable OpenShiftTodoDemoIT in IBM PE/Z Maven profile as webbundler does not have supported for s390x & ppc64le. 

- cache/redis/src/main/java/io/quarkus/ts/cache/redis/ApplicationScopeService.java
- cache/redis/src/main/java/io/quarkus/ts/cache/redis/BaseServiceWithCache.java
- cache/redis/src/main/java/io/quarkus/ts/cache/redis/RequestScopeService.java
- cache/redis/src/main/java/io/quarkus/ts/cache/redis/ServiceWithCacheResource.java
- cache/redis/src/main/java/io/quarkus/ts/cache/redis/TemplateCacheResource.java
- cache/redis/src/test/java/io/quarkus/ts/cache/redis/RedisCacheIT.java
Fix package names inside `cache/redis` module. I think, them were copied from `cache/caffeine` without change.
> Rename package names in redis cache module

- .github/workflows/ci.yml
- .github/workflows/daily.yaml
Adding the logic to run the Linux native run if no modules are detected. This change not include windows as on PRs we don't even run native windows.
I decided make `NATIVE_MODULES_MAVEN_PARAM`  on multiple row as it's more readable. So I need to clean it with `tr -d -s '\n' ' '` for env variable to be one line string.
Also updating the modules load for native execution time be similar for all modules.
> Updating PR CI to run full native if no changes in modules are detected

- README.md
- cache/infinispan/pom.xml
- cache/infinispan/src/main/java/io/quarkus/ts/cache/infinispan/ApplicationScopeService.java
- cache/infinispan/src/main/java/io/quarkus/ts/cache/infinispan/BaseServiceWithCache.java
- cache/infinispan/src/main/java/io/quarkus/ts/cache/infinispan/BlockingWithCacheResource.java
- cache/infinispan/src/main/java/io/quarkus/ts/cache/infinispan/CacheExpirationResource.java
- cache/infinispan/src/main/java/io/quarkus/ts/cache/infinispan/ReactiveWithCacheResource.java
- cache/infinispan/src/main/java/io/quarkus/ts/cache/infinispan/RequestScopeService.java
- cache/infinispan/src/main/java/io/quarkus/ts/cache/infinispan/ServiceWithCacheResource.java
- cache/infinispan/src/main/resources/application.properties
- cache/infinispan/src/test/java/io/quarkus/ts/cache/infinispan/InfinispanCacheIT.java
- cache/infinispan/src/test/java/io/quarkus/ts/cache/infinispan/OpenShiftInfinispanCacheIT.java
- cache/infinispan/src/test/resources/test.properties
- pom.xml
Test coverage for QQE-832
TP: https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QQE-832.md 
New tests:
- Use [custom POJOs](https://quarkus.io/guides/cache-infinispan-reference#marshalling-your-pojos) as cache value, verify marshalling in Quarkus Infinispan. See `ExpensiveResponse` in cache service.
-  Test [Cache expiration](https://quarkus.io/guides/cache-infinispan-reference#expiration)  properties. `testCacheLifespan` and `testCacheMaxIdle`.
> Add coverage for Infinispan cache extension

- messaging/kafka-strimzi-avro-reactive-messaging/src/main/resources/application.properties
Daily build fails over https://github.com/quarkusio/quarkus/issues/42504. I copied this workaround from https://github.com/quarkus-qe/beefy-scenarios/pull/498 so that we run other tests as well (now they are cancelled) and detect problems early.
> Dereference schema to workaround Strimzi/Apicurio failures

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/update/AbstractQuarkusCliUpdateIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/update/RHBQPlatformAppManager.java
This PR does not work, as it requires https://github.com/quarkus-qe/quarkus-test-framework/pull/1188 to be effective here.
This makes a proposal how Quarkus CLI test could look in the future. Idea is to create common tests and other support methods in parent class and making some kind of a "framework". For each new tested version we can add new class, which should be more or else simple.
Edit: This PR requires https://github.com/quarkus-qe/quarkus-test-framework/pull/1236 and other things in framework 1.5.0.Beta13. **So do not merge until this is released and updated in TS.** 
> Quarkus CLI update test

- .github/workflows/ci.yml
CI is trying to build also apps that are stored in **/resouces/*. Run into this issue in https://github.com/quarkus-qe/quarkus-test-suite/pull/1927
These apps are not tests but are used in actual tests. We should not build them as a modules.
> [3.8] Exclude apps in resources/* from CI

- .github/workflows/ci.yml
CI is trying to build also apps that are stored in **/resouces/*. Run into this issue in https://github.com/quarkus-qe/quarkus-test-suite/pull/1927
These apps are not tests but are used in actual tests. We should not build them as a modules.
> Exclude apps in resources/* from CI

- .github/workflows/ci.yml
- README.md
- sql-db/narayana-transactions/src/main/java/io/quarkus/ts/service/ServiceResource.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/MssqlTransactionGeneralUsageIT.java
When XA is enabled, connections to MS SQL may leak. This tests checks, that this is not happening.
> Reproducer for leaking connection in XA mode

- pom.xml
Updating the name of `build/docker` module for `root-modules-no-qute` profile. This should fix the problem with rebasing of dependabot.
Also adding `bulid/podman` to the profile.
> Update `root-modules-no-qute` profile modules

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateExtensionIT.java
Generated extensions use maven-enforcer-plugin, which,among other things, enforces https for repositories and mirrors.  This patch disables this behavior.
Potential permanent solution: https://issues.redhat.com/browse/QQE-907
> Let created extension to use insecure repositories

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliConfigEncryptIT.java
Related to this test framewor changes-->  https://github.com/quarkus-qe/quarkus-test-framework/pull/1238 
There are some failures in our win jenkins jobs related to QuarkusCliConfigEncryptIT because special characters and bold formatted Strings that affect the test execution on Windows OS.
> Fix secretFormat on QuarkusCliConfigEncryptIT for Windows job

- .github/workflows/ci.yml
- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/GzipMaxInputIT.java
- pom.xml
- Bumps Quarkus version to 3.8.6
- Enable gzip `sendMaximumAllowedPayload` test in native mode as issue was fixed and backported to 3.8 (3.8.6)
> [3.8] Bump Quarkus version to 3.8.6 and enable sendMaximumAllowedPayload test in native

- .github/workflows/ci.yml
- .github/workflows/daily.yaml
> Reduce log size in CI runs

- monitoring/micrometer-prometheus-kafka/src/main/java/io/quarkus/ts/micrometer/prometheus/kafka/Channels.java
- monitoring/micrometer-prometheus-kafka/src/main/java/io/quarkus/ts/micrometer/prometheus/kafka/UndeliverableConsumer.java
- monitoring/micrometer-prometheus-kafka/src/main/java/io/quarkus/ts/micrometer/prometheus/kafka/UndeliverableProducer.java
- monitoring/micrometer-prometheus-kafka/src/main/resources/application.properties
- monitoring/micrometer-prometheus-kafka/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/DLQMetricCountIT.java
Add test for messages send to kafka dead-letter-queue and their counting in micrometer metrics. See https://github.com/smallrye/smallrye-reactive-messaging/issues/2473
> add test for DLQ metric counting

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/update/AbstractQuarkusCliUpdateIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/update/Quarkus213to38CliUpdateIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/update/Quarkus32to38CliUpdateIT.java
Quarkus update test should only run if tested version is RHBQ (as we have test for RHBQ). Also adding tag "quarkus-cli" which was missing.
This should fix issues in GH CI, which was trying to run this on windows (missing quarkus-cli tag) and with upstream version. Which caused CI to fail (see fail in e.g. https://github.com/quarkus-qe/quarkus-test-suite/pull/1966)
> Run quarkus cli update only on RHBQ and with tag "quarkus-cli"

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/update/AbstractQuarkusCliUpdateIT.java
Similar to https://github.com/quarkus-qe/quarkus-test-suite/pull/1967. add quarkus-cli tag. Check RHBQ version in updated app only if we actually work RHBQ.
> Add quarkus-cli tag to update test and check RH version only on RHBQ

- monitoring/micrometer-prometheus-kafka-reactive/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/reactive/KafkaAndMetricsIT.java
Ensure Kafka version is visible in metrics, especially in native mode
Triggers: https://github.com/quarkusio/quarkus/pull/41278 and https://github.com/quarkusio/quarkus/issues/42865
Backport is blocked until fix for https://github.com/quarkusio/quarkus/issues/42865 gets into Quarkus 3.8 and 3.15
FAIL: `mvn clean verify -f monitoring/micrometer-prometheus-kafka-reactive -Dit.test=KafkaAndMetricsIT -Dnative -Dquarkus.platform.version=3.14.1 -Dquarkus.native.container-build=false -Dreruns=0`
PASS: `mvn clean verify -f monitoring/micrometer-prometheus-kafka-reactive -Dit.test=KafkaAndMetricsIT -Dnative -Dquarkus.platform.version=999-SNAPSHOT -Dquarkus.native.container-build=false`
> Ensure Kafka version is visible in metrics, especially in native mode

- http/http-minimum-reactive/src/main/java/io/quarkus/ts/http/minimum/reactive/AbstractApplication.java
- http/http-minimum/src/main/java/io/quarkus/ts/http/minimum/AbstractApplication.java
Ensure abstract jakarta.ws.rs.core.Application is ignored
Trigger: https://github.com/quarkusio/quarkus/pull/41465
Identified issue: https://github.com/quarkusio/quarkus/issues/42963
PASS:  `mvn clean verify -f http/http-minimum -Dreruns=0 -Dquarkus.platform.version=3.12.1`
FAIL: `mvn clean verify -f http/http-minimum -Dreruns=0 -Dquarkus.platform.version=3.12.0`
Reactive - `mvn clean verify -f http/http-minimum-reactive -Dreruns=0 -Dquarkus.platform.version=3.12.0`
> Ensure abstract jakarta.ws.rs.core.Application is ignored

- http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/DownloadResource.java
- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/DownloadResourceIT.java
Make sure AsyncFile gets closed
Trigger: https://github.com/quarkusio/quarkus/issues/41811
PASS: `mvn clean verify -f http/http-advanced-reactive -Dit.test=DownloadResourceIT -Dquarkus.platform.version=3.12.3`
FAIL: `mvn clean verify -f http/http-advanced-reactive -Dit.test=DownloadResourceIT -Dquarkus.platform.version=3.12.2`
> Make sure AsyncFile gets closed

- security/vertx-jwt/src/test/java/io/quarkus/ts/security/vertx/AbstractCommonIT.java
Addresses correct point raised here https://github.com/quarkus-qe/quarkus-test-suite/pull/1973#discussion_r1743954822
Context: ATM we always set CA cert to truststore (which is correct place) even when `configureTruststore=false`. My logic was that you rarely need PEM key/cert without CA cert. But we need to tweak CertificateBuilder and correct Javadoc to explain why is CA cert set. Or agree to explicitly require `configureTruststore=true`.
Whatever we agree on, my thinking is that this option has no negative impact for this scenario while previous configures HTTPS.
> Dont configure HTTPS in security Vert.X JWT tests

- build/podman/pom.xml
The machines we use for OCP do not have podman and fail when we are trying to run the build on them
> Disable podman build on Openshift runs

- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/fault/tolerance/HeaderResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/fault/tolerance/RequestIdClientRequestFilter.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/fault/tolerance/RequestIdContainerRequestFilter.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/fault/tolerance/RequestIdManager.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/fault/tolerance/RequestIdManagerImpl.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/fault/tolerance/RetryClient.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/fault/tolerance/ServerRetryResource.java
- http/rest-client-reactive/src/main/resources/application.properties
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientRetryIT.java
Migrates issue reproducer from QUARKUS-4477. Issue fix was provided in https://github.com/quarkusio/quarkus/pull/39988/commits/b9cc3c2dc65a6f61641c83a940e13c116ce6cd0c
Prerequisite:
```
sed -i 's/quarkus-rest-client-jackson/quarkus-rest-client-reactive-jackson/g' http/rest-client-reactive/pom.xml
sed -i 's/quarkus-rest-jackson/quarkus-resteasy-reactive-jackson/g' http/rest-client-reactive/pom.xml
Comment BrokenBlockingApi as it fails compilation in older Quarkus versions
```
PASS: `mvn clean verify -f http/rest-client-reactive -Dit.test=ReactiveRestClientRetryIT -Dquarkus.platform.version=3.8.6 -Dnative`
FAIL: `mvn clean verify -f http/rest-client-reactive -Dit.test=ReactiveRestClientRetryIT -Dquarkus.platform.version=3.8.5 -Dnative -Dreruns=0`
> Verify fault tolerance with rest client reactive

- quarkus-cli/pom.xml
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliTlsCommandIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/tls/surefire/TlsCommandTest.java
Adds Quarkus CLI TLS command test coverage as planned in the TP: https://github.com/quarkus-qe/quarkus-test-plans/pull/184
> Add Quarkus CLI TLS command test coverage

- lifecycle-application/pom.xml
Update lifecycle-applicatio to be more robust and independent
* Using quarkus-spring-core-api which has no deps, spring-di depends on arc 
* Customizing BOM instead of version which turned out to be quite problematic because of branching
> Update lifecycle-applicatio to be more robust and independent

- .github/workflows/ci.yml
Sometimes we see that GitHub action `tj-actions/changed-files` fails with `Merge base is not in the local history, fetching remote target branch again..` and `Unable to find merge base between ...` etc.
We have seen this message (it is present twice in that script, but we hit the one I am pointing to): https://github.com/tj-actions/changed-files/blob/1d9fdda44c9da3604e9be858b3edb3e0501302af/src/commitSha.ts#L598
My thinking is that we compare it with base branch HEAD SHA from GH PR event. However:
- between PR event and time when `changed-files` action and `checkout` are run, there is some time so there can be changes on the target branch, therefore ideally we want to have event base HEAD SHA to be matching to the actual base HEAD sha that is fetched; action taken
- moving checkout and …
> Fix GitHub changed-files issue occurring when fork branch is not rebased on the PR target branch resulting in inability to detect changes

- build/podman/pom.xml
Follow-up to https://github.com/quarkus-qe/quarkus-test-suite/pull/1981 which id double verified on our Jenkins
> Properly disable the build of podman on openshift

- http/management/src/main/java/io/quarkus/qe/ManagementRoute.java
- http/management/src/test/java/io/quarkus/qe/MutualTlsManagementInterfaceIT.java
- tests TLS registry with management interface
- tests certificate reloading
> Test Mutual TLS with Management interface configured using TLS Registry extension and certificate reloading

- http/rest-client-reactive/src/test/java/hero/Hero.java
- http/rest-client-reactive/src/test/java/hero/HeroClient.java
- http/rest-client-reactive/src/test/java/hero/HeroClientResource.java
- http/rest-client-reactive/src/test/java/hero/HeroResource.java
- http/rest-client-reactive/src/test/java/hero/Villain.java
- http/rest-client-reactive/src/test/java/hero/VillainClient.java
- http/rest-client-reactive/src/test/java/hero/VillainClientResource.java
- http/rest-client-reactive/src/test/java/hero/VillainResource.java
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/OpenShiftServingCertificatesIT.java
- http/rest-client-reactive/src/test/resources/certificate-serving-client.properties
- http/rest-client-reactive/src/test/resources/certificate-serving-server.properties
This is quite similar to what I have done in QE Test Framework https://github.com/quarkus-qe/quarkus-test-framework/pull/1270 because I think it tests all we need from TLS Registry integration with REST client and OpenShift certificate serving. Few differences:
- test native as well; what we want to test in native is:
- certificates are picked up by Quarkus app in the native mode (that is TLS registry level, shared)
- integration with OpenShift according to the TLS registry section https://quarkus.io/guides/tls-registry-reference#utilizing-openshift-serving-certificates (again, not relevant to specific client impl.)
- here it is tested that both HTTP server and REST client are configured with TLS version configured in TLS registry and they do require it
> Test OpenShift serving certificates and TLS registry with REST client

- monitoring/opentelemetry/src/test/java/io/quarkus/ts/opentelemetry/OpenTelemetryManagementIT.java
We have 15 tests with Jaeger container, so I have decided to enable TLS in one of them and include test coverage for TLS registry integration with OpenTelemetry there.
> Test OpenTelemetry integration with TLS registry and exporting traces using secured channel

- infinispan-client/src/test/resources/infinispan_cluster_config.yaml
"Cache" service is deprecated and removed from the newest versions of Inifinspan[1][2] and it already became a problem for IBM folks[3]
[1] https://access.redhat.com/solutions/7010384
[2] https://access.redhat.com/solutions/6972352
[3] https://issues.redhat.com/browse/QQE-961
> Switch to supported service type

- README.md
- pom.xml
* To avoid needing to define the same multiarch container versions for bare metal and OpenShift use cases, this commit turns openshift-arm into general aarch64 profile.
* Updating the readme file with examples on how to run this profile with both OpenShift and bare metal uses.
> [3.15] Turn openshift-arm profile into general aarch64

- README.md
- pom.xml
* To avoid needing to define the same multiarch container versions for bare metal and OpenShift use cases, this commit turns openshift-arm into general aarch64 profile.
* Updating the readme file with examples on how to run this profile with both OpenShift and bare metal uses.
> [3.8] Turn openshift-arm profile into general aarch64

- infinispan-client/src/test/resources/infinispan_cluster_config.yaml
"Cache" service is deprecated and removed from the newest versions of Inifinspan[1][2] and it already became a problem for IBM testing folks[3]
[1] https://access.redhat.com/solutions/7010384
[2] https://access.redhat.com/solutions/6972352
[3] https://issues.redhat.com/browse/QQE-961
Backports https://github.com/quarkus-qe/quarkus-test-suite/pull/1994
> [3.8] Switch to supported service type

- external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftWorkshopHeroesIT.java
[3.8] Pin OpenShiftWorkshopHeroesIT to concrete commit
The one before https://github.com/quarkusio/quarkus-workshops/commit/269a8d59be2784e5f291d32a171b5322bb50ad68 change
Tried `mvn clean verify -f external-applications/ -Dit.test=OpenShiftWorkshopHeroesIT -Dopenshift` and it passed
> [3.8] Pin OpenShiftWorkshopHeroesIT to concrete commit

- sql-db/vertx-sql/src/test/java/io/quarkus/ts/vertx/sql/dbpool/PostgresqlResource.java
Fixing the `PostgresqlResource` when it's used with `registry.redhat.io/rhel9/postgresql-15` or other RH images.
The official from [docker hub](https://hub.docker.com/_/postgres) use `POSTGRES_` prefix for env variables, but RH one use `POSTGRESQL_` for env variables.
In general think that this should use `PostgresqlService` if possible to test it. Will look at it when I'll have time.
> [3.8] Fix PostgresqlResource which failing to start when using RH postgres image

- build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/AbstractAnalyticsIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DisabledOnRHBQAarch64NativeConditions.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DisabledOnRHBQWindowsConditions.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliExtensionsIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/update/AbstractQuarkusCliUpdateIT.java
Replaced `QuarkusProperties.getVersion().contains("redhat")` usage with `QuarkusProperties.isRHBQ()`
https://github.com/quarkus-qe/quarkus-test-framework/pull/1294
Waiting for merge
> Added isRHBQ method to check if the version contains string redhat

- pom.xml
Bumps Quarkus QE Test Framework to 1.4.12.
> [3.8] Bump Quarkus QE Test Framework to 1.4.12

- sql-db/sql-app-compatibility/src/test/java/io/quarkus/ts/sqldb/compatibility/DB2DatabaseIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DB2DatabaseIT.java
* Disabling DB2 tests on aarch64 profile as DB2 is not supported on aarch64 architecture, so our test service will not work.
Related issue:
* https://github.com/quarkus-qe/quarkus-test-suite/issues/2020
> Excluding DB2 tests from aarch64 profile

- sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/MsSQLDatabaseHibernateReactiveIT.java
- sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/openshift/OpenShiftHibernateReactiveMsSQLIT.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/MssqlTransactionGeneralUsageIT.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/OpenShiftMssqlTransactionGeneralUsageIT.java
- sql-db/reactive-rest-data-panache/src/test/java/io/quarkus/ts/reactive/rest/data/panache/MssqlPanacheResourceIT.java
- sql-db/reactive-rest-data-panache/src/test/java/io/quarkus/ts/reactive/rest/data/panache/OpenShiftMssqlPanacheResourceIT.java
- sql-db/reactive-vanilla/src/test/java/io/quarkus/ts/reactive/db/clients/DevModeMultipleReactiveSqlClientsIT.java
- sql-db/reactive-vanilla/src/test/java/io/quarkus/ts/reactive/db/clients/DevModeReactiveMssqlDevServiceUserExperienceIT.java
- sql-db/sql-app-compatibility/src/test/java/io/quarkus/ts/sqldb/compatibility/MssqlDatabaseIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMssqlDevServicesUserExperienceIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMssqlIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/MssqlDatabaseIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/OpenShiftMssqlDatabaseIT.java
- sql-db/vertx-sql/src/test/java/io/quarkus/ts/vertx/sql/handlers/MssqlHandlerIT.java
* Disabling MS SQL tests on aarch64 profile as MS SQL is not supported on aarch64 architecture, so our test service will not work.
Related issues:
* https://github.com/quarkus-qe/quarkus-test-suite/issues/2017
* https://github.com/quarkus-qe/quarkus-test-suite/issues/2018
* https://github.com/quarkusio/quarkus/issues/43375
> Excluding MS SQL tests from aarch64 profile

- security/jpa/src/test/java/io/quarkus/ts/security/jpa/OraclePlaintextExternalRolesJpaIT.java
- security/jpa/src/test/java/io/quarkus/ts/security/jpa/OracleSha512JpaIT.java
- sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/OracleDatabaseIT.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/OracleTransactionGeneralUsageIT.java
- sql-db/reactive-rest-data-panache/src/test/java/io/quarkus/ts/reactive/rest/data/panache/OraclePanacheResourceIT.java
- sql-db/sql-app-compatibility/src/test/java/io/quarkus/ts/sqldb/compatibility/OracleDatabaseIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeOracleDevServiceUserExperienceIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeOracleIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/OracleDatabaseIT.java
- sql-db/vertx-sql/src/test/java/io/quarkus/ts/vertx/sql/handlers/OracleHandlerIT.java
* Disabling Oracle tests on aarch64 profile as there's no Oracle container available for aarch64 architecture, so our test service will not work.
Related issues:
* https://github.com/quarkusio/quarkus/issues/43375
* https://github.com/quarkus-qe/quarkus-test-suite/issues/2022
> Excluding Oracle tests from aarch64 profile

- logging/thirdparty/src/test/java/io/quarkus/ts/logging/jboss/SyslogIT.java
- spring/spring-cloud-config/src/test/java/io/quarkus/ts/spring/cloud/config/SpringCloudConfigIT.java
* Disabling syslog tests on aarch64 as the currently used container is
not multiarch.
* Disabling Spring Cloud Server tests on aarch64 as there's no aarch64
based container we can use as test service.
Related issues:
* https://github.com/quarkus-qe/quarkus-test-suite/issues/2024
* https://github.com/quarkus-qe/quarkus-test-suite/issues/2025
> Disable tests missing aarch64 test services

- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftAmqStreamsKafkaStreamIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftStrimziKafkaStreamIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OperatorOpenShiftAmqStreamsKafkaStreamIT.java
- messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/OpenShiftAmqStreamsKafkaAvroIT.java
- messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/OpenShiftStrimziKafkaAvroIT.java
- messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/StrimziKafkaAvroIT.java
- monitoring/micrometer-prometheus-kafka-reactive/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/reactive/OpenShiftAmqStreamsAlertEventsReactiveIT.java
- monitoring/micrometer-prometheus-kafka-reactive/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/reactive/OpenShiftKafkaAlertEventsReactiveIT.java
- monitoring/micrometer-prometheus-kafka/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/OpenShiftAmqStreamsAlertEventsIT.java
- monitoring/micrometer-prometheus-kafka/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/OpenShiftKafkaAlertEventsIT.java
Due to https://github.com/quarkus-qe/quarkus-test-suite/pull/1854, we can re-enable the tests that were using the zookeeper image on IBM platforms. The previously skipped tests passing on latest 3.8 release.
Example test runs:
- https://master-jenkins-csb-runtimes-ibmzqe.apps.ocp-c1.prod.psi.redhat.com/view/RHOAR/job/rhbq-3.x-ocp4-rhel8-jdk17-new/40/
- https://master-jenkins-csb-runtimes-ibmzqe.apps.ocp-c1.prod.psi.redhat.com/view/RHOAR/job/rhbq-3.x-ocp4-rhel8-jdk21-new/46/
> [3.8] Re-enable tests on IBM platforms due to removal of zookeeper

- pom.xml
- quarkus-picocli/pom.xml
- quarkus-picocli/src/main/java/io/quarkus/ts/qe/command/AgeCommand.java
- quarkus-picocli/src/main/java/io/quarkus/ts/qe/command/CommonOptions.java
- quarkus-picocli/src/main/java/io/quarkus/ts/qe/command/EntryCommand.java
- quarkus-picocli/src/main/java/io/quarkus/ts/qe/command/HelloCommand.java
- quarkus-picocli/src/main/java/io/quarkus/ts/qe/command/OtherCommand.java
- quarkus-picocli/src/main/java/io/quarkus/ts/qe/command/OtherEntryCommand.java
- quarkus-picocli/src/main/java/io/quarkus/ts/qe/configuration/Config.java
- quarkus-picocli/src/main/java/io/quarkus/ts/qe/services/AgeService.java
- quarkus-picocli/src/main/java/io/quarkus/ts/qe/services/HelloService.java
- quarkus-picocli/src/test/java/PicocliDevIT.java
- quarkus-picocli/src/test/java/PicocliProdIT.java
- quarkus-picocli/src/test/resources/dev.properties
- quarkus-picocli/src/test/resources/prod.properties
JIRA: https://issues.redhat.com/browse/QUARKUS-4221
Currently, we are going to support Quarkus Picocli, so that's the reason for this new test coverage.
> Add coverage for quarkus-picocli

- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftAmqStreamsKafkaStreamIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftStrimziKafkaStreamIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OperatorOpenShiftAmqStreamsKafkaStreamIT.java
- messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/OpenShiftAmqStreamsKafkaAvroIT.java
- messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/OpenShiftStrimziKafkaAvroIT.java
- messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/StrimziKafkaAvroIT.java
- monitoring/micrometer-prometheus-kafka-reactive/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/reactive/OpenShiftAmqStreamsAlertEventsReactiveIT.java
- monitoring/micrometer-prometheus-kafka-reactive/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/reactive/OpenShiftKafkaAlertEventsReactiveIT.java
- monitoring/micrometer-prometheus-kafka/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/OpenShiftAmqStreamsAlertEventsIT.java
- monitoring/micrometer-prometheus-kafka/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/OpenShiftKafkaAlertEventsIT.java
Same as https://github.com/quarkus-qe/quarkus-test-suite/pull/2030, cherry-picking commit from previous PR.
> Re-enable tests on IBM platforms due to removal of zookeeper

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliTlsCommandIT.java
Here https://github.com/quarkus-qe/quarkus-test-suite/pull/2036 I fixed the issue for a keystore and didn't realize there is another issue with a truststore. I apologize for doing it on parts, but honestly, spawning Windows machine and setting up environment (or adjusting job) is way more time consuming then just fixing it here. Hope it's alright. Fixes:
```
[ERROR] io.quarkus.ts.quarkus.cli.tls.surefire.TlsCommandTest.testCommunicationUsingGeneratedCerts -- Time elapsed: 1.479 s <<< ERROR!
java.io.FileNotFoundException: C:UsersnameAppDataLocalTempquarkus-tls-command-tests17294939791165376470 ls-command-testquarkus-qe-cert-truststore.p12 (The filename, directory name, or volume label syntax is incorrect)
```
If there will be yet another issue after this one, I'll setup an instance.
Please …
> Fix QuarkusCliTlsCommandIT truststore config property value on Windows

- logging/thirdparty/pom.xml
- logging/thirdparty/src/main/java/io/quarkus/ts/logging/jboss/LogResource.java
- logging/thirdparty/src/main/resources/application.properties
- logging/thirdparty/src/test/java/io/quarkus/ts/logging/jboss/SyslogIT.java
- logging/thirdparty/src/test/resources/syslog-ng.conf
1. Use new syslog image (fixes https://github.com/quarkus-qe/quarkus-test-suite/issues/2024)
2. Refactor the test, since Quarkus changed the minimal limit to 128
> Change syslog image

- monitoring/opentelemetry/src/test/java/io/quarkus/ts/opentelemetry/JaegerLocalhostDockerManagerResource.java
- monitoring/opentelemetry/src/test/java/io/quarkus/ts/opentelemetry/OpenTelemetryManagementIT.java
Our AWS Windows runners use remote Docker agent and recently https://github.com/quarkus-qe/quarkus-test-suite/pull/1988 that forced host verification between Quarkus OpenTelemetry OTLP exporter and Jaeger traces collector. Hence test failed over:
```
15:48:19,981 INFO  [jaeger] {"level":"info","ts":1727106498.3438833,"caller":"grpc@v1.60.0/server.go:983","msg":"[core][Server #5] grpc: Server.Serve failed to create ServerTransport: connection error: desc = \"ServerHandshake(\\\"xx.xxx.xx.xx:51177\\\") failed: remote error: tls: unknown certificate\"","system":"grpc","grpc_log":true}
15:48:22,311 INFO  [pong] 15:48:18,305 Failed to export TraceRequestMarshalers. The request could not be executed. Full error message: Failed to create SSL connection
15:48:22,311 INFO  [pong] 15:48:18,305 …
```
> Fix OpenTelemetryManagementIT on Windows (when Linux containers are available) by porting remote Docker agent to localhost

- sql-db/reactive-vanilla/src/main/java/io/quarkus/ts/reactive/db/clients/HardCoverBookResource.java
- sql-db/reactive-vanilla/src/main/java/io/quarkus/ts/reactive/db/clients/ReactiveClientConverter.java
- sql-db/reactive-vanilla/src/main/java/io/quarkus/ts/reactive/db/clients/model/HardCoverBook.java
- sql-db/reactive-vanilla/src/main/resources/application.properties
- sql-db/reactive-vanilla/src/main/resources/mariadb-init-script.sql
- sql-db/reactive-vanilla/src/test/java/io/quarkus/ts/reactive/db/clients/DevModeMultipleReactiveSqlClientsIT.java
- sql-db/reactive-vanilla/src/test/java/io/quarkus/ts/reactive/db/clients/DevModeReactiveMssqlDevServiceUserExperienceIT.java
- sql-db/reactive-vanilla/src/test/java/io/quarkus/ts/reactive/db/clients/DevModeReactiveMysqlDevServiceUserExperienceIT.java
- sql-db/reactive-vanilla/src/test/java/io/quarkus/ts/reactive/db/clients/DevModeReactivePostgresqlDevServiceUserExperienceIT.java
- Closes: https://github.com/quarkus-qe/quarkus-test-suite/issues/2018
This test has 3 dbs (pg, mysql, mssql), MsSQL doesn't work on ARM64, other 2 options (DB2, Oracle) doesn't have OOTB containers for this platform. QUARKUS-1080 and QUARKUS-1408 doesn't seem specific for MSSQL. Hence using MariaDB.
> Fix DevModeMultipleReactiveSqlClientsIT on Aarch64 by switching MSSQL for MariaDB

- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftAmqStreamsKafkaStreamIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftStrimziKafkaStreamIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OperatorOpenShiftAmqStreamsKafkaStreamIT.java
- messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/OpenShiftAmqStreamsKafkaAvroIT.java
- messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/OpenShiftStrimziKafkaAvroIT.java
- messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/StrimziKafkaAvroIT.java
- monitoring/micrometer-prometheus-kafka-reactive/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/reactive/OpenShiftAmqStreamsAlertEventsReactiveIT.java
- monitoring/micrometer-prometheus-kafka-reactive/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/reactive/OpenShiftKafkaAlertEventsReactiveIT.java
- monitoring/micrometer-prometheus-kafka/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/OpenShiftAmqStreamsAlertEventsIT.java
- monitoring/micrometer-prometheus-kafka/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/OpenShiftKafkaAlertEventsIT.java
Same as https://github.com/quarkus-qe/quarkus-test-suite/pull/2030, cherry-picking commit from previous PR.
> [3.15] Re-enable tests on IBM platforms due to removal of zookeeper

- .github/workflows/ci.yml
This is the first step to improve flakiness reporting. I need to have the file that we can inspect. Later I can experiment on commenting etc..
Tested: https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/11019026504?pr=2045
> Improve flakiness reporting by storing flaky run report with failed test name and failure message

- .github/workflows/add-flaky-test-label.yml
This workflow needs to be in the main repo to test it (so this CI doesn't test this PR). What changes do is basically to download (optionally) flaky test reports (if present). And then use JBang script to create comment. I am using JBang script because parsing of the report is non-trivial. Any future improvements can be driven from the Flaky Run Reporter for both TS and FW.
I have tried it locally and I also wrote automated tests for that JBang script, but I cannot guarantee this will work OOTB.
One thing I am not sure about is uniqueness of the artifact names in case there is matrix within same job with multiple flakes. It's not exactly easy to figure from GH docs so far, so I say we shall see.
> Improve GitHub PR comments on flaky tests

- .github/workflows/ci.yml
Same as here https://github.com/quarkus-qe/quarkus-test-suite/pull/2045. I am creating dedicated commit because release workflows are not identical between main and the 3.15 branch. I believe changes on the main https://github.com/quarkus-qe/quarkus-test-suite/pull/2047 will also report 3.15 if this gets in and the 3.15 branch is going to be around for a while.
For example, here I saw flakes report comment: https://github.com/quarkus-qe/quarkus-test-suite/pull/2046
> [3.15] Archive flaky run reports

- .github/workflows/add-flaky-test-label.yml
I run test here https://github.com/quarkus-qe/quarkus-test-suite/pull/2050 and it seems that I need to setup Java for the JBang https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/11041992883/job/30673453268. I didn't experience this locally for obvious reasons.
> Setup Java for JBang purposes in the Flaky test workflow

- .github/workflows/add-flaky-test-label.yml
Tried it here https://github.com/quarkus-qe/quarkus-test-suite/pull/2050 and got https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/11049285587/job/30694514227. `Error: No file in /home/runner/work/quarkus-test-suite/quarkus-test-suite matched to [**/pom.xml], make sure you have checked out the target repository`
I made mistake. I read https://github.com/actions/setup-java?tab=readme-ov-file#caching-packages-dependencies. What I need is POM.xml if I want to cache it's dependencies, but there is no pom and JBang deps are not supported.
> Don't use Maven cache option in Flaky workflow Java setup

- .github/workflows/ci.yml
Here https://github.com/quarkus-qe/quarkus-test-suite/pull/2050#issuecomment-2376688319 I have got comment that was extracted from flaky run report. However there wasn't all the information I wanted show as in the action https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/11051367395/job/30701097990 that parses these information following thing happened:
```
Run gh run download $WORKFLOW_ID -n flaky-run-report-linux-jvm-latest || true
error downloading flaky-run-report-linux-native-latest: error extracting zip archive: error extracting "flaky-run-report.json": open flaky-run-report.json: file exists
error downloading flaky-run-report-windows-jvm-latest: error extracting zip archive: error extracting "flaky-run-report.json": open flaky-run-report.json: file exists
```
So my …
> Rename Flaky Run reports to avoid conflicts when multiple flakes happen in different runs

- http/jakarta-rest-reactive/src/main/java/io/quarkus/ts/http/jakartarest/reactive/CompressionResource.java
- http/jakarta-rest-reactive/src/test/java/io/quarkus/ts/http/jakartarest/reactive/CompressionHandlerIT.java
- http/reactive-routes/src/main/java/io/quarkus/ts/http/reactiveroutes/CompressionHandler.java
- http/reactive-routes/src/test/java/io/quarkus/ts/http/reactiveroutes/CompressionHandlerIT.java
The `io.quarkus.ts.http.reactiveroutes.CompressionHandlerIT` and `io.quarkus.ts.http.jakartarest.reactive.CompressionHandlerIT` are failing because defaults has changed https://github.com/quarkusio/quarkus/pull/43497/files. Application/json and XHTML/XML are now compressed by default. This breaking changes is documented https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.16#http-compression.
This PR:
- moves APP/JSON from uncompressed by default to the types that are compressed by default
- adds new type that is compressed by default (XHTML/XML)
- keeps original behavior of test that verifies mixing of compressed and uncompressed types by default, the app/json is replaced by app/xml which is is uncompressed by default
> Fix compression test failures as media types compressed by defaults has changed

- funqy/knative-events/pom.xml
- funqy/knative-events/src/test/java/io/quarkus/ts/funqy/knativeevents/FunqyKnEventsIT.java
- funqy/knative-events/src/test/java/io/quarkus/ts/funqy/knativeevents/ServerlessExtensionOpenShiftFunqyKnEventsIT.java
Following the recommendation from https://github.com/quarkusio/quarkus/issues/43360
> Enable funqy tests in Native

- messaging/infinispan-grpc-kafka/src/main/java/io/quarkus/ts/messaging/infinispan/grpc/kafka/providers/SaslSslKafkaProvider.java
- messaging/infinispan-grpc-kafka/src/test/java/io/quarkus/ts/messaging/infinispan/grpc/kafka/InfinispanKafkaSaslSslIT.java
- messaging/kafkaSSL/src/main/java/io/quarkus/qe/messaging/ssl/providers/SaslSslKafkaProvider.java
- messaging/kafkaSSL/src/main/java/io/quarkus/qe/messaging/ssl/providers/SslKafkaProvider.java
- messaging/kafkaSSL/src/main/java/io/quarkus/qe/messaging/ssl/quickstart/SaslSslKafkaEndpoint.java
- messaging/kafkaSSL/src/main/java/io/quarkus/qe/messaging/ssl/quickstart/SslKafkaEndpoint.java
- messaging/kafkaSSL/src/test/java/io/quarkus/qe/messaging/ssl/KafkaSaslSslTlsRegistryIT.java
- messaging/kafkaSSL/src/test/java/io/quarkus/qe/messaging/ssl/KafkaSslTlsRegistryIT.java
- security/https/src/main/java/io/quarkus/ts/security/https/CertificateReloader.java
- security/https/src/main/java/io/quarkus/ts/security/https/SecuredResource.java
- security/https/src/main/resources/application.properties
- security/https/src/test/java/io/quarkus/ts/security/https/secured/MutualTlsSecurityIT.java
- adds Kafka TLS registry test coverage as https://github.com/quarkusio/quarkus/issues/43107 is fixed now; changes:
- SASL_SSL client and producer were created and initialized (tried to consume topic) when only SSL was tested and vice versa, so I made sure we don't initialize it when we don't test it (as it would fail for TLS registry [missing named config])
- newly we are taking SSL/SASL_SSL config from default broker as documented here https://quarkus.io/guides/kafka#kafka-bare-clients because it already contains what we set plus for TLS config scenario it also contains what Quarkus Kafka extension set (`ssl.engine.factory.class=io.quarkus.kafka.client.tls.QuarkusKafkaSslEngineFactory` among other non-TLS props) which is required otherwise SSL context is not created from the TLS …
> Test Kafka TLS registry support and manual reloading of TLS registry configuration

- security/keycloak-oidc-client-extended/src/test/resources/kc-logout-realm.json
- security/keycloak-oidc-client-reactive-extended/src/test/resources/kc-logout-realm.json
Tests for aarch64 are failing, because keycloak requires secure context for cookies, unless configured otherwise. (Which AFAIK means, it should require either TLS connection or running on localhost). This causes tests to fail during keycloak login. This PR changes keycloak to not require TLS.
What I found about this, it should be expected behavior for keycloak v24+.
https://github.com/keycloak/keycloak/issues/24821
https://github.com/keycloak/keycloak/issues/30977
Honestly I have no idea why is this not failing in other test suites.
> Disable SSL requirement for keycloak realms

- sql-db/panache-flyway/src/test/java/io/quarkus/ts/sqldb/panacheflyway/init/OpenShiftDefaultInitContainerIT.java
Disabling default init container on OCP and aarch64.
Related issue: https://github.com/quarkus-qe/quarkus-test-suite/issues/2071
> Disable OpenShiftDefaultInitContainerIT on aarch64

- .github/workflows/ci.yml
- pom.xml
> [3.15] Update framework and Quarkus to the latest versions

- build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/AbstractAnalyticsIT.java
- messaging/kafka-producer/src/test/java/io/quarkus/ts/messaging/kafka/producer/BlockingProducerIT.java
- messaging/kafka-streams-reactive-messaging/src/main/java/io/quarkus/ts/messaging/kafka/reactive/streams/shutdown/SlowTopicResource.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/KafkaGratefulShutdownIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OperatorOpenShiftAmqStreamsKafkaStreamIT.java
- pom.xml
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/MssqlTransactionGeneralUsageIT.java
Bump of framework.
Backporting features which causing testing of RHBQ failing. Testing it with latest RHBQ will leave comment when it's done.
Backport of:
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1854
- Removed snappy as 3.2 was never tested with it
- Added `strimzi-test-container` artifact as 3.2 branch seems to have old version and for kraft we need new
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1899
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1905
> [3.2] Backport 8/10/2024

- sql-db/vertx-sql/src/test/java/io/quarkus/ts/vertx/sql/dbpool/PostgresqlResource.java
Porting this fix from 3.8 as it will need to be in 3.15 and future releases as well not to break IBM testing.
Fix PR https://github.com/quarkus-qe/quarkus-test-suite/pull/2004
> Fix PostgresqlResource which failing to start when using RH postgres image

- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DisabledOnAarch64Native.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DisabledOnAarch64NativeConditions.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftAmqStreamsKafkaStreamIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftStrimziKafkaStreamIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OperatorOpenShiftAmqStreamsKafkaStreamIT.java
Generalizing the DisabledOnAarch annotation, since the same failure (https://issues.redhat.com/browse/QUARKUS-4321) also affect quarkus main. It is also reported upstream for some time - https://github.com/quarkusio/quarkus/issues/30545
> Disable kafka streams test also on quarkus main aarch native

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliExtensionsIT.java
We have `--stream` parameter enabled everywhere by default, but this behavior conflicts with `--platform option`, we use in several tests
> Fix failures in CLI

- funqy/knative-events/pom.xml
- funqy/knative-events/src/test/java/io/quarkus/ts/funqy/knativeevents/FunqyKnEventsIT.java
- funqy/knative-events/src/test/java/io/quarkus/ts/funqy/knativeevents/ServerlessExtensionOpenShiftFunqyKnEventsIT.java
- messaging/infinispan-grpc-kafka/src/main/java/io/quarkus/ts/messaging/infinispan/grpc/kafka/providers/SaslSslKafkaProvider.java
- messaging/infinispan-grpc-kafka/src/test/java/io/quarkus/ts/messaging/infinispan/grpc/kafka/InfinispanKafkaSaslSslIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DisabledOnAarch64Native.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DisabledOnAarch64NativeConditions.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftAmqStreamsKafkaStreamIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftStrimziKafkaStreamIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OperatorOpenShiftAmqStreamsKafkaStreamIT.java
- messaging/kafkaSSL/src/main/java/io/quarkus/qe/messaging/ssl/providers/SaslSslKafkaProvider.java
- messaging/kafkaSSL/src/main/java/io/quarkus/qe/messaging/ssl/providers/SslKafkaProvider.java
- messaging/kafkaSSL/src/main/java/io/quarkus/qe/messaging/ssl/quickstart/SaslSslKafkaEndpoint.java
- messaging/kafkaSSL/src/main/java/io/quarkus/qe/messaging/ssl/quickstart/SslKafkaEndpoint.java
- messaging/kafkaSSL/src/test/java/io/quarkus/qe/messaging/ssl/KafkaSaslSslTlsRegistryIT.java
- messaging/kafkaSSL/src/test/java/io/quarkus/qe/messaging/ssl/KafkaSslTlsRegistryIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliExtensionsIT.java
- security/https/src/main/java/io/quarkus/ts/security/https/CertificateReloader.java
- security/https/src/main/java/io/quarkus/ts/security/https/SecuredResource.java
- security/https/src/main/resources/application.properties
- security/https/src/test/java/io/quarkus/ts/security/https/secured/MutualTlsSecurityIT.java
- security/keycloak-oidc-client-extended/src/test/resources/kc-logout-realm.json
- security/keycloak-oidc-client-reactive-extended/src/test/resources/kc-logout-realm.json
- sql-db/panache-flyway/src/test/java/io/quarkus/ts/sqldb/panacheflyway/init/OpenShiftDefaultInitContainerIT.java
- sql-db/vertx-sql/src/test/java/io/quarkus/ts/vertx/sql/dbpool/PostgresqlResource.java
Backports these PRs:
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2059
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2060
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2066
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2073
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2075
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2077
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2080
> [3.15] Backports

- http/http-advanced-reactive/pom.xml
- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/Brotli4JHttpIT.java
- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/DevModeBrotli4JHttpIT.java
- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/OpenShiftBrotli4JIT.java
- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/brotli4j/Brotli4JHttpServerConfig.java
- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/brotli4j/Brotli4JResource.java
- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/brotli4j/Brotli4JRestMock.java
Move brotli4j sources to test/src, because it breakes other tests on OCP on aarch.
Also disable this test on aarch64, where it is failing because of https://github.com/quarkusio/quarkus/issues/43770
> Move brotli4j into test sources and disable it on aarch64

- messaging/kafka-producer/src/test/java/io/quarkus/ts/messaging/kafka/producer/OpenShiftKafkaSnappyIT.java
- messaging/kafka-producer/src/test/java/io/quarkus/ts/messaging/kafka/producer/SnappyCompressionIT.java
Disabling kafka-snappy tests on aarch64 native because of https://github.com/quarkusio/quarkus/issues/43801.
Disabling annotation is added in https://github.com/quarkus-qe/quarkus-test-framework/pull/1365, so don't merge before it is added.
> Disable kafka snappy tests on aarch64 native

- http/http-advanced/pom.xml
We currently have a hardcoded classifier for linux_x86_64 which causes this module to fail on aarch. Change it to use aarch's version on aarch.
I'm not sold on putting the profile into module's pom, but this thing is related only to this module so I don't want to put it into parent pom.
> Change netty-native-epoll classifier to work on aarch

- security/keycloak/src/test/java/io/quarkus/ts/security/keycloak/DevModeKeycloakDevServiceUserExperienceIT.java
- security/keycloak/src/test/java/io/quarkus/ts/security/keycloak/DevModeOidcSecurityIT.java
See https://issues.redhat.com/browse/QUARKUS-5054 for details
This is already fixed in upstream and should be backported to 3.15.2, so this pr goes directly to 3.15 and not in main
> [3.15] Disable Keycloak in devmode

- .github/quarkus-snapshots-mvn-settings.xml
- .github/workflows/ci.yml
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
Spare cca 20 minuts in every PR. Not making change in the daily build as there no one is waiting and it might be smart to have independent build checked from time to time (in case upstream does something wrong?).
Big disadvantage is that if we want to enable some test after PR fix or if our CI is affected by something fixed in the main, we need to the next periodic build (every 24 hours) for the fix. We could have both (new approach and old workflow that builds Quarkus main) but it would add complexity.
> Use periodic Quarkus snapshot build in PR workflows

- nosql-db/infinispan/src/main/resources/application.properties
- nosql-db/infinispan/src/test/resources/infinispan-it.properties
https://issues.redhat.com/browse/QUARKUS-4612 causes nosql/infinispan module to fail on FIPS and mandrel. Add workaround for that
> Add QUARKUS-4612 workaround to nosql/infinispan

- sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/MsSQLDatabaseHibernateReactiveIT.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/MssqlTransactionGeneralUsageIT.java
- sql-db/reactive-rest-data-panache/src/test/java/io/quarkus/ts/reactive/rest/data/panache/MssqlPanacheResourceIT.java
- sql-db/reactive-vanilla/src/test/java/io/quarkus/ts/reactive/db/clients/DevModeReactiveMssqlDevServiceUserExperienceIT.java
- sql-db/sql-app-compatibility/src/test/java/io/quarkus/ts/sqldb/compatibility/MssqlDatabaseIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMssqlDevServicesUserExperienceIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/MssqlDatabaseIT.java
- sql-db/vertx-sql/src/test/java/io/quarkus/ts/vertx/sql/handlers/MssqlHandlerIT.java
Looks like secured communication is required and cannot be disabled in MSSQL JDBC driver by no means I had tried based on https://learn.microsoft.com/en-us/sql/connect/jdbc/fips-mode?view=sql-server-ver16 (no, FIPS property doesn't work). I have tried several providers including SunPKCS11 with RH OpenJDK 17/21 and BouncyCastle FIPS, but only provider that did the trick for MSSQL JDBC driver was BouncyCastle JSSE FIPS. However this provide is not native compatible as documented here https://quarkus.io/guides/security-customization#bouncy-castle-jsse-fips (I tried it, doesn't work). So what this PR does:
- we have one TLS MSSQL test, that is migrated to BC JSSE FIPS so that we test MSSQL in FIPS-enabled environment
- remaining MSSQL tests that doesn't use secured communication are disabled …
> Fix TLS MSSQL test in FIPS-enabled environment and disable non-TLS MSSQL tests in FIPS-enabled environment

- sql-db/vertx-sql/src/main/java/io/quarkus/ts/vertx/sql/Application.java
The `@IfBuildProfile` is for bean classes and method and field bean producers, not for injection points. It has no function as far as I could tell. I search Quarkus code base and reference and cannot find a single mention this should work for injection points. I think it is only confusing us when we leave it there.
> Drop @IfBuildProfile from injection points in VertX SQL module as it has no function at all

- config/src/test/java/io/quarkus/ts/configmap/api/server/ConfigIT.java
- config/src/test/java/io/quarkus/ts/configmap/api/server/DisabledOnFipsAndNative.java
- config/src/test/java/io/quarkus/ts/configmap/api/server/DisabledOnFipsAndNativeCondition.java
This test doesn't work in FIPS-enabled environment in native mode. I have talked to Severin and he wants to check if that is/is not Mandrel bug so I created https://issues.redhat.com/browse/MANDREL-245. Nothing that can be done on our side.
> Disable ConfigIT in native in FIPS-enabled environment due to Mandrel bug

- build/podman/pom.xml
The module `build/podman` was included in root-module profiles then the Quarkus Maven Plugin attempted Podman container builds even if our Jenkins machines was not configured with Podman. With a property based approach we can control when module build/podman is included and avoid build failures jobs.
Change in the POM:
- Remove module build/podman from the root profiles.
- Adding a new property podman-disabled in build/podman
Also, we will modify the Jenkins jobs according to this change.
Log failure:
```
15:31:11 [ERROR] Failed to execute goal com.redhat.quarkus.platform:quarkus-maven-plugin:3.15.1.temporary-redhat-00007:build (build) on project podman-build: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
15:31:11 [ERROR] …
```
> Introduce podman property podman-disabled in build/podman

- build/podman/pom.xml
This is a forwardport of PR--> https://github.com/quarkus-qe/quarkus-test-suite/pull/2092 
The module build/podman was included in root-module profiles then the Quarkus Maven Plugin attempted Podman container builds even if our Jenkins machines was not configured with Podman. With a property based approach we can control when module build/podman is included and avoid build failures jobs.
Change in the POM:
- Add the property `<quarkus.build.skip>${podman-disabled}</quarkus.build.skip>`
> Add porperty quarkus.bild.skip podman-disabled

- build/podman/pom.xml
Still, it doesn't skip Podman by default, with this change we are skipping the Podman build.
> Set podman disabled true by default

- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/HttpAdvancedIT.java
In our daily jobs, we experienced `OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000006af400000, 4034920448, 0) failed; error=' Not enough space' (errno=12)#`.
It was some improvements with https://github.com/quarkus-qe/quarkus-test-framework/pull/1351 
Apart from that, the' HttpAdvancedIT' test also needs to be updated, and I did with this PR. 
I've tested in our Jenkins-job and the test PASSED.
> Fix not enough space error for keycloak container image quay.io/keycloak/keycloak:25.0

- sql-db/reactive-vanilla/src/main/java/io/quarkus/ts/reactive/db/clients/NoteBookResource.java
- sql-db/reactive-vanilla/src/main/java/io/quarkus/ts/reactive/db/clients/ReactiveClientConverter.java
- sql-db/reactive-vanilla/src/main/java/io/quarkus/ts/reactive/db/clients/SoftCoverBookResource.java
Now that datasources can be deactivated, see  https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.17, our DEV mode tests in the Reactive Vanilla module are failing because they don't have set URL (which is a good thing, we don't test them so don't start database). I followed migration guide and choose to use `Instance` for pool injection points that may or may not be active.
This is one of the failures of our GH CI daily build.
> Fix using of inactive datasource in Reactive Vanilla module

- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/HttpAdvancedIT.java
It's a backport from https://github.com/quarkus-qe/quarkus-test-suite/pull/2067 
> [3.15] Set Java Heap limit as a Workaround for Keycloak container memory issues

- pom.xml
Updated mongodb image for IBM Z/ P openshift in pom.xml because mongodb 4.4.6 is the supported image for IBM Z/P, noticed while testing RHBQ 3.15.1 version.
> Update mongodb image for IBM Z/ P openshift in pom.xml

- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/HttpAdvancedIT.java
According this issue comment : https://github.com/quarkus-qe/quarkus-test-suite/issues/2106#issuecomment-2431786538   
it's better set JAVA_OPTS_KC_HEAP in order to not override all JVM opts in Keycloak container
> set JAVA_OPTS_KC_HEAP in order to not override all JVM opts in Keycloak container

- pom.xml
Adding ":latest" suffix to all docker images, that didn't have version. 
Our test framework [expects the images to have version](https://github.com/quarkus-qe/quarkus-test-framework/blob/main/quarkus-test-images/src/main/java/io/quarkus/test/utils/ImageUtil.java#L29). Otherwise it will fail.
On some places, tests are also working with image version so it makes sense to have them.
This is also causing failures in aarch64 tests.
> Add version suffix to docker images

- pom.xml
In aarch64 and openshift-ibm-z-p-containers profiles, we overwrite image for maven-failsafe plugin. But no images for surefire. Thus tests that are not IT will run with the default images and fail. (I found out about this with AgroalPoolTest on aarch64). This PR should fix that.
No sure what test ibm-z is running, if this is actually beneficial for it. But at least this shouldn't break it.
> Overwrite images also in surefire plugin

- pom.xml
IBM only runs unit tests, they are hitting pull rate limit and investigating failures for no reason. This is outcome of https://github.com/quarkus-qe/quarkus-test-suite/pull/2123#issuecomment-2435035621.
> Skip unit tests when IBM OpenShift Maven profile is active

- pom.xml
There is no upstream Infinispan for ppc64le or s390x, we must use the downstream Data Grid. Also, needed a mariadb 10 multi-arch image.
> Reference images, in the POM file, that do support ppc64le or s390x.

- http/http-advanced-reactive/src/main/resources/application.properties
- http/http-advanced/src/main/resources/application.properties
Here https://github.com/quarkusio/quarkus/pull/43345 behavior for MP Rest client configuration changed. Reasons are explained in here https://github.com/quarkusio/quarkus/issues/44067#issuecomment-2434913091. This behavior was never documented and now it is removed. Migration guide mentions this change https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.17#rest-client. I plan to use config key when https://github.com/quarkusio/quarkus/pull/44073 is merged and 999-SNAPSHOT artifacts are deployed to Sonatype.
> Stop using simple class name in MP Rest client configuration property keys as upstream removed support lately

- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/annotations/EnabledIfPostgresImageCommunity.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/annotations/EnabledIfPostgresImageCommunityCondition.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/annotations/EnabledIfPostgresImageProduct.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/annotations/EnabledIfPostgresImageProductCondition.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/PostgresqlCommunityTransactionGeneralUsageIT.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/PostgresqlProductTransactionGeneralUsageIT.java
Since #2129 is not going to fly, we need another way how to use both community and product psotgres image with prepared transaction. Configuring two versions for this.
> Configure postgres transaction separately for images

- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/MariaDbTransactionGeneralUsageIT.java
Daily build is failing, I reported this bug here https://github.com/quarkusio/quarkus/issues/44160 (see for details), no response so far, let's disable it.
> Disable MariaDB transaction recovery test as it doesn't work with `mariadb-java-client` 3.5.0 bumped upstream

- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientProxyIT.java
- http/rest-client-reactive/src/test/resources/nginx.conf.template
- pom.xml
* Since in some environments we are not allowed to use external DNS, this commit allows to configure resolver to be used by nginx. Default will still be 8.8.8.8.
> Make nginx proxy resolver configurable

- pom.xml
- sql-db/reactive-vanilla/src/test/java/io/quarkus/ts/reactive/db/clients/DevModeReactivePostgresqlDevServiceUserExperienceIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModePostgresqlDevServiceUserExperienceIT.java
Image from Red Hat registry currently doesn't work in Dev Services for PostgreSQL: https://github.com/quarkusio/quarkus/issues/44196. So using Docker.io one.
> Use Docker PostgreSQL image from Docker.io and not from Red Hat registry in Dev Service tests on Aarch64

- nosql-db/infinispan/src/test/java/io/quarkus/ts/infinispan/DevModeInfinispanIT.java
- pom.xml
This works around https://issues.redhat.com/browse/QUARKUS-5242 by using Datagrid image and disabling Ryuk for one test only.
> Fix DevModeInfinispanIT on Aarch64 platform as only image from Red Hat registry is supported for this platform

- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/SaslSslAlertMonitorIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/SslAlertMonitorIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/StrimziKafkaStreamIT.java
* See https://issues.redhat.com/browse/QUARKUS-4321.
> Disabling Kafka Streams tests due to QUARKUS-4321

- messaging/infinispan-grpc-kafka/src/test/java/io/quarkus/ts/messaging/infinispan/grpc/kafka/InfinispanKafkaIT.java
- messaging/infinispan-grpc-kafka/src/test/java/io/quarkus/ts/messaging/infinispan/grpc/kafka/InfinispanKafkaSaslSslIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/SaslSslAlertMonitorIT.java
- messaging/kafkaSSL/src/test/java/io/quarkus/qe/messaging/ssl/KafkaSaslSslIT.java
- messaging/kafkaSSL/src/test/java/io/quarkus/qe/messaging/ssl/KafkaSaslSslTlsRegistryIT.java
Disables Infinispan and Kafka tests in native mode in FIPS-enabled environment due to reported known issue.
> Disable SSL and SASL_SSL Kafka and Infinispan tests in FIPS-enabled environment in native mode

- spring/spring-data/src/test/java/io/quarkus/ts/spring/data/rest/additional/OpenAPIIT.java
https://github.com/quarkusio/quarkus/pull/44055 updated OpenAPI to 4.0 and schema has changed, therefore our daily JVM build failed.
> Update OpenAPIIT to new schema in Spring data module after breaking upstream changes

- .github/quarkus-ecosystem-test
- .github/workflows/ci.yml
- .github/workflows/daily.yaml
- super-size/many-extensions/pom.xml
Daily build is failing in native mode due raised build-time RSS usage https://github.com/quarkusio/quarkus/issues/44216. It was suggested that we should raise Xmx https://github.com/quarkusio/quarkus/issues/44216#issuecomment-2449753077. Increasing Xmx by 2 g works around the issue.
> Raise Many extensions module native image `Xmx` to avoid out of memory build failures and decrease Xmx used by GH actions to 4g from 5g

- pom.xml
- sql-db/sql-app-compatibility/pom.xml
- sql-db/sql-app/pom.xml
Increase the default memory limit for native-image to 5g
GitHib Actions runners have more memory now, Jenkins runners are usualy having 16GB
More memory should mean slightly faster native image build and less GC activity
This should also help with daily CI failure in `funqy-knative-events` module probably caused by https://github.com/quarkusio/quarkus/issues/44216
> Increase the default memory limit for native-image to 5g

- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/HttpAdvancedIT.java
As we discussed in this fix: https://github.com/quarkus-qe/quarkus-test-framework/pull/1389
It is not already necessary to have this property `JAVA_OPT_KC_HEAP` for KeycloakService
> Remove property JAVA_OPT_KC_HEAP

- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/OpenShiftMariaDbTransactionGeneralUsageIT.java
https://github.com/quarkus-qe/quarkus-test-suite/pull/2143 follow-up
> Disable MariaDB XA transaction recovery test in OpenShift

- funqy/knative-events/pom.xml
follow-up for https://github.com/quarkus-qe/quarkus-test-suite/pull/2155 and https://github.com/quarkus-qe/quarkus-test-suite/pull/2153 as periodic OpenShift native build fails (also) over this.
> Increase Native image Xmx used for `ServerlessExtensionOpenShiftFunqyKnEventsIT` in native mode

- service-binding/postgresql-crunchy-classic/src/test/java/io/quarkus/ts/sb/postgresql/OpenShiftPostgreSqlSbIT.java
- service-binding/postgresql-crunchy-reactive/src/test/java/io/quarkus/ts/sb/reactive/OpenShiftPostgreSqlReactiveSbIT.java
See https://github.com/quarkusio/quarkus/issues/44297. I'll apply workarounds if we get them, but I'd like to get OpenShift tests green more.
> Disable service binding tests as they often fail over inactive datasource

- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/HttpAdvancedIT.java
- pom.xml
It's a backport from https://github.com/quarkus-qe/quarkus-test-suite/pull/2154
It is not already necessary to have this property JAVA_OPT_KC_HEAP for KeycloakService
> [3.15] Backport for remove property JAVA_OPT_KC_HEAP

- logging/jboss/src/test/java/io/quarkus/ts/logging/jboss/AccessLoggingIT.java
When `AccessLoggingIT` is executed in native mode in FIPS-enabled environment, working directory path in Jenkins can be long, which according to https://github.com/quarkusio/quarkus/issues/44346 means that maximum log file size can get bigger than required size. Therefore I am applying workaround - making sure that path to log directory is short.
This test was added recently https://github.com/quarkus-qe/quarkus-test-suite/pull/2119 and the TD was backported, therefore this fix needs to be backported to 3.15 as well.
> Fix `AccessLoggingIT` when test is executed with long working directory path

- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/GzipMaxInputIT.java
Refactors `GzipMaxInputIT` to reduce memory usage, avoiding spikes in memory consumption.
I compared prints on our Jenkins jobs in the previous one GzipMaxInputIT and observed a rapid spike in memory consumption, but currently, these changes are almost negligible.
This approach addresses the memory issues observed in Podman Jenkins jobs related to Keycloak container failures.
> Optimize GzipMaxInputIT in order to reduce the JVM memory consumption

- logging/jboss/src/test/java/io/quarkus/ts/logging/jboss/AccessLoggingIT.java
Backports https://github.com/quarkus-qe/quarkus-test-suite/pull/2172. I have tested it, see `rhbq-3.15-baremetal-ts-native` run number 24.
> [3.15] Increase access log file size limit

- sql-db/panache-flyway/src/test/java/io/quarkus/ts/sqldb/panacheflyway/init/OpenShiftDefaultInitContainerIT.java
- sql-db/panache-flyway/src/test/resources/build.sh
- Add a script to generate an image for x86, ARM, IBM P and IBM Z
- Enable back the tests on the new architectures
Fixes https://github.com/quarkus-qe/quarkus-test-suite/issues/2071
> Allow wait container to run on different architectures

- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftAmqStreamsKafkaStreamIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftStrimziKafkaStreamIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OperatorOpenShiftAmqStreamsKafkaStreamIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/SaslSslAlertMonitorIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/SslAlertMonitorIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/StrimziKafkaStreamIT.java
* Updating disabled reason for Kafka streams tests on native aarch64 from QUARKUS-4321 to QUARKUS-5180 as QUARKUS-4321 was a misreport.
> Update disable reason for Kafka streams on aarch64

- spring/spring-data/src/test/java/io/quarkus/ts/spring/data/rest/additional/OpenAPIIT.java
Update spring-data test to expect rolesAllowed in OpenAPI scheme - as changes in https://github.com/quarkusio/quarkus/pull/44407
> Expect rolesAllowed in OpenAPI scheme

- super-size/many-extensions/pom.xml
Increase memory limit for super-size/many-extensions test. Migration to `@ConfigMapping` makes the native compilation require a lot more memory - see https://github.com/quarkusio/quarkus/issues/44216
> Increase memory limit for many-extensions test

- build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/AbstractAnalyticsIT.java
- build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/AnalyticsUtils.java
- build/docker/src/main/resources/application.properties
- build/podman/src/main/resources/application.properties
- cache/caffeine/src/main/java/io/quarkus/ts/cache/caffeine/ReactiveWithCacheResource.java
- cache/caffeine/src/main/java/io/quarkus/ts/cache/caffeine/ServiceWithCacheResource.java
- cache/redis/src/main/java/io/quarkus/ts/cache/redis/ServiceWithCacheResource.java
- config/src/main/java/io/quarkus/ts/configmap/api/server/secrets/InjectedPropertiesResource.java
- config/src/test/java/io/quarkus/ts/configmap/api/server/OpenShiftBaseConfigIT.java
- env-info/README.md
- env-info/src/main/java/io/quarkus/ts/envinfo/OsJvmEnvInfoLogger.java
Apply code suggestions from idea to TS, modules A-F. Changes are mostly typos, wrong whitespaces etc. Nothing too big found.
> Apply idea code analysis suggestions. A-F modules

- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/BookClient.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/PlainBookResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/ReactiveClientBookResource.java
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientIT.java
This PR form part of the _[3.15] 3.15.2 backports 1_ (https://github.com/quarkusio/quarkus/pull/43985)  and adds test coverage to ensure that` @RestForm Map<String, String>` is properly handled in REST client requests, covering the fix for Quarkus issue [#43784](https://github.com/quarkusio/quarkus/issues/43784). 
> Add test  for @RestForm Map<String, String> handling in REST Client

- http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/GreetingInterface.java
- http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/GreetingOptionAndHeadResource.java
- http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/GreetingSubResources.java
- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/BaseHttpAdvancedReactiveIT.java
Adding coverage for https://github.com/quarkusio/quarkus/issues/43422 issue.
The PR to fix the original issue is https://github.com/quarkusio/quarkus/pull/43440
> Add coverage for Quarkus #43422

- sql-db/vertx-sql/src/test/java/io/quarkus/ts/vertx/sql/dbpool/PostgresqlResource.java
- closes https://github.com/quarkus-qe/quarkus-test-suite/issues/2076
> Document why we use GenericContainer in PostgresqlResource

- spring/spring-cloud-config/src/test/java/io/quarkus/ts/spring/cloud/config/SpringCloudConfigIT.java
- closes https://github.com/quarkus-qe/quarkus-test-suite/issues/2025
I have rebuild Quarkus QE image and created manifest for both Aarch64 and AMD64. I also updated instructions how to do it here https://quay.io/repository/quarkusqeteam/spring-cloud-config-server?tab=info. Then I tested this new image in beaker executor and the test is now passing on Aarch64.
> Run SpringCloudConfigIT on Aarch64

- http/jakarta-rest-reactive/src/main/java/io/quarkus/ts/http/jakartarest/reactive/client/MultipartService.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/files/FileResource.java
- http/vertx-web-client/src/main/java/io/quarkus/ts/http/vertx/webclient/handler/ChuckNorrisResource.java
Replace deprecated APIs in HTTP modules. 
- `@MultipartForm` Can be removed without replacement in certain conditions (that we meet).
> Replace deprecated API in HTTP modules

- build-time-analytics/pom.xml
- build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/CliProdModeNativeIT.java
- http/http-advanced-reactive/pom.xml
- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/Brotli4JHttpIT.java
- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/OpenShiftBrotli4JIT.java
- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/BaseHttpAdvancedIT.java
- http/http-minimum/src/main/java/io/quarkus/ts/http/minimum/AbstractApplication.java
- http/vertx-web-validation/src/main/java/io/quarkus/ts/vertx/web/validation/ValidationHandlerOnRoutes.java
- messaging/kafka-producer/src/test/java/io/quarkus/ts/messaging/kafka/producer/OpenShiftKafkaSnappyIT.java
- messaging/kafka-producer/src/test/java/io/quarkus/ts/messaging/kafka/producer/SnappyCompressionIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftAmqStreamsKafkaStreamIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftStrimziKafkaStreamIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OperatorOpenShiftAmqStreamsKafkaStreamIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/SaslSslAlertMonitorIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/SslAlertMonitorIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/StrimziKafkaStreamIT.java
- sql-db/reactive-vanilla/src/test/java/io/quarkus/ts/reactive/db/clients/DevModeMultipleReactiveSqlClientsIT.java
- Enable tests, which were disabled due to issues, which are now fixed (one of them required changes)
- Remove a test which was disabled since Quarkus 2 era
> Enable several disabled tests, remove others

- spring/spring-data/src/test/java/io/quarkus/ts/spring/data/primitivetypes/SpringDataCompositeEntityIT.java
- spring/spring-data/src/test/java/io/quarkus/ts/spring/data/primitivetypes/SpringDataSimpleEntityIT.java
- spring/spring-data/src/test/java/io/quarkus/ts/spring/data/rest/AbstractPagingAndSortingRepositoryRestResourceIT.java
- spring/spring-data/src/test/java/io/quarkus/ts/spring/data/rest/CrudRepositoryRestResourceIT.java
- spring/spring-properties/src/main/java/io/quarkus/ts/spring/properties/CollectionsController.java
- spring/spring-properties/src/main/java/io/quarkus/ts/spring/properties/ValueController.java
- spring/spring-properties/src/test/java/io/quarkus/ts/spring/properties/SpringPropertiesIT.java
- spring/spring-web-reactive/src/main/java/io/quarkus/ts/spring/web/reactive/bootstrap/persistence/model/Book.java
- spring/spring-web-reactive/src/main/java/io/quarkus/ts/spring/web/reactive/bootstrap/web/BookController.java
- spring/spring-web-reactive/src/test/java/io/quarkus/ts/spring/web/reactive/bootstrap/AbstractSpringWebRestReactiveIT.java
- spring/spring-web/src/main/java/io/quarkus/ts/spring/web/bootstrap/persistence/model/Book.java
- spring/spring-web/src/test/java/io/quarkus/ts/spring/web/bootstrap/AbstractSpringWebRestIT.java
- sql-db/hibernate-fulltext-search/src/main/java/io/quarkus/ts/hibernate/search/MyCustomIdGenerator.java
- sql-db/hibernate-fulltext-search/src/test/java/io/quarkus/ts/hibernate/search/MysqlMultitenantHibernateSearchIT.java
- sql-db/hibernate-reactive/src/main/java/io/quarkus/ts/hibernate/reactive/http/BookDescription.java
- sql-db/hibernate-reactive/src/main/java/io/quarkus/ts/hibernate/reactive/http/GroundedEndpoint.java
- sql-db/hibernate-reactive/src/main/java/io/quarkus/ts/hibernate/reactive/http/PanacheEndpoint.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/MariaDbTransactionGeneralUsageIT.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/OpenShiftMariaDbTransactionGeneralUsageIT.java
- sql-db/panache-flyway/src/main/java/io/quarkus/ts/sqldb/panacheflyway/ApplicationQueryResource.java
- sql-db/reactive-rest-data-panache/src/main/java/io/quarkus/ts/reactive/rest/data/panache/ApplicationQueryResource.java
- sql-db/sql-app-compatibility/src/test/java/io/quarkus/ts/sqldb/compatibility/AbstractSqlDatabaseIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/AbstractSqlDatabaseIT.java
- sql-db/vertx-sql/src/main/java/io/quarkus/ts/vertx/sql/Application.java
- sql-db/vertx-sql/src/main/java/io/quarkus/ts/vertx/sql/services/DbPoolService.java
- super-size/many-extensions/src/main/java/io/quarkus/ts/many/extensions/Hello.java
- test-tooling/pact/src/test/java/io/quarkus/ts/http/pact/ConsumerPactTest.java
Apply idea code changes to modules Service* to the end. Mostly replacing deprecated API and code simplification.
> Apply idea code analysis suggestions Service*-End

- http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/MultipartResource.java
- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/MultipartInputstreamIT.java
- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/OpenShiftMultipartInputstreamIT.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/multipart/FileUploadClient.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/multipart/MultipartBodyWithMediaType.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/multipart/MultipartBodyWithoutMediaType.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/FileUploadClientTestResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/FileUploadResource.java
- http/rest-client-reactive/src/main/resources/modern.properties
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientIT.java
Add test coverage for the optional media type handling in InputStream multipart requests, testing Rest client-side and HTTP server-side handling. Addressing the issue https://github.com/quarkusio/quarkus/issues/43364 with the fix https://github.com/quarkusio/quarkus/pull/43985/commits/f6710518a8cc293664b888db7617047d30e2b5f8
> Add test coverage for #43364 - InputStream when using multipart

- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftAmqStreamsKafkaStreamIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftStrimziKafkaStreamIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OperatorOpenShiftAmqStreamsKafkaStreamIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/SaslSslAlertMonitorIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/SslAlertMonitorIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/StrimziKafkaStreamIT.java
Remove the  @DisabledOnAarch64Native annotations on kafka tests addressing https://github.com/quarkusio/quarkus/pull/43985/commits/cff4148abcd42f3bf5fc34c49cb77d582887b02c that fix https://github.com/quarkusio/quarkus/issues/43319
I created a specific aarch64 Jenkins node to verify and execute these tests.
> [3.15] 3.15 Backport Enable kafka tests on aarch64 for test coverage issue #43319

- external-applications/src/test/java/io/quarkus/ts/external/applications/TodoDemoIT.java
Since https://github.com/quarkusio/quarkus/pull/44584 fixed the problem with TodoDemoIT on windows, there is no longer need to have it disabled.
> Enable TodoDemoIT on Windows

- pom.xml
- service-discovery/stork/src/main/java/io/quarkus/ts/stork/PongReplicaResource.java
- sql-db/sql-app-compatibility/src/test/java/io/quarkus/ts/sqldb/compatibility/DB2DatabaseIT.java
- sql-db/sql-app-compatibility/src/test/java/io/quarkus/ts/sqldb/compatibility/MariaDBDatabaseIT.java
- sql-db/sql-app-compatibility/src/test/java/io/quarkus/ts/sqldb/compatibility/MssqlDatabaseIT.java
- sql-db/sql-app-compatibility/src/test/java/io/quarkus/ts/sqldb/compatibility/MySqlDatabaseIT.java
- sql-db/sql-app-compatibility/src/test/java/io/quarkus/ts/sqldb/compatibility/OracleDatabaseIT.java
- sql-db/sql-app-compatibility/src/test/java/io/quarkus/ts/sqldb/compatibility/PostgresqlDatabaseIT.java
Bumps Quarkus QE Framework to https://github.com/quarkus-qe/quarkus-test-framework/releases/tag/1.6.0.Beta15.
**Update:** 
- SQL Compatibility changes: I'll investigate why are changes in the SQL Compatiblity module required separately (let's not wait for this and proceed with this PR). I think there must be a flaw in build-time properties detection when `withProperties` is used, but in general, I think changes in SQL Compatibility module are more frequent way to import property files.
- Stork module changes on the other hand shows great improvement of this bump - it shows that tested app is now truly isolated from the rest. Previously static import `import static io.quarkus.ts.stork.PongResource.PONG_SERVICE_NAME;` should had failed for the `pongReplicaService` app build if the …
> Bump Quarkus QE framework to 1.6.0.Beta15 and adapt TS to the framework changes

- messaging/kafka-streams-reactive-messaging/src/main/java/io/quarkus/ts/messaging/kafka/reactive/streams/shutdown/ReadinessObserver.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/KafkaGratefulShutdownIT.java
- messaging/kafka-streams-reactive-messaging/src/test/resources/kafka.grateful.shutdown.application.properties
- closes https://github.com/quarkus-qe/quarkus-test-suite/issues/2016
I analyzed our flaky tests and `io.quarkus.ts.messaging.kafka.reactive.streams.KafkaGratefulShutdownIT.testConnection` probably fails most often (I didn't count it, maybe AgroalPoolTest that I have also fixed failed as often). When we started to use Kafka Kraft mode https://github.com/quarkus-qe/quarkus-test-suite/pull/1854 we were affected by the fact that Quarkus application is ready even though Kafka channels are not. According to the https://github.com/quarkusio/quarkus/issues/41441 this is expected (ha ha). Suggested solution was to add either custom check or rebalancer https://github.com/quarkusio/quarkus/issues/41441#issuecomment-2203068816. Custom check is unnecessary because SR Messaging can already test …
> Fix flaky KafkaGratefulShutdownIT by waiting until messaging channels are ready

- monitoring/opentelemetry-reactive/src/test/java/io/quarkus/ts/opentelemetry/reactive/OpentelemetryReactiveIT.java
The `OpentelemetryReactiveIT.testSecurityEvents` test is bit flaky:
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2062#issuecomment-2392453159
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2093#issuecomment-2416309511
I can't reproduce it, so this is very much a guessing game. Here are my findings:
- GPath always take `data[0]` and the first span matching `findAll { span -> span.operationName == 'GET /admin' }[0]`
- there are other spans matching this span GPath, looks like pre-flight request is unauthorized (which is correct), so it does not match `quarkus.security.authorization.success`
- if both spans are there in different order, the GPath will not match any result
Changes in this PR:
- don't care about span and log order
- stop polling admin endpoint as we only …
> Fix flaky `OpentelemetryReactiveIT#testSecurityEvents` test

- .github/workflows/ci.yml
This adding the rebase for us to test on latest version of branch, it help only detect the changed file in the PR. Also the rebase fail if the contributor have outdated branch in this case 16 or more commits (in my POV it should be enough)
To test the rebase I used the f66d24d805480689a62b4f863bb3c64ca23ae3e8 commit as base for this branch
This PR also fix the problem when main `pom.xml` was updated but the PR also contains other changes (updating tests etc.) so only selected modules were run. Wth this fix all the modules will be executed.
> Add git rebase to PR CI and fix not running full CI when pom.xml is changed

- README.md
- cache/caffeine-resteasy/pom.xml
- cache/caffeine-resteasy/src/main/java/io/quarkus/ts/cache/caffeine/restclient/ClientBookResource.java
- cache/caffeine-resteasy/src/main/java/io/quarkus/ts/cache/caffeine/restclient/RestInterface.java
- cache/caffeine-resteasy/src/main/java/io/quarkus/ts/cache/caffeine/restclient/types/Book.java
- cache/caffeine-resteasy/src/main/java/io/quarkus/ts/cache/caffeine/restclient/types/BookAsJsonResource.java
- cache/caffeine-resteasy/src/main/java/io/quarkus/ts/cache/caffeine/restclient/types/BookAsXmlResource.java
- cache/caffeine-resteasy/src/main/resources/application.properties
- cache/caffeine-resteasy/src/test/java/io/quarkus/ts/cache/caffeine/restclient/OpenShiftRestClientWithCacheIT.java
- cache/caffeine-resteasy/src/test/java/io/quarkus/ts/cache/caffeine/restclient/RestClientWithCacheIT.java
- pom.xml
Adding coverage for [QUARKUS-5068](https://issues.redhat.com/browse/QUARKUS-5068).
Adding it to new module as this mainly check cache with reasteasy client. Atm we don't have any cache module where we using `resteasy-client` or `resteasy` extension. If you want I can add it to resteasy client test module but personally thing it should be more in cache modules.
**Note for 3.8 backport** it should be [QUARKUS-5293](https://issues.redhat.com/browse/QUARKUS-5293)
> Add coverage for @CacheResult with resteasy client to cover QUARKUS-5068

- http/servlet-undertow/src/test/java/io/quarkus/ts/http/undertow/UndertowMissingServletClassIT.java
- http/servlet-undertow/src/test/java/io/quarkus/ts/http/undertow/WithMissingServlet.java
- http/servlet-undertow/src/test/resources/META-INF/invalid-web.xml
This PR introduces a test to verify that the absence of a <servlet-class> tag in web.xml does not cause a build failure when using Undertow. It adds coverage for the fix implemented https://github.com/quarkusio/quarkus/pull/44063 for the original issue: https://github.com/quarkusio/quarkus/issues/43825
> Add test to verify missing servlet-class in web.xml doesn't cause build failure with Undertow

- README.md
- messaging/kafka-processor/pom.xml
- messaging/kafka-processor/src/main/java/io/quarkus/ts/messaging/kafka/processor/decorator/HeaderDecorator.java
- messaging/kafka-processor/src/main/java/io/quarkus/ts/messaging/kafka/processor/processor/PingProcessor.java
- messaging/kafka-processor/src/main/resources/application.properties
- messaging/kafka-processor/src/test/java/io/quarkus/ts/messaging/kafka/processor/DevModeKafkaProcessorIT.java
- pom.xml
This adding the coverage for https://issues.redhat.com/browse/QUARKUS-5178. It's tested with Quarkiverse extension as the reproducer attached in issue and it was only scenario which I was able to reproduce.
To test this you need external lib which contains class (lib_class) implementing the interface. This interface is also aplied on class anotated as decorator in Quarkus app when the bean of lib_class is injected at the same time.
This error happen randomly in dev/test mode.
The Quarkus PR is https://github.com/quarkusio/quarkus/pull/43245
I tried to use same test which they using but wasn't able to reproduce the original issue.
**Note for 3.8 backport: the relevant issue is** https://issues.redhat.com/browse/QUARKUS-5292
> Add coverage for ArC fix when a framework bean uses the decorator

- http/servlet-undertow/src/test/java/io/quarkus/ts/http/undertow/UndertowMissingServletClassIT.java
- http/servlet-undertow/src/test/java/io/quarkus/ts/http/undertow/WithMissingServlet.java
- http/servlet-undertow/src/test/resources/META-INF/invalid-web.xml
This PR introduces a test to verify that the absence of a tag in web.xml does not cause a build failure when using Undertow. It adds coverage for the fix implemented https://github.com/quarkusio/quarkus/pull/44063 for the original issue: https://github.com/quarkusio/quarkus/issues/43825
> [3.15] Add test to verify missing servlet-class in web.xml doesn't cause build failure with Undertow

- logging/jboss/src/test/java/io/quarkus/ts/logging/jboss/AccessLoggingIT.java
This fixes problem when running native on jenkins, This is affected by long path what our jenkins runners using. The actual size from my testing is around `5449`.
I also try to move it to more nested directory named `test` and the actual size were `5499`.
From this testing I thing the raise the buffer by `100` should be enough.
> Raise the buffer for max file size to fix run on jenkins

- pom.xml
This PR follows https://github.com/quarkus-qe/quarkus-test-framework/pull/1418
Changes the default quarkus test framework version to daily snapshot. This should affect all jobs, that tests against main branch.
> Use test FW snapshot by default

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/update/AbstractQuarkusCliUpdateIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/update/QuarkusCli35to315UpdateIT.java
This PR addresses the issue encountered in the QuarkusCli35to315UpdateIT test suite when verifying RHBQ-specific version.
> Fix QuarkusCli35to315UpdateIT to proper handling RHBQ versions

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/update/AbstractQuarkusCliUpdateIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/update/QuarkusCli35to315UpdateIT.java
This PR addresses the issue encountered in the QuarkusCli35to315UpdateIT test suite when verifying RHBQ-specific version.
> [3.15] Fix QuarkusCli35to315UpdateIT to use RHBQ versions

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/update/AbstractQuarkusCliUpdateIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/update/QuarkusCli35to315UpdateIT.java
QuarkusCli35to315UpdateIT failed from 3.5 upstream to 3.15 RHBQ which is atm not supported, but with 3.8 as is LTS so it has RHBQ version then it works.
> Fix QuarkusCli35to315UpdateIT

- .github/actions/prepare-quarkus-cli/action.yml
- .github/workflows/ci.yml
- .github/workflows/daily.yaml
- pom.xml
- Daily build is failing as following changes in Quarkus QE Test Framewok, we now use 999-SNAPSHOT deployed to Sonatype snapshot repository, however daily build is not configured to use the snapshot repository. This PR sets daily build to use it, and as we already use the snapshot repository where Quarkus main build is, there is little point to keep building it (we can save some time, green planet :-) ).
- WebAuthn module fails to compile due to changes in the https://github.com/quarkusio/quarkus/pull/44105, I'll have look later this week if I can patch it somehow
- I didn't check Jenkins jobs whether someone is using "non-snaphost" Maven settings, I'll check later if we can drop it as well
> Fix daily build by taking Quarkus QE Test Framework dependencies from Sonatype snapshot repository and stop building Quarkus main

- messaging/kafka-producer/src/test/java/io/quarkus/ts/messaging/kafka/producer/DevModeKafkaSnappyIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DevModeKafkaStreamIT.java
Renaming the veztorized to redpandadata in tests. For more info see https://github.com/quarkusio/quarkus/pull/45028
> Remane vectorized/redpanda to redpandadata/redpanda as the name was realocated

- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/OpenShiftHeadersIT.java
The test needs to be disabled on openshift as for comunication outside, the valid 'Host' header needs to be set. This not need to be set when the request and endpoint is running on same machine.
This is followup of https://github.com/quarkus-qe/quarkus-test-suite/pull/2215 where I miss that HeadersIt also run on openshift so I dind't check it.
> Dissable the testHttp10WithoutHostHeader on openshift

- http/http-advanced-reactive/src/main/resources/application.properties
- http/http-advanced/src/main/resources/application.properties
- super-size/many-extensions/src/main/resources/application.properties
Renaming 
- `quarkus.health.extensions.enabled` → `quarkus.smallrye-health.extensions.enabled`
- `quarkus.health.openapi.included` → `quarkus.smallrye-health.openapi.included`
For more info see https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.14#smallrye-health
> Rename some deprecated `quarkus.health` properties to `quarkus.smallrye-health`

- .github/workflows/ci.yml
- .github/workflows/daily.yaml
- pom.xml
When someone does `mvn clean verify` and doesn't have Quarkus QE Test Framework built locally already, compilation fails over missing artifacts (unless you have your settings configured for the snapshots). We already have the snapshots repository added here https://github.com/quarkus-qe/quarkus-test-suite/pull/2224/files so there is no point of not doing same for plugins (because the test preparer is a plugin).
> Add plugins snapshots repository

- .github/workflows/ci.yml
- .github/workflows/daily.yaml
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliConfigSetIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliSpecialCharsIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliVersionIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/config/surefire/SetPropertyTest.java
This PR enable the testing Quarkus CLI in 999-SNAPSHOT version on windows machine. Fixes #1464
On GH action the windows runners are missing some language packs so they are not able to represent all chars (not happening at our AWS images). As this is a reason we need to disable some test which using these "unknow" characters.
I add the `gh-action-disable-on-win` as we only want them disable here on GH windows
The `QuarkusCliVersionIT` can be enable as we move to JDK 21 as lowest testing java and `Dfile.encoding=UTF8` can be removed as since JDK 18 the UFT-8 is default encoding.
> Test enable win CLI test

- security/webauthn/src/main/java/io/quarkus/ts/security/webauthn/model/User.java
- security/webauthn/src/main/java/io/quarkus/ts/security/webauthn/model/WebAuthnCredential.java
- security/webauthn/src/main/java/io/quarkus/ts/security/webauthn/security/MyWebAuthnSetup.java
- security/webauthn/src/main/resources/META-INF/resources/index.html
- security/webauthn/src/test/java/io/quarkus/ts/security/webauthn/AbstractWebAuthnTest.java
The https://github.com/quarkusio/quarkus/pull/45132 introduces renaming of `userName` to `username`, I rename our ocurencess as well to be same.
The `REGISTER_CHALLENGE_OPTIONS_URL` not use GET request insted of POST
> Fix webauthn failiures after changes on upstream

- http/http-minimum-reactive/src/main/java/io/quarkus/ts/http/minimum/reactive/JakartaRestInterceptor.java
- http/http-minimum-reactive/src/main/java/io/quarkus/ts/http/minimum/reactive/Operator.java
- http/http-minimum-reactive/src/main/java/io/quarkus/ts/http/minimum/reactive/OperatorResource.java
- http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/HttpMinimumReactiveIT.java
Described here:
https://github.com/quarkusio/quarkus/issues/44564
https://github.com/quarkusio/quarkus/pull/44613
https://issues.redhat.com/browse/QQE-1234
> Add coverage for "method not registered" error in native mode

- spring/spring-data/src/main/java/io/quarkus/ts/spring/data/primitivetypes/HttpCommonsHeaders.java
Disable the session header because of the https://github.com/quarkusio/quarkus/issues/45191
ATM don't know how it will work in the future so this is probably best approach to keep the spring-data test running and not disable them as it's affecting most of the test. This should fix daily aswell
> Disable the session header as it's not possible to invoke it

- security/keycloak-oidc-client-extended/src/main/resources/application.properties
Initialize org.keycloak.common.util.BouncyIntegration at runtime
We use org.keycloak:keycloak-authz-client directly and not the keycloak-authorization extension 
Fixes daily CI failures, triggered by switch to standalone Keycloak client in Quarkus main
https://github.com/quarkusio/quarkus/blob/main/extensions/keycloak-authorization/deployment/src/main/java/io/quarkus/keycloak/pep/deployment/KeycloakReflectionBuildStep.java#L88
> Initialize org.keycloak.common.util.BouncyIntegration at runtime

- spring/spring-data/src/main/java/io/quarkus/ts/spring/data/primitivetypes/BookStore.java
- spring/spring-data/src/test/java/io/quarkus/ts/spring/data/primitivetypes/SpringDataCompositeEntityIT.java
The original test was based on serialization, which is no longer possible out of bot. In quarkusio/quarkus#41292 was suggested use this modification to make the original code work. Now we checking if retunred json, pageable item contains specific values.
For more info see https://github.com/quarkusio/quarkus/issues/41292#issuecomment-2371862795
> Refactor the spring serialization test disabled by quarkus#41292

- .github/workflows/daily.yaml
Explicitly enable all modules to be executed on Windows daily runs
https://github.com/quarkus-qe/quarkus-test-suite/pull/2244 changes introduced `include.quarkus-cli-tests` property in the command which enables `quarkus-cli-tests` profile and thus profiles with `activeByDefault` are not activated
> Explicitly enable all modules to be executed on Windows daily runs

- http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/HttpMinimumReactiveIT.java
Otherwise the test fails on Openshift
> Wait for logs to update

- http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/HttpMinimumReactiveIT.java
- http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/ServerlessExtensionDockerBuildStrategyOpenShiftHttpMinimumReactiveIT.java
- http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/ServerlessExtensionOpenShiftHttpMinimumReactiveIT.java
Follow-up to https://github.com/quarkus-qe/quarkus-test-suite/pull/2266
> Do not check logs in serverless tests

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateExtensionIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
Test that Quarkus snapshot CLI can create applications and extensions with the latest released Quarkus versions. More on the motivation here https://github.com/quarkus-qe/quarkus-test-framework/pull/1467. Not all of the tests are switched to use `@TestQuarkusCli` because it adds execution time (even though I only chose JVM tests), so I tried to be reasonable.
> Test creating of Quarkus applications and extensions with the latest released Quarkus version using Quarkus snapshot CLI

- messaging/kafka-producer/src/test/java/io/quarkus/ts/messaging/kafka/producer/SnappyCompressionIT.java
Default KRaft logs dir has changed when Kafka version was bumped here https://github.com/quarkus-qe/quarkus-test-framework/pull/1465. This PR fixes SnappyCompressionIT that fails the daily build.
> Fix SnappyCompressionIT as KRaft default logs directory has changed when we bumped Kafka version

- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OperatorOpenShiftAmqStreamsKafkaStreamIT.java
- messaging/kafka-streams-reactive-messaging/src/test/resources/amq-streams-operator-kafka-instance.yaml
Latest AMQ streams operator v2.8 [supports Kafka 3.8.0 or less](https://docs.redhat.com/en/documentation/red_hat_streams_for_apache_kafka/2.8/html/release_notes_for_streams_for_apache_kafka_2.8_on_openshift/features-str#kafka_3_8_0_support) while default Kafka version from FW is [3.9.0](https://github.com/quarkus-qe/quarkus-test-framework/pull/1465/files#diff-9d228cf040aec0ac8a0076cf781225a1c21cd68ab05352450d6ff892212d9848)
This PR brings temporary solution to be able run `OperatorOpenShiftAmqStreamsKafkaStreamIT` tests until new AMQ streams operator version will be out.
FW [OpenShiftStrimziOperatorKafkaWithoutRegistryMessagingIT](https://github.com/quarkus-qe/quarkus-test-framework/blob/b6fc6fcf108ab41c480d4853ad71551f5d189747/examples/kafka/src/test/java/io/quarkus/qe/OpenShiftStrimziOpe …
> Use custom yaml with kafka 3.8.0 for AMQ streams operator tests

- .github/workflows/quarkus-snapshot.yaml
This repository is discontinued and `yq` has been part of the runner images for a while.
> Fix Ecosystem CI

- messaging/kafka-producer/src/test/java/io/quarkus/ts/messaging/kafka/producer/DevModeKafkaSnappyIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DevModeKafkaStreamIT.java
Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/2245
> [3.15] Backport of #2245 rename vectorized/redpanda

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliTlsCommandIT.java
- Message for generated certificates has changed
> Fixes for daily failures

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
Fixing compilation as https://github.com/quarkus-qe/quarkus-test-framework/pull/791 changed expected type to enum.
> Fix QuarkusCliCreateJvmApplicationIT compilation by replacing string property with enum constant after FW changes

- messaging/infinispan-grpc-kafka/src/main/resources/infinispan-config.xml
The `InfinispanKafkaSaslSslIT` and `InfinispanKafkaIT` are failing with `Caused by: java.lang.SecurityException: ISPN004031: The selected authentication mechanism 'DIGEST-SHA-512' is not among the supported server mechanisms: [PLAIN, DIGEST-MD5, BASIC]` over changes made in https://github.com/quarkusio/quarkus/pull/45982. The daily build is failing because of this https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/13111089359/job/36575005028. I saw this fix in QE FW https://github.com/quarkus-qe/quarkus-test-framework/pull/1484 so I didn't have to do much thinking. Tested it locally and fixed the issue.
> Fix Infinispan Kafka tests by adding SHA-512 SASL mechanism as upstream has changed to support FIPS enabled environment

- build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/AbstractAnalyticsIT.java
- build-time-analytics/src/test/resources/test.properties
As result of the https://github.com/quarkus-qe/quarkus-test-framework/pull/791 we expect that all QE FW properties are listed as enum constants in `Property`, however in past it was possible to set also Quarkus properties as `ts.global`, which now results in failure. Due to this issue, daily build fails https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/13111089359/job/36575004262 over `[ERROR] java.util.ServiceConfigurationError: org.junit.platform.launcher.TestExecutionListener: Provider io.quarkus.test.listener.QuarkusTestResourceCleaningFilter could not be instantiated`. I have debugged it and found out that everytime `new PropertyLookup` constructor is instantiated in this module, loading of the global configuration fails as no such element.
This is expected to fail until …
> Fix build-time analytics module execution failure as we should only set QE FW test properties in the test properties

- security/https/src/test/java/io/quarkus/ts/security/https/enabled/EnabledHttpsSecurityIT.java
- security/https/src/test/java/io/quarkus/ts/security/https/redirect/RedirectHttpsSecurityIT.java
This is required because of changes made in the https://github.com/quarkusio/quarkus/pull/45769.
> Fix compilation of security/https module after Vert.x HTTP extension migrated to @ConfigMapping

- spring/spring-properties/src/test/java/io/quarkus/ts/spring/properties/SpringPropertiesIT.java
Not sure when they fix it https://github.com/quarkusio/quarkus/issues/46172, but we need green daily build ASAP, it wasn't green for more than a month, hence disabling the test.
> Disable SpringPropertiesIT in native due to upstream issue

- sql-db/vertx-sql/src/test/java/io/quarkus/ts/vertx/sql/handlers/MssqlHandlerIT.java
Daily build https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/13221313816/job/36906702884 failed in JVM due to https://github.com/quarkusio/quarkus/issues/46083. I have also mentioned that sometimes, failure is not over closed connection in a Flyway migration, but our FW simply prints `MssqlHandlerIT Resource failed to start` without any details like today https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/13232004578. But I can't reproduce that and I think the root cause is the most likely same as in the 46083. I have mentioned one difference, with this old image I can see logged also exception:
```
12:16:00,059 INFO  [app] 12:15:58,738 MSSQL Info {number=3621, state=0, severity=0, message='The statement has been terminated.', serverName='892a39568244', …
```
> Use older MSSQL image for MssqlHandlerIT due to bug in the newest RHEL-based image

- .github/workflows/daily.yaml
- README.md
- build/docker/pom.xml
- build/docker/src/main/docker/Dockerfile-compatibility.jvm
- build/docker/src/main/docker/Dockerfile-compatibility.native
- build/podman/pom.xml
- build/podman/src/main/docker/Dockerfile-compatibility.jvm
- build/podman/src/main/docker/Dockerfile-compatibility.native
- build/podman/src/main/docker/Dockerfile.jvm
- build/podman/src/main/docker/Dockerfile.native
- pom.xml
- sql-db/panache-flyway/src/test/resources/Dockerfile
This switches from UBI8 to UBI9 following changes in Quarkus 3.19 as documented in migration guide https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.19 and similar changes in QE FW https://github.com/quarkus-qe/quarkus-test-framework/pull/1493 https://github.com/quarkus-qe/quarkus-test-framework/pull/1494.  I believe this will help to fix OpenShift failures in native mode (the glibc stuff).
I expect it will be necessary to follow-up with adding a compatibility to FW docker files as well. But I don't want to do that all in one big PR, want to see daily build with this and address possible issues ASAP. I also suspect I'll need to follow-up regarding these changes in panache-flyway docker file, I am yet to understand how it works, need to check in next days.
Please select the …
> Switch from UBI8 to UBI9 and add compatibility smoke tests for UBI8

- .github/actions/use-docker-mirror/action.yml
- .github/workflows/ci.yml
- .github/workflows/daily.yaml
In our last daily build JVM test of database modules https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/13283501825/job/37086888778 I saw failures like these:
```
2025-02-12T16:14:00.4278915Z 16:14:00,361 INFO  [base] Initialize service (docker.io/library/mysql:8.4)
2025-02-12T16:14:00.4279616Z 2025-02-12 16:14:00,363 INFO  [tc.doc.io/.4] (main) Pulling docker image: docker.io/library/mysql:8.4. Please be patient; this may take some time but only needs to be done once.
2025-02-12T16:14:00.6282143Z 2025-02-12 16:14:00,547 ERROR [com.git.doc.api.asy.ResultCallbackTemplate] (docker-java-stream-1144214995) Error during callback: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"toomanyrequests: You have reached your pull rate limit. You may …
```
> Use gcr.io Docker mirror to avoid pull rate limits to fix failures in JVM database modules

- pom.xml
Updating the DB2 image, upstream also moved to this version https://github.com/quarkusio/quarkus/pull/45448. From 11.5.9 the db2 moved to icr.io. 
> Update IBM DB2 image to 12.1.0.0

- .github/workflows/daily.yaml
The current CI is set to start at 0:30 UTC, but it's starting around 1:55 UTC (I don't know the reason), but as we now consuming the artifacts from snapshot repository, it causing sometimes problems. The main reason is that the Quarkus snapshot build start around 2:22 UTC, so some of the artifact which are used when testing are day old and some of them are latest. So this PR set the daily execution 1 hour after the Quarkus snapshot build which is defined in [deploy-snapshots.yml](https://github.com/quarkusio/quarkus/blob/main/.github/workflows/deploy-snapshots.yml#L5) 
I run it for 3 days now on my CI and the time when the daily start was around 3:12 UTC. The average build time of Quarkus 
is 30 min so the latest version of Quarkus should be always prepared before the start of our daily. …
> Move the start of TS CI to be executed 1 hour after Quarkus snapshot build

- http/rest-client-reactive/pom.xml
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/UrlOverrideableClient.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/UrlOverrideClientTestResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/UrlOverrideResource.java
- http/rest-client-reactive/src/main/resources/application.properties
- http/rest-client-reactive/src/main/resources/urlOverride.properties
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/UrlOverrideClientIT.java
Implement test coverage for https://github.com/quarkusio/quarkus/pull/43331
> Tests for rest-client-reactive URL override feature

- build/docker/src/main/docker/Dockerfile-compatibility.native
- build/podman/src/main/docker/Dockerfile-compatibility.native
Use ubi-minimal:8.10 instead of 8.6 as it is the latest 8.x version
https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8
> Use ubi-minimal:8.10 instead of 8.6

- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/MariaDbTransactionGeneralUsageIT.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/OpenShiftMariaDbTransactionGeneralUsageIT.java
Enable MariaDB transaction tests after bump to mariadb-java-client to 3.5.2 (https://github.com/quarkusio/quarkus/pull/46221)
> Enable MariaDB transaction tests after bump to mariadb-java-client to 3.5.2

- monitoring/opentelemetry-reactive/pom.xml
- monitoring/opentelemetry-reactive/src/test/java/io/quarkus/ts/opentelemetry/reactive/OpenTelemetryMetricsIT.java
- monitoring/opentelemetry-reactive/src/test/resources/metrics.properties
Test coverage to ensure MicroProfile Telemetry Metrics are available and quarkus.otel.instrument configuration works
TP: https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-5656.md
Guide: https://quarkus.io/guides/opentelemetry-metrics
This coverage doesn't go in details as the main metrics story for Quarkus is connected with Micrometer and this is primarily for compliance reasons.
> Test coverage to ensure MicroProfile Telemetry Metrics are available and quarkus.otel.instrument configuration works

- http/grpc/pom.xml
- messaging/infinispan-grpc-kafka/pom.xml
- messaging/kafkaSSL/pom.xml
- monitoring/opentelemetry-reactive/pom.xml
- monitoring/opentelemetry/pom.xml
- pom.xml
Drop quarkus-maven-plugin definitions from modules to avoid dual build in native mode
Root pom.xml defines execution with id build, and modules use default execution. As such, 2 builds are happening, which is especially noticeable in native mode.
```
quarkus:999-SNAPSHOT:build (build) @ monitoring-opentelemetry-reactive
quarkus:999-SNAPSHOT:build (default) @ monitoring-opentelemetry-reactive
```
Aligning definition in root `pom.xml` with https://quarkus.io/guides/maven-tooling#build-tool-maven
> Drop quarkus-maven-plugin definitions from modules to avoid dual build in native mode

- monitoring/opentelemetry-reactive/src/test/java/io/quarkus/ts/opentelemetry/reactive/MetricsIT.java
- monitoring/opentelemetry-reactive/src/test/java/io/quarkus/ts/opentelemetry/reactive/OpentelemetryReactiveIT.java
- Add checks for exemplars in metrics (Covers QUARKUS-5424)
- Verify, that dynamic tag is not used in netty metrics (QUARKUS-5637)
> Cover changes in 3.15.4 backports

- http/grpc/src/test/java/io/quarkus/ts/http/grpc/GrpcMtlsEncryptedPemTlsRegistryIT.java
- security/https/src/main/java/io/quarkus/ts/security/https/TlsRegistryResource.java
- security/https/src/test/java/io/quarkus/ts/security/https/secured/HttpsEncryptedPemIT.java
- security/https/src/test/java/io/quarkus/ts/security/https/secured/TlsRegistryCertificateReloadingIT.java
- security/https/src/test/java/io/quarkus/ts/security/https/secured/TlsRegistryDecryptedKeyIT.java
- security/https/src/test/java/io/quarkus/ts/security/https/utils/Certificates.java
These tests will be added to cover https://github.com/quarkusio/quarkus/pull/44549 
Jira issue: [QUARKUS-5666](https://issues.redhat.com/browse/QUARKUS-5666)
TP: [TP-QUARKUS-5666](https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-5666.md)
Also we did some TF support --> [1507](https://github.com/quarkus-qe/quarkus-test-framework/pull/1507 )
- Https communication using encrypted Pem, ensure you can communicate with Quarkus REST endpoint using HTTPS (no client-side authentication).
- Certificate reloading, validate with newly generated certificate, it works for encrypted PEMs as well .
- Injecting TLS registry configuration and can see the private key decrypted (so you can see keystore and check some x509 attributes).
> Adding test coverage to support encrypted PEM Keys

- http/grpc/src/test/java/io/quarkus/ts/http/grpc/GrpcMtlsEncryptedPemTlsRegistryIT.java
- security/https/src/test/java/io/quarkus/ts/security/https/secured/HttpsEncryptedPemIT.java
- security/https/src/test/java/io/quarkus/ts/security/https/secured/TlsRegistryCertificateReloadingIT.java
- security/https/src/test/java/io/quarkus/ts/security/https/secured/TlsRegistryDecryptedKeyIT.java
Add tag Tag("fips-incompatible") to the test coverage related to Support encrypted pkcs#8
> Add tag Tag("fips-incompatible") to the test coverage related to Support encrypted pkcs#8

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/update/QuarkusCli35to315UpdateIT.java
https://github.com/quarkusio/quarkus/pull/46772 is merged, this test should now pass.
> Enable QuarkusCli35to315UpdateIT as upstream bug is now fixed

- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientIT.java
Disable test affected by https://github.com/quarkusio/quarkus/issues/46816.
This issue is already reported and doesn't seem to be fixed soon. Also this issue causes a lot of our test pipelines to fails.
> Disable test affected by issue 46816

- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/PlainBookResource.java
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientIT.java
Remove test and endpoint for map in queryParam for rest-client-reactive since this is no longed supported, after https://github.com/quarkusio/quarkus/pull/46863
> Remove map in queryParam test + endpoint

- sql-db/panache-flyway/src/test/java/io/quarkus/ts/sqldb/panacheflyway/init/OpenShiftFlywayInitContainerIT.java
- sql-db/panache-flyway/src/test/resources/Dockerfile
This need the https://github.com/quarkus-qe/quarkus-test-framework/pull/1530 to work as new properties weren't detected as buildtime.
> Enable and update the `OpenShiftFlywayInitContainerIT` test

- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/DomainSocketIT.java
- pom.xml
- properties/src/test/java/io/quarkus/ts/properties/bulk/ConfigValueIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCompletionIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliConfigEncryptIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliConfigRemoveIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliConfigSetIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateExtensionIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliExtensionsIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliHelpIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliSpecialCharsIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliTlsCommandIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliVersionIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/update/AbstractQuarkusCliUpdateIT.java
The profile.id property was introduced 4 years ago (PR 58). 
Since then the `@EnableOnNative` and `@DisableOnNative` annotation was introduced, so this replacing the `profile.id` for newer method.
The `ConfigValueIT` need to change detection of native mode as it was connected to `profile.id` value.
Also changing the `@DisableOnNative` reason from comment to annotation property. As it will be easier to filter with our new [disabled-tests-inspector](https://github.com/quarkus-qe/quarkus-utilities/tree/main/disabled-tests-inspector)
Maybe the native test in `QuarkusCliSpecialCharsIT` can be removed, as they are skiped, as `@DisableOnNative` annotate the class. I'm leaving them there atm.
> Remove profile.id property and replace it with Enable/DisableDisabled annotation

- spring/spring-data/pom.xml
- spring/spring-data/src/test/java/io/quarkus/ts/spring/data/primitivetypes/SpringDataCompositeEntityIT.java
- sql-db/panache-flyway/pom.xml
Upstream PR https://github.com/quarkusio/quarkus/pull/46879 has breaking change, moving panache from resteasy-classic to resteasy-reactive. 
This also covers "spring-data-rest" and "hibernate-orm-rest-data-panache". These are used in our test module "spring-data" and "panache-flyway". This PR update those modules to use quarkus-rest-jackson instead of quarkus-resteasy-jackson to be in sync with quarkus extensions.
> Move spring-data and panache-flyway to quarkus-rest-jackson

- test-tooling/pact/src/test/java/io/quarkus/ts/http/pact/ConsumerPactTest.java
- test-tooling/pact/src/test/java/io/quarkus/ts/http/pact/ProviderPactTest.java
Enabling the pact tests for consumer as they are working.
Update provider pact test disabled reason (as the old one is fixed/ work with Quarkus 3.15)
> Enable and update disabled reason for pact tests

- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OperatorOpenShiftAmqStreamsKafkaStreamIT.java
- messaging/kafka-streams-reactive-messaging/src/test/resources/amq-streams-operator-kafka-instance.yaml
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliTlsCommandIT.java
- Backports this https://github.com/quarkus-qe/quarkus-test-suite/pull/2277
- Checks message in both old and new format (follow-up to https://github.com/quarkus-qe/quarkus-test-suite/pull/2286)
> [3.15] Fix several failures in RHBQ tests

- http/http-minimum-reactive/src/main/java/io/quarkus/ts/http/minimum/reactive/MinMaxResource.java
- http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/HttpMinimumReactiveIT.java
- http/http-minimum/src/main/java/io/quarkus/ts/http/minimum/MinMaxResource.java
- http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/HttpMinimumIT.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/json/Book.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/json/BookAsJsonResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/PlainBookResource.java
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientIT.java
Work for https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-5621.md
It's the first part to cover simple case of grouping parameters in a custom class / Java Record (feature specific to Quarkus REST, not available in Quarkus RESTEasy) and to use Java Record in Rest Client scenario.
* `http/http-minimum` and `http/http-minimum-reactive`
* Grouping PathParams into a custom class and record
* `http/rest-client-reactive`
* Convert Book class to record
> Grouping PathParams into a custom class and record, Convert Book class to record in `http/rest-client-reactive`

- http/hibernate-validator/src/test/java/io/quarkus/ts/http/hibernate/validator/ResteasyReactiveMoviesResourceIT.java
- http/hibernate-validator/src/test/java/io/quarkus/ts/http/hibernate/validator/sources/MoviesResource.java
- http/http-advanced-reactive/pom.xml
- http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/records/CheeseResource.java
- http/http-advanced-reactive/src/main/resources/application.properties
- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/BaseHttpAdvancedReactiveIT.java
Part 2 of work for https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-5621.md
Part 1: https://github.com/quarkus-qe/quarkus-test-suite/pull/2357
`http/http-advanced-reactive`
* Covering grouping parameters in a custom class and Java Records
* Quarkus REST specific functionality, not available in Quarkus RESTEasy
* Covering all the HTTP request parameter annotations 
* https://quarkus.io/guides/rest#accessing-request-parameters
* Includes validation of provided parameter
`http/hibernate-validator`
* Hibernate Validator and Java Records
* OpenAPI schema checks for the validation rules
> Grouping parameters in a custom class and Java Records, validation of Java Records

- .github/workflows/ci.yml
Similar thing was done in quarkus-qe/quarkus-test-suite#2299
Advantage of this is that we will see all the error on the first run instead of one faster job fail and end all other jobs. Mainly the native part when updating the `pom.xml`.
> Set fail-fast to false in CI for PRs

- README.md
- pom.xml
- security/keycloak-oidc-client-standalone/pom.xml
- security/keycloak-oidc-client-standalone/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/standalone/TokenResource.java
- security/keycloak-oidc-client-standalone/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/standalone/DevModeOidcClientDevServiceUserExperienceIT.java
- security/keycloak-oidc-client-standalone/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/standalone/DevModeOidcClientTokensIT.java
- security/keycloak-oidc-client-standalone/src/test/resources/oidc-client.properties
The coverage checking that `quarkus-oidc-client` can use Keycloak dev services without need for `quarkus-oidc` extension
TP: https://github.com/quarkus-qe/quarkus-test-plans/pull/208
JIRA: https://issues.redhat.com/browse/QUARKUS-5611
> Add coverage for QUARKUS-5611 (quarkus-oidc-client developer experience)

- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/DevModeGrpcIntegrationReactiveIT.java
- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/DevModeGrpcIntegrationIT.java
Disable testGrpcDevUIServicesView tests due to regression in upstream
upstream issue: https://github.com/quarkusio/quarkus/issues/47138
> Disable testGrpcDevUIServicesView tests due to regression in upstream

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/update/QuarkusCli38to320UpdateIT.java
We cannot support update from unsupported 3.2 stream, test should be updated to match supported streams at the moment when 3.20 will be released
> [3.20] Change Quarkus CLI update test to match supported streams

- pom.xml
Bumps Quarkus QE Test Framework to 1.6.z, this should fix RHBQ CLI test scenarios.
> [3.20] Bump Quarkus QE Test Framework to 1.6.2

- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/DevModeGrpcIntegrationReactiveIT.java
- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/DevModeGrpcIntegrationIT.java
Revert "Disable testGrpcDevUIServicesView tests due to regression in upstream"
https://github.com/quarkusio/quarkus/issues/47138 should be fixed
This reverts commit c9b119b6146b843d5c4a78b8c36ebf880461ef3d.
> Revert "Disable testGrpcDevUIServicesView tests due to regression in upstream"

- pom.xml
Bumping Keycloak to 26.1 to align with Quarkus and FW (https://github.com/quarkus-qe/quarkus-test-framework/pull/1558)
The RHBK (`registry.redhat.io/rhbk/keycloak-rhel9:26.0`) don't need to be updated as the latest is used
> Bump Keycloak image to 26.1

- .github/workflows/daily.yaml
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCompletionIT.java
* Start daily GH Actions 2.5 hours earlier
* Simplify QuarkusCliCompletionIT to be less log verbose 
* Completion help command produces 12 lines, completion command produces 3096 lines
* Use unique archive names for AArch64 runs
* Artifacts are not archived properly when name collision occurs
> Misc improvements - GH Actions and QuarkusCliCompletionIT

- messaging/kafka-processor/src/test/java/io/quarkus/ts/messaging/kafka/processor/DevModeKafkaProcessorIT.java
Disables `DevModeKafkaProcessorIT` when it is run on Windows with RHBQ as it fails due to known issue. I don't want to do it on the main branch because this failure prompts us to update linked Quarkus ticket when processing new Quarkus streams. However I acknowledge that it is matter of opinion...
> [3.20] Disable DevModeKafkaProcessorIT on Windows when run with RHBQ

- README.md
- pom.xml
- websockets/websocket-next/pom.xml
- websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/QuarkusQEUpgradeCheck.java
- websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/clients/PingPongClient.java
- websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/clients/UserDataClient.java
- websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/endpoints/AdminChatWebsocket.java
- websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/endpoints/AdminOnlyChatWebSocket.java
- websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/endpoints/AuthenticatedChatWebSocket.java
- websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/endpoints/ChatWebSocket.java
- websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/endpoints/ConcurrentBlockingWebSocket.java
- websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/endpoints/CustomSerializationWebsocket.java
- websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/endpoints/FailingWebsocket.java
- websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/endpoints/NativeSerializationWebsocket.java
- websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/endpoints/ParentWebSocket.java
- websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/endpoints/PingPongWebSocket.java
- websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/endpoints/PropertiesSecuredWebSocket.java
- websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/endpoints/ReactiveWebsocket.java
- websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/endpoints/SerialBlockingWebSocket.java
- websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/endpoints/UserDataWebSocket.java
- websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/resources/AuthenticatedChatResource.java
- websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/resources/PingPongResource.java
- websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/resources/TLSChatResource.java
- websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/resources/UserDataResource.java
- websockets/websocket-next/src/main/resources/application.properties
- websockets/websocket-next/src/main/resources/tls.properties
- websockets/websocket-next/src/test/java/io/quarkuss/ts/websocketNext/BaseWebSocketIT.java
- websockets/websocket-next/src/test/java/io/quarkuss/ts/websocketNext/OpenShiftWebSocketIT.java
- websockets/websocket-next/src/test/java/io/quarkuss/ts/websocketNext/TlsWebSocketIT.java
(cherry picked from commit 3d3cfda1bead5de54b626618491e023c34f2a6ee)
Backports https://github.com/quarkus-qe/quarkus-test-suite/pull/2356 with exception of OIDC module, which is used for testing `@BearerTokenAuthentication` annotation, which is not implemented for 3.20.
> [3.20] Add websocket next tests

- websockets/websocket-next-oidc/src/main/resources/application.properties
- websockets/websocket-next-oidc/src/test/java/io/quarkuss/ts/websocketNext/VertxWebSocketClientIT.java
- websockets/websocket-next-oidc/src/test/java/io/quarkuss/ts/websocketNext/WebSocketNextBrowserAuthorizationIT.java
Test coverage for https://issues.redhat.com/browse/QUARKUS-5857
Test Plan--> https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-5857.md 
This TD implements tests for sending authorization headers from web browsers using JavaScript clients with WebSockets Next. The tests verify that both browser-based with Playwright and programmatic clients can successfully authenticate using Bearer tokens via standard headers and Sec-WebSocket-Protocol.
> Adding test coverage for QUARKUS-5857 WebSockets Next send authorization headers from web browsers using JS clients

- sql-db/sql-app/pom.xml
DB2 tests are not enabled in FIPS-enabled environment, but DB2 JDBC driver presence itself causes issue in FIPS-enabled environment. During native build, following exception is raised:
```
20:14:25,406 INFO  mvn: [2/8] Performing analysis...  []                                                                        (32.3s @ 1.65GB)
20:14:25,411 INFO  mvn:    16,986 reachable types   (82.5% of   20,588 total)
20:14:25,425 INFO  mvn:    28,604 reachable fields  (48.9% of   58,457 total)
20:14:25,468 INFO  mvn:    86,471 reachable methods (50.6% of  170,851 total)
20:14:25,468 INFO  mvn:     6,017 types,   782 fields, and 6,175 methods registered for reflection
20:14:25,470 INFO  mvn: 
20:14:25,471 INFO  mvn: Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error …
```
> Avoid SQL application module failures in FIPS-enabled environment as DB2 JDBC driver is not FIPS-compatible

- sql-db/sql-app-compatibility/pom.xml
This is the same thing as I have done in https://github.com/quarkus-qe/quarkus-test-suite/pull/2388, but I didn't realize we run compatibility tests in native mode as well (turns out we run _some_ of them).
> Fix SQL application native failures in compatibility module when run in FIPS-enabled environment

- security/keycloak/pom.xml
- security/keycloak/src/test/java/io/quarkus/ts/security/keycloak/MultiMechanismAuthenticationIT.java
- security/keycloak/src/test/java/io/quarkus/ts/security/keycloak/OpenShiftMultiMechanismAuthenticationIT.java
- security/keycloak/src/test/resources/multi-mechanism.properties
TP: https://github.com/quarkus-qe/quarkus-test-plans/pull/217
Jira: https://issues.redhat.com/browse/QUARKUS-5617
Adding tests to check if multiple authentication mechanism are enforced at same time.
> Add coverage for QUARKUS-5617 (Support for two or more authentications for a single request)

- pom.xml
- sql-db/hibernate-fulltext-search/src/test/java/io/quarkus/ts/hibernate/search/OpenShiftPostgresqlMultitenantHibernateSearchIT.java
- sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/openshift/OpenShiftPostgresql12HibernateReactiveIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/OpenShiftPostgresql12DatabaseIT.java
Changed motivated by https://issues.redhat.com/browse/QUARKUS-5472, TP https://github.com/quarkus-qe/quarkus-test-plans/pull/220.
> Switch PostgreSQL in baremetal tests from 16 to 17

- websockets/websocket-next/src/main/java/io/quarkus/ts/websocketNext/clients/PingPongClient.java
- websockets/websocket-next/src/test/java/io/quarkuss/ts/websocketNext/OpenShiftWebSocketsNextMetricsIT.java
- websockets/websocket-next/src/test/java/io/quarkuss/ts/websocketNext/WebSocketsNextMetricsIT.java
Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/2404
* Adding tests for Micrometer metrics exposed for WebSockets.
Test plan: https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-5667.md
Feature issue: https://issues.redhat.com/browse/QUARKUS-5667
Code changes: https://github.com/quarkusio/quarkus/pull/44379
> [3.20] Adding Micrometer tests for WebSockets.next

- sql-db/multiple-pus/pom.xml
- sql-db/multiple-pus/src/main/java/io/quarkus/ts/sqldb/multiplepus/FungusResource.java
- sql-db/multiple-pus/src/main/java/io/quarkus/ts/sqldb/multiplepus/producer/DatasourceProducer.java
- sql-db/multiple-pus/src/main/java/io/quarkus/ts/sqldb/multiplepus/producer/DatasourceProducerResource.java
- sql-db/multiple-pus/src/main/resources/application.properties
- sql-db/multiple-pus/src/test/java/io/quarkus/ts/sqldb/multiplepus/AbstractCustomDatasourceProducerIT.java
- sql-db/multiple-pus/src/test/java/io/quarkus/ts/sqldb/multiplepus/AbstractMultiDatabaseActiveInactiveIT.java
- sql-db/multiple-pus/src/test/java/io/quarkus/ts/sqldb/multiplepus/CustomDatasourceProducerIT.java
- sql-db/multiple-pus/src/test/java/io/quarkus/ts/sqldb/multiplepus/MultiDatabaseActiveInactiveIT.java
- sql-db/multiple-pus/src/test/java/io/quarkus/ts/sqldb/multiplepus/OpenShiftCustomDatasourceProducerIT.java
- sql-db/multiple-pus/src/test/java/io/quarkus/ts/sqldb/multiplepus/OpenShiftMultiDatabaseActiveInactiveIT.java
- sql-db/multiple-pus/src/test/resources/datasource-producer.properties
Adding coverage for QUARKUS-5659.
Jira https://issues.redhat.com/browse/QUARKUS-5659
TP https://github.com/quarkus-qe/quarkus-test-plans/pull/223
> Add coverage for QUARKUS-5659 (Use Arc features in datasource extensions for eager startup and active/inactive)

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
Disable shouldKeepUsingTheSameQuarkusVersionAfterReload test because of upstream regression
> Disable shouldKeepUsingTheSameQuarkusVersionAfterReload test because of upstream regression

- http/http-advanced-reactive/pom.xml
We also have `native-linux-aarch64` for the same purpose, I used Maven profile because I don't think we should add dependencies we don't use, these things can be activated for example by `arch`, but I used the property we already have.
Tested here: https://jenkins-csb-runtimes-ibmzqe-master.dno.corp.redhat.com/view/RHOAR/job/rhbq-3.x-ocp4-rhel8-rhel9-jdk17-test/jdk=openjdk17,label=quarkus,scenario=http-modules/224/consoleFull 
> Fix Brotli4j scenarios with S390X and ppc64le architectures tested by our IBM partners

- websockets/websocket-next/src/main/java/io/quarkus/ts/websockets/next/endpoints/AuthenticatedChatWebSocket.java
- websockets/websocket-next/src/main/resources/application.properties
- websockets/websocket-next/src/test/java/io/quarkus/ts/websockets/next/BaseWebSocketIT.java
Enhancement with permission checkers for WebSockets Next
Primary motivation is native coverage
TP: https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-5859.md
> Enhancement with permission checkers for WebSockets Next

- pom.xml
Updating the supported mongodb  image for IBM 
Test job 
https://jenkins-csb-runtimes-ibmzqe-master.dno.corp.redhat.com/view/RHOAR/job/rhbq-3.x-ocp4-rhel8-rhel9-jdk17-test/jdk=openjdk17,label=quarkus,scenario=databases-modules/219/console
> [3.20] Updating the supported mongodb  image for IBM 

- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/OpenShiftHttpAdvancedReactiveIT.java
- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/OpenShiftHttpAdvancedIT.java
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/AbstractLogoutSinglePageAppFlowIT.java
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/AbstractOidcRestClientIT.java
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/LogoutSinglePageAppFlowIT.java
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/OidcRestClientIT.java
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/OpenApiStoreSchemaIT.java
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/OpenShiftOidcRestClientIT.java
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/OpenShiftOidcSinglePageAppLogoutFlowIT.java
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/SecurityClaimsIT.java
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/TokenPropagationFilterIT.java
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/TokenUtils.java
@ramdr suggested that if we start using the Keycloak image provided  by Red Hat, our IBM partners will be able to run more tests. This PR makes changes similar to what has been done in #2409. 
> Use Red Hat Build of Keycloak for OpenShift tests and thus enable IBM partners to run more Keycloak tests

- websockets/websocket-next/src/main/java/io/quarkus/ts/websockets/next/clients/PingPongClient.java
- websockets/websocket-next/src/test/java/io/quarkus/ts/websockets/next/OpenShiftWebSocketsNextMetricsIT.java
- websockets/websocket-next/src/test/java/io/quarkus/ts/websockets/next/WebSocketsNextMetricsIT.java
* Add missing tag to WebSockets next Metrics tests
* Since the endpoint produced new exception for every ping after the
second one, this commit changes the endpoint to produce the exception
only on the third ping. This removes raciness from the test.
> WebSocketsNextMetricsIT fixes

- websockets/websocket-next/pom.xml
- websockets/websocket-next/src/test/java/io/quarkus/ts/websockets/next/BaseWebSocketIT.java
- websockets/websocket-next/src/test/java/io/quarkus/ts/websockets/next/Client.java
- websockets/websocket-next/src/test/java/io/quarkus/ts/websockets/next/OpenShiftWebSocketsNextOpenTelemetryIT.java
- websockets/websocket-next/src/test/java/io/quarkus/ts/websockets/next/WebSocketsNextMetricsIT.java
- websockets/websocket-next/src/test/java/io/quarkus/ts/websockets/next/WebSocketsNextOpenTelemetryIT.java
* Adding a test verifying that websocket operations (open/close) are traced by OpenTelemetry, and that the traces refer to eachother.
Issue: https://github.com/quarkusio/quarkus/issues/39143
Code change: https://github.com/quarkusio/quarkus/pull/41956
Documentation: https://quarkus.io/version/main/guides/websockets-next-reference#telemetry
Test plan: https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-5658.md
> QUARKUS-5658 WS.next + Otel tests

- pom.xml
- websockets/websocket-next-oidc/pom.xml
- websockets/websocket-next-oidc/src/main/java/io/quarkus/ts/websockets/next/endpoints/AdminChatWebSocket.java
- websockets/websocket-next-oidc/src/main/java/io/quarkus/ts/websockets/next/endpoints/AuthenticatedWebSocket.java
- websockets/websocket-next-oidc/src/main/resources/application.properties
- websockets/websocket-next-oidc/src/test/resources/test-realm-realm.json
Changes:
- replaces `@BearerAuthentication` (not supported in 3.20) with HTTP permission-based path policy
- enables WebSockets Next OIDC module
The only difference between the `main` and `3.20` branch after this PR will be `@BeareAuthentication` mechanism and 3 configuration properties.
> [3.20] Enable and fix WebSockets Next OIDC module

- pom.xml
- security/jpa/src/test/java/io/quarkus/ts/security/jpa/MariaDbMd5JpaIT.java
- spring/spring-web-reactive/src/test/java/io/quarkus/ts/spring/web/reactive/MariaDBConstants.java
- spring/spring-web-reactive/src/test/java/io/quarkus/ts/spring/web/reactive/bootstrap/SpringWebQuteReactiveIT.java
- spring/spring-web-reactive/src/test/java/io/quarkus/ts/spring/web/reactive/bootstrap/SpringWebRestReactiveIT.java
- spring/spring-web-reactive/src/test/java/io/quarkus/ts/spring/web/reactive/openapi/SpringWebOpenApiReactiveIT.java
- spring/spring-web/src/test/java/io/quarkus/ts/spring/web/MariaDBConstants.java
- spring/spring-web/src/test/java/io/quarkus/ts/spring/web/bootstrap/SpringWebQuteIT.java
- spring/spring-web/src/test/java/io/quarkus/ts/spring/web/bootstrap/SpringWebRestIT.java
- spring/spring-web/src/test/java/io/quarkus/ts/spring/web/openapi/SpringWebOpenApiIT.java
- sql-db/multiple-pus/src/test/java/io/quarkus/ts/sqldb/multiplepus/CustomDatasourceProducerIT.java
- sql-db/multiple-pus/src/test/java/io/quarkus/ts/sqldb/multiplepus/MultiDatabaseActiveInactiveIT.java
- sql-db/multiple-pus/src/test/java/io/quarkus/ts/sqldb/multiplepus/MultiplePersistenceIT.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/MariaDbTransactionGeneralUsageIT.java
- sql-db/reactive-rest-data-panache/src/test/java/io/quarkus/ts/reactive/rest/data/panache/MariaDBPanacheResourceIT.java
- sql-db/sql-app-compatibility/src/test/java/io/quarkus/ts/sqldb/compatibility/MariaDBDatabaseIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/MariaDBDatabaseIT.java
I recently bumped MariaDB to 11.4 https://github.com/quarkus-qe/quarkus-test-suite/pull/2400, but MariaDB 11.4 doesn't start in FIPS-enabled environment https://issues.redhat.com/browse/QUARKUS-5984, so instead of having failing tests or disabling all the tests, I think we should use 10.11 in FIPS-enabled environment.
Tested in `rhbq-3.20-extended-platform/job/rhbq-3.20-baremetal-ts-jvm/18`.
> Use MariaDB 10.11 in FIPS-enabled environment because 11.4 version does not start

- service-discovery/stork-custom/pom.xml
- service-discovery/stork/pom.xml
Explicit dependency on quarkus-smallrye-stork in Stork modules
Trigger: https://github.com/quarkusio/quarkus/pull/47435 
Quarkus upstream moved away from strong coupling between REST Client and Stork to optional dependency.
Stork modules should depend on `quarkus-smallrye-stork` anyway.
> Explicit dependency on quarkus-smallrye-stork in Stork modules

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
Revert "Disable shouldKeepUsingTheSameQuarkusVersionAfterReload test because of upstream regression"
This reverts commit 002e50b51645cca103e45c2c8291f090824b48ea.
> Revert "Disable shouldKeepUsingTheSameQuarkusVersionAfterReload test because of upstream regression"

- monitoring/opentelemetry-reactive/src/main/java/io/quarkus/ts/opentelemetry/reactive/PartiallyTraceableResource.java
- monitoring/opentelemetry-reactive/src/main/java/io/quarkus/ts/opentelemetry/reactive/UntraceableResource.java
- monitoring/opentelemetry-reactive/src/test/java/io/quarkus/ts/opentelemetry/reactive/OpentelemetryReactiveIT.java
* Adding test for ability to exclude URIs from tracing.
Jira: https://issues.redhat.com/browse/QUARKUS-5668
Upstream documentation: https://quarkus.io/guides/opentelemetry-tracing#disabling-traces-for-app-endpoints
Code changes:
* https://github.com/quarkusio/quarkus/pull/43885
* https://github.com/quarkusio/quarkus/pull/44724
> QUARKUS-5668 tests

- monitoring/opentelemetry-reactive/src/main/java/io/quarkus/ts/opentelemetry/reactive/PartiallyTraceableResource.java
- monitoring/opentelemetry-reactive/src/main/java/io/quarkus/ts/opentelemetry/reactive/UntraceableResource.java
- monitoring/opentelemetry-reactive/src/test/java/io/quarkus/ts/opentelemetry/reactive/OpentelemetryReactiveIT.java
* Adding test for ability to exclude URIs from tracing.
Jira: https://issues.redhat.com/browse/QUARKUS-5668
Upstream documentation: https://quarkus.io/guides/opentelemetry-tracing#disabling-traces-for-app-endpoints
Code changes:
* https://github.com/quarkusio/quarkus/pull/43885
* https://github.com/quarkusio/quarkus/pull/44724
(cherry picked from commit 84226a2c47533918a7be73e0a1617b494ada3f60)
> [3.20] QUARKUS-5668 -  Adding test for ability to exclude URIs from tracing

- websockets/websocket-next-oidc/src/test/java/io/quarkus/ts/websockets/next/AbstractOidcWebSocketIT.java
- websockets/websocket-next-oidc/src/test/java/io/quarkus/ts/websockets/next/OidcWebSocketIT.java
- websockets/websocket-next-oidc/src/test/java/io/quarkus/ts/websockets/next/OpenShiftOidcWebSocketIT.java
Same reason as #2419 and #2409.
> Fix OpenShiftOidcWebSocketIT execution on IBM PE/Z by using Red Hat Build of Quarkus in OpenShift

- .github/workflows/daily.yaml
Reduce the execution time of the daily CI run
* Drop of ubi9-quarkus-graalvmce-builder-image:jdk-21, Mandrel our main focus
* Focus on Java 21 in JVM runs, Java 17 is used for compilation in Native runs
* root-modules as a separate entry in JVM runs, execution time is ~45 minutes, and it grows thanks to the CLI
> Reduce the execution time of the daily CI run

- messaging/amqp-reactive/src/test/java/io/quarkus/ts/messaging/amqpreactive/TLSAmqpReactiveIT.java
Verify fix [#46900](https://github.com/quarkusio/quarkus/pull/46900) for TLS ALPN config exception
The test created will fail  with the exception `UnsupportedOperationException` described in the issue [46652](https://github.com/quarkusio/quarkus/issues/46652) with mvn execution specifying a previous version before the fix:
`mvn clean verify -Dit.test=TLSAmqpReactiveIT -Dreruns=0 -Dquarkus.platform.version=3.19.0
`
> TD for verifies AMQP messaging works correctly when ALPN is disabled -  issue #46900

- http/rest-client-reactive/src/main/resources/modern.properties
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/DevModeIT.java
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/LargeFileHandlingIT.java
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/LocalProxyIT.java
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientIT.java
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientProxyIT.java
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/UrlOverrideClientIT.java
The property forces framework to use the file as the main properties file; The method adds all properties to CLI.
The user usually wants the former.
This patch affects only tests in rest-client-reactive and only if they they work without any problems after the change.
> Use option `properties` instead of method withProperties in reactive REST client tests

- qute/reactive/src/main/java/io/quarkus/ts/qute/Application.java
- qute/reactive/src/main/java/io/quarkus/ts/qute/UserTemplates.java
- qute/reactive/src/main/resources/templates/UserWithOrder.html
- qute/reactive/src/test/java/io/quarkus/ts/qute/QuteReactiveIT.java
Test coverage for fix implemented in PR [47001](https://github.com/quarkusio/quarkus/pull/47001) related also with [46980](https://github.com/quarkusio/quarkus/issues/46980)
> Coverage for fix Qute record constructor search with nested type-safe fragment #47001

- websockets/websocket-next/src/test/java/io/quarkus/ts/websockets/next/BaseWebSocketIT.java
Enable nativeSerializationTest from websocket-next for 3.20.1 
In this case, this test was only disabled in our 3.20 branch.
Original issue-->  https://github.com/quarkusio/quarkus/issues/47269 
This was fix in main here--> https://github.com/quarkusio/quarkus/pull/47027 
> [3.20] - Enable nativeSerializationTest from websocket-next 

- sql-db/narayana-transactions/src/main/java/io.quarkus.ts.transactions/ClientEntity.java
- sql-db/narayana-transactions/src/main/java/io.quarkus.ts.transactions/ClientResource.java
- sql-db/narayana-transactions/src/main/java/io.quarkus.ts.transactions/ClientService.java
- sql-db/narayana-transactions/src/main/resources/import.sql
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/TransactionCommons.java
- sql-db/narayana-transactions/src/test/resources/mariadb_import.sql
- sql-db/narayana-transactions/src/test/resources/mssql_import.sql
- sql-db/narayana-transactions/src/test/resources/mysql_import.sql
- sql-db/narayana-transactions/src/test/resources/oracle_import.sql
Coverage for [QUARKUS-5950](https://issues.redhat.com/browse/QUARKUS-5950) and [QUARKUS-5882](https://issues.redhat.com/browse/QUARKUS-5882) which trigger it. Also this was discovered in https://github.com/quarkusio/quarkus/issues/45087
It cover the case where the SQL query was executed after the transaction timeout. The transaction should not be commited in this case. Before the Agroal fix the transaction was commited even after the timeout.
> Add coverage for Agroal bug when the transaction was commited after the timeout

- http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/ResourcesFinderResource.java
- http/http-advanced-reactive/src/main/resources/application.properties
- http/http-advanced-reactive/src/main/resources/resource-finder-dir/resource_finder_dir.txt
- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/ResourceFinderIT.java
This adding coverage for https://github.com/quarkusio/quarkus/pull/47378.
It testing if the resources is directory it should be returned with `/`. Otherwise the RunnerClassLoader can point to wrong path. This is more useful for extension as they are likely will be touching classpath then aplication.
> Add coverage for RunnerClassLoader returnnig resource with `/` if they end with `/`

- http/hibernate-validator/pom.xml
- http/hibernate-validator/src/test/java/io/quarkus/ts/http/hibernate/validator/HibernateValidatorGraalVMFeatureValidationIT.java
- http/hibernate-validator/src/test/java/io/quarkus/ts/http/hibernate/validator/sources/GraalVMFeatureResource.java
- http/hibernate-validator/src/test/resources/graalvm-feature-validation.properties
Verifies: https://github.com/quarkusio/quarkus/issues/47033
Supersedes: https://github.com/quarkus-qe/quarkus-test-suite/pull/2457
PASS: `mvn clean verify -Dnative -Dit.test=HibernateValidatorGraalVMFeatureValidationIT -Dquarkus.platform.version=3.20.1`
FAIL: `mvn clean verify -Dnative -Dit.test=HibernateValidatorGraalVMFeatureValidationIT -Dquarkus.platform.version=3.20.0`
> Verify Hibernate Validator extension with GraalVM Feature

- service-discovery/stork/pom.xml
- service-discovery/stork/src/main/java/io/quarkus/ts/stork/GreetingResource.java
- service-discovery/stork/src/main/java/io/quarkus/ts/stork/IGreetingResource.java
- service-discovery/stork/src/main/java/io/quarkus/ts/stork/KafkaPriceProducer.java
- service-discovery/stork/src/main/java/io/quarkus/ts/stork/PriceConsumer.java
- service-discovery/stork/src/main/resources/application.properties
- service-discovery/stork/src/test/java/io/quarkus/ts/stork/KafkaWithStorkIT.java
Adding test coverage for https://github.com/quarkusio/quarkus/issues/41658 which fixes a NPE that occurred during shutdown when using Kafka with Stork-based service discovery
The command where the original NPE from the issue comes up was:
1. `mvn quarkus:dev`
2. press` 's'`
3. Look at the error traces logs
The specific NPE was : 
`Cannot invoke "io.smallrye.stork.Stork.getService(String)" because the return value of "io.smallrye.stork.Stork.getInstance()" is null` and the test validates that the specific Stork NPE no longer occurs during shutdown.
Note: To run this test locally, you need to start Consul first (as some existing classes depend on it):
`$ docker run --rm --name consul -p 8500:8500 -p 8501:8501 consul:1.7 agent -dev -ui -client=0.0.0.0 -bind=0.0.0.0 --https-port=8501
` 
The …
> Test coverage for NPE kafka stork #41658

- websockets/websocket-next/src/test/java/io/quarkus/ts/websockets/next/AutoPingCancellationIT.java
Test coverage for the fix implemented in PR #47235, improves robustness regarding an issue with WebSockets auto-ping timers.
Upstream fix --> https://github.com/quarkusio/quarkus/pull/47271 
Original issue --> https://github.com/quarkusio/quarkus/issues/47235 
> Test coverage for Websocket next server autoping timer #47271

- sql-db/hibernate/src/main/java/io/quarkus/qe/hibernate/items/MyEntity.java
- sql-db/hibernate/src/main/java/io/quarkus/qe/hibernate/items/MyEntityId.java
- sql-db/hibernate/src/main/java/io/quarkus/qe/hibernate/items/MyEntityResource.java
- sql-db/hibernate/src/test/java/io/quarkus/qe/hibernate/BaseHibernateIT.java
Coverage for https://issues.redhat.com/browse/QUARKUS-5714
Bad validation of EmbeddedId when creation and update of entity is in one transaction.
For more info see https://hibernate.atlassian.net/browse/HHH-19206
Command to show that this test checking issue `mvn -fae -V -B clean verify -Dreruns=0 -Psql-db-modules -pl sql-db/hibernate  -Dit.test="ProdHibernateIT" -Dquarkus.platform.version=3.15.4`
> Add coverage for QUARKUS-5714 (Bad validation of Embedded ID)

- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/OpenShiftBrotli4JIT.java
The test failing for IBM team. The issue was fixed in 3.20 but is not backported to 3.15 and there is no plan to backport it. So disable this test with same reason as arm.
> [3.15] Disable OpenShiftBrotli4JIT for IBM execution

- security/keycloak-oidc-client-extended/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/dpop/DpopProtectedResource.java
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/AbstractDpopIT.java
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/DpopIT.java
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/OpenShiftDpopIT.java
Implement tests based on https://github.com/quarkus-qe/quarkus-test-plans/pull/232. 
> Add test coverage for QUARKUS-5858

- service-binding/postgresql-crunchy-classic/src/test/java/io/quarkus/ts/sb/postgresql/OpenShiftPostgreSqlSbIT.java
- service-binding/postgresql-crunchy-reactive/src/test/java/io/quarkus/ts/sb/reactive/OpenShiftPostgreSqlReactiveSbIT.java
Related to https://issues.redhat.com/browse/QQE-1587
Backport of:
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2162
> [3.15] Backport - Disable service binding ocp tests - failing with crunchydb operator

- sql-db/hibernate-reactive/src/main/java/io/quarkus/ts/hibernate/reactive/database/AuthorIdGenerator.java
- sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/MsSQLDatabaseHibernateReactiveIT.java
- sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/PostgresqlDatabaseHibernateReactiveIT.java
* API for ReactiveIdentifierGenerator changed with Hibernate 7.0 (see
https://github.com/hibernate/hibernate-reactive/issues/1826). This
commit adds the missing method implementations.
* Disabling tests that detect
https://github.com/quarkusio/quarkus/issues/48476.
> Updates to address Hibernate 7 update in Quarkus

- security/keycloak/src/main/java/io/quarkus/ts/security/keycloak/OidcProviderClientResource.java
- security/keycloak/src/test/java/io/quarkus/ts/security/keycloak/BaseOidcSecurityIT.java
- security/keycloak/src/test/resources/test-realm-realm.json
TP: https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-5653.md
`Security event-driven token revocation` cannot be really tested with Keycloak as it automatically revoke tokens during logout process and there is no way to distinguish between KC internal event and manual token revocation.
At least there is a [mock test](https://github.com/quarkusio/quarkus/blob/main/integration-tests/oidc-wiremock-logout/src/test/java/io/quarkus/it/keycloak/CodeFlowAuthorizationTest.java) on upstream side
> Test OIDC token revocation using OidcProviderClient 

- sql-db/narayana-transactions/src/test/resources/mssql.properties
- sql-db/reactive-rest-data-panache/src/test/resources/mssql.properties
- sql-db/sql-app-compatibility/src/test/resources/mssql.properties
- sql-db/sql-app/src/test/resources/mssql.properties
- In Hibernate 7.0 `SQLServer2012Dialect` was replaced with `SQLServerDialect`
> SQLServer2012Dialect replaced by SQLServerDialect

- spring/spring-web-reactive/src/test/java/io/quarkus/ts/spring/web/reactive/bootstrap/OpenShiftSpringWebQuteReactiveIT.java
- spring/spring-web-reactive/src/test/java/io/quarkus/ts/spring/web/reactive/bootstrap/OpenShiftSpringWebRestReactiveIT.java
- spring/spring-web-reactive/src/test/java/io/quarkus/ts/spring/web/reactive/openapi/OpenShiftSpringWebOpenApiReactiveIT.java
- sql-db/hibernate-fulltext-search/src/test/java/io/quarkus/ts/hibernate/search/OpenShiftPostgresqlMultitenantHibernateSearchIT.java
- sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/openshift/OpenShiftPostgresql12HibernateReactiveIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/OpenShiftPostgresql12DatabaseIT.java
OpenShift tests are failing as Red Hat MariaDB and PostgreSQL images are using older versions than defaults configured at the build time. This is expected failure as [minimum database versions](https://docs.jboss.org/hibernate/orm/7.0/dialect/dialect.html) has changed after upgrade to Hibernate ORM 7.0
Also in Quarkus 3.25 migration guide: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.25#hibernate-reactive
Our MariaDB `10.3` vs  default `10.5`
Our PostgreSQL `12` vs default `13`
> Set explicitly min database version for older db images to fix OCP tests

- sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/MsSQLDatabaseHibernateReactiveIT.java
- sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/PostgresqlDatabaseHibernateReactiveIT.java
https://github.com/quarkusio/quarkus/issues/48476 is fixed and tests are passing locally on my workstation.
> Enable Hiberante Reactive tests disabled due to #48476 upstream issue

- security/oidc-client-mutual-tls/src/test/java/io/quarkus/ts/security/oidcclient/mtls/OidcMtlsBindingIT.java
In this test the already created keystore/trustore are used. They have predefined SANs which not match windows one (The ip for containers are used there). For mtls this was solved by `LocalHostKeycloakContainerManagedResourceBuilder` but I miss this when creating test coverage for mtls binding. Setting the builder is fixing the issue on windows.
> Fix OidcMtlsBindingIT on windows due to dynamic SAN

- security/keycloak-oidc-client-extended/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/ping/clients/TokenPropagationPongClient.java
- security/keycloak-oidc-client-reactive-extended/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/ping/clients/TokenPropagationPongClient.java
The `io.quarkus.oidc.token.propagation.AccessToken` was deprecated and marked for removal in Quarkus 3.19. Before next LTS we should update it to test what is recommended
> Replace deprecated `@AccessToken` import path

- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMssqlIT.java
- sql-db/sql-app/src/test/resources/container-license-acceptance.txt
Fix MS SQL Server Dev Mode tests on macOS
mcr.microsoft.com/azure-sql-edge:latest is used instead of mcr.microsoft.com/mssql/server:2022-latest on macOS
> Fix MS SQL Server Dev Mode tests on macOS

- sql-db/sql-app/src/test/resources/postgresql-compose-devservices.yml
Aarch64 is using RH image that expects different environment variables, which is reason why Aarch64 daily build is failing. We have these properties in our PG service already, see https://github.com/quarkus-qe/quarkus-test-framework/blob/main/quarkus-test-service-database/src/main/java/io/quarkus/test/bootstrap/PostgresqlService.java. I have tested this fix on a Beaker machine.
> Fix DevModePostgresqlComposeIT on Aarch64

- pom.xml
- security/keycloak-authz-classic/src/test/java/io/quarkus/ts/security/keycloak/authz/OpenShiftRhSsoAuthzSecurityIT.java
- security/keycloak-authz-reactive/src/test/java/io/quarkus/ts/security/keycloak/authz/reactive/OpenShiftRhSsoAuthzSecurityReactiveIT.java
- security/keycloak-jwt/src/test/java/io/quarkus/ts/security/keycloak/jwt/OpenShiftRhSsoOidcJwtSecurityIT.java
- security/keycloak-multitenant/src/test/java/io/quarkus/ts/security/keycloak/multitenant/OpenShiftRhSsoMultiTenantSecurityIT.java
- security/keycloak-multitenant/src/test/java/io/quarkus/ts/security/keycloak/multitenant/OpenShiftRhSsoStaticMultiTenantUserInfoIT.java
- security/keycloak-oauth2/src/test/java/io/quarkus/ts/security/keycloak/oauth2/OpenShiftRhSsoOauth2SecurityIT.java
- security/keycloak-oidc-client-basic/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/basic/OpenShiftRhSsoOidcClientSecurityIT.java
- security/keycloak-oidc-client-reactive-basic/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/basic/OpenShiftRhSsoOidcClientSecurityIT.java
- security/keycloak-webapp/src/test/java/io/quarkus/ts/security/keycloak/webapp/OpenShiftRhSsoWebappSecurityIT.java
- security/keycloak/src/test/java/io/quarkus/ts/security/keycloak/OpenShiftRhSsoOidcSecurityIT.java
- security/oidc-client-mutual-tls/src/test/java/io/quarkus/ts/security/oidcclient/mtls/OpenShiftRhSsoOidcMtlsIT.java
Fixes #1145 
The RHBK 26.2 is first one which fully support ARM64 architecture.
https://catalog.redhat.com/software/containers/rhbk/keycloak-rhel9/64f0add883a29ec473d40906?architecture=arm64&image=687a6ce6590f6e279ac7a826
> Bump RHBK version to the latest one and enable ARM tests

- messaging/kafka-streams-reactive-messaging/src/test/resources/amq-streams-operator-kafka-instance.yaml
Backport https://github.com/quarkus-qe/quarkus-test-suite/pull/2539 into 3.20
> [3.20] Backport - Migrate to KRaft in kafka operator deployment

- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/AbstractSqlDatabaseIT.java
I restricted the Docker Compose Windows workaround to Docker as I thought Podman Compose will kick in, but our tests in Jenkins failed, so applying the same workaround as we do for the Docker. Tested in Jenkins run `periodic-builds/job/quarkus-main-win22-jdk17-baremetal-ts-jvm-podman-monthly/38/label=RHEL8 && medium,scenario=databases-modules-1/testReport/io.quarkus.ts.sqldb.sqlapp/`.
> Fix Docker Compose test cases on Windows with Podman

- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/RemoteDevModeHttpAdvancedIT.java
I have reported that remote dev mode behaves bit different on Windows here https://github.com/quarkusio/quarkus/issues/49434, though it may be that things are just slower on Windows, don't know. I think we need to retry as even when the application was ready, it can start reloading.
Tested in `job/quarkus-main-win22-jdk17-baremetal-ts-jvm-podman-monthly/40/`.
> Workaround remote dev Windows issue

- sql-db/hibernate-reactive/src/main/java/io/quarkus/ts/hibernate/reactive/http/GroundedEndpoint.java
- sql-db/hibernate-reactive/src/main/resources/application.properties
- sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/AbstractDatabaseHibernateReactiveIT.java
Verifies https://github.com/quarkusio/quarkus/pull/49163. The Hibernate Reactive session is lost without the fix so request fails, with the fix, response is correct. The endpoint modified in this commit was unused.
- pass: `mvn clean verify -Dit.test=PostgresqlDatabaseHibernateReactiveIT`
- fail: `mvn clean verify -Dquarkus.platform.version=3.20.2 -Dit.test=PostgresqlDatabaseHibernateReactiveIT`
The upstream test coverage doesn't really test it with Hibernate Reactive as we do.
> [3.20] Verify Vert.X duplicated context propagation when Hiberante Reactive session is used with Quarkus REST

- http/vertx/src/test/java/io/quarkus/ts/vertx/PortConflictIT.java
* Removing version conditioned disabled on PortConflictIT. The test should fail on versions where the bug is present, and those are out of support now already.
> Remove versioned disable on PortConflictIT

- sql-db/narayana-transactions/src/main/java/io/quarkus/ts/transactions/recovery/TransactionLogsResource.java
- sql-db/narayana-transactions/src/main/java/io/quarkus/ts/transactions/recovery/service/QuarkusTransactionCallRecoveryService.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/OracleTransactionGeneralUsageIT.java
- sql-db/narayana-transactions/src/test/resources/oracle.properties
I got suggestions in https://github.com/quarkusio/quarkus/issues/35333 to grant rights to the database user to use 2-Phase Commit. Despite the links, I think these suggestions basically match official docs here https://docs.oracle.com/en/database/oracle/oracle-database/23/adfns/xa.html#GUID-91007BAE-9DD3-4993-8220-C3EC8391376B. However I checked and our database user has required permissions. The issue was that Oracle JDBC driver optimizes 2PC and use 1PC if the XA resources points to the same database. Hence this PR creates a new database and makes sure that the transaction recovery is performed on 2 databases.
If you want to check (apart of the object store check which would simply fail if 2PC didn't happen), you can also add:
```
quarkus.log.category."org.hibernate.SQL".level=TRACE …
```
> Fix and enable Narayana transaction recovery with Oracle database

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
Our daily builds and pretty much any PR CI that runs full test coverage fails as the latest Quarkus Gradle plugin wasn't reachable. @rsvoboda fixed and documented the issue upstream https://github.com/quarkusio/quarkus/pull/49694 https://github.com/quarkusio/quarkus/pull/49675 and now we need to point to the right repository.
I have reproduced the issue locally, deleted locally built artifact and verified that this fix does the trick for my setup.
> Fix link to Maven snapshot repository in Gradle settings used by Quarkus CLI tests

- monitoring/micrometer-opentelemetry/src/test/java/io/quarkus/ts/monitoring/micrometeropentelemetry/test/OpenShiftMicrometerOpenTelemetryBridgeIT.java
- pom.xml
- IBM Z/P Profile update: Upgraded AMQ Streams from kafka-35–rhel8 (2.6.0) → kafka-38–rhel9 (2.9.1) in pom.xml.
- Disabled OpenShiftMicrometerOpenTelemetryBridgeIT on IBM Z/P, since the grafana/otel-lgtm container is not available on s390x and ppc64le.
> IBM Z/P Profile update and Disabled OpenShiftMicrometerOpenTelemetryBridgeIT

- sql-db/narayana-transactions/src/main/resources/application.properties
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/MariaDbTransactionGeneralUsageIT.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/TransactionCommons.java
Implements the https://github.com/quarkus-qe/quarkus-test-plans/pull/257 test plan. I had to add a check for a logging message in order to assure that the test reliably fails without the `quarkus.datasource.%s.jdbc.enable-recovery` configuration property. It was that or waiting for 10 seconds, so I think the log message is quicker.
> Test enabling and disabling XA transaction recovery for individual datasources

- monitoring/micrometer-opentelemetry/src/test/java/io/quarkus/ts/monitoring/micrometeropentelemetry/test/DevModeOtelCapabilitiesIT.java
Test coverage for [#47458](https://github.com/quarkusio/quarkus/pull/47458) 
Original issue in the user comment --> [#47031](https://github.com/quarkusio/quarkus/issues/47031#issuecomment-2781308022)
The test validates that the warning traces `Failed to export LogsRequestMarshalers` and `Failed to export MetricsRequestMarshalers` described by the user here https://github.com/quarkusio/quarkus/issues/47031#issuecomment-2781308022 are not present after the fix.
Mvn command executed for the test:
`mvn clean verify -Dit.test=DevModeOtelCapabilitiesIT -Dreruns=0`
And fail with:
`mvn clean verify -Dquarkus.platform.version=3.21.1 -Dit.test=DevModeOtelCapabilitiesIT -Dreruns=0`
> Add test coverage for #47458 Add Metrics and Logs to OTel Capabilities

- pom.xml
* Adding configuration to Maven compiler plugin to ensure that annotation processor dependency resolution respects dependency management of the project rather than dependencies of the processor.
More info: https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#annotationProcessorPathsUseDepMgmt
> Ensure annotation processor respect depmgmt

- .github/actions/prepare-quarkus-cli/action.yml
- .github/workflows/ci.yml
- build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/AnalyticsUtils.java
- external-applications/src/test/java/io/quarkus/ts/external/applications/QuickstartIT.java
- pom.xml
* Updating to 3.27 snapshot of Quarkus dependency
* Updating actions to run with 3.27 Quarkus branch
* Updating to framework 1.7.2 based on Quarkus 3.27
* Making QuickstartsIT use 3.27 branch of quickstarts repository
> Update to 3.27 Quarkus branch

- pom.xml
https://github.com/quarkusio/quarkus/pull/49429 bumped Hibernate Search to 8.1 which [claims to support Elastic 9.1](https://in.relation.to/2025/08/08/hibernate-search-8-1-0-Final/) (though the ticket title is bit confusing https://hibernate.atlassian.net/browse/HSEARCH-5438 but I suppose they won't claim support for each micro). Elastic is now at 9.1.4 in the main https://github.com/quarkusio/quarkus/blob/86d4b6bd6264846f88e8a6c395af37d56847577a/bom/application/pom.xml#L104 and the bump will be backported to 3.27 https://github.com/quarkusio/quarkus/pull/50185. For that reason, I'd like to bump our Elastic version as well.
This change is related to https://issues.redhat.com/browse/QUARKUS-6545.
This change affect only 2 modules (`nosql-db/elasticsearch` and …
> Bump Elastic to 9.1.4

- pom.xml
- properties/src/test/java/io/quarkus/ts/properties/consul/OpenShiftConsulConfigSourceIT.java
The `registry.connect.redhat.com/hashicorp/consul:1.21` is official hashicorp image in RH registry. Tested it locally and on our runner and it was able to download it.
This is recommended image for openshift platform by https://developer.hashicorp.com/consul/docs/deploy/server/k8s/platform/openshift
> Enable consul on openshift, by using official openshift hashicorp/consul image

- external-applications/src/test/java/io/quarkus/ts/external/applications/TodoDemoIT.java
Pin TodoDemoIT to specific commit for the app. Upstream TodoDemo app is currently on quarkus 3.28, which doesn't work in 3.20 branch.
> [3.20] Pin TodoDemoIT app to specific commit

- monitoring/micrometer-opentelemetry/pom.xml
- monitoring/micrometer-opentelemetry/src/main/java/io/quarkus/ts/monitoring/micrometeropentelemetry/rest/LoggingResource.java
- monitoring/micrometer-opentelemetry/src/main/resources/application.properties
- monitoring/micrometer-opentelemetry/src/test/java/io/quarkus/ts/monitoring/micrometeropentelemetry/test/DevModeOtelCapabilitiesIT.java
- pom.xml
Add classes needed to execute the test DevModeOtelCapabilitiesIT because [QUARKUS-6612](https://issues.redhat.com/browse/QUARKUS-6612)
> [3.20] Add classes needed to execute DevModeOtelCapabilitiesIT inside monitoring/micrometer-opentelemetry
