quarkus-qe/quarkus-test-suite

messaging/kafka-avro-reactive-messaging/src/test/java/io/quarkus/ts/openshift/messaging/kafka/OpenShiftAmqStreamsKafkaAvroIT.java
messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/openshift/messaging/kafka/OpenShiftAmqStreamsKafkaStreamIT.java
micrometer/prometheus-kafka/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/AmqStreamsOpenShiftAlertEventsIT.java
pom.xml

This is related to the changes in https://github.com/quarkus-qe/quarkus-openshift-test-suite/pull/279. 
The Strimzi upgrade is done as part of the Test Framework: https://github.com/quarkus-qe/quarkus-test-framework/issues/15
This PR addresses the AMQ streams upgrade only.
Fix https://github.com/quarkus-qe/quarkus-test-suite/issues/31

Upgrade AMQ Streams to 1.7.0

---

pom.xml

When using Quarkus Universe Bom, it brings a lot of dependencies. One of them is https://mvnrepository.com/artifact/org.apache.camel.quarkus/camel-quarkus-support-retrofit/1.8.1 which brings retrofit:2.5.0. 
The problem is that quarkiverse apicurio dependency needs retrofit:2.9.0 and makes the test fails on Native.
However, should we report this incompability issue? Wdyt @mjurc ?

Use retrofit:2.9.0 to overwrite version from quarkus-universe-bom

---

sql-db/multiple-pus/src/test/java/io/quarkus/ts/openshift/sqldb/multiplepus/MultiplePersistenceIT.java

When I run the test on my local environment I saw some "errors" on the log
```
Expected status code <204> but was <404>.
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:59)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callCon …
```

Fix annoying error message on MultiplePersistenceIT tearUp test

---

README.md
messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/openshift/messaging/kafka/OpenShiftOperatorAmqStreamsKafkaStreamIT.java
pom.xml

The provided AMQ Streams solution uses the official Red Hat Operator, so in order to cover it we need to install the operator within the same test namespace and use it.
In order to run this scenario, we need to use:
```
mvn clean verify -Dinclude.operator-scenarios
```
Verified in OCP 4.7

Add AMQ Streams provided by Red Hat Operator

---

.github/dependabot.yml

For Quarkus Maven Plugin, updates are managed by Quarkus Bom dependency

Dependabot: Ignore io.quarkus:quarkus-maven-plugin updates

---

.github/workflows/ci.yml
.github/workflows/daily.yaml
README.md
pom.xml
quarkus-cli/pom.xml
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCompletionIT.java
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateApplicationIT.java
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliExtensionsIT.java
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliHelpIT.java
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliSpecialCharsIT.java
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliVersionIT.java
quarkus-cli/src/test/resources/test.properties

The first set of scenarios include:
- Check Quarkus CLI version
- Create / Build applications with/out extensions. On JVM and Native
- Run applications on DEV mode
- Check completion installation
- Check Help option for some commands
- Check with special characters
- Check list of extensions when not in a current Quarkus project

Add scenarios for Quarkus CLI

---

OPENSHIFT_TS_MIGRATION_STATUS.md
lifecycle-application/pom.xml
lifecycle-application/src/main/java/io/quarkus/ts/lifecycle/ArgsResource.java
lifecycle-application/src/main/java/io/quarkus/ts/lifecycle/Main.java
lifecycle-application/src/main/resources/application.properties
lifecycle-application/src/test/java/io/quarkus/ts/lifecycle/LifecycleApplicationIT.java
lifecycle-application/src/test/java/io/quarkus/ts/lifecycle/OpenShiftLifecycleApplicationIT.java

The quarkus openshift arguments was fixed as part of https://github.com/quarkusio/quarkus/pull/17889
Fix https://github.com/quarkus-qe/quarkus-test-suite/issues/70
NOTE that I verify this module to be working locally and in OpenShift, but the test suite needs to be using the quarkus test framework 0.0.3 (it depends on https://github.com/quarkus-qe/quarkus-test-framework/pull/140).

Added lifecycle module ++ coverage of quarkus openshift arguments

---

.github/workflows/ci.yml
README.md
http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/DevModeHttpMinimumIT.java
pom.xml
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateApplicationIT.java
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliExtensionsIT.java
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliSpecialCharsIT.java
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliVersionIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/openshift/sqldb/AbstractSqlDatabaseIT.java
sql-db/sql-app/src/test/resources/h2.properties
sql-db/sql-app/src/test/resources/mariadb.properties
sql-db/sql-app/src/test/resources/mssql.properties
sql-db/sql-app/src/test/resources/mysql.properties
sql-db/sql-app/src/test/resources/postgresql.properties

- Upgrade Quarkus Test Framework to 0.0.3
- Detect modules to be executed as part of the Native CI run. Fix https://github.com/quarkus-qe/quarkus-test-suite/issues/60
- Delete mention to ephemeral namespaces. Fix https://github.com/quarkus-qe/quarkus-test-suite/issues/65
- Fix sql-app modules by not using shared properties (this change is derived by the latest version of the test framework) and using integers instead of longs.
- Update Quarkus CLI and Continuous Testing latest changes
- When creating applications using the Quarkus CLI, we can't start on DEV mode. This will be fixed when using Quarkus Test Framework 0.0.4.
- Bump versions of: quarkus-qpid-jms, formatter-maven-plugin, impsort-maven-plugin and xml-format-maven-plugin.

Fix daily run

---

.github/workflows/ci.yml
pom.xml

This was done in OpenShift Test Suite as part of https://github.com/quarkus-qe/quarkus-openshift-test-suite/commit/5d9eadd0dbf72b5cbf531bb08f26d6bbbb7c9c74.
For Strimzi in local, we're already using the version 2.7, but an old version, I will update it in the test framework as a low priority task.
Fix https://github.com/quarkus-qe/quarkus-test-suite/issues/67

Upgrade Kafka to use 2.7

---

OPENSHIFT_TS_MIGRATION_STATUS.md
README.md
external-applications/pom.xml
external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftQuickstartUsingS2iIT.java
external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftTodoDemoIT.java
external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftWorkshopHeroesIT.java
external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftWorkshopVillainsIT.java
external-applications/src/test/resources/test.properties
pom.xml

It contains three applications:
This test produces an S2I source deployment config for OpenShift with [todo-demo-app](https://github.com/quarkusio/todo-demo-app) 
serving a simple todo checklist. The code for this application lives outside of the test suite's codebase.
The test verifies that the application with a sample of libraries is buildable and deployable via supported means.
This test produces an S2I source deployment config for OpenShift with 
[Quarkus Super heroes workshop](https://github.com/quarkusio/quarkus-workshops) application.
The code for this application lives outside of the test suite's codebase.
The test verifies that the application is buildable and deployable. It also verifies that the REST and MicroProfile APIs
function properly on OpenShift, as well as the database …

Migrate external applications modules from Quarkus OpenShift TS

---

README.md
micrometer/prometheus-kafka/src/test/resources/service-monitor.yaml
micrometer/prometheus/pom.xml
micrometer/prometheus/src/main/java/io/quarkus/ts/micrometer/prometheus/UsingMicroProfilePingPongResource.java
micrometer/prometheus/src/main/java/io/quarkus/ts/micrometer/prometheus/UsingRegistryPingPongResource.java
micrometer/prometheus/src/main/java/io/quarkus/ts/micrometer/prometheus/WithoutCustomMetricsPingPongResource.java
micrometer/prometheus/src/main/resources/application.properties
micrometer/prometheus/src/test/java/io/quarkus/ts/micrometer/prometheus/HttpServerMetricsIT.java
micrometer/prometheus/src/test/java/io/quarkus/ts/micrometer/prometheus/UsingMicroProfilePingPongResourceIT.java
micrometer/prometheus/src/test/java/io/quarkus/ts/micrometer/prometheus/UsingRegistryPingPongResourceIT.java
micrometer/prometheus/src/test/resources/service-monitor.yaml

We have copied the coverage from 015 into the existing micrometer/prometheus module.
Note that I don't think this coverage is relevant to be run on OpenShift.
Fix https://github.com/quarkus-qe/quarkus-test-suite/issues/85

Migrate 015-quarkus-micrometer into micrometer/prometheus from Beefy

---

README.md
pom.xml
sql-db/panache-flyway/pom.xml
sql-db/panache-flyway/src/main/java/io/quarkus/qe/sqldb/panacheflyway/ApplicationEntity.java
sql-db/panache-flyway/src/main/java/io/quarkus/qe/sqldb/panacheflyway/ApplicationQueryResource.java
sql-db/panache-flyway/src/main/java/io/quarkus/qe/sqldb/panacheflyway/ApplicationResource.java
sql-db/panache-flyway/src/main/java/io/quarkus/qe/sqldb/panacheflyway/DataSourceResource.java
sql-db/panache-flyway/src/main/java/io/quarkus/qe/sqldb/panacheflyway/ServiceEntity.java
sql-db/panache-flyway/src/main/java/io/quarkus/qe/sqldb/panacheflyway/UserEntity.java
sql-db/panache-flyway/src/main/java/io/quarkus/qe/sqldb/panacheflyway/UserRepository.java
sql-db/panache-flyway/src/main/java/io/quarkus/qe/sqldb/panacheflyway/UserResource.java
sql-db/panache-flyway/src/main/java/io/quarkus/qe/sqldb/panacheflyway/VersionEntity.java
sql-db/panache-flyway/src/main/resources/application.properties
sql-db/panache-flyway/src/main/resources/db/migration/V1.0.0__init.sql
sql-db/panache-flyway/src/main/resources/db/migration/V1.0.1__entity_with_id_varchar.sql
sql-db/panache-flyway/src/main/resources/db/migration/V1.0.2__add_service.sql
sql-db/panache-flyway/src/main/resources/db/migration/V1.0.3__add_user.sql
sql-db/panache-flyway/src/test/java/io/quarkus/qe/sqldb/panacheflyway/ApplicationResourceIT.java
sql-db/panache-flyway/src/test/java/io/quarkus/qe/sqldb/panacheflyway/BaseIT.java
sql-db/panache-flyway/src/test/java/io/quarkus/qe/sqldb/panacheflyway/DataSourceIT.java
sql-db/panache-flyway/src/test/java/io/quarkus/qe/sqldb/panacheflyway/UserResourceIT.java
sql-db/panache-flyway/src/test/java/io/quarkus/qe/sqldb/panacheflyway/dbpool/AgroalPoolTest.java
sql-db/panache-flyway/src/test/java/io/quarkus/qe/sqldb/panacheflyway/dbpool/AgroalTestProfile.java
sql-db/panache-flyway/src/test/java/io/quarkus/qe/sqldb/panacheflyway/dbpool/MySqlDatabaseTestResource.java

Migrate 011-quarkus-panache-rest-flyway and 014-quarkus-panache-with-transactions-xa into sql-db/panache-flyway.
Module that test whether we can setup a REST API using ORM Panache with Flyway and a MySQL database. Moreover, it covers XA transactions.
Topics covered here:
- https://quarkus.io/guides/hibernate-orm-panache
- https://quarkus.io/guides/rest-data-panache
- https://quarkus.io/guides/flyway
Base application:
- Define multiple datasources (https://quarkus.io/guides/datasource#multiple-datasources): default (transactions enabled), `with-xa` (transactions xa).
- Define Panache entity `ApplicationEntity` and its respective REST resource `ApplicationResource` (https://quarkus.io/guides/rest-data-panache).
- Define a REST resource `DataSourceResource` that provides info about the …

Migrate 011 and 014 into sql-db

---

README.md
http/servlet-undertow/pom.xml
http/servlet-undertow/src/main/java/io/quarkus/ts/filters/CustomRequestFilter.java
http/servlet-undertow/src/main/java/io/quarkus/ts/listener/SessionListener.java
http/servlet-undertow/src/main/java/io/quarkus/ts/servlets/HelloWorld.java
http/servlet-undertow/src/main/resources/META-INF/web.xml
http/servlet-undertow/src/main/resources/application.properties
http/servlet-undertow/src/test/java/io/quarkus/ts/servlets/HttpServletWithSessionListenerIT.java
http/servlet-undertow/src/test/resources/test.properties
pom.xml

Servlet’s are supported using a modified version of Undertow that runs on top of Vert.x, and RESTEasy is used to provide JAX-RS support. This PR cover basic use cases of undertow  HTTP server
This PR covers basic scenarios about HTTP servlets under `quarkus-undertow` server more in details:
- Http session eviction
- Undertow web.xml configuration
Fix #132

Add undertow http server scenarios

---

BEEFY_TS_MIGRATION_STATUS.md
README.md
pom.xml
spring/spring-data-rest/README.md
spring/spring-data-rest/pom.xml
spring/spring-data-rest/src/main/java/io/quarkus/ts/spring/data/rest/Book.java
spring/spring-data-rest/src/main/java/io/quarkus/ts/spring/data/rest/BookRepository.java
spring/spring-data-rest/src/main/java/io/quarkus/ts/spring/data/rest/Library.java
spring/spring-data-rest/src/main/java/io/quarkus/ts/spring/data/rest/LibraryRepository.java
spring/spring-data-rest/src/main/resources/application.properties
spring/spring-data-rest/src/main/resources/import.sql
spring/spring-data-rest/src/test/java/io/quarkus/ts/spring/data/rest/AbstractDbIT.java
spring/spring-data-rest/src/test/java/io/quarkus/ts/spring/data/rest/BookRepositoryIT.java
spring/spring-data-rest/src/test/java/io/quarkus/ts/spring/data/rest/LibraryRepositoryIT.java
spring/spring-data-rest/src/test/java/io/quarkus/ts/spring/data/rest/OpenShiftBookRepositoryIT.java
spring/spring-data-rest/src/test/java/io/quarkus/ts/spring/data/rest/OpenShiftLibraryRepositoryIT.java
spring/spring-data-rest/src/test/resources/test.properties

Migration of the module `602-spring-data-rest` from BeefyTS into `spring/spring-data-rest`.
Other modules expected in the `spring` group (see https://github.com/quarkus-qe/quarkus-test-suite/issues/98).
This module is a candidate for a merger with `spring/spring-data-primitivetypes` (see https://github.com/quarkus-qe/quarkus-test-suite/pull/134 and related issue).

Migrate 602-spring-data-rest from BeefyTS

---

BEEFY_TS_MIGRATION_STATUS.md
README.md
lifecycle-application/pom.xml

Quarkus and Maven profiles coverage
Enhancing `lifecycle-application` module to save execution time.
Fixes https://github.com/quarkus-qe/quarkus-test-suite/issues/78 / migrates https://github.com/quarkus-qe/beefy-scenarios/tree/main/005-quarkus-and-maven-profiles

Quarkus and Maven profiles coverage

---

.github/dependabot.yml

The dependency io.quarkus:quarkus-spring-di is using a concrete version in the module `lifecycle-application` to verify some Maven configuration error. Therefore, we need Dependabot to ignore version bumps for this dependency.

Dependabot to ignore io.quarkus:quarkus-spring-di

---

.github/workflows/daily.yaml
quarkus-cli/pom.xml
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCompletionIT.java
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateNativeApplicationIT.java
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliExtensionsIT.java
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliHelpIT.java
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliSpecialCharsIT.java
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliVersionIT.java
scheduling/quartz/src/test/java/io/quarkus/qe/scheduling/quartz/AnnotationScheduledJobsMySqlQuartzIT.java

++ Run only http/http-minimum in Windows native only
++ Disable AnnotationScheduledJobsMySqlQuartzIT on Native as it takes around 30 min to finish
++ There were some duplicated test cases in QuarkusCliVersionIT and QuarkusCliCreateJvmApplicationIT

Improve Native time on Daily action

---

properties/src/main/java/io/quarkus/qe/properties/configmapping/ConfigMappingResource.java
properties/src/main/java/io/quarkus/qe/properties/configmapping/Person.java
properties/src/test/java/io/quarkus/qe/properties/configmapping/ConfigMappingResourceIT.java

Quarkus upstream upgraded SmallRye Config to 2.4.3 and it seems that there is no longer possible to use the annotation @ConfigMapping on classes, only in interfaces.
As we're already covering the interface mapping, I removed the field coverage.
Related issue: https://github.com/quarkusio/quarkus/issues/19298

Fix properties module by removing the Person field

---

http/http-advanced/pom.xml

Drop quarkus-maven-plugin definition from http-advanced module
quarkus-maven-plugin is defined in root pom

Drop quarkus-maven-plugin definition from http-advanced module

---

README.md
logging/jboss/pom.xml
logging/jboss/src/main/java/io/quarkus/ts/logging/jboss/LogResource.java
logging/jboss/src/test/java/io/quarkus/ts/logging/jboss/LogResourceIT.java
pom.xml

Module that covers the logging functionality using JBoss Logging Manager. The following scenarios are covered:
- Usage of `quarkus-logging-json` extension
- Inject the `Logger` instance in beans
- Inject a `Logger` instance using a custom category
- Setting up the log level property for logger instances
Fix https://github.com/quarkus-qe/quarkus-test-suite/issues/168

Add module to covers `quarkus-logging-json` dependency

---

README.md
cache/caffeine/pom.xml
cache/caffeine/src/main/java/io/quarkus/ts/cache/caffeine/ApplicationScopeService.java
cache/caffeine/src/main/java/io/quarkus/ts/cache/caffeine/BaseServiceWithCache.java
cache/caffeine/src/main/java/io/quarkus/ts/cache/caffeine/BlockingWithCacheResource.java
cache/caffeine/src/main/java/io/quarkus/ts/cache/caffeine/ReactiveWithCacheResource.java
cache/caffeine/src/main/java/io/quarkus/ts/cache/caffeine/RequestScopeService.java
cache/caffeine/src/main/java/io/quarkus/ts/cache/caffeine/ServiceWithCacheResource.java
cache/caffeine/src/test/java/io/quarkus/ts/cache/caffeine/cache/caffeine/OpenShiftServiceWithCacheResourceIT.java
cache/caffeine/src/test/java/io/quarkus/ts/cache/caffeine/cache/caffeine/ServiceWithCacheResourceIT.java
pom.xml

Verifies the `quarkus-cache` extension using the `@CacheResult`, `@CacheInvalidate` and `@CacheKey` annotations.
It covers different usages: 
1. from an application scoped service
2. from a request scoped service
3. from a blocking endpoint
4. from a reactive endpoint
Fix https://github.com/quarkus-qe/quarkus-test-suite/issues/165

Add coverage of `quarkus-cache`

---

README.md
http/rest-client/pom.xml
http/rest-client/src/main/java/io/quarkus/ts/http/restclient/ClientBookResource.java
http/rest-client/src/main/java/io/quarkus/ts/http/restclient/RestInterface.java
http/rest-client/src/main/java/io/quarkus/ts/http/restclient/xml/Book.java
http/rest-client/src/main/java/io/quarkus/ts/http/restclient/xml/BookAsJsonResource.java
http/rest-client/src/main/java/io/quarkus/ts/http/restclient/xml/BookAsXmlResource.java
http/rest-client/src/main/resources/application.properties
http/rest-client/src/test/java/io/quarkus/ts/http/restclient/ClientBookResourceIT.java
pom.xml

Verifies Rest Client configuration using `quarkus-rest-client-jaxb` (XML support) and `quarkus-rest-client-jsonb` (JSON support).
This module will setup a very minimal configuration (only `quarkus-resteasy`) and have four endpoints:
- Two endpoints to get a book in JSON and XML formats.
- Two endpoints to get the value of the previous endpoints using the rest client interface.
Fix https://github.com/quarkus-qe/quarkus-test-suite/issues/170

Add coverage for `rest-client-jaxb` and `rest-client-jsonb`

---

README.md
cache/spring/pom.xml
cache/spring/src/main/java/io/quarkus/ts/cache/spring/ApplicationScopeService.java
cache/spring/src/main/java/io/quarkus/ts/cache/spring/BaseServiceWithCache.java
cache/spring/src/main/java/io/quarkus/ts/cache/spring/RequestScopeService.java
cache/spring/src/main/java/io/quarkus/ts/cache/spring/RestControllerWithCacheResource.java
cache/spring/src/main/java/io/quarkus/ts/cache/spring/ServiceWithCacheResource.java
cache/spring/src/test/java/io/quarkus/ts/cache/spring/OpenShiftServiceWithCacheResourceIT.java
cache/spring/src/test/java/io/quarkus/ts/cache/spring/ServiceWithCacheResourceIT.java
pom.xml

Verifies the `quarkus-spring-cache` extension using `@Cacheable`, `@CacheEvict` and `@CachePut`.
It covers different usages: 
1. from an application scoped service
2. from a request scoped service
3. from a REST controller endpoint (using `@RestController)
More information about this extension in https://quarkus.io/guides/spring-cache.
Fix https://github.com/quarkus-qe/quarkus-test-suite/issues/179

Add module `cache/spring` to cover the `quarkus-spring-cache` extension

---

README.md
pom.xml
spring/spring-properties/pom.xml
spring/spring-properties/src/main/java/io/quarkus/ts/spring/properties/CollectionsController.java
spring/spring-properties/src/main/java/io/quarkus/ts/spring/properties/GreetingController.java
spring/spring-properties/src/main/java/io/quarkus/ts/spring/properties/GreetingProperties.java
spring/spring-properties/src/main/java/io/quarkus/ts/spring/properties/ListWiringProperties.java
spring/spring-properties/src/main/java/io/quarkus/ts/spring/properties/MapWiringProperties.java
spring/spring-properties/src/main/java/io/quarkus/ts/spring/properties/ValueController.java
spring/spring-properties/src/main/resources/application.properties
spring/spring-properties/src/test/java/io/quarkus/ts/spring/properties/SpringPropertiesIT.java

Exploratory testing for the `quarkus-spring-boot-properties` Quarkus extension. The application consists of a REST endpoint
with some different approaches to inject properties.
Current limitations:
- Relaxing name convention is not supported and it won't be supported: https://github.com/quarkusio/quarkus/issues/12483
- The annotation `@ConstructorBinding` is not supported yet: https://github.com/quarkusio/quarkus/issues/19364
Fix https://github.com/quarkus-qe/quarkus-test-suite/issues/172

Add coverage for the `quarkus-spring-boot-properties` Quarkus extension

---

.github/quarkus-ecosystem-test
.github/workflows/ci.yml
.github/workflows/daily.yaml
.github/workflows/quarkus-snapshot.yaml
.github/workflows/quarkus-test-framework-snapshot.yaml
README.md
external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftQuickstartUsingS2iIT.java
external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftTodoDemoIT.java
external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftWorkshopHeroesIT.java
external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftWorkshopVillainsIT.java
http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/DevModeGrpcIntegrationIT.java
http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/DevModeHttpMinimumIT.java
messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/DevModeKafkaStreamIT.java
micrometer/prometheus/src/main/java/io/quarkus/ts/micrometer/prometheus/PrimeNumberResource.java
pom.xml
properties/src/test/java/io/quarkus/qe/properties/toggle/ToggleablePropertiesOnDevModeIT.java
scheduling/quartz/src/main/java/io/quarkus/qe/scheduling/quartz/basic/ManuallyScheduledCounter.java
scheduling/quartz/src/test/java/io/quarkus/qe/scheduling/quartz/AnnotationScheduledJobsMySqlQuartzIT.java
security/keycloak/src/test/java/io/quarkus/ts/security/DevModeOidcSecurityIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModePostgresqlIT.java
super-size/many-extensions/src/test/java/io/quarkus/ts/many/extensions/DevModeManyExtensionsIT.java

The idea would be to run the modules that take the most of the time in individual jobs, so the jobs do not exceed the timeout.
++ Update Mandrel image to use 21.2
++ Update reason of @DisabledOnNative for S2i deployments. Caused by: https://github.com/quarkus-qe/quarkus-test-framework/issues/206
++ Exclude DevMode tests on Native by Maven configuration
++ Refactor scheduling/quartz module to run tests on Native without build
++ Avoid to use RandomStringUtils in micrometer/prometheus, fails on Native
Fix https://github.com/quarkus-qe/quarkus-test-suite/issues/154

Split Native job to run selected modules

---

README.md
pom.xml
spring/spring-cloud-config/README.md
spring/spring-cloud-config/pom.xml
spring/spring-cloud-config/src/main/java/io/quarkus/ts/spring/cloud/config/ConfigMappingGreetingResource.java
spring/spring-cloud-config/src/main/java/io/quarkus/ts/spring/cloud/config/CustomMessageConfig.java
spring/spring-cloud-config/src/main/java/io/quarkus/ts/spring/cloud/config/JaxRsGreetingResource.java
spring/spring-cloud-config/src/main/java/io/quarkus/ts/spring/cloud/config/SpringWebGreetingResource.java
spring/spring-cloud-config/src/main/resources/application.properties
spring/spring-cloud-config/src/test/java/io/quarkus/ts/spring/cloud/config/SpringCloudConfigIT.java
spring/spring-cloud-config/src/test/resources/config/application-SpringCloudConfigIT.properties

Verifies that we can use an external Spring Cloud Server to inject configuration in our Quarkus applications.
Fix https://github.com/quarkus-qe/quarkus-test-suite/issues/184

Add module for `spring/spring-cloud-config`

---

README.md
pom.xml
scheduling/spring/pom.xml
scheduling/spring/src/main/java/io/quarkus/qe/scheduling/spring/AnnotationScheduledCounter.java
scheduling/spring/src/main/java/io/quarkus/qe/scheduling/spring/CountResource.java
scheduling/spring/src/main/java/io/quarkus/qe/scheduling/spring/services/CounterService.java
scheduling/spring/src/test/java/io/quarkus/qe/scheduling/spring/OpenShiftSpringScheduledIT.java
scheduling/spring/src/test/java/io/quarkus/qe/scheduling/spring/SpringScheduledIT.java

We cover the following scenario from guide: https://quarkus.io/guides/spring-scheduled with some adjustments to use only Spring API.
Fix https://github.com/quarkus-qe/quarkus-test-suite/issues/186

Add module `scheduling/spring` to cover `quarkus-spring-scheduled` ext

---

.github/workflows/daily.yaml
.github/workflows/quarkus-test-framework-snapshot.yaml

Due to this change: https://github.com/quarkusio/quarkus/pull/19534, when using the 20.0 GraalVM version, it was failing with:
```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM Version 21.0.0 (Java Version 11.0.10+8-jvmci-21.0-b06)
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] C:\hostedtoolcache\windows\GraalVM\21.0.0-java11-amd64\x64\bin\native-image.cmd -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Duser.language=en -J-Duser.country=US …
```

Update GraalVM version to 21.2 for Windows Native

---

http/jaxrs-reactive/src/test/java/io/quarkus/ts/jaxrs/reactive/HttpCachingResourceIT.java

Related issue has been resolved in Quarkus upstream:
https://github.com/quarkusio/quarkus/issues/19822

[2.2] Enable disabled HTTP Caching test in jaxrs-reactive

---

quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliExtensionsIT.java

The stream ID 2.0 is gone from the platform site and this might eventually happen in the future for other versions.
So, in order to fix this test and prevent future failures, we need to infer the stream ID from the current Quarkus version.

CLI: Fix using stream test by getting stream ID from version

---

.github/workflows/ci.yml
http/jaxrs-reactive/src/test/java/io/quarkus/ts/jaxrs/reactive/HttpCachingResourceIT.java
lifecycle-application/pom.xml
pom.xml
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliExtensionsIT.java

RHBQ will be based on 2.2.1.Final.
Daily action for branches are not being triggered, so we don't need to update it.
++ Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/207

[2.2] Use Quarkus version 2.2.1.Final

---

.github/quarkus-ecosystem-test
.github/workflows/ci.yml
.github/workflows/daily.yaml
http/jaxrs-reactive/src/test/java/io/quarkus/ts/jaxrs/reactive/HttpCachingResourceIT.java
lifecycle-application/pom.xml
pom.xml

Due to this issue: https://github.com/quarkusio/quarkus/issues/19875, we can't use 999-SNAPSHOT until is fixed, therefore Main will be based on 2.2.1.Final.
++ Daily actions and Quarkus Ecosystem will still use 999-SNAPSHOT to check out the status with 999-SNAPSHOT
++ Disable HttpCachingResourceIT.shouldGetNoCacheUnqualified due to https://github.com/quarkusio/quarkus/issues/19822

Use Quarkus version 2.2.1.Final

---

pom.xml

As this dependency is not part of RHBQ, we need to use the upstream version always.
Dependabot will maintain it.

Maintain Quarkus Ide Config independently

---

.github/workflows/ci.yml
lifecycle-application/pom.xml
pom.xml
spring/spring-cloud-config/src/main/java/io/quarkus/ts/spring/cloud/config/ConfigMappingGreetingResource.java
spring/spring-cloud-config/src/main/java/io/quarkus/ts/spring/cloud/config/CustomMessageConfig.java
spring/spring-cloud-config/src/test/java/io/quarkus/ts/spring/cloud/config/SpringCloudConfigIT.java

++ Using 2.2.2.Final is mandatory to build the branch 2.2 in Quarkus upstream (needed to use Quarkus CLI)
++ Enable tests for QUARKUS-1218: Regression issue for @ConfigMapping
The issue https://github.com/quarkusio/quarkus/issues/19448 was fixed by https://github.com/quarkusio/quarkus/pull/19937

Upgrade Quarkus to 2.2.2.Final

---

pom.xml

As this dependency is not part of RHBQ, we need to use the upstream version always.
Dependabot will maintain it.
Back port of https://github.com/quarkus-qe/quarkus-test-suite/pull/232

[2.2] Maintain Quarkus Ide Config independently

---

README.md
pom.xml
test-tooling/pact/pom.xml
test-tooling/pact/src/test/java/io/quarkus/ts/http/pact/ConsumerPactTest.java
test-tooling/pact/src/test/java/io/quarkus/ts/http/pact/ProviderPactTest.java
test-tooling/pact/src/test/resources/pacts/TheConsumer-TheProvider.json

Coverage for Pact-JVM, in context of this issue: https://github.com/quarkusio/quarkus/issues/9677
Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/212

[2.2] Feature/pact coverage

---

quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java

Test for JaCoCo extension, Using CLI to generate the project and to invoke the build.
Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/242 into 2.2 branch

[2.2] Test for JaCoCo extension

---

README.md
messaging/kafka-producer/pom.xml
messaging/kafka-producer/src/main/java/io/quarkus/ts/messaging/kafka/Application.java
messaging/kafka-producer/src/main/java/io/quarkus/ts/messaging/kafka/FailureHandler.java
messaging/kafka-producer/src/main/java/io/quarkus/ts/messaging/kafka/KafkaBlockingProducer.java
messaging/kafka-producer/src/main/resources/application.properties
messaging/kafka-producer/src/test/java/io/quarkus/ts/messaging/kafka/BlockingProducerIT.java
messaging/kafka-producer/src/test/java/io/quarkus/ts/messaging/kafka/CustomStrimziKafkaContainer.java
messaging/kafka-producer/src/test/resources/test.properties
pom.xml

When a topic doesn't exist then Kafka producer blocks 60sec (default time). 
This scenario verified that the main thread is not blocked and also that the total amount of time needed to complete a request doesn't exceed `ProducerConfig.MAX_BLOCK_MS_CONFIG`.

Add blocking Kafka producer scenario

---

http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/RemoteDevModeHttpAdvancedIT.java

This PR is to verify https://issues.redhat.com/browse/QUARKUS-834
Back port of https://github.com/quarkus-qe/quarkus-test-suite/pull/244

[2.2] RemoteDev scenario to check DEV ui is not found

---

quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliHelpIT.java

The help message changed in Upstream from "List, add, and remove extensions of an existing project." to "Configure extensions of an existing project."

Update Extensions Help command in Quarkus CLI

---

messaging/kafka-avro-reactive-messaging/pom.xml
messaging/kafka-avro-reactive-messaging/src/main/resources/application.properties
messaging/kafka-avro-reactive-messaging/src/main/resources/docker-compose-strimzi.yaml
messaging/kafka-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/OpenShiftAmqStreamsKafkaAvroIT.java
messaging/kafka-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/StrimziKafkaAvroIT.java
messaging/kafka-avro-reactive-messaging/src/test/resources/strimzi-application.properties
pom.xml

depends on: https://github.com/quarkus-qe/quarkus-test-framework/pull/230
New Quarkus Apicurio registry library was released in order to produce/consumer Kafka AVRO messages. 
If you are using Kafka Strimzi the only dependency that is required are:
`io.quarkus:quarkus-avro` // Quarkus extension for generating Java code from Avro schemas
`io.quarkus:quarkus-apicurio-registry-avro`// in order to integrate Apirurio AVRO registry into Quarkus app
Doc Ref: https://quarkus.io/guides/kafka-schema-registry-avro

Move on to new Quarkus apicurio registry library

---

sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/OpenShiftMssqlDatabaseIT.java
sql-db/vertx-sql/pom.xml
sql-db/vertx-sql/src/main/java/io/quarkus/qe/vertx/sql/Application.java
sql-db/vertx-sql/src/main/java/io/quarkus/qe/vertx/sql/domain/Airline.java
sql-db/vertx-sql/src/main/java/io/quarkus/qe/vertx/sql/domain/Airport.java
sql-db/vertx-sql/src/main/java/io/quarkus/qe/vertx/sql/domain/Flight.java
sql-db/vertx-sql/src/main/java/io/quarkus/qe/vertx/sql/domain/PricingRules.java
sql-db/vertx-sql/src/main/java/io/quarkus/qe/vertx/sql/handlers/FailureHandler.java
sql-db/vertx-sql/src/main/java/io/quarkus/qe/vertx/sql/services/DbPoolService.java
sql-db/vertx-sql/src/main/resources/application.properties
sql-db/vertx-sql/src/main/resources/db/migration/mssql/V1.0.0__init.sql
sql-db/vertx-sql/src/test/java/io/quarkus/qe/vertx/sql/handlers/Db2HandlerIT.java
sql-db/vertx-sql/src/test/java/io/quarkus/qe/vertx/sql/handlers/MSsqlHandlerIT.java
sql-db/vertx-sql/src/test/java/io/quarkus/qe/vertx/sql/handlers/MysqlHandlerIT.java
sql-db/vertx-sql/src/test/java/io/quarkus/qe/vertx/sql/handlers/PostgresqlHandlerIT.java

[2.2] Reactive MS SQL client support

---

security/keycloak-jwt/src/test/java/io/quarkus/ts/security/keycloak/jwt/BaseOidcJwtSecurityIT.java
security/keycloak-multitenant/src/test/java/io/quarkus/ts/security/keycloak/multitenant/BaseMultiTenantSecurityIT.java
security/keycloak-webapp/src/test/java/io/quarkus/ts/security/keycloak/webapp/BaseWebappSecurityIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/MssqlDatabaseIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/OpenShiftMssqlDatabaseIT.java

The problem is that in RH SSO 7.3 is expected `Log in to test-realm` and in RH SSO 7.4 is `Sign in to test-realm`.
I fixed it by using a regular expression.
Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/260

[2.2] Fix OpenShift Keycloak + Sql Server scenarios

---

.github/workflows/ci.yml
super-size/many-extensions/src/main/resources/application.properties

The OpenShift deployment needs the healthcheck to be UP, but it was:
```
{"status":"DOWN","checks":[{"name":"Database connections health check","status":"UP"},{"name":"Artemis JMS health check","status":"DOWN"}]}
```
I think the purpose of this module is to cover as many extensions as possible, so I decided to exclude all the checks via property.
++ Building the Quarkus Test Suite parent separately:
This is a consequence that we're building only the changed modules in the PR workflow.
Also, the test framework does not deal well when the parent is not in the parent folder of the current module.

Many Extensions: Disable health extension

---

http/http-advanced/pom.xml
http/reactive-routes/pom.xml
http/vertx-web-client/pom.xml
messaging/kafka-producer/pom.xml
security/vertx-jwt/pom.xml
sql-db/vertx-sql/pom.xml

Related to these PRs in upstream:
https://github.com/quarkusio/quarkus/pull/19933
https://github.com/quarkusio/quarkus/pull/20058
- Rename quarkus-vertx-web to quarkus-reactive-routes extensions
- merge the quarkus-vertx and quarkus-vertx-core extentions

Replace quarkus-vertx dependencies

---

.github/workflows/ci.yml
super-size/many-extensions/src/main/resources/application.properties

The OpenShift deployment needs the healthcheck to be UP, but it was:
```
{"status":"DOWN","checks":[{"name":"Database connections health check","status":"UP"},{"name":"Artemis JMS health check","status":"DOWN"}]}
```
I think the purpose of this module is to cover as many extensions as possible, so I decided to exclude all the checks via property.
++ Building the Quarkus Test Suite parent separately:
This is a consequence that we're building only the changed modules in the PR workflow.
Also, the test framework does not deal well when the parent is not in the parent folder of the current module.
Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/270

[2.2] Many Extensions: Disable health extension

---

README.md
logging/jboss/src/main/java/io/quarkus/ts/logging/jboss/LogResource.java
logging/jboss/src/main/resources/application.properties
logging/jboss/src/test/java/io/quarkus/ts/logging/jboss/LogResourceIT.java

This PR covers the default behavior of  `quarkus.log.min-level` over JBoss Logger. 
related issue: 
https://github.com/quarkusio/quarkus/issues/20066
https://github.com/quarkusio/quarkus/pull/13376

Cover quarkus.log.min-level scenario

---

pom.xml

Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/282

[2.2] Upgrade Quarkus Test Framework to 0.0.11

---

monitoring/micrometer-prometheus-kafka/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/BaseOpenShiftAlertEventsIT.java
monitoring/micrometer-prometheus/src/test/java/io/quarkus/ts/micrometer/prometheus/OpenShiftPrimeNumberResourceIT.java

Issue on fabric8 side, related to https://github.com/quarkus-qe/quarkus-test-framework/issues/270 and reported in https://github.com/fabric8io/kubernetes-client/issues/3473
Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/284

[2.2] Workaround to fix OpenShiftClient.execOnPod issue

---

pom.xml

Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/289

[2.2] Run only OpenShift tests when using the OpenShift Maven profile

---

.github/workflows/ci.yml
.github/workflows/daily.yaml

Adopt OpenJDK got moved to Eclipse Temurin and won't be updated anymore
More details: https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/

Adopt OpenJDK got moved to Eclipse Temurin

---

sql-db/vertx-sql/src/main/resources/application.properties
sql-db/vertx-sql/src/test/java/io/quarkus/qe/vertx/sql/handlers/Db2HandlerIT.java
sql-db/vertx-sql/src/test/java/io/quarkus/qe/vertx/sql/handlers/MysqlHandlerIT.java
sql-db/vertx-sql/src/test/java/io/quarkus/qe/vertx/sql/handlers/PostgresqlHandlerIT.java

Reported in https://github.com/IBM/Db2/issues/43
Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/290

[2.2] Tag DB2 Handler IT as incompatible with FIPS

---

.github/workflows/daily.yaml

Add JDK 17 to GitHub CI
- Quarkus Upstream is still using JDK 11 
- JVM test (Linuz/Win) runs over JDK17
- Native runs over JDK 11

Support JDK 17

---

README.md
messaging/kafka-avro-reactive-messaging/src/main/java/io/quarkus/ts/messaging/kafka/KStockPriceProducer.java
messaging/kafka-avro-reactive-messaging/src/main/java/io/quarkus/ts/messaging/kafka/StockPriceDto.java
messaging/kafka-avro-reactive-messaging/src/main/java/io/quarkus/ts/messaging/kafka/StockPriceEndpoint.java
messaging/kafka-avro-reactive-messaging/src/main/resources/application.properties
messaging/kafka-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/BaseKafkaAvroGroupIdIT.java
messaging/kafka-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/ConfluentKafkaAvroGroupIdIT.java
messaging/kafka-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/StrimziKafkaAvroGroupIdIT.java
messaging/kafka-avro-reactive-messaging/src/test/resources/confluent-application.properties
messaging/kafka-avro-reactive-messaging/src/test/resources/strimzi-application.properties

Doc: https://quarkus.io/guides/kafka#using-unique-consumer-groups
We have added a scenario Strimzi/confluent in order to check that an auto-generated Kafka groupId is created when an application starts.

Add auto generated group ID scenario

---

README.md
messaging/kafka-streams-reactive-messaging/src/main/resources/application.properties
messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/KafkaGratefulShutdownIT.java

Auto-detect serializers and deserializers for the Reactive Messaging Kafka Connector scenario.
- tested over KStreams with String serializer + Strimzi/apicurio
Related issues: quarkus-qe/quarkus-test-framework#278

Auto-detect serializers and deserializers 

---

messaging/kafka-producer/src/main/resources/application.properties
messaging/kafka-producer/src/test/java/io/quarkus/ts/messaging/kafka/BlockingProducerIT.java

- Increase Network test delay threshold from 80 ms to 300 ms
- Kafka `max.block.ms` from 100 ms to 1 sec (this param will not make the test more resilient) but make more sense for this scenario. So, Kafka producer will be waiting for a response up to 1 sec, and then return an error (because the topic doesn't exist). The test will success if this response time takes less than 300 ms.

Improve Kafka-producer resilience

---

external-applications/src/test/java/io/quarkus/ts/external/applications/QuickstartIT.java

Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/319

[2.2] Disable QuickstartIT on Windows due to long file paths

---

pom.xml
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/OpenShiftMariaDB102DatabaseIT.java
websockets/quarkus-websockets/src/main/java/io/quarkus/ts/Chat.java
websockets/websockets-client/src/main/java/io/quarkus/ts/Chat.java

- Use Log.error instead of System.out in Websockets modules
- Fix scheduling/quartz due to regression in #296
Regression entered in https://github.com/quarkus-qe/quarkus-test-suite/pull/296.
Where mariadb.102 and mysql 80 images were wrongly marked as redhat registry private which they are open.

Fix scheduling/quartz ++ Use Log.error instead of System.out in Websockets modules

---

infinispan-client/src/test/java/io/quarkus/ts/infinispan/client/BaseOpenShiftInfinispanIT.java
infinispan-client/src/test/java/io/quarkus/ts/infinispan/client/OperatorOpenShiftInfinispanCountersIT.java
infinispan-client/src/test/java/io/quarkus/ts/infinispan/client/OperatorOpenShiftInfinispanObjectsIT.java

++ To move all the common functionality into a base class.
Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/332

[2.2] Refactor Infinispan to delete cluster when startup failures

---

http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/DevModeGrpcIntegrationIT.java
http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/utils/GrpcWebSocketListener.java
monitoring/micrometer-prometheus-kafka/pom.xml
monitoring/micrometer-prometheus-oidc/pom.xml
monitoring/micrometer-prometheus/pom.xml
monitoring/microprofile-opentracing/pom.xml
monitoring/opentelemetry/pom.xml
monitoring/opentelemetry/src/test/java/io/quarkus/ts/opentelemetry/OpentelemetryIT.java
monitoring/opentracing-reactive-grpc/pom.xml

- Fix OpentelemetryIT as is now checking if nested properties do exist
This change is only affecting 999-SNAPSHOT (due to some enhancements in arc)
- Change DevModeGrpcIntegration route to io.quarkus.quarkus-grpc/grpc-test
The `/q/dev/grpc-test` route has been changed by https://github.com/quarkusio/quarkus/pull/20465. It's now `/q/dev/io.quarkus.quarkus-grpc/grpc-test` ++ Moved GrpcWebSocketListener as it's a test source.
- Fix monitoring modules with correct artifact and description

Fix DevModeGrpcIntegration and OpentelemetryIT tests

---

quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliHelpIT.java

The HELP command for extensions has changed with the following sentence: "List platforms and extensions."

Update help command for quarkus CLI extension command

---

cache/spring/pom.xml
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
scheduling/spring/pom.xml
spring/spring-cloud-config/pom.xml
spring/spring-properties/pom.xml
spring/spring-web/pom.xml

RESTEasy Classic dependencies were added to all modules using
`quarkus-spring-web`, as RESTEasy Classic and `quarkus-spring-web`
were decoupled.
quarkusio/quarkus#21089.

Add RESTEasy Classic dependencies in spring-web modules

---

sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeOracleDevServiceUserExperienceIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeOracleIT.java

Dev Services support for the Oracle DB has been implemented
in Quarkus: https://github.com/quarkusio/quarkus/pull/20959.

Add Oracle DB dev mode and Dev Services tests

---

sql-db/sql-app/pom.xml

This reverts commit 5b8319a41b612d65f80312702aa6794eb0390994.
An unnecessary workaround.

Revert "Increase native build memory limit 4 -> 5 GB"

---

security/vertx-jwt/pom.xml

As a result of https://github.com/quarkusio/quarkus/pull/21142,
`io.quarkus:quarkus-jackson` has to be added manually alongside
`io.quarkus:quarkus-vertx` if we want to use
`com.fasterxml.jackson.databind` classes or other
`quarkus-jackson`-provided functionality.
In case of `security/vertx-jwt`, the use of property
`quarkus.jackson.fail-on-empty-beans` in `application.properties`
requires this dependency.
Related to https://github.com/quarkus-qe/beefy-scenarios/pull/262.

Add `quarkus-jackson` alongside `quarkus-vertx`

---

quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliVersionIT.java

Amend test  in order to fit this commit:
https://github.com/quarkusio/quarkus/commit/47c2d948d01dc8bea0262f495f29e5ea85ab1c1c#diff-ffe15562f1c91992754190c19745597d15b171f0868bd7970990b8d08a4c33a1
`quarkus-cli --version` only return version value instead of  `client Version {{ version value }}`

Quarkus-cli --version only returns version value

---

sql-db/vertx-sql/src/test/resources/docker-compose.yaml

* Making the docker-compose file in `sql-db/vertx-sql` use
`quarkusqeteam` image rather than the personal one.
Fixes #390.

[#390] Removing personal images from test suite

---

README.md
http/http-minimum-reactive/pom.xml
http/http-minimum-reactive/src/main/java/io/quarkus/ts/http/minimum/reactive/Hello.java
http/http-minimum-reactive/src/main/java/io/quarkus/ts/http/minimum/reactive/HelloResource.java
http/http-minimum-reactive/src/main/resources/application.properties
http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/DevModeHttpMinimumReactiveIT.java
http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/HttpMinimumReactiveIT.java
http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/OpenShiftHttpMinimumReactiveIT.java
http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/OpenShiftUsingExtensionDockerBuildStrategyHttpMinimumReactiveIT.java
http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/OpenShiftUsingExtensionHttpMinimumReactiveIT.java
http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/ServerlessExtensionDockerBuildStrategyOpenShiftHttpMinimumReactiveIT.java
http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/ServerlessExtensionOpenShiftHttpMinimumReactiveIT.java
http/http-minimum-reactive/src/test/resources/HelloResourceTest.java.template
http/http-minimum-reactive/src/test/resources/NoFunctionalTest.java.template
http/rest-client-reactive/pom.xml
http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/ReactiveClientBookResource.java
http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestInterface.java
http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/json/Book.java
http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/json/BookAsJsonResource.java
http/rest-client-reactive/src/main/resources/application.properties
http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ClientBookResourceIT.java
pom.xml

Main things to look at:
1. Parent pom.xml references
2. New reactive package in counterparts
3. Test classes name should reflect they're Reactive
4. Update endpoints from blocking to non-blocking signature
5. Update dependencies in the module's POM

Introduce reactive counterparts of http-minimum and rest-client modules under /http

---

pom.xml

We have reached dockerHub request limits on Jenkins. 
This PR moves `hyness/spring-cloud-config-server` image to `quay.io/quarkusqeteam/spring-cloud-config-server`

DockerHub limits: Moves hyness/spring-cloud-config-server to quay

---

pom.xml

Keycloak 15.0.2 fails at start time when runs over RHEL8.5 and FIPS enabled with the following error:
`java.lang.RuntimeException: PBKDF2 algorithm not found `

Downgrade keycloak version to 15.0.1 to support FIPS

---

sql-db/vertx-sql/src/test/java/io/quarkus/qe/vertx/sql/dbpool/PostgresqlResource.java

`quay.io/bitnami/postgresql:latest` was removed. Move on to version 13.4.0 as the main branch

[2.2] `quay.io/bitnami/postgresql:latest` is not available anymore

---

pom.xml

backport https://github.com/quarkus-qe/quarkus-test-suite/pull/395

[2.2] Downgrade keycloak version to 15.0.1 to support FIPS

---

sql-db/vertx-sql/pom.xml
sql-db/vertx-sql/src/main/resources/application.properties
sql-db/vertx-sql/src/test/java/io/quarkus/qe/vertx/sql/handlers/MssqlHandlerIT.java

After Quarkus' upgrade to Flyway 8.1.0, wherever `quarkus-flyway`
is used together with SQL Server, an external dependency
`org.flywaydb:flyway-sqlserver` (managed by Quarkus BOM) must be
also present.
https://github.com/quarkusio/quarkus/pull/21715#issuecomment-979587768

Add flyway-sqlserver dependency

---

.github/workflows/ci.yml
.github/workflows/daily.yaml
.github/workflows/quarkus-snapshot.yaml

Setup-java@2 supports now caching, which behaves by default the same way as it was configured in our actions/cache@v1.
Performance improvement:
1. We don't need caching on **Build Dependencies** and **Validate Format**. **Build Dependencies** already performs zipping of the **~/.m2/repository** folder after the build and this zipped archive is unzipped in subsequent steps. Caching at this stage will only create a new cache key with only dependencies from Quarkus Build which we will hit all the time in the next steps (if any of the pom.xml files _was not_ changed!).
Performing caching at the stage of `Test Suite Build` will create a new cache key if any of the pom.xml was changed and will save to this cache all the resolved dependencies during the build (this was not the case before). This …

Update github actions versions for Setup-java and Checkout

---

sql-db/vertx-sql/src/main/resources/application.properties

This reverts commit 30573cafb7f5223e379b9a811ea1daa0950ce918.
Follow-up to https://github.com/quarkus-qe/quarkus-test-suite/pull/399.
Reverts one of the commits with a workaround to https://github.com/quarkusio/quarkus/issues/21835, which has since been resolved.

Revert "Add workaround to Flyway 8.1.0 + SQL Server issue"

---

quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java

The CLI test generates an app with `kogito-quarkus-rules` extension.
After https://github.com/kiegroup/kogito-runtimes/pull/1643, Kogito
needs both `quarkus-resteasy` and `quarkus-resteasy-jackson` to be
able to build with tests - tests invoke REST endpoint.
The Kogito PR was merged in Kogito `1.13.0.Final` (in Quarkus Platform
`2.5.0.CR1`)

Add RESTEasy extensions to CLI apps with Kogito

---

.github/workflows/ci.yml
.github/workflows/daily.yaml

Due to Quarkus main re-structure, some modules have been moved under the "relocations" profile.

Add relocations profile to Quarkus main build

---

messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/DevModeKafkaStreamIT.java
messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/DevModeRedPandaDevServiceUserExperienceIT.java

The daily build is failing because the user-experience Kafkadevservice scenario is failing. 
I could not reproduce the error locally but this scenario is checking the default log messages logged by kafka devservices. More in detail is checking the default messages when redpanda docker image doesn't exist. The scenario remove redpanda docker image as a previous test step. In order to avoid some conflicts with other scenarios that also are using this default image, let's use a custom image for this case. 
`kafkaContainerShouldBeStarted` test was failing because the started log has changed

Use a non default devService Kafka version on user experience tests

---

sql-db/panache-flyway/pom.xml
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMariadbIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMysqlIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeOracleIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModePostgresqlIT.java

Flyway 8.X needs `flyway-mysql` dependency. 
Doc Ref: https://flywaydb.org/documentation/database/mysql#java-usage
Issue Ref: https://github.com/quarkusio/quarkus/issues/22400

Fix some DB devServices logs verification + Add flyway-mysql dependency

---

cache/caffeine/src/test/java/io/quarkus/ts/cache/caffeine/cache/caffeine/ServiceWithCacheResourceIT.java
http/vertx-web-client/pom.xml
monitoring/opentelemetry-reactive/pom.xml
monitoring/opentelemetry/pom.xml

Disable reactive tests in `cache/caffeine`.
- Workaround to https://github.com/quarkusio/quarkus/issues/22251.
Disable native build in `monitoring/opentelemetry*` and `http/vertx-web-client`.
- Workaround to https://github.com/quarkusio/quarkus/issues/22275.

Disable failing tests - workarounds to reported issues

---

sql-db/vertx-sql/pom.xml

Flyway 8.X needs flyway-mysql dependency.
Doc Ref: https://flywaydb.org/documentation/database/mysql#java-usage
Issue Ref: quarkusio/quarkus#22400

Add missing 'flyway-mysql' to vertx-sql module

---

scheduling/quartz/pom.xml

Flyway 8.X needs flyway-mysql dependency.
Doc Ref: https://flywaydb.org/documentation/database/mysql#java-usage
Issue Ref: quarkusio/quarkus#22400

Add flyway-mysql extension to scheduling/quartz

---

http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/HttpHostDisabledIT.java

Quarkus application should start even with property `quarkus.http.host-enabled=false`

Quarkus app should startup without domain socket

---

http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/HttpHostDisabledIT.java

[2.2] Quarkus app should startup without domain socket

---

http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/HttpCustomHeadersIT.java

Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/441.
Contrary to the original PR, this backport covers only RESTEasy Classic (`http/http-minimum`) and not RESTEasy Reactive, because `http/http-minimum-reactive` is not present in `2.2` branch.

Add coverage for case-insensitive HTTP `Accept` header

---

http/http-minimum-reactive/src/main/java/io/quarkus/ts/http/minimum/reactive/HelloResource.java
http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/HttpCustomHeadersIT.java
http/http-minimum/src/main/java/io/quarkus/ts/http/minimum/HelloResource.java
http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/HttpCustomHeadersIT.java

Verifies that the RESTEasy Classic / RESTEasy Reactive handles the
`Content-Type` response header correctly and always sends properly
formatted string.

Add coverage for HTTP `Content-Type` response header

---

http/http-minimum/src/main/java/io/quarkus/ts/http/minimum/HelloResource.java
http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/HttpCustomHeadersIT.java

Verifies that the RESTEasy Classic handles the `Content-Type` response
header correctly and always sends properly formatted string.
Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/450.

[2.2] Add coverage for HTTP `Content-Type` response header

---

README.md
pom.xml
security/form-authn/pom.xml
security/form-authn/src/main/java/io/quarkus/ts/security/form/authn/UserResource.java
security/form-authn/src/main/resources/application.properties
security/form-authn/src/test/java/io/quarkus/ts/security/form/authn/BasicAuthnIT.java
security/form-authn/src/test/java/io/quarkus/ts/security/form/authn/FormAuthnIT.java
security/form-authn/src/test/resources/basicAuthN.properties
security/form-authn/src/test/resources/formAuthN.properties

- Don't enable basic auth as a fallback if it has been disabled
- Basic coverage of Quarkus Form authN. 
Doc: https://quarkus.io/guides/security-built-in-authentication#form-auth

FormAuthN Coverage

---

security/basic/pom.xml
security/basic/src/main/java/io/quarkus/ts/openshift/security/basic/UnannotatedResource.java
security/basic/src/test/java/io/quarkus/ts/openshift/security/basic/SecurityTest.java
security/basic/src/test/java/io/quarkus/ts/openshift/security/basic/SecurityTestProfile.java

Verifies that the `quarkus.security.jaxrs.deny-unannotated-endpoints`
property and  `@TestSecurity` annotation work correctly together and in
combination with Basic Auth.

Add coverage of `quarkus-test-security` extension

---

config/src/main/java/io/quarkus/ts/configmap/api/server/Hello.java
http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/Hello.java
http/http-advanced/src/main/java/io/quarkus/ts/http/advanced/Hello.java
http/http-minimum-reactive/src/main/java/io/quarkus/ts/http/minimum/reactive/Cluster.java
http/http-minimum-reactive/src/main/java/io/quarkus/ts/http/minimum/reactive/ClusterResource.java
http/http-minimum-reactive/src/main/java/io/quarkus/ts/http/minimum/reactive/Clusters.java
http/http-minimum-reactive/src/main/java/io/quarkus/ts/http/minimum/reactive/Hello.java
http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/HttpMinimumReactiveIT.java
http/http-minimum/src/main/java/io/quarkus/ts/http/minimum/Hello.java
http/jaxrs-reactive/src/main/java/io/quarkus/ts/jaxrs/reactive/json/UnquotedFields.java
http/vertx-web-client/src/main/java/io/quarkus/qe/vertx/webclient/model/Joke.java
messaging/kafka-avro-reactive-messaging/src/main/java/io/quarkus/ts/messaging/kafka/StockPriceDto.java
security/keycloak-oidc-client-extended/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/model/Score.java
sql-db/reactive-vanilla/src/main/java/io/quarkus/qe/model/Book.java
sql-db/reactive-vanilla/src/main/java/io/quarkus/qe/model/NoteBook.java
sql-db/reactive-vanilla/src/main/java/io/quarkus/qe/model/Record.java
sql-db/vertx-sql/src/main/java/io/quarkus/qe/vertx/sql/domain/Address.java
sql-db/vertx-sql/src/main/java/io/quarkus/qe/vertx/sql/domain/Airline.java
sql-db/vertx-sql/src/main/java/io/quarkus/qe/vertx/sql/domain/Airport.java
sql-db/vertx-sql/src/main/java/io/quarkus/qe/vertx/sql/domain/Basket.java
sql-db/vertx-sql/src/main/java/io/quarkus/qe/vertx/sql/domain/Flight.java
sql-db/vertx-sql/src/main/java/io/quarkus/qe/vertx/sql/domain/Passenger.java
sql-db/vertx-sql/src/main/java/io/quarkus/qe/vertx/sql/domain/PricingRules.java
sql-db/vertx-sql/src/main/java/io/quarkus/qe/vertx/sql/domain/QueryFlightSearch.java
sql-db/vertx-sql/src/main/java/io/quarkus/qe/vertx/sql/domain/Record.java

This PR talks about native mode
Some `RegisterForReflection` annotations are not required based on this commit: https://github.com/quarkusio/quarkus/pull/20225
Also, we have added a new scenario with a data structure as is described on this issue:
https://github.com/quarkusio/quarkus/issues/20200

Remove some RegisterForReflection annotation that are not required any more

---

http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/RemoteDevWithoutPasswordIT.java

If a Quarkus remote dev is executed without a password, then start-up should fail.

RemoteDevMode without password scenario

---

security/basic/pom.xml
security/basic/src/main/java/io/quarkus/ts/openshift/security/basic/UnannotatedResource.java
security/basic/src/test/java/io/quarkus/ts/openshift/security/basic/SecurityTest.java
security/basic/src/test/java/io/quarkus/ts/openshift/security/basic/SecurityTestProfile.java

Verifies that the `quarkus.security.jaxrs.deny-unannotated-endpoints`
property and  `@TestSecurity` annotation work correctly together and in
combination with Basic Auth.
Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/440.

[2.2] Add coverage of `quarkus-test-security` extension

---

README.md
http/graphql/pom.xml
http/graphql/src/main/java/io/quarkus/ts/http/graphql/Person.java
http/graphql/src/main/java/io/quarkus/ts/http/graphql/PersonsEndpoint.java
http/graphql/src/main/resources/application.properties
http/graphql/src/test/java/io/quarkus/ts/http/graphql/GraphQLIT.java
http/graphql/src/test/java/io/quarkus/ts/http/graphql/OpenShiftGraphQLIT.java
pom.xml

Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/446

[2.2] Graphql coverage

---

messaging/artemis-jta/src/main/resources/application.properties
messaging/kafka-avro-reactive-messaging/src/test/resources/strimzi-application.properties

In order to avoid the following warning:
```
[WARNING] [io.quarkus.kubernetes.deployment.KubernetesConfigUtil] Usage of quarkus.openshift.expose is deprecated in favor of quarkus.openshift.route.expose
```
Replace all `quarkus.openshift.expose` by `quarkus.openshift.route.expose`
Doc Ref: https://quarkus.io/guides/deploying-to-openshift#exposing_routes

`quarkus.openshift.expose` was deprecated

---

.github/workflows/ci.yml
.github/workflows/daily.yaml
README.md
docker-build/pom.xml
docker-build/src/main/docker/Dockerfile.jvm
docker-build/src/main/docker/Dockerfile.legacy-jar
docker-build/src/main/docker/Dockerfile.native
docker-build/src/main/docker/Dockerfile.native-distroless
docker-build/src/main/java/io/quarkus/ts/docker/HelloResource.java
docker-build/src/main/resources/application.properties
docker-build/src/test/java/io/quarkus/ts/docker/DockerBuildIT.java
pom.xml

issue Ref: https://github.com/quarkusio/quarkus/pull/19958
A Quarkus app that uses the extension `container-image-docker` fails if the docker image name (`quarkus.application.name`) contains some spaces at the end. 
The issue has been fixed.  Verified by this PR.

Add docker image name with empty spaces scenario

---

messaging/artemis-jta/src/main/resources/application.properties
messaging/kafka-avro-reactive-messaging/src/test/resources/strimzi-application.properties

[2.2] quarkus.openshift.expose was deprecated

---

docker-build/src/main/resources/application.properties
docker-build/src/test/java/io/quarkus/ts/docker/NativeConfigurationIT.java

Native image generation scenario:
Verify that a cache is created alongside the generated native image in a subdirectory named `test`. Note that folder "test" was created with an additional argument `-H:DebugInfoSourceCacheRoot=test` supported by this commit: https://github.com/oracle/graal/commit/dee66ca6e28fd519cef061130d20e28ec35d1a1f

Add gdb debugging sources scenario

---

security/vertx-jwt/src/main/java/io/quarkus/ts/security/vertx/services/AbstractRedisDao.java

Related to: https://github.com/quarkusio/quarkus/commit/8243740c44f8bf8fc11c47c33bab8d679ed8f906
Doc Ref (Mutiny 1.3.0): https://github.com/smallrye/smallrye-mutiny/releases
Take a look to  "Breaking Changes" :
```
method MultiCollect<T> Multi<T>::collectItems() has been removed
```
Quarkus Doc issue: https://github.com/quarkusio/quarkus/issues/22843

Mutiny `collectItems` is not supported anymore

---

docker-build/src/main/docker/Dockerfile.native

Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/480

[2.2] Docker file was restored for native runs and now uses supported base image

---

sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/reactive/DB2DatabaseIT.java

- sql-db/vertx-sql already has `fips-incompatible` tag

Add tag `fips-incompatible`  to DB2 scenarios

---

javaee-like-getting-started/pom.xml
super-size/many-extensions/pom.xml

Deprecated quarkus-undertow-websockets was removed

Deprecated quarkus-undertow-websockets was removed

---

http/vertx-web-client/src/test/java/io/quarkus/qe/vertx/webclient/ChuckNorrisResourceIT.java

Update: Use default Jaeger image specified in test-framework
Was:
Currently during Quarkus 2.2.5 testing on IBM Z, the default Jaeger container image, `jaegertracing/all-in-one:1.21.0`, is not supported on both s390x/ppc64le. Proposing a change to use the latest Jaeger container which is supports all 3 architectures similar to this [line](https://github.com/quarkus-qe/quarkus-test-suite/blob/330118b66868495962b26e3d0118fb3c2b44d7fa/http/vertx-web-client/src/test/java/io/quarkus/qe/vertx/webclient/ChuckNorrisResourceIT.java#L52) in another test.

[2.2] Use default Jaeger image specified in test-framework

---

sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/reactive/DB2DatabaseIT.java

[2.2] Disable DB2 tests on FIPS-enabled machines

---

.github/workflows/quarkus-snapshot.yaml

So that the other tests are run to completion when one failed.
See https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/1804675252 for a good example of why we don't want this option enabled.

Disable fail-fast in Ecosystem CI

---

pom.xml

Disable kafka-streams and kafka-strimzi scenarios and qute/multimodule scenarios, we need green ci to spot other issues without need for daily checks of the logs
They are not working after move to strimzi-test-container 0.100.0 in Quarkus main
https://github.com/quarkus-qe/quarkus-test-framework/issues/400
qute/multimodule is related to https://issues.redhat.com/browse/QUARKUS-1695 (@fedinskiy please make sure this get re-enabled in few days)

Disable kafka-streams and kafka-strimzi scenarios and qute/multimodule

---

sql-db/sql-app/src/test/resources/container-license-acceptance.txt

container-license-acceptance.tx update to cover mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
otherwise there is test fail like in case of https://github.com/quarkus-qe/quarkus-test-suite/pull/520
related to bump in https://github.com/quarkusio/quarkus/pull/23428 and https://github.com/quarkusio/quarkus/pull/23465

container-license-acceptance.tx update to cover mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04

---

pom.xml

Upgrade Quarkus test framework to 1.0.5.Final. 
This upgrade will fix an issue that we have with external applications. When an application uses a quarkus maven plugin with a different version than quarkus platform, the scenario fails because of an issue with the test framework.

Upgrade Quarkus framework QE to 1.0.5.Final

---

sql-db/vertx-sql/pom.xml
sql-db/vertx-sql/src/main/resources/application.properties
sql-db/vertx-sql/src/test/java/io/quarkus/qe/vertx/sql/dbpool/PostgresPoolTest.java

Vertx-sql module is failing with FIPS enabled. The issue is related to the test itself, looks that Mutiny HTTPClient fails with a default configuration. 
Replace Vertx HttpClient by RestAssurance

Replace Vertx HttpClient by restAssurance in PostgresPoolTest scenario

---

sql-db/vertx-sql/pom.xml
sql-db/vertx-sql/src/main/resources/application.properties
sql-db/vertx-sql/src/test/java/io/quarkus/qe/vertx/sql/dbpool/PostgresPoolTest.java

[2.2] Replace Vertx HttpClient by restAssurance in PostgresPoolTest scenario

---

http/vertx-web-client/src/test/java/io/quarkus/qe/vertx/webclient/PureVertxHttpClientTest.java

TestSceanrio: Vertx HttpClient + QuarkusTest is failing over FIPS protocol. 
Related to: https://github.com/quarkusio/quarkus/issues/23684

QuarkusTest + Vertx HttpClient + FIPS scenario

---

external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftQuickstartIT.java
external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftTodoDemoIT.java
external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftWorkshopHeroesIT.java
external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftWorkshopVillainsIT.java

On `OpenShiftWorkshopVillainsIT` we have to move on to this commit `db3802ecfdcd1f8d6a813ee53471463583c73e0e` because has some required parametrized values as `quarkus.platform.group-id`, "The problem" (is not a big deal because is not relevant to this test) is that this commit doesn't have some features that we use to have as `metrics` or `/health` API

[2.2] Add  param to OCP external applications

---

pom.xml

New version fixes log4j vulnerability.

Bump DB2 image from 11.5.5.0 to 11.5.7.0

---

http/vertx-web-client/src/test/java/io/quarkus/qe/vertx/webclient/PureVertxHttpClientTest.java
sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/reactive/DB2DatabaseIT.java

As a result of a retrospective meeting, we conclude that all scenarios must be enabled (related to FIPS). So from now, we will not exclude any FIPS scenario by flags exclusions. 
Example,
```
mvn -B -V -Dopenshift -Dall-modules -DexcludedGroups=fips-incompatible
```
Remove `excludeGroups` property is done in other PR, related to CI jobs. 
Note: I decided to leave the tag `@Tag("fips-incompatible")` from now until be sure that all of these scenarios are fixed. This tag doesn't have any impact, is just for tracing proposes.

FIPS workaround rollback

---

.github/workflows/ci.yml
lifecycle-application/pom.xml
pom.xml

- Bump to Quarkus 2.7.3.Final
- Build just deps for CLI
- Fast fail for format issues
- Qute module drop for now

Bump to Quarkus 2.7.3.Final

---

messaging/infinispan-grpc-kafka/pom.xml

artifactId: `strimzi-test-container` is not directly used on this scenario
Instead we are using Quarkus test framework annotations:
```
@KafkaContainer(vendor = KafkaVendor.STRIMZI, protocol = KafkaProtocol.SASL)
static final KafkaService kafkasasl = new KafkaService();
```

Testcontainer dependency was left over in infinispan-grpc-kafka module

---

external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftWorkshopHeroesIT.java
external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftWorkshopVillainsIT.java
external-applications/src/test/java/io/quarkus/ts/external/applications/QuickstartIT.java
external-applications/src/test/java/io/quarkus/ts/external/applications/TodoDemoIT.java
pom.xml

Depends on the following PR:
* [Upgrade todo-demo-app to Quarkus 2.7.1.Final](https://github.com/quarkus-qe/quarkus-test-framework/pull/417)
* [Parametrize Quarkus Platform and plugin version](https://github.com/quarkusio/todo-demo-app/blob/master/pom.xml)
* [Parametrize Quarkus Platform and plugin version](https://github.com/quarkusio/quarkus-quickstarts/pull/1067)
* [Support platform group ID parametrization](https://github.com/quarkus-qe/quarkus-test-framework/pull/417)

Add platform group id to external applications

---

checkstyle.xml

Currently, there is no java style rule that verifies `this.` overlapping
For example:
```
public class Test {
private int a;
private int b;
private int c;
public Test(int a) {
this.a = a; //make sense
a = a; //Technically will compile, but doesn't make sense because there is an overlapping between property `this.a` and local variable `a`
}
}
```
This PR creates a rule that validates these cases.

Add RequireThis rule if there is overlapping on java checkstyle

---

pom.xml

Quarkus 2.7.x has moved to [Keycloak 16.1.0](https://github.com/quarkusio/quarkus/blob/2733bae7cb7ded76d324b41a3a9f4e81b89ee122/bom/application/pom.xml#L186) as a default supported Keykloak.
This PR bump keycloak version according to these changes. 
Upgrade Keycloak container: 15.0.1 -> 16.1.0

Bump Keycloak version to 16.1.0

---

http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/HttpAdvancedReactiveIT.java
http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/HttpAdvancedIT.java
monitoring/micrometer-prometheus-oidc/src/test/java/io/quarkus/ts/micrometer/oidc/BaseMicrometerOidcSecurityIT.java
security/keycloak-authz-classic/src/test/java/io/quarkus/ts/security/keycloak/authz/KeycloakAuthzSecurityIT.java
security/keycloak-authz-reactive/src/test/java/io/quarkus/ts/security/keycloak/authz/KeycloakAuthzSecurityIT.java
security/keycloak-jwt/src/test/java/io/quarkus/ts/security/keycloak/jwt/KeycloakOidcJwtSecurityIT.java
security/keycloak-multitenant/src/test/java/io/quarkus/ts/security/keycloak/multitenant/KeycloakMultiTenantSecurityIT.java
security/keycloak-oauth2/src/test/java/io/quarkus/ts/security/KeycloakOauth2SecurityIT.java
security/keycloak-oidc-client-basic/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/basic/KeycloakOidcClientSecurityIT.java
security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/BaseIT.java
security/keycloak-webapp/src/test/java/io/quarkus/ts/security/keycloak/webapp/KeycloakWebappSecurityIT.java
security/keycloak/src/test/java/io/quarkus/ts/security/KeycloakOidcSecurityIT.java

Keycloak docker container 16.1.x is not working over FIPS protocol. This issue is already [reported ](https://github.com/keycloak/keycloak/issues/9916).
This PR apply a suggested patch on the above PR in order to make Keycloak "work" over FIPS

Add FIPS/keycloak workaround

---

external-applications/pom.xml

Module "external apps" was failing during production tests, since they use maven plugin with `com.redhat.quarkus.platform` group and it was not disabled before this change.

Disable quarkus plugin during prod run also

---

spring/spring-data/src/test/java/io/quarkus/ts/spring/data/di/SpringDiTest.java
sql-db/vertx-sql/src/test/java/io/quarkus/qe/vertx/sql/dbpool/PostgresPoolTest.java

PostgresPoolTest is a baremetal test and should be excluded from Openshift runs.
Also QuarkusTest SpringDiIT was renamed to SpringDiTest 

Disable Vertx PostgresPoolTest QuarkusTest scenario over Openshift

---

config/src/main/java/io/quarkus/ts/configmap/api/server/Hello.java

OCP native runs are failing because we are missing a required `@RegisterForReflection`

Add a missing RegisterForReflexion annotation on a java pojo

---

pom.xml

Quarkus test framework upgrade: 1.1.0.Beta2 -> 1.1.0.Beta3

Upgrade Quarkus test framework to 1.1.0.Beta3

---

README.md
external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftWorkshopHeroesIT.java
external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftWorkshopVillainsIT.java
pom.xml
spring/spring-data/src/test/java/io/quarkus/ts/spring/data/AbstractDbIT.java
spring/spring-web/src/test/java/io/quarkus/ts/spring/web/MariaDBUtils.java
spring/spring-web/src/test/java/io/quarkus/ts/spring/web/boostrap/BookResourceIT.java
spring/spring-web/src/test/java/io/quarkus/ts/spring/web/boostrap/HomePageIT.java
spring/spring-web/src/test/java/io/quarkus/ts/spring/web/openapi/OpenApiIT.java
sql-db/hibernate-fulltext-search/src/test/java/io/quarkus/qe/hibernate/search/MysqlMultitenantHibernateIT.java
sql-db/hibernate-fulltext-search/src/test/java/io/quarkus/qe/hibernate/search/PostgresqlMultitenantHibernateIT.java
sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/reactive/PostgresqlDatabaseIT.java
sql-db/hibernate/src/test/java/io/quarkus/qe/hibernate/ProdHibernateIT.java
sql-db/multiple-pus/src/test/java/io/quarkus/ts/sqldb/multiplepus/MultiplePersistenceIT.java
sql-db/multiple-pus/src/test/java/io/quarkus/ts/sqldb/multiplepus/OpenShiftMultiplePersistenceIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/MySqlDatabaseIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/OpenShiftPostgresql13DatabaseIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/Postgresql13DatabaseIT.java
sql-db/vertx-sql/src/test/java/io/quarkus/qe/vertx/sql/dbpool/PostgresqlResource.java
sql-db/vertx-sql/src/test/java/io/quarkus/qe/vertx/sql/handlers/PostgresqlHandlerIT.java
sql-db/vertx-sql/src/test/resources/docker-compose.yaml

We check that MariaDB container started, by looking into log and waiting
for special lines. Before that change, we were looking for a line "ready for connections",
which was duplicated and its first appearance was right before a reload
of the container, so in some cases we were trying to connect to
non-working DBMS. Now we use a unique line.

Fix "unexpected end of stream" error.

---

messaging/infinispan-grpc-kafka/src/test/java/io/quarkus/qe/messaging/infinispan/InfinispanKafkaIT.java
messaging/infinispan-grpc-kafka/src/test/java/io/quarkus/qe/messaging/infinispan/InfinispanKafkaSaslIT.java
messaging/infinispan-grpc-kafka/src/test/java/io/quarkus/qe/messaging/infinispan/InfinispanKafkaSslIT.java

infinispan-grpc-kafka / native scenarios are flacky. We have refactored these scenarios in order to decouple each one into a separate scenario and by this way improve the traceability. 
cmd `mvn clean verify -Dnative -Dit.test=InfinispanKafkaSslIT -Dmaven.failsafe.debug=true -Dmaven.surefire.debug=true -Dall-modules -pl messaging/infinispan-grpc-kafka`

Refactor infinispan-grpc-kafka sceanrio due to a native error

---

quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java

Explicitly specify BOM GAV for created application
As Quarkus 2.8 is available the default app is generated with the latest version, causing troubles with restarts because of extension removal when the latest bits get picked

Explicitly specify BOM GAV for created application

---

http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/OsUtils.java
http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/files/FileClientResource.java
http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/files/FileResource.java
http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/LargeFileHandlingIT.java

This pull request fixes the following [daily](https://github.com/quarkus-qe/quarkus-test-suite/runs/6167108941?check_suite_focus=true) build issues:
- Http/restClientReactive: fails because the event-loop was blocked. This issue requires a refactor of the current scenario. We have moved from an imperative code style to a reactive implementation. 

Daily build fixs

---

http/jaxrs-reactive/src/main/java/io/quarkus/ts/jaxrs/reactive/client/PojoData.java
http/jaxrs-reactive/src/test/java/io/quarkus/ts/jaxrs/reactive/client/MultipartClientResourceIT.java

Re-enable disabled rest-client-reactive multipart test.
Fix bugs in the test:
- Typo in expected response body.
- Wrong assumption about letter case in names of response headers: filed names are case-insesitive.
- Missing `@RegisterForReflection` in `PojoData` class.
This test is reproducer for https://issues.redhat.com/browse/QUARKUS-1225.

Enable and fix rest-client-reactive multipart test

---

quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliExtensionsIT.java

Quarkus-cli gets extensions + streamsId moves to Quarkus 2.8+ , so Quarkus-cli 2.7 get extension is not supported anymore. 
This PR disables this scenario in Quarkus 2.7

Disable Quarkus-cli getAllExtension by streams

---

pom.xml
spring/spring-data/src/test/java/io/quarkus/ts/spring/data/AbstractDbIT.java
sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/reactive/PostgresqlDatabaseIT.java
sql-db/multiple-pus/src/test/java/io/quarkus/ts/sqldb/multiplepus/OpenShiftMultiplePersistenceIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/OpenShiftPostgresql13DatabaseIT.java

Some of the images we used could not be used on OpenShift without mounted volumes. Since volumes can not be mounted via framework, we need workarounds for that.

Use images, which can be run on OpenShift without volumes

---

pom.xml

Workaround for memory issues with the official Elasticsearch image.
https://github.com/quarkus-qe/quarkus-test-suite/issues/627
The official image uses maximum available memory when started
without memory restrictions. That caused problems in testing environment
(Jenkins nodes) and the container kept exitting on OOM (container exit
code 137).
The bitnami image (identical release) is more conservative in memory
management and tends to constantly use ~1.3 GB.

Switch to bitnami elasticsearch image

---

quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateExtensionIT.java
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateNativeApplicationIT.java
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliExtensionsIT.java
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliSpecialCharsIT.java
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliUtils.java

We are going to fix Quarkus streams to a fixed version in most of the quarkusClient scenarios in order to avoid some registry configuration issues.

Set a fixed stream version on Quarkus-cli commands

---

.github/workflows/ci.yml
.github/workflows/daily.yaml

This PR disables Quarkus-cli daily build.
depends on: https://github.com/quarkusio/registry.quarkus.io/pull/97

Disable quarkus-cli scenarios on daily builds

---

external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftWorkshopHeroesIT.java
external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftWorkshopVillainsIT.java
pom.xml

Put postgres data dir to folder, where root access is not required
Remove duplicated consul image

Fix failing tests

---

security/oidc-client-mutual-tls/src/test/java/io/quarkus/ts/security/oidcclient/mtls/DeclaredKsFileTypeOidcMtlsIT.java
security/oidc-client-mutual-tls/src/test/java/io/quarkus/ts/security/oidcclient/mtls/IncorrectKsFileTypeOidcMtlsIT.java
security/oidc-client-mutual-tls/src/test/java/io/quarkus/ts/security/oidcclient/mtls/JksOidcMtlsIT.java
security/oidc-client-mutual-tls/src/test/java/io/quarkus/ts/security/oidcclient/mtls/Pkcs12OidcMtlsIT.java

Some Mutual TLS scenarios are not FIPS compatible, one way around this is using `BouncyCastleFipsProvider`, however we should still have scenarios without provider set and [upstream issue](https://github.com/quarkusio/quarkus/pull/25234) that enabled us to set provider is not in latest RHBQ (2.7.5.ER4). I will provide tests for FIPS scenario in a separate PR.

Disable mTLS test suite with FIPS

---

messaging/infinispan-grpc-kafka/src/test/java/io/quarkus/qe/messaging/infinispan/InfinispanKafkaIT.java
messaging/infinispan-grpc-kafka/src/test/java/io/quarkus/qe/messaging/infinispan/InfinispanKafkaSaslIT.java
messaging/infinispan-grpc-kafka/src/test/java/io/quarkus/qe/messaging/infinispan/InfinispanKafkaSslIT.java

Infinispan doesn't support FIPS on this relea
Add "fips-incompatible" tag to infinispan scenarios

Disable infinispan scenarios on FIPS

---

lifecycle-application/src/main/resources/application.properties

Setting [quarkus.openshift.arguments](https://quarkus.io/guides/deploying-to-openshift#quarkus-openshift-openshift-config_quarkus.openshift.arguments) in native mode iff [entrypoint](https://docs.openshift.com/container-platform/4.10/applications/deployments/managing-deployment-processes.html#deployments-exe-cmd-in-container_deployment-operations) is not set nor overriden by [quarkus.openshift.command](https://quarkus.io/guides/deploying-to-openshift#quarkus-openshift-openshift-config_quarkus.openshift.command) leads to `CreateContainerError`. The behavior is nicely explained [here](https://github.com/openshift/origin/issues/21547#issuecomment-442863354). Tested with OpenShift 4.10 and 4.6, but I suspect the same behavior will affect Kubernetes. Tested both with 2.7.5.CR1 and upstream. …

Fix container startup in native mode with Openshift arguments set

---

lifecycle-application/src/main/resources/application.properties
lifecycle-application/src/test/java/io/quarkus/ts/lifecycle/LifecycleApplicationIT.java
lifecycle-application/src/test/resources/empty.properties
lifecycle-application/src/test/resources/native.properties

My PR #645 fixed OpenShift container startup in native mode, however the command should not be applied in JVM mode as the entrypoint does not exist there and OpenShift command is used by Quarkus to start application (thus we should not override it without a good reason).

Don't set OpenShift command in JVM mode (only set it in native)

---

sql-db/sql-app/src/test/resources/oracle.properties

`drop-and-create` causes Oracle to complain about dropping non-existent
objects, but it ensures empty DB, in case there are concerns about test
isolation.

Fix Hibernate generation in Oracle DB

---

README.md
http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/PremierLeagueContainerRequestFilter.java
http/http-advanced-reactive/src/main/resources/application.properties
http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/ContainerRequestFilterReactiveIT.java
http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/OpenShiftContainerRequestFilterReactiveIT.java
http/http-advanced/src/main/java/io/quarkus/ts/http/advanced/PremierLeagueContainerRequestFilter.java
http/http-advanced/src/main/resources/application.properties
http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/ContainerRequestFilterIT.java
http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/OpenShiftContainerRequestFilterIT.java

`javax.ws.rs.core.Context` field injection in classes annotated by `javax.ws.rs.ext.Provider` in Quarkus 2.2.4 and lesser in a native mode. This PR adds a new tests that cover `@Context` field injection for both JAX-RS RESTEasy Reactive and JAX-RS RESTEasy.
- [Upstream issue](https://github.com/quarkusio/quarkus/issues/20161)
- [JAX-RS reference guide, chapter Four](https://download.oracle.com/otn-pub/jcp/jaxrs-1.0-fr-eval-oth-JSpec/jaxrs-1.0-final-spec.pdf?AuthParam=1652777207_5a0cbee43bdc95478115076c1aec592d)
- [StackOverflow summarization on Providers](https://stackoverflow.com/questions/13557442/what-does-provider-in-jax-rs-mean)
- [Red Hat Fuse ContainerRequestContext example](https://access.redhat.com/documentation/en-us/red_hat_fuse/7.4/html/apache_cxf_development_guide/jaxrs20filte …

Test field injection of JAX-RS Providers

---

quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java

Quarkus-cli `QuarkusCliCreateJvmApplicationIT#verifyRestEasyReactiveAndClassicResteasyCollisionUserMsg` was using a default Quarkus stream (the latest one) when an application was created. This PR changed this behavior on this scenario in order to follow the same pattern of the rest Quarkus-cli test. 

[2.7] Quarkus-cli verify resteasy collision test should use a fixed stream 2.7

---

.github/workflows/ci.yml
.github/workflows/daily.yaml
http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/files/FileResource.java
messaging/kafka-confluent-avro-reactive-messaging/pom.xml
pom.xml
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliExtensionsIT.java
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliSpecialCharsIT.java
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliUtils.java
qute/multimodule/qute-test/src/main/resources/messages/alert_el.properties
qute/multimodule/qute-test/src/main/resources/messages/msg_cs.properties
service-discovery/stork-custom/pom.xml
service-discovery/stork-custom/src/main/java/io/quarkus/ts/stork/custom/SimpleLoadBalancer.java
service-discovery/stork-custom/src/main/java/io/quarkus/ts/stork/custom/SimpleLoadBalancerProvider.java
service-discovery/stork-custom/src/main/java/io/quarkus/ts/stork/custom/SimpleServiceDiscovery.java
service-discovery/stork-custom/src/main/java/io/quarkus/ts/stork/custom/SimpleServiceDiscoveryProvider.java
service-discovery/stork-custom/src/main/resources/application.properties
service-discovery/stork-custom/src/test/java/io/quarkus/ts/stork/custom/StorkCustomServiceDiscoveryAndLoadBalancerIT.java

Move to Quarkus 999-SNAPSHOT including daily and PR CI
Changes in testSuite:
* Reactive resteasy multipart should return a [RestResponse](https://quarkus.io/guides/resteasy-reactive#setting-other-response-properties)
* Use [confluent AVRO registry extension](https://quarkus.io/guides/kafka-schema-registry-avro#creating-the-maven-project)
* Qute multimodule scenario has duplicate properties defined in both projects
* Missing Stork `stork-configuration-generator` path on `maven-compiler-plugin`
-  https://github.com/quarkusio/quarkus/issues/25746 
* Add support to 999-SNAPSHOT - Quarkus-cli + the following issue resolution
- https://github.com/quarkusio/quarkus/issues/25761  

Move to Quarkus 999-SNAPSHOT including daily and PR CI

---

http/http-advanced-reactive/pom.xml
http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/Hello.java
http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/HelloAllResource.java
http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/MediaTypeResource.java
http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/MediaTypeWrapper.java
http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/MediaTypeWrapperSerializer.java
http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/MultipartFormDataDTO.java
http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/MultipartResource.java
http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/NinetyNineBottlesOfBeerResource.java
http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/ReflectionConfiguration.java
http/http-advanced-reactive/src/main/resources/application.properties
http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/HttpAdvancedReactiveIT.java
http/http-advanced-reactive/src/test/resources/file.txt
http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/BookClient.java
http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/PlainBookResource.java
http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/ReactiveClientBookResource.java
http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/files/FileResource.java
http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientIT.java

Test coverage for [recently reported issues](https://github.com/quarkusio/quarkus/issues?q=is%3Aissue+author%3Asithmein+) related to a RESTEasy Reactive client and RESTEasy Reactive and the closest context.
- [Quarkus Issue #25326](https://github.com/quarkusio/quarkus/issues/25326) pointed out that special characters in a request path are not correctly encoded. `ReactiveRestClientIT#decodedRequestPath` checks that characters in foreign languages and reserved characters are encoded using a special subset of ASCII characters (Alphanumeric, Unereserved, Reserved). Must be tested with `mvn clean install -Dit.test=ReactiveRestClientIT#decodedRequestPath,ReactiveRestClientIT#encodedRequestPath -Dquarkus.platform.version=2.8.3.Final` as in 2.7.5.Final both encoded and decoded characters in …

Test RESTEasy Reactive issues

---

http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/HttpCustomHeadersIT.java

We expected Content-Type header to contain only "application/json".
But it can(and now does) contain other things,
namely "charset" and "boundary" fields[1].
Therefore, we need to fix our tests.
[1] https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type

Check, that header *contains* application/json

---

http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/NinetyNineBottlesOfBeerResource.java
http/http-advanced-reactive/src/main/resources/application.properties
http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/HttpAdvancedReactiveIT.java

Follow up to [PR 655](https://github.com/quarkus-qe/quarkus-test-suite/pull/655), one test must be disabled by build property in order to prevent build failure if run with Quarkus 2.7.5 and lesser.
Class `io.quarkus.ts.http.advanced.reactive.NinetyNineBottlesOfBeerResource` breaks the build as `Path#value()` contain special characters as dash etc. [Issue 25258](https://github.com/quarkusio/quarkus/issues/25258) fixed the bug, the fix has been added to Quarkus since 2.7.6 and 2.8.3. The test resource is registered unless explicitly disabled with `-Dquarkus-platform-version-less-than-2.8.3=true`.

Enable `HttpAdvancedReactiveIT#uriPathTemplate` in Github workflows

---

spring/spring-data/src/main/java/io/quarkus/ts/spring/data/primitivetypes/BookRepository.java
spring/spring-data/src/main/java/io/quarkus/ts/spring/data/primitivetypes/BookResource.java
spring/spring-data/src/main/java/io/quarkus/ts/spring/data/primitivetypes/model/BookProjection.java
spring/spring-data/src/test/java/io/quarkus/ts/spring/data/primitivetypes/SpringDataBookResourceIT.java

Verifies [Quarkus Issue 24800](https://github.com/quarkusio/quarkus/issues/24800). Calling repository methods returning interface-based projection defined outside of `PanacheRepository` causes a runtime exception. The issue was fixed in Quarkus 2.8.1 and backported to 2.7.6. The issue can be reproduced by commenting out `@DisabledOnQuarkusVersion` on the test and running `mvn clean verify -Dit.test=SpringDataBookResourceIT#testInterfaceBasedProjection -Dquarkus.platform.version=2.7.5.Final`.

Test Spring Data JPA Interface-based Projection declared outside of Repo

---

quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java

Ensure the same Quarkus version is used after reload
TD for https://github.com/quarkusio/quarkus/issues/25184
FAIL: `mvn clean verify -f quarkus-cli -Dit.test=QuarkusCliCreateJvmApplicationIT#shouldKeepUsingTheSameQuarkusVersionAfterReload -Dquarkus.platform.group-id=com.redhat.quarkus.platform  -Dquarkus.platform.artifact-id=quarkus-bom -Dquarkus.platform.version=2.7.5.Final-redhat-00011 -Prh`
PASS: `mvn clean verify -f quarkus-cli -Dit.test=QuarkusCliCreateJvmApplicationIT#shouldKeepUsingTheSameQuarkusVersionAfterReload -Dquarkus.platform.group-id=io.quarkus.platform  -Dquarkus.platform.artifact-id=quarkus-bom -Dquarkus.platform.version=2.7.6.Final`

Ensure the same Quarkus version is used after reload

---

http/rest-client-reactive/pom.xml
http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientIT.java

Verifies [Quarkus Issue 24344](https://github.com/quarkusio/quarkus/issues/24344). Test class annotated with `javax.ws.rs.Path` and registered as client via `org.eclipse.microprofile.rest.client.inject.RegisterRestClient` must not be included in OpenAPI Document.
Issue reproducer:
If you comment out
`//    @DisabledOnQuarkusVersion(version = "(2\\.[0-6]\\..*)|(2\\.7\\.[0-5]\\..*)", reason = "Fixed in Quarkus 2.7.6.")`
and run
`mvn clean verify -Dit.test=ReactiveRestClientIT#restClientIsNotIncludedInOpenApiDocument -Dquarkus.platform.version=2.7.4.Final`
the test will fail because clients paths are added to the OpenAPI Document. The same test passes in 2.7.6 and higher.

Test Reactive RestClient with @Path is not included in OpenAPI Document

---

quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java

When a Quarkus app is created with Java 18 will use Java 17 and not Java 11

Add Quarkus-cli Java18 coverage

---

http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/MultipleResponseSerializersResource.java
http/http-advanced-reactive/src/main/resources/application.properties
http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/HttpAdvancedReactiveIT.java

Verifies [Quarkus Issue 22119](https://github.com/quarkusio/quarkus/issues/22119). According to JAX-RS standard, if request specifies accepted Media type, the type should be passed to `javax.ws.rs.ext.MessageBodyWriter`, however for use case when `javax.ws.rs.core.Response` is returned, that was only fixed in Quarkus 2.8.1 and backported to 2.7.6. Previously, if multiple media types were defined in `@Produces`, the first one was taken. This test verifies that a value of `Accept` HTTP header is same as the media type passed to `MessageBodyWriter` when endpoint response type is `Response`.
`mvn clean verify -Dit.test=HttpAdvancedReactiveIT#testMediaTypePassedToMessageBodyWriter -Dquarkus.platform.version=2.8.0.Final -Dquarkus-platform-version-less-than-2.8.3=true` with commented out …

Test MessageBodyWriter receives right accepted Media Type with Response

---

http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/HttpAdvancedReactiveIT.java
http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/HttpAdvancedIT.java
pom.xml

Bump formatter-maven-plugin from 2.18.0 to 2.19.0
Replaces https://github.com/quarkus-qe/quarkus-test-suite/pull/678

Bump formatter-maven-plugin from 2.18.0 to 2.19.0

---

security/oidc-client-mutual-tls/src/main/resources/application.properties

A new property `quarkus.oidc.tls.trust-store-provider` was added to Quarkus.
This PR verifies the correct behavior of this property

Add oidc TLS providers configuration coverage

---

http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/files/FileResource.java
http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/proxy/ProxyClient.java
http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/proxy/ProxyResource.java
http/rest-client-reactive/src/main/resources/proxy.properties
http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ProxyIT.java
http/rest-client-reactive/src/test/resources/proxy/Dockerfile
http/rest-client-reactive/src/test/resources/proxy/deploy.sh
http/rest-client-reactive/src/test/resources/proxy/nginx.conf
lifecycle-application/pom.xml
pom.xml
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliExtensionsIT.java

[Quarkus 2.7.6.Final](https://github.com/quarkusio/quarkus/releases/tag/2.7.6.Final) has been released and branch 2.7 should use it.

Update 2.7 branch to use Quarkus 2.7.6

---

.github/pull_request_template.md

Add missing PR GitHub template option

Add backport as an option in PR github template

---

http/graphql-telemetry/src/test/java/io/quarkus/ts/http/graphql/telemetry/GraphQLTelemetryIT.java
http/vertx-web-client/src/test/java/io/quarkus/ts/http/vertx/webclient/VertxWebClientIT.java

Jaeger openation name has changed:
operation -> operationName

Fix jaeger operation name query param

---

http/vertx-web-client/src/test/java/io/quarkus/ts/http/vertx/webclient/VertxWebClientIT.java

Jaeger operationName doesn't start with slash anymore

Fix Vertx-WebClient / jaeger scenario

---

monitoring/opentelemetry-reactive/src/test/java/io/quarkus/ts/opentelemetry/reactive/OpentelemetryReactiveIT.java
pom.xml

Enable monitoring opentelemetry-reactive scenarios

Re-enable opentelemetry-reactive

---

security/jwt/src/main/resources/application.properties

PEM files `private-key.pem` and `public-key.pem` were not kept, thus f.e. `OpenShiftCookieJwtSecurityIT#securedEveryoneViewGroup` was failing.

Keep PEM files in native mode

---

spring/spring-data/src/main/java/io/quarkus/ts/spring/data/di/ListInjectionBean.java
spring/spring-data/src/test/java/io/quarkus/ts/spring/data/di/ListInjectionIT.java

Test dependency injection using ArC `@All` with `List`.
See also https://github.com/quarkusio/quarkus/pull/25784.

Test ArC @All list injection

---

http/vertx-web-client/src/test/java/io/quarkus/ts/http/vertx/webclient/VertxWebClientIT.java

Seems that not always all spans or child spans include the expected operation names, for example
https://github.com/quarkus-qe/quarkus-test-suite/runs/6809549627?check_suite_focus=true
```
Expected: every item is a string containing "trace/ping"
but: an item was "[HTTP GET, /chuck/bodyCodec]" within 1 minutes.
```
Note: This operation ID come from an other test: `public void getChuckJokeByJsonBodyCodec()`
Maybe when the current scenario that is failing was created, this other test doesn't exist and at that time all the spans has the expected operation name

Fix VertxWebClient + jaeger, some spans/childSpans doesn't include expected operationName

---

http/graphql-telemetry/src/test/java/io/quarkus/ts/http/graphql/telemetry/GraphQLTelemetryIT.java

Currently traces are filtered by `operationName` which is not valid filter parameter and operations are not filtered by this. That causes problem in OpenShift where there are other calls (other operations with different names, e.g. `HTTP GET` - probably probe check). Problem can be easily reproduced locally on `GraphQLTelemetryIT` when you call GET to `/` couple of times, which leads to test failure.

Fix OpenShiftGraphQLTelemetryIT - filter Jaeger traces by operation name

---

monitoring/opentelemetry-reactive/src/test/java/io/quarkus/ts/opentelemetry/reactive/OpentelemetryReactiveIT.java

Follow up #708, disabling another test for same reasons.

Disable OpentelemetryReactiveIT in native mode

---

http/graphql-telemetry/src/main/resources/application.properties
http/graphql-telemetry/src/main/resources/reflection-config.json

Related to: https://github.com/quarkusio/quarkus/issues/26083

Missing UdsNettyChannelProvider register for reflexion on http/graphql-telemetry

---

http/vertx-web-client/src/test/java/io/quarkus/ts/http/vertx/webclient/VertxWebClientIT.java
monitoring/opentelemetry-reactive/src/test/java/io/quarkus/ts/opentelemetry/reactive/OpentelemetryReactiveIT.java
monitoring/opentelemetry/src/test/java/io/quarkus/ts/opentelemetry/OpentelemetryIT.java

List of all traces were always retrieved as query parameter is in fact called [operation](https://github.com/jaegertracing/jaeger/blob/main/cmd/query/app/query_parser.go#L36) instead of `operationName`. Condition `thenCheckOperationNamesIsEqualTo` has been adjusted as previously it wasn't asserting that all checked operation names were equal to the expected one. `JsonPath` expression returned f.e. `[[chuck/pong, HTTP GET, trace/ping], [HTTP GET, trace/ping, chuck/pong], [chuck/pong, HTTP GET, trace/ping]]` mapped to `List<String>`, thus condition did assert that just one of the operation names contained operation name, not all of them. It's important to realize that traces filtered by operation name are returning traces with that operation name and their children traces (e.g. if you use …

Fix `VertxWebClientIT` condition assertion & correct Span operation name

---

http/http-advanced-reactive/pom.xml
http/http-advanced/pom.xml
pom.xml
properties/pom.xml

Jsoup is not a Quarkus-junit5  transitive dependency any longer (Quarkus Upstream). This PR adds Jsoup dependency to all scenarios where is need it. 

Add jsoup dependency to http-advanced scenarios

---

http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/BookClient.java
http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/PlainBookResource.java
http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/ReactiveClientBookResource.java
http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/json/BookIdWrapper.java
http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/json/BookRepository.java
http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientIT.java

Reactive Rest Client newly supports ([Quarkus PR 24783](https://github.com/quarkusio/quarkus/pull/24783)) passing a query parameters as a map. This is very useful when user don't know query parameters in advance. Feature details can be found in a [TP here](https://github.com/quarkus-qe/quarkus-test-plans/pull/82). Test covers situation when query parameters are of primitive type, Java class or an array (supported by `MultivaluedMap`) and more than one formal parameter is annotated with `@RestQuery`.

Test Reactive Rest Client support of dynamic number of query parameters

---

http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/BookClient.java
http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/PlainBookResource.java
http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/ReactiveClientBookResource.java
http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/json/BookIdWrapper.java
http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/json/BookRepository.java
http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientIT.java

Backport of: [Test Reactive Rest Client support of dynamic number of query parameters](https://github.com/quarkus-qe/quarkus-test-suite/pull/719)

[2.7] Test Reactive Rest Client support of dynamic number of query parameters

---

quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateExtensionIT.java

This reverts commit fb912d2af7c6a987ee3626620b8e09d69806df6b. [Quarkus Issue 26014](https://github.com/quarkusio/quarkus/issues/26014) has been fixed, thus changes made in https://github.com/quarkus-qe/quarkus-test-suite/issues/693 should be reverted.

Revert "Disable Quarkus-cli create ext. scenario on Quarkus upstream"

---

service-discovery/stork/src/main/java/io/quarkus/ts/stork/PongReplicaResource.java
service-discovery/stork/src/main/java/io/quarkus/ts/stork/PongResource.java
service-discovery/stork/src/main/java/io/quarkus/ts/stork/PungResource.java

Tests fails as path called by Rest Client is not found. IMHO that's due to [this PR](https://github.com/quarkusio/quarkus/pull/26101). One way or another, adjusting resource/client paths fixes the issue. Daily run (Linux Native mode) are failing because of this issue. I read PR 26101 in a way that `/pung/` is cut to `/pung` and so is the `/pong/`.

Fix `NativeStorkServiceDiscoveryIT` and `StorkLoadBalancerIT`

---

quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateExtensionIT.java

Revert "Disable Quarkus-cli create extension scenario on Quarkus upstream"
This reverts commit fb912d2af7c6a987ee3626620b8e09d69806df6b.
Fixed in https://github.com/quarkusio/quarkus/pull/26130, we do not need to wait for Quarkus 2.10 release

Revert "Disable Quarkus-cli create extension scenario on Quarkus upstream"

---

sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/OracleDatabaseIT.java
sql-db/vertx-sql/src/main/java/io/quarkus/ts/vertx/sql/handlers/FailureHandler.java

Resolved upstream issues:
- https://github.com/quarkusio/quarkus/issues/24501
- https://github.com/quarkusio/quarkus/issues/24264
Follow-up to https://github.com/quarkus-qe/quarkus-test-suite/pull/563.

Enable disabled Oracle tests

---

.github/workflows/ci.yml
.github/workflows/daily.yaml

Quarkus Helm extension is coming on the following releases. This PR install Helm client on Github CI jobs

Add HelmClient to Github CI jobs

---

security/jwt/src/test/java/io/quarkus/ts/security/jwt/CookieJwtSecurityIT.java
security/jwt/src/test/java/io/quarkus/ts/security/jwt/Oauth2JwtSecurityIT.java

Review all fips incompatible scenarios and add the missing tag `fips-incompatible` if is required.
`smallrye-jwt-3.5.3` can sign/verify JWT tokens with Quarkus using the keys loaded directly from PEM but also from NSSDB  (RHEL8  + FIPS). This version of `smallrye-jwt` was only released on Quarkus upstream.

Add tag 'fips-incompatible' to quarkus JWT sceanrios

---

security/jwt/src/test/java/io/quarkus/ts/security/jwt/CookieJwtSecurityIT.java
security/jwt/src/test/java/io/quarkus/ts/security/jwt/Oauth2JwtSecurityIT.java

[2.7]  Add tag 'fips-incompatible' to quarkus JWT sceanrios

---

http/http-advanced-reactive/pom.xml
http/http-advanced/pom.xml
pom.xml

Bumps Quarkus Test Framework from 1.2.0.Beta1 to 1.2.0.Beta2 and adds `quarkus-test-service-grpc` to modules `http/http-advanced` and `http/http-advanced-reactive` as gRPC [has recently been decoupled](https://github.com/quarkus-qe/quarkus-test-framework/pull/515) from `quarkus-test-core`.

Bump Quarkus Test Framework from 1.2.0.Beta1 to 1.2.0.Beta2

---

messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/SslAlertMonitorIT.java

KafkaSSL scenario is also failing in FIPS mode and should be disabled from now.

Disable KafkaSSL on FIPS builds

---

http/http-advanced-reactive/pom.xml
http/http-advanced/pom.xml
pom.xml

Bumps Quarkus Test Framework from 1.1.0.Final to 1.1.1.Final and adds `quarkus-test-service-grpc` to modules `http/http-advanced` and `http/http-advanced-reactive` as gRPC [has recently been decoupled](https://github.com/quarkus-qe/quarkus-test-framework/pull/515) from `quarkus-test-core`.

[2.7] Bump Quarkus Test Framework from 1.1.0.Final to 1.1.1.Final

---

.github/workflows/daily.yaml
README.md
pom.xml

Default Mandrel image has been updated to 22.1
Ref: https://github.com/quarkusio/quarkus/commit/b6c2db24c48db432ce69a3abfae7bc7848daa873

Update mandrel docker image to 22.1

---

http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/NinetyNineBottlesOfBeerResource.java

verifies: https://github.com/quarkusio/quarkus/pull/25385
When we provide `MessageBodyWriter` that does not extend `ServerMessageBodyWriter`, related resource methods must be registered for the reflection. Previously, we had to do this manually, now it's done by the Quarkus for us.
Issue reproducer
1. go to Quarkus project
2. revert PR `git revert 224ec8c3e8e50930970e9c8b7316622ba898b0b9` and `mvn -Dquickly`
3. checkout this PR
4. `cd quarkus-test-suite/http/http-advanced-reactive`
5. run `mvn clean verify -Dit.test=HttpAdvancedReactiveIT -Dnative`

Test `MessageBodyWriters` resources works in native mode

---

monitoring/opentelemetry-reactive/src/test/java/io/quarkus/ts/opentelemetry/reactive/OpentelemetryReactiveIT.java
monitoring/opentelemetry/src/test/java/io/quarkus/ts/opentelemetry/OpentelemetryIT.java

Logic behind Rest Client span names has changed in https://github.com/quarkusio/quarkus/pull/26694, this reflect changes and fixes related test failures in daily CI.

Fix OpenTelemetry rest client span name

---

pom.xml

Keycloak 18 introduce some changes regarding keycloak mtls that needs to be investigated
related to: https://github.com/quarkus-qe/quarkus-test-framework/pull/523

Disable security/oidc-client-mutual-tls. Requires further investigation regarding keycloak 18

---

http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/HttpAdvancedReactiveIT.java
http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/HttpAdvancedIT.java
security/bouncycastle-fips/bcFipsJsse/src/test/java/io/quarkus/ts/security/bouncycastle/fips/jsse/BouncyCastleFipsJsseIT.java
spring/spring-data/src/test/java/io/quarkus/ts/spring/data/di/SpringDiTest.java
sql-db/panache-flyway/src/test/java/io/quarkus/ts/sqldb/panacheflyway/dbpool/AgroalPoolTest.java
super-size/many-extensions/src/test/java/io/quarkus/ts/many/extensions/ManyExtensionsIT.java

Some scenarios are failing on FIPS native mode. This PR will disable those scenarios until some valuable improvement from development / QE team 

Disable FIPS native failures - part II

---

.github/workflows/ci.yml
.github/workflows/daily.yaml
docker-build/pom.xml
docker-build/src/main/resources/application.properties
docker-build/src/test/java/io/quarkus/ts/docker/DockerBuildIT.java

This PR introduces some amendments based on these comments: https://github.com/quarkus-qe/quarkus-test-suite/pull/438
- Enable `DockerBuildIT` on native mode
- Rename scenario to something more meaningful
- Remove `quarkus.container-image.build=false` from GH CI

Remove `quarkus.container-image.build=false` from GH CI

---

security/jwt/pom.xml
security/jwt/src/main/java/io/quarkus/ts/security/jwt/GenerateJwtResource.java
security/jwt/src/main/java/io/quarkus/ts/security/jwt/GraphQLResource.java
security/jwt/src/test/java/io/quarkus/ts/security/jwt/BaseJwtSecurityIT.java
security/jwt/src/test/java/io/quarkus/ts/security/jwt/CookieJwtSecurityIT.java
security/jwt/src/test/java/io/quarkus/ts/security/jwt/DevModeJwtSecurityIT.java

Verifies: https://github.com/quarkusio/quarkus/issues/26748
In the Quarkus Smallrye GraphQL 2.10.2.Final and 2.10.1.Final, a route context had not been properly terminated. If BE received 3+ requests then 3rd (and every other) request were handled with the first request's route context (thus identity, headers etc. were incorrect). I could only reproduce this behavior with `mvn quarkus:dev` and `@QuarkusTest`, my best guess is that's due to [this hack](https://github.com/quarkusio/quarkus/blob/main/extensions/smallrye-graphql/deployment/src/main/java/io/quarkus/smallrye/graphql/deployment/SmallRyeGraphQLProcessor.java#L303), but I can be easily wrong!
Issue can be reproduced with `mvn clean verify -Dit.test=DevModeJwtSecurityGraphQLIT -Dquarkus.platform.version=2.10.2.Final`.
The issue …

SmallRye GraphQL - test route context in DEV mode is terminated

---

http/http-advanced-reactive/src/test/resources/keycloak-realm.json
http/http-advanced/src/test/resources/keycloak-realm.json

From now I didn't see this problem in other scenarios so I am not going to propagate this scope to all the realms/scenarios. Maybe is need it on `http/http-advanced` ( and reactive) because `quarkus-keycloak-authorization` is making some internal query that requires `uma_protection` (this is only an issue with Keycloak 18 +)

Keycloak 18 requires uma_protection scope on http/http_advanced

---

messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/StrimziKafkaAvroGroupIdIT.java
messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/StrimziKafkaAvroIT.java

Quarkus test framework already supports apicurio 2.2.3.Final
CodeRef: https://github.com/quarkus-qe/quarkus-test-framework/commit/6fa41715e2f498ca0681caddc3ceb4f52845410b#diff-97cd2066f40b4ab3ffc4cb3d0060d3da6a0c7f869b2f01757e9942760d704415L5

Re-enable some Kafka strimzi scenarios

---

security/keycloak-oidc-client-basic/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/basic/KeycloakOidcClientSecurityIT.java

We have a daily issue on daily build that looks that is related to Keycloak 18. Is a flaky test, but I could not reproduce on Keycloak 19.

Upgrade Keycloak 18 -> 19 on oidc client scenarios

---

security/keycloak-multitenant/src/test/java/io/quarkus/ts/security/keycloak/multitenant/KeycloakMultiTenantSecurityIT.java
security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/BaseOidcIT.java
security/keycloak-oidc-client-reactive/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/RequestHeadersIT.java

We have some flaky test on Keycloak 18 that looks like they are not happening on Keycloak 19. 
This PR moves all oidc scenarios to Keycloak 19

Moves oidc Keycloak scenarios to Keycloak 19

---

sql-db/vertx-sql/src/main/resources/application.properties

Native `Vertx-sql` compilation was failing due to unregistered class on Quarkus-oracle extension
Fixed by: https://github.com/quarkusio/quarkus/pull/27124

Fix vertx-sql native compilation error

---

.github/mvn-settings.xml

Motivation: we have a daily issue that we can't reproduce locally pointing to the latest Quarkus bits
Currently, we are compiling Quarkus latest code on Github CI and reusing these bits in the sub-sequence steps of the build. 
This PR disables download snapshots from Maven repositories

Github CI: disable Snapshot download

---

.github/workflows/daily.yaml
README.md
lifecycle-application/pom.xml
pom.xml

Updates GraalVM/Mandrel version to 22.2.

Update native image builders - use version 22.2

---

sql-db/vertx-sql/pom.xml

Ref Issue: https://github.com/quarkusio/quarkus/issues/27246
Disable native compilation on Vertx-sql due to an open issue that needs some clarification

Disable native compilation on Vertx-sql 

---

lifecycle-application/pom.xml

Related Conversatrion: https://github.com/quarkusio/quarkus/issues/26640
This PR upgrade lifecycle Quarkus app to the latest released version that is compatible with mandrel 22.2

Update lifecycle application Quarkus version to 2.11.2.Final

---

sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/OpenShiftMssqlDatabaseIT.java
sql-db/sql-app/src/test/resources/mssql.properties
sql-db/vertx-sql/src/test/java/io/quarkus/ts/vertx/sql/handlers/MssqlHandlerIT.java

Mssql driver has been updated: https://github.com/quarkusio/quarkus/commit/bccd9a1b3e125649cd0b91fb5e4d3af34bed92fc#diff-f1a3b4e6df9f63193be9632bac4425e522e28a3445149dfde5510c213f4a4493R8
This PR add a required property by the new driver version: `quarkus.datasource.jdbc.additional-jdbc-properties.trustServerCertificate`

Add missing Mssql required property to 'application.properties' file

---

sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/OpenShiftMssqlDatabaseIT.java
sql-db/sql-app/src/test/resources/mssql.properties

Mssql trustservercertificate required property must be in lower case otherwise doesn't work in OpenShift / K8s
Related to: https://github.com/quarkusio/quarkus/issues/27330

Mssql trustservercertificate required property must be in lower case

---

messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DevModeStrimziKafkaStreamIT.java

Kafka strimzi is also supported as DevService provider. This PR adds the coverage for this scenario
Doc: https://quarkus.io/guides/kafka#configuring-the-image

Add Kafka Strimzi DevService coverage

---

messaging/kafka-strimzi-avro-reactive-messaging/src/main/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/KStockPriceProducer.java
messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/StrimziKafkaAvroGroupIdIT.java

Sometimes we are getting errors from CI because a Kafka consumer is reading more events than should be read.
This scenario shares some code with other cases where events are generated by a cronjob. This commit will make
more reliable the group ID scenario.

Improve Strimzi Kafka group ID stability (flaky patch)

---

messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/BaseKafkaAvroIT.java

Batch processing sometimes fails because it consumes all events in a single request and then
there are no more events for the following request. This commit tries to make more reliable
this scenario by expecting just one request with more than one event.

Improve Strimzi Kafka AVRO stability (flaky patch)

---

http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/OpenShiftHttpAdvancedReactiveIT.java
http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/OpenShiftHttpAdvancedIT.java

Keycloak was updated to 19 version but some OCP scenarios were still using the old way to start Keycloak. This PR fix these scenarios. 

Fix Keycloak 19 OCP scenarios

---

http/http-advanced/src/main/java/io/quarkus/ts/http/advanced/RequestDetailsResource.java
http/http-advanced/src/main/resources/application.properties
http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/BaseHttpAdvancedIT.java

Server and client address checks
`http-advanced-reactive` doesn't need to be enhanced because the test is working with data from `io.vertx.core.http.HttpServerRequest` which is not JAX-RS specific.

Server and client address checks

---

pom.xml

Bump quarkus.qe.framework to version 1.2.0.Beta5

Bump quarkus.qe.framework to version 1.2.0.Beta5

---

pom.xml
security/keycloak-multitenant/src/test/java/io/quarkus/ts/security/keycloak/multitenant/KeycloakMultiTenantSecurityIT.java
security/keycloak-oidc-client-basic/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/basic/KeycloakOidcClientSecurityIT.java
security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/BaseOidcIT.java
security/keycloak-oidc-client-reactive/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/RequestHeadersIT.java
security/oidc-client-mutual-tls/src/test/java/io/quarkus/ts/security/oidcclient/mtls/IncorrectKsFileTypeOidcMtlsIT.java
security/oidc-client-mutual-tls/src/test/java/io/quarkus/ts/security/oidcclient/mtls/JksOidcMtlsIT.java
security/oidc-client-mutual-tls/src/test/java/io/quarkus/ts/security/oidcclient/mtls/Pkcs12OidcMtlsIT.java

Keycloak 19 is used by default on Quarkus test framework `1.2.0.Beta5`. This PR remove all hardcode references to Keycloak 19 docker image

Remove hardcode keycloak 19 docker image references

---

http/graphql-telemetry/pom.xml
http/graphql-telemetry/src/test/java/io/quarkus/ts/http/graphql/telemetry/GraphQLTelemetryIT.java
http/graphql/src/test/java/io/quarkus/ts/http/graphql/GraphQLTracingIT.java
http/vertx-web-client/pom.xml
http/vertx-web-client/src/main/resources/application.properties
http/vertx-web-client/src/test/java/io/quarkus/ts/http/vertx/webclient/VertxWebClientIT.java
http/vertx-web-client/src/test/resources/application.properties
monitoring/microprofile-opentracing/src/test/java/io/quarkus/ts/microprofile/opentracing/MicroProfileIT.java
monitoring/opentelemetry-reactive/pom.xml
monitoring/opentelemetry-reactive/src/test/java/io/quarkus/ts/opentelemetry/reactive/OpentelemetryReactiveIT.java
monitoring/opentelemetry/pom.xml
monitoring/opentelemetry/src/test/java/io/quarkus/ts/opentelemetry/OpentelemetryIT.java
monitoring/opentracing-reactive-grpc/src/test/java/io/quarkus/ts/monitoring/opentracing/reactive/grpc/AbstractTraceIT.java
pom.xml

Replaces OpenTelemetry Jaeger exporter with a gRPC OTPL exporter. The Quarkus Test Framework version is updated as the changes as this change is only enabled by the latest release.

Replace OpenTelemetry Jaeger exporter with gRPC OTPL exporter

---

.github/workflows/daily.yaml
README.md
pom.xml

Replace `ubi-quarkus-native-image:22.2-java11` by `ubi-quarkus-native-image:22.2-java17`
Remove `ubi-quarkus-mandrel:22.2-java11`

Remove JDK11 docker native image references

---

pom.xml

Bumps Quarkus QE FW from 1.2.0.Beta6 to 1.2.0.Beta9. This should be an answer to (most) of our OpenShiftClient issues.

Bump Quarkus QE FW from 1.2.0.Beta6 to 1.2.0.Beta9

---

README.md
lifecycle-application/pom.xml
pom.xml

Wherever possible.
Red Hat registry images unchanged.
Other images synchronized with Quarkus upstream or updated to the latest
applicable version.
Note to `docker.io/infinispan/server:13.0`: there is a newer tag `14.0`,
but `quarkus-infinispan-client` uses Infinispan `13.0.10` which does not
work with server version `14.0`.
New versions inspected using `mvn versions:display-dependency-updates`.
Maven plugins updated to latest available version.
Faststart image has faster startup in exchange for bigger image size.
See
https://github.com/gvenzl/oci-oracle-xe/pkgs/container/oracle-xe#image-flavors.

Update dependencies and images to latest versions

---

pom.xml

Bumps Test Framework from 1.2.0.Beta11 to 1.2.0.Beta12, so we could put issues with `OpenShiftClient` behind us.

Bump Test Framework from 1.2.0.Beta11 to 1.2.0.Beta12

---

config/src/main/java/io/quarkus/ts/configmap/api/server/HelloConfigProperties.java
config/src/main/java/io/quarkus/ts/configmap/api/server/HelloResource.java
config/src/main/resources/application.properties
config/src/test/java/io/quarkus/ts/configmap/api/server/OpenShiftBaseConfigIT.java
config/src/test/java/io/quarkus/ts/configmap/api/server/OpenShiftConfigSourcePriorityIT.java
config/src/test/java/io/quarkus/ts/configmap/api/server/OpenShiftFailOnMissingConfigIT.java
config/src/test/resources/config-source-priority.properties
config/src/test/resources/configmap-yaml.yaml
config/src/test/resources/configmap-yml.yaml
config/src/test/resources/secret-yml.yaml

In addition to existing test coverage of the Quarkus Kubernetes Config, we newly test that:
1. Properties retrieved from ConfigMaps and Secrets created from an `application.yml` file.
2. Priority of obtained properties:
1. Properties defined in Secrets have higher priority than same properties defined in Config Maps.
2. When multiple ConfigMaps (or Secrets) are used, ConfigMaps (or Secrets) defined later in the list have a higher priority that ConfigMaps defined earlier in the list.
3. The properties obtained from the ConfigMaps and Secrets have a higher priority than (i.e. they override) any properties of the same name that are found in application.properties (or the YAML equivalents), but they have lower priority than properties set via Environment Variables or Java System Properties. …

Test Kubernetes Config sources prioritization

---

README.md
monitoring/opentelemetry-reactive/README.md
monitoring/opentelemetry/README.md

Jaeger Exporter will be moved to Quarkiverse in favor of OLTP
This PR remove any reference to `quarkus-opentelemetry-exporter-jaeger`
TP: https://github.com/quarkus-qe/quarkus-test-plans/pull/102

Remove deprecated Jaeger exporter references

---

messaging/kafka-confluent-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/BaseKafkaAvroGroupIdIT.java
messaging/kafka-confluent-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/BaseKafkaAvroIT.java
messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/BaseKafkaAvroGroupIdIT.java
messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/BaseKafkaAvroIT.java

In daily runs, `ConfluentKafkaAvroGroupIdIT`, `ConfluentKafkaAvroIT`, `StrimziKafkaAvroIT` and `StrimziKafkaAvroGroupIdIT`, `DevModeApicurioIT` and others  are sometimes failing. I can't reproduce issues locally (over 50 successful runs in row), neither I can be sure what's the root cause without more information. Now we log state of relevant variables. I'll revert the PR in a week time (provided tests are going to fail).

Add debug logging to Kafka Avro Reactive Messaging tests

---

.github/pull_request_template.md

Add a hint to the PR template that if you wanna run OCP tests, you must type a comment `run tests`. That's going to be necessary as I adjusted JVM and native Jenkins jobs (please see the PR in the Jenkins project for more info).

Template hint for OCP run

---

messaging/kafka-confluent-avro-reactive-messaging/src/main/java/io/quarkus/ts/messaging/kafka/KStockPriceProducer.java
messaging/kafka-confluent-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/ConfluentKafkaAvroGroupIdIT.java
messaging/kafka-strimzi-avro-reactive-messaging/src/main/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/KStockPriceProducer.java
messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/StrimziKafkaAvroGroupIdIT.java

Fixes
- `testAlertMonitorEventStream` in `kafka-confluent-avro-reactive-messaging`. This test scheduled generation of events to the midnight (when also our CI runs) and therefore test results sometimes (depending on when CI started) had 100 more events than expected. I think the intention of scheduling this to midnight was to disable generation of events in certain tests.
- ```ScheduledInvoker_generate_c9e4876862861cd03eb297791b102d51bdc3ba72, cron=* * * * * ?]: java.util.concurrent.CompletionException: java.lang.RuntimeException: Error injecting org.eclipse.microprofile.reactive.messaging.Emitter<io.quarkus.ts.messaging.kafka.StockPrice> io.quarkus.ts.messaging.strimzi.kafka.reactive.KStockPriceProducer.emitter``` We tried to emit events before `source-stock-price` channel was ready, …

Fix flaky Kafka tests

---

service-discovery/stork-custom/pom.xml

Looks that `quarkus-extension-processor` is no longer needed.
Maybe was a leftover because I could not find any reference on the original documentation: http://smallrye.io/smallrye-stork/1.2.0/quarkus/

CustomStork doesn't require 'quarkus-extension-processor' annotation processor path any longer

---

README.md
http/graphql-telemetry/pom.xml
http/vertx-web-client/pom.xml
monitoring/opentelemetry-reactive/README.md
monitoring/opentelemetry-reactive/pom.xml
monitoring/opentelemetry/README.md
monitoring/opentelemetry/pom.xml

https://github.com/quarkusio/quarkus/pull/28487 moved `quarkus-opentelemetry-exporter-otlp` dependency to the `quarkus-opentelemetry`. This PR fixes build and reflect the move in our TS.
https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.14#opentelemetry-exporters-moved

Replace `quarkus-opentelemetry-exporter-otlp` dependency with `quarkus-opentelemetry`

---

sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/openshift/OpenShiftHibernateReactiveMsSQLIT.java
sql-db/reactive-rest-data-panache/src/test/java/io/quarkus/ts/reactive/rest/data/panache/OpenShiftMssqlPanacheResourceIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/OpenShiftMssqlDatabaseIT.java

Mssql database is running as a non-root container but requires a non-preallocated K8s / OCP user, basically, run as `anyuid`. 

Re-enable mssql scenario

---

pom.xml

There is an issue on Upstream related to dekorate that makes this module fails on compile time
Ref: https://github.com/quarkiverse/quarkus-helm/issues/114

Remove helm-minimum scenarios from root-modules

---

test-tooling/pact/pom.xml
test-tooling/pact/src/test/java/io/quarkus/ts/http/pact/ProviderPactTest.java

Update Pact to supported 4.1 version which uses V3 specification
Details in https://github.com/pact-foundation/pact-jvm#supported-jdk-and-specification-versions
Also fixes some issues reported by Snyk.io

Update Pact to supported 4.1

---

pom.xml

Currently, we are not supporting Quarkus/helm due to upstream extension instability. 

Remove Quarkus-helm dependency from main pom

---

http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/LargeFileHandlingIT.java

Related to: https://github.com/quarkus-qe/quarkus-test-suite/pull/884
You were right @michalvavrik :) also, we need to disable these two scenarios due an upstream issue

Disable LargeFilesIT: multiplart form data request body is always null

---

config/src/main/java/io/quarkus/ts/configmap/api/server/secrets/BuiltConfigResource.java
config/src/main/java/io/quarkus/ts/configmap/api/server/secrets/ConfigInterceptorFactory.java
config/src/main/java/io/quarkus/ts/configmap/api/server/secrets/InjectedConfigResource.java
config/src/main/java/io/quarkus/ts/configmap/api/server/secrets/InjectedProperitesResource.java
config/src/main/java/io/quarkus/ts/configmap/api/server/secrets/SecretResource.java
config/src/main/resources/META-INF/services/io.smallrye.config.ConfigSourceInterceptorFactory
config/src/main/resources/application.properties
config/src/test/java/io/quarkus/ts/configmap/api/server/ConfigIT.java

Issue: https://issues.redhat.com/browse/QUARKUS-2479
Test plans: https://github.com/quarkus-qe/quarkus-test-plans/pull/105

Add support for marking configs as secret

---

config/src/main/java/io/quarkus/ts/configmap/api/server/secrets/BuiltConfigResource.java
config/src/main/java/io/quarkus/ts/configmap/api/server/secrets/ConfigInterceptorFactory.java
config/src/main/java/io/quarkus/ts/configmap/api/server/secrets/InjectedConfigResource.java
config/src/main/java/io/quarkus/ts/configmap/api/server/secrets/InjectedProperitesResource.java
config/src/main/java/io/quarkus/ts/configmap/api/server/secrets/SecretResource.java
config/src/main/resources/META-INF/services/io.smallrye.config.ConfigSourceInterceptorFactory
config/src/main/resources/application.properties
config/src/test/java/io/quarkus/ts/configmap/api/server/ConfigIT.java

Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/886

[2.13] Add support for marking configs as secret

---

pom.xml

* This update should address exceptions in cleanup for operator managed resources.
Depends on https://github.com/quarkus-qe/quarkus-test-framework/pull/609

Update Quarkus QE test framework to 1.2.0.Beta15

---

http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/files/FileResource.java

Some resources such as http/restclient reactive "FileResource" creates some files on the filesystem. This commit ensures compatibility between windows and other OS.

Windows friendly syntax on http/restclient reactive

---

.github/workflows/daily.yaml
lifecycle-application/pom.xml
pom.xml

`quay.io/quarkus/ubi-quarkus-mandrel:22.2-java11` -> `quay.io/quarkus/ubi-quarkus-mandrel:22.3-java17`

Update mandrel image to 22.3-java17

---

.github/ci-prerequisites.sh

Remove more unused docker images to free up space (14GB)
Getting from
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        84G   54G   30G  65% /
```
to
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/root**        84G   40G   44G  48% /
```

Remove more unused docker images to free up space

---

pom.xml

Bump quarkus-qpid-jms from 0.38.0 to 0.39.0

Bump quarkus-qpid-jms from 0.38.0 to 0.39.0

---

security/keycloak-oidc-client-reactive-extended/src/test/resources/logout.properties

Backport:
[Remove a logout debug log that was leftover](https://github.com/quarkus-qe/quarkus-test-suite/pull/921) | 373e4fdd8fd78183cbcf67e8104996d9deb330f2

[2.13] Remove a logout debug log that was leftover

---

security/keycloak-oidc-client-reactive-extended/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/ping/clients/AutoAcquireTokenPongClient.java

Use OidcClientFilter which is available for reactive since 2.13.2.Final
`RequestHeadersClient` from keycloak-oidc-client-reactive-basic module keeps using `@RegisterProvider(OidcClientRequestReactiveFilter.class)`

Use OidcClientFilter which is available for reactive since 2.13.2.Final

---

http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/HeadersResource.java
http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/PathSpecificHeadersResource.java
http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/HeadersIT.java
http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/OpenShiftHeadersIT.java
http/http-advanced-reactive/src/test/resources/headers.properties
http/http-advanced/src/main/java/io/quarkus/ts/http/advanced/HeadersResource.java
http/http-advanced/src/main/java/io/quarkus/ts/http/advanced/PathSpecificHeadersResource.java
http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/HeadersIT.java
http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/OpenShiftHeadersIT.java
http/http-advanced/src/test/resources/headers.properties

Tests of additional HTTP headers and additional HTTP headers per path (QUARKUS-2490).
Coverage for both non-reactive and reactive execution + OpenShift.
See also
https://quarkus.io/guides/http-reference#additional-http-headers.

Add additional HTTP headers coverage

---

sql-db/panache-flyway/src/test/java/io/quarkus/ts/sqldb/panacheflyway/dbpool/AgroalTestProfile.java

Property quarkus.datasource.devservices was deprecated
`quarkus.datasource.devservices` -> `quarkus.datasource.devservices.enabled`

Property quarkus.datasource.devservices was deprecated in favor of quarkus.datasource.devservices.enabled

---

messaging/infinispan-grpc-kafka/pom.xml
messaging/kafkaSSL/pom.xml
monitoring/micrometer-prometheus-kafka/pom.xml
monitoring/opentracing-reactive-grpc/pom.xml
monitoring/opentracing-reactive-grpc/src/main/java/io/quarkus/ts/monitoring/opentracing/reactive/grpc/ping/ServerSentEventsPingResource.java
monitoring/opentracing-reactive-grpc/src/main/java/io/quarkus/ts/monitoring/opentracing/reactive/grpc/ping/clients/ServerSentEventsPongClient.java
monitoring/opentracing-reactive-grpc/src/test/java/io/quarkus/ts/monitoring/opentracing/reactive/grpc/AbstractTraceIT.java

`quarkus-resteasy-mutiny` was deprecated on Quarkus 2.13.x
Replace `quarkus-resteasy-mutiny` by `quarkus-resteasy-reactive`

quarkus-resteasy-mutiny is deprecated, replace by quarkus-resteasy-reactive

---

http/jaxrs-reactive/src/main/resources/application.properties
http/jaxrs-reactive/src/test/java/io/quarkus/ts/http/jaxrs/reactive/OpenShiftExecutionModelIT.java

Large single streams of data are failing on OCP/native mode. Is not related to compression feature. 
This issue requires further investigation. 
Related to: https://github.com/quarkusio/quarkus/issues/29642

Reduce generated byte[] on compression scenario due to an out of memory exception on native / OCP

---

http/jaxrs-reactive/src/main/resources/application.properties
http/jaxrs-reactive/src/test/java/io/quarkus/ts/http/jaxrs/reactive/OpenShiftExecutionModelIT.java

Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/933

[2.13] Reduce generated bute[] on compression scenario due to an out of memory exception on native / OCP

---

http/jaxrs-reactive/src/main/resources/application.properties

OpenShiftHttpCachingIT is failing in native mode in both RHBQ 2.13 and upstream as `QUARKUS_OPTS` are enclosed as one value in double quotes, I've explained it here https://github.com/quarkusio/quarkus/issues/29642#issuecomment-1341644852. Bug was added to our TS in https://github.com/quarkus-qe/quarkus-test-suite/pull/933.

Fix OpenShiftHttpCachingIT in native mode

---

README.md
security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/LogoutSinglePageAppFlowIT.java
security/keycloak-oidc-client-reactive-extended/src/test/resources/kc-logout-realm.json
security/keycloak-oidc-client-reactive-extended/src/test/resources/logout.properties

Enables PKCE for logout SPA flow test in `LogoutSinglePageAppFlowIT` and `OpenShiftOidcSinglePageAppLogoutFlowIT`. Reasoning explained in depth in https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-2491.md. We know tests verifies PKCE as with changes in `kc-logout-realm.json` and without enabling PKCE in `application.properties`, tests are failing.

Enable PKCE for reactive logout SPA flow test

---

messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DevModeStrimziKafkaStreamIT.java

Due to https://github.com/quarkusio/quarkus/commit/0f3a9384a0da9ca149b40a4b88f8713fc0a80b46, now `quarkus.kafka.devservices.provider` should be defined, so `quarkus.kafka.devservices.image-name` is not really needed.
Otherwise, there may be an issue, as the default `provider` is set to `redpanda` instead of `strimzi`. See [[1]](https://github.com/quarkusio/quarkus/issues/29954)

`quarkus.kafka.devservices.provider` property should be now used for Kafka dev services

---

README.md
http/jaxrs-reactive/src/main/java/io/quarkus/ts/http/jaxrs/reactive/MediaTypeResource.java
http/jaxrs-reactive/src/test/java/io/quarkus/ts/http/jaxrs/reactive/MediaTypeSelectionIT.java

Tests [matching requests to resource methods](https://jakarta.ee/specifications/restful-ws/3.1/jakarta-restful-ws-spec-3.1.html#mapping_requests_to_java_methods) with multiple [media types](https://www.iana.org/assignments/media-types/media-types.xhtml). I combined it with [content negotiation and wildcards](https://www.rfc-editor.org/rfc/rfc9110.html#section-12.4.2) as they are handled by the same [MediaTypeMapper](https://github.com/quarkusio/quarkus/blob/main/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/MediaTypeMapper.java#L38). Main purpose of this PR is to verify https://github.com/quarkusio/quarkus/issues/29732, intention is not to cover all scenarios (f.e. I didn't cover HTTP status 416) as these situations are …

RESTEasy Reactive - Test selecting from multiple media types

---

README.md
http/jaxrs-reactive/src/main/java/io/quarkus/ts/http/jaxrs/reactive/MultipartBody.java
http/jaxrs-reactive/src/main/java/io/quarkus/ts/http/jaxrs/reactive/MultipartResource.java
http/jaxrs-reactive/src/main/java/io/quarkus/ts/http/jaxrs/reactive/client/MultipartService.java
http/jaxrs-reactive/src/main/resources/application.properties
http/jaxrs-reactive/src/test/java/io/quarkus/ts/http/jaxrs/reactive/MediaTypeSelectionIT.java
http/jaxrs-reactive/src/test/java/io/quarkus/ts/http/jaxrs/reactive/RESTEasyReactiveMultipartIT.java
http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/files/FileClient.java
http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/files/FileResource.java

Verifies: https://github.com/quarkusio/quarkus/issues/29725
Test plan PR: https://github.com/quarkus-qe/quarkus-test-plans/pull/120
Minor commits:
- [Tag MediaTypeSelectionIT with QUARKUS-2743](https://github.com/quarkus-qe/quarkus-test-suite/commit/4bcee563563f9a1d9deb009d5eb4069c441f268e) - adds a tag over tests created by https://github.com/quarkus-qe/quarkus-test-suite/pull/960 as [ticket QUARKUS-2743](https://issues.redhat.com/browse/QUARKUS-2743) didn't exist when I was writing the test
- [Drop deprecated @MultipartForm annotation, it is surplus to requirements](https://github.com/quarkus-qe/quarkus-test-suite/commit/a3d897abdc9ccb0be07d1161c4136d7d6f209b75) - the annotation has been deprecated and will be removed in the future version

Test handling a multipart request part as a file based on the content-type

---

security/keycloak-oidc-client-extended/src/test/resources/logout.properties
security/keycloak-oidc-client-reactive-extended/src/test/resources/logout.properties

As part of https://github.com/quarkusio/quarkus/pull/29692, since no "origin" is longer supported out of the box by quarkus, we need to specifically mentioned this in our TS, by using `quarkus.http.cors.origins` property

Do not support any Origin by default if CORS is enabled

---

http/jaxrs-reactive/src/main/java/io/quarkus/ts/http/jaxrs/reactive/client/MultipartService.java
http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/files/FileResource.java

[Here I dropped occurrence in 4 files](https://github.com/quarkus-qe/quarkus-test-suite/pull/961/commits/a3d897abdc9ccb0be07d1161c4136d7d6f209b75) of deprecated `@MultipartForm` in RESTEasy Reactive modules. [I made mistake to think they are not used](https://github.com/quarkus-qe/quarkus-test-suite/pull/961#issuecomment-1363850598) at all as I was searching in compiled source code and code occurence/ text searching didn't work there. Apologies @rsvoboda . Now I put the annotation back to 2 files as user still might use it, even though it should have no affect according to annotation JavaDoc. I can see one function in Quarkus relevant to reverts in `org.jboss.resteasy.reactive.common.processor.EndpointIndexer#extractParameterInfo`. We could use `@BeanParam`, however all relevant DTOs have …

Partially revert 'Test handling a multipart request part as a file based on the content-type'

---

.github/workflows/ci.yml

Fix based on the example https://github.com/tj-actions/changed-files#usage.

Fix changed modules detection in PRs and run only necessary CI modules

---

.github/workflows/ci.yml

- reverts https://github.com/quarkus-qe/quarkus-test-suite/pull/967 (I made mistake)
- fixes step output according to https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs#overview
Proof that this fixes issue is here https://github.com/michalvavrik/quarkus-test-suite/pull/3.

Fix detection of changes in the PR by correcting step output

---

pom.xml
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/XAPostgresIT.java

Provides coverage for https://issues.redhat.com/browse/QUARKUS-2742

Test Extended Architecture (XA) connection

---

sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DB2DatabaseIT.java

DB2 driver and Oracle have some internal conflicts in native mode. 
Related to: https://github.com/quarkusio/quarkus/issues/30176

Disable DB2 on native mode due to a reported error

---

lifecycle-application/pom.xml
lifecycle-application/src/main/java/io/quarkus/ts/lifecycle/Main.java
lifecycle-application/src/test/java/io/quarkus/ts/lifecycle/AlphabeticallyFirstTest.java
lifecycle-application/src/test/java/io/quarkus/ts/lifecycle/HelloMainTest.java

Required for https://issues.redhat.com/browse/QUARKUS-2789.
Names of the tests are important, see the first comment to the issue

Coverage for mixing @QuarkusMainTest and @QuarkusTest in the same package

---

lifecycle-application/src/test/java/io/quarkus/ts/lifecycle/OpenShiftLifecycleApplicationIT.java
pom.xml

Motivation:
- https://github.com/quarkus-qe/quarkus-test-framework/pull/625 - merged in FW `1.2.0.Beta16`, fixes interop OCP failures.

[2.13] Bump quarkus.qe.framework.version from 1.2.0.Beta13 to 1.2.0.Final

---

http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/PlainRootResource.java
http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/ReactiveClientRootResource.java
http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/SubResourcesClient.java
http/rest-client-reactive/src/main/resources/modern.properties
http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientIT.java

Verify that Reactive RestClient `@PathParam` parameters are applied to the web target before passing it to the sub-resource instance.

Reactive Rest Client: Process paths before sub resources

---

README.md
nosql-db/infinispan/pom.xml
nosql-db/infinispan/src/main/java/io/quarkus/ts/infinispan/client/FirstCounterResource.java
nosql-db/infinispan/src/main/java/io/quarkus/ts/infinispan/client/InfinispanClientApp.java
nosql-db/infinispan/src/main/java/io/quarkus/ts/infinispan/client/InfinispanCounterResource.java
nosql-db/infinispan/src/main/java/io/quarkus/ts/infinispan/client/SecondCounterResource.java
nosql-db/infinispan/src/main/resources/application.properties
nosql-db/infinispan/src/main/resources/cache-configuration.xml
nosql-db/infinispan/src/test/java/io/quarkus/ts/infinispan/DevModeInfinispanIT.java
nosql-db/infinispan/src/test/java/io/quarkus/ts/infinispan/InfinispanIT.java
pom.xml

Adds coverage for a bug, encountered in https://issues.redhat.com/browse/QUARKUS-2747.
The separate module was created, since `application.properties ` files for this scenario and for scenarios in `infinispan` module are not compatible and we cannot customise them with per-app granularity, because of https://github.com/quarkus-qe/quarkus-test-framework/issues/174.
The module has as little coverage as possible to minimise running time and consumed resources.

Add minimal coverage for local Infinispan and for working with DevMode

---

monitoring/micrometer-prometheus-oidc/src/test/java/io/quarkus/ts/micrometer/oidc/BaseMicrometerOidcSecurityIT.java
monitoring/micrometer-prometheus/src/test/java/io/quarkus/ts/micrometer/prometheus/HttpServerMetricsIT.java
monitoring/micrometer-prometheus/src/test/java/io/quarkus/ts/micrometer/prometheus/MicroProfileApiIT.java

See https://github.com/quarkusio/quarkus/issues/30343 for details

Fix daily runs: Adapt to the new format of Prometheus metrics

---

README.md
external-applications/src/test/java/io/quarkus/ts/external/applications/TodoDemoIT.java
http/http-advanced-reactive/src/main/resources/application.properties
http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/DevModeHttpsIT.java
lifecycle-application/src/main/java/io/quarkus/ts/lifecycle/Main.java
lifecycle-application/src/test/java/io/quarkus/ts/lifecycle/AlphabeticallyFirstTest.java
lifecycle-application/src/test/java/io/quarkus/ts/lifecycle/HelloMainTest.java
nosql-db/infinispan/pom.xml
nosql-db/infinispan/src/main/java/io/quarkus/ts/infinispan/client/FirstCounterResource.java
nosql-db/infinispan/src/main/java/io/quarkus/ts/infinispan/client/InfinispanClientApp.java
nosql-db/infinispan/src/main/java/io/quarkus/ts/infinispan/client/InfinispanCounterResource.java
nosql-db/infinispan/src/main/java/io/quarkus/ts/infinispan/client/SecondCounterResource.java
nosql-db/infinispan/src/main/resources/application.properties
nosql-db/infinispan/src/main/resources/cache-configuration.xml
nosql-db/infinispan/src/test/java/io/quarkus/ts/infinispan/DevModeInfinispanIT.java
nosql-db/infinispan/src/test/java/io/quarkus/ts/infinispan/InfinispanIT.java
pom.xml

depends on: https://github.com/quarkus-qe/quarkus-test-suite/pull/997
Backport of these PRs:
https://github.com/quarkus-qe/quarkus-test-suite/pull/987 (Verify, that uberjar can be built even with empty suffix)
https://github.com/quarkus-qe/quarkus-test-suite/pull/986 (Verify, that dev ui page can be updated via "browser" and HTTPS)
https://github.com/quarkus-qe/quarkus-test-suite/pull/984 (Add minimal coverage for local Infinispan and for working with DevMode)
https://github.com/quarkus-qe/quarkus-test-suite/pull/979 (Coverage for mixing @QuarkusMainTest and @QuarkusTest in the same package )

[2.13] backports for uberjar, Dev ui with HTTPS, local infinispan and mixing of tests

---

http/http-advanced/src/main/java/io/quarkus/ts/http/advanced/HelloResource.java
http/http-advanced/src/main/java/io/quarkus/ts/http/advanced/LocalCustomContext.java
http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/BaseHttpAdvancedIT.java

When firing an async CDI Event, the requestScope context from the emitter briefly exists for the observer and is then terminated. This commit is a reproducer of this scenario that happens on `Quarkus 2.13.0.Final`
**How to reproduce**
```mvn clean verify -Dit.test=HttpAdvancedIT#keepRequestScopeValuesAfterEventPropagation -Dquarkus.platform.version=2.13.0.Final -Dquarkus.platform.group-id=io.quarkus.platform```

New Scenario: RequestScope custom context was removed after `javax.enterprise` event propagation

---

http/http-advanced/src/main/java/io/quarkus/ts/http/advanced/HelloResource.java
http/http-advanced/src/main/java/io/quarkus/ts/http/advanced/LocalCustomContext.java
http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/BaseHttpAdvancedIT.java
http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/ResourceAndSubResourcesClient.java
http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/PlainBookResource.java
http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/PlainComplexClientResource.java
http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/ReactiveClientBookResource.java
http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/ReactivecomplexClientResource.java
http/rest-client-reactive/src/main/resources/modern.properties
http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientIT.java
pom.xml
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/XAPostgresIT.java

Backport of
[Test Extended Architecture (XA) connection](https://github.com/quarkus-qe/quarkus-test-suite/pull/971)
[Improve "process paths before sub resources" scenario](https://github.com/quarkus-qe/quarkus-test-suite/pull/995)
[New Scenario: RequestScope custom context was removed after `javax.enterprise` event propagation](https://github.com/quarkus-qe/quarkus-test-suite/pull/996)

[2.13] coverage of Architecture (XA) connection, Http Restclient path and subpath params and Request Scope event Propagation

---

http/graphql/src/test/java/io/quarkus/ts/http/graphql/GraphQLTracingIT.java
monitoring/microprofile-opentracing/src/test/java/io/quarkus/ts/microprofile/opentracing/MicroProfileIT.java
monitoring/opentracing-reactive-grpc/src/test/java/io/quarkus/ts/monitoring/opentracing/reactive/grpc/AbstractTraceIT.java

Explicit useOtlpCollector for JaegerContainer
Preparation for https://github.com/quarkus-qe/quarkus-test-framework/issues/653 when the default will be changed
Needed just for main branch.

Explicit useOtlpCollector for JaegerContainer

---

monitoring/opentelemetry-reactive/pom.xml
monitoring/opentelemetry-reactive/src/main/java/io/quarkus/ts/opentelemetry/reactive/grpc/GrpcPingResource.java
monitoring/opentelemetry-reactive/src/main/java/io/quarkus/ts/opentelemetry/reactive/grpc/GrpcPongResource.java
monitoring/opentelemetry-reactive/src/main/java/io/quarkus/ts/opentelemetry/reactive/grpc/GrpcPongService.java
monitoring/opentelemetry-reactive/src/main/java/io/quarkus/ts/opentelemetry/reactive/sse/ServerSentEventsPingResource.java
monitoring/opentelemetry-reactive/src/main/java/io/quarkus/ts/opentelemetry/reactive/sse/ServerSentEventsPongClient.java
monitoring/opentelemetry-reactive/src/main/java/io/quarkus/ts/opentelemetry/reactive/sse/ServerSentEventsPongResource.java
monitoring/opentelemetry-reactive/src/main/java/io/quarkus/ts/opentelemetry/reactive/traceable/TraceableResource.java
monitoring/opentelemetry-reactive/src/main/proto/pong.proto
monitoring/opentelemetry-reactive/src/main/resources/application.properties
monitoring/opentelemetry-reactive/src/test/java/io/quarkus/ts/opentelemetry/reactive/OpenTelemetryGrpcIT.java
monitoring/opentelemetry-reactive/src/test/java/io/quarkus/ts/opentelemetry/reactive/OpenTelemetrySseIT.java
monitoring/opentelemetry/pom.xml
monitoring/opentelemetry/src/main/java/io/quarkus/ts/opentelemetry/grpc/GrpcPingResource.java
monitoring/opentelemetry/src/main/java/io/quarkus/ts/opentelemetry/grpc/GrpcPongResource.java
monitoring/opentelemetry/src/main/java/io/quarkus/ts/opentelemetry/grpc/GrpcPongService.java
monitoring/opentelemetry/src/main/java/io/quarkus/ts/opentelemetry/sse/ServerSentEventsPingResource.java
monitoring/opentelemetry/src/main/java/io/quarkus/ts/opentelemetry/sse/ServerSentEventsPongClient.java
monitoring/opentelemetry/src/main/java/io/quarkus/ts/opentelemetry/sse/ServerSentEventsPongResource.java
monitoring/opentelemetry/src/main/java/io/quarkus/ts/opentelemetry/traceable/TraceableResource.java
monitoring/opentelemetry/src/main/proto/pong.proto
monitoring/opentelemetry/src/main/resources/application.properties
monitoring/opentelemetry/src/test/java/io/quarkus/ts/opentelemetry/OpenTelemetryGrpcIT.java
monitoring/opentelemetry/src/test/java/io/quarkus/ts/opentelemetry/OpenTelemetrySseIT.java

gRPC and SSE coverage for OpenTelemetry
Partial port of the coverage from https://github.com/quarkus-qe/quarkus-test-suite/tree/main/monitoring/opentracing-reactive-grpc + small rework.

gRPC and SSE coverage for OpenTelemetry

---

security/vertx-jwt/src/main/java/io/quarkus/ts/security/vertx/Application.java
security/vertx-jwt/src/main/java/io/quarkus/ts/security/vertx/CommonApplication.java
security/vertx-jwt/src/main/java/io/quarkus/ts/security/vertx/model/HelloEvent.java
security/vertx-jwt/src/test/java/io/quarkus/ts/security/vertx/BladeRunnerHandlerIT.java

https://issues.redhat.com/browse/QUARKUS-2746
ConsumeEvent annotation should be invoked once when the generic parent class
has an abstract method for it.
How to reproduce:
`mvn clean verify -Dit.test=BladeRunnerHandlerIT#verifyConsumeEventAnnotation -Dquarkus.platform.version=2.14.0.Final -Dquarkus.platform.group-id=io.quarkus.platform`

Add coverage to eventbus '@ConsumeEvent' annotation

---

http/vertx-web-client/pom.xml

Drop duplicated definition of quarkus-opentelemetry
ATM one gets following warning in console:
```
Warning:  Some problems were encountered while building the effective model for io.quarkus.ts.qe:vertx-web-client:jar:1.0.0-SNAPSHOT
Warning:  'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: io.quarkus:quarkus-opentelemetry:jar -> duplicate declaration of version (?) @ line 18, column 21
```

Drop duplicated definition of quarkus-opentelemetry

---

monitoring/opentelemetry-reactive/src/main/java/io/quarkus/ts/opentelemetry/reactive/sse/ServerSentEventsPingResource.java
monitoring/opentelemetry-reactive/src/test/java/io/quarkus/ts/opentelemetry/reactive/OpenTelemetrySseIT.java

Jira: https://issues.redhat.com/browse/QUARKUS-2745
OutboundSseEvent is throwing a serialization error on Quarkus 2.13.5.Final 
This PR covers the upstream patch.
Reproducer:
`mvn clean verify -Dit.test=OpenTelemetrySseIT#verifySeeRawSerialization -Dquarkus.platform.version=2.13.5.Final -Dquarkus.platform.group-id=io.quarkus.platform`

OutboundSseEvent is not correctly serialized

---

.github/workflows/daily.yaml
README.md
pom.xml

Move to new builder images introduced in Quarkus 2.14
PR with the change - https://github.com/quarkusio/quarkus/pull/27997
NEW is active - https://quay.io/repository/quarkus/ubi-quarkus-mandrel-builder-image?tab=tags
OLD is without update for 3 months - https://quay.io/repository/quarkus/ubi-quarkus-mandrel?tab=tags

Move to new builder images introduced in Quarkus 2.14

---

quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliSpecialCharsIT.java

* Disabling QuarkusCliSpecialCharsIT#shouldCreateApplicationOnJvmWithSpaces until a fix that would make it fail rather than block the session indefinitely is implemented as to not block CI runs.

Disable blocking CLI special character test

---

quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
quarkus-cli/src/test/resources/test.properties

Check, that dev-mode is omitted on projects with pom packaging
Required for QUARKUS-2757

Check, that dev-mode is omitted on projects with pom packaging

---

http/http-advanced-reactive/src/main/resources/application.properties
http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/AbstractDevModeIT.java
http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/DevModeHttpIT.java

adding http test and improving error messages

Refactoring of QUARKUS-2748

---

service-binding/postgresql-crunchy-classic/src/test/java/io/quarkus/ts/sb/postgresql/OpenShiftPostgreSqlSbIT.java
service-binding/postgresql-crunchy-reactive/src/test/java/io/quarkus/ts/sb/reactive/OpenShiftPostgreSqlReactiveSbIT.java

* Disabling the service binding tests caused by https://github.com/quarkusio/quarkus/issues/30682

Disabling service binding tests caused by bug

---

spring/spring-data/pom.xml
spring/spring-data/src/main/java/io/quarkus/ts/spring/data/rest/secured/DenyAllRepository.java
spring/spring-data/src/main/java/io/quarkus/ts/spring/data/rest/secured/PermitAllRepository.java
spring/spring-data/src/main/java/io/quarkus/ts/spring/data/rest/secured/PublicRepository.java
spring/spring-data/src/main/java/io/quarkus/ts/spring/data/rest/secured/RolesAllowedRepository.java
spring/spring-data/src/main/resources/application.properties
spring/spring-data/src/test/java/io/quarkus/ts/spring/data/rest/secured/OpenShiftSecuredRepositoryRestResourcesIT.java
spring/spring-data/src/test/java/io/quarkus/ts/spring/data/rest/secured/SecuredRepositoryRestResourcesIT.java
sql-db/panache-flyway/pom.xml
sql-db/panache-flyway/src/main/java/io/quarkus/ts/sqldb/panacheflyway/secured/EntityDenyAllResource.java
sql-db/panache-flyway/src/main/java/io/quarkus/ts/sqldb/panacheflyway/secured/EntityPermitAllResource.java
sql-db/panache-flyway/src/main/java/io/quarkus/ts/sqldb/panacheflyway/secured/EntityPublicResource.java
sql-db/panache-flyway/src/main/java/io/quarkus/ts/sqldb/panacheflyway/secured/EntityResourcePropertiesRolesAllowedResource.java
sql-db/panache-flyway/src/main/java/io/quarkus/ts/sqldb/panacheflyway/secured/EntityRolesAllowedResource.java
sql-db/panache-flyway/src/main/java/io/quarkus/ts/sqldb/panacheflyway/secured/RepositoryDenyAllResource.java
sql-db/panache-flyway/src/main/java/io/quarkus/ts/sqldb/panacheflyway/secured/RepositoryPermitAllResource.java
sql-db/panache-flyway/src/main/java/io/quarkus/ts/sqldb/panacheflyway/secured/RepositoryPublicResource.java
sql-db/panache-flyway/src/main/java/io/quarkus/ts/sqldb/panacheflyway/secured/RepositoryResourcePropertiesRolesAllowedResource.java
sql-db/panache-flyway/src/main/java/io/quarkus/ts/sqldb/panacheflyway/secured/RepositoryRolesAllowedResource.java
sql-db/panache-flyway/src/main/resources/application.properties
sql-db/panache-flyway/src/test/java/io/quarkus/ts/sqldb/panacheflyway/secured/AbstractSecuredPanacheResourceIT.java
sql-db/panache-flyway/src/test/java/io/quarkus/ts/sqldb/panacheflyway/secured/OpenShiftSecuredPanacheEntityResourceIT.java
sql-db/panache-flyway/src/test/java/io/quarkus/ts/sqldb/panacheflyway/secured/OpenShiftSecuredPanacheRepositoryResourceIT.java
sql-db/panache-flyway/src/test/java/io/quarkus/ts/sqldb/panacheflyway/secured/SecuredPanacheEntityResourceIT.java
sql-db/panache-flyway/src/test/java/io/quarkus/ts/sqldb/panacheflyway/secured/SecuredPanacheRepositoryResourceIT.java

Quarkus extensions based on `rest-data-panache` support propagation of security annotations into generated JAX-RS resources. These tests provide coverage of this feature for extensions:
- `quarkus-hibernate-orm-rest-data-panache`
- `quarkus-spring-data-rest`
See also related test plan:
- https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-2788.md

Add test for security annotations in rest-data-panache

---

lifecycle-application/pom.xml
pom.xml

- Missing upgrade `quarkus.platform.version` to Quarkus 2.13.7.Final on maven main pom.xml
- Update native builder image reference used on lifecycle-application module

[2.13] Fix quarkus platform version when no maven profile is provided

---

http/jaxrs-reactive/src/test/java/io/quarkus/ts/http/jaxrs/reactive/client/MultipartClientIT.java
security/keycloak-oidc-client-reactive-basic/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/basic/KeycloakOidcClientSecurityIT.java

* Disabling Resteasy reactive client tests due to issue with serialization/deserialization.
Issue: https://github.com/quarkusio/quarkus/issues/30814

Disabling tests due to serialization

---

http/http-minimum-reactive/src/main/java/io/quarkus/ts/http/minimum/reactive/HelloResource.java
http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/HttpMinimumReactiveIT.java
http/http-minimum/src/main/java/io/quarkus/ts/http/minimum/HelloResource.java
http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/HttpMinimumIT.java

Coverage for Path Param group name containing a dash
JIRA: https://issues.redhat.com/browse/QUARKUS-2893
Issue was present in RESTEasy Reactive, covering the scenario also in RESTEasy Classic module to ensure the same behaviour.
PASS: `mvn clean verify -Dit.test=HttpMinimumReactiveIT -f http/http-minimum-reactive -Dquarkus.platform.version=2.16.1.Final`
PASS: `mvn clean verify -Dit.test=HttpMinimumReactiveIT -f http/http-minimum-reactive -Dquarkus.platform.version=2.7.7.Final`
FAIL: `mvn clean verify -Dit.test=HttpMinimumReactiveIT -f http/http-minimum-reactive -Dquarkus.platform.version=2.7.6.Final`

Coverage for Path Param group name containing a dash

---

messaging/kafka-confluent-avro-reactive-messaging/pom.xml
pom.xml

Move Confluent repository definition into relevant module
Confluent repository definition in root pom.xml causes slow build / run of the TS because https://packages.confluent.io/maven/ gets contacted for every artifact that needs to be downloaded. Confluent repository definition is relevant just for `kafka-confluent-avro-reactive-messaging` module

Move Confluent repository definition into relevant module

---

http/jaxrs-reactive/pom.xml
http/jaxrs-reactive/src/test/java/io/quarkus/ts/http/jaxrs/reactive/client/MultipartClientIT.java
security/keycloak-oidc-client-reactive-basic/pom.xml
security/keycloak-oidc-client-reactive-basic/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/basic/KeycloakOidcClientSecurityIT.java

* Adding rest-client-reactive-jackson extensions to modules using reactive rest client. This change is needed as the server and client extension has been split in https://github.com/quarkusio/quarkus/pull/30529

Adding rest-client-reactive-jackson

---

.github/workflows/ci.yml
.github/workflows/daily.yaml

Faster build of Quarkus main in GH Actions
Avoiding build of integration tests and tck modules
Reduces the number of built modules from 1049 to 816 (valid data for 2023-02-03)

Faster build of Quarkus main in GH Actions

---

http/http-minimum-reactive/src/main/java/io/quarkus/ts/http/minimum/reactive/HelloResource.java
http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/HttpMinimumReactiveIT.java
http/http-minimum/src/main/java/io/quarkus/ts/http/minimum/HelloResource.java
http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/HttpMinimumIT.java
messaging/kafka-confluent-avro-reactive-messaging/pom.xml
pom.xml

- [Move Confluent repository definition into relevant module](https://github.com/quarkus-qe/quarkus-test-suite/pull/1032) rsvoboda
- [Coverage for Path Param group name containing a dash](https://github.com/quarkus-qe/quarkus-test-suite/pull/1031) rsvoboda

[2.13] re-location of Confluent maven repository and coverage of pathParams groupName with slash

---

http/jaxrs-reactive/src/test/java/io/quarkus/ts/http/jaxrs/reactive/RESTEasyReactiveMultipartIT.java

Multipart with several content types is partially fixed but is still failing on quarkus 2.13.7.Final
This PR disable those test that is failing for this 2.13 branch

[2.13] Disable some Multipart scenarios: missing backport from upstream

---

http/http-minimum-reactive/src/main/java/io/quarkus/ts/http/minimum/reactive/HelloResource.java
http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/HttpMinimumReactiveIT.java
http/http-minimum/src/main/java/io/quarkus/ts/http/minimum/HelloResource.java
http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/HttpMinimumIT.java

The combination of these two HTTP headers is illegal, so let's make sure RESTEasy Reactive does not send the Content-Length header when Transfer-Encoding is set
JiraLink: https://issues.redhat.com/browse/QUARKUS-2754

Verify that Transfer-Encoding and Content-Length doesn´t goes together in the same http response

---

spring/spring-data/pom.xml
spring/spring-data/src/main/java/io/quarkus/ts/spring/data/rest/secured/RolesAllowedRepository.java
spring/spring-data/src/test/java/io/quarkus/ts/spring/data/rest/additional/OpenAPIIT.java
spring/spring-data/src/test/java/io/quarkus/ts/spring/data/rest/additional/OpenShiftOpenAPIIT.java

Required for https://issues.redhat.com/browse/QUARKUS-2787
Replaces https://github.com/quarkus-qe/quarkus-test-suite/pull/1038
Backport to 2.13: https://github.com/quarkus-qe/quarkus-test-suite/pull/1040

Cover OpenAPI together with Spring Data

---

spring/spring-data/pom.xml
spring/spring-data/src/main/java/io/quarkus/ts/spring/data/rest/secured/RolesAllowedRepository.java
spring/spring-data/src/test/java/io/quarkus/ts/spring/data/rest/additional/OpenAPIIT.java
spring/spring-data/src/test/java/io/quarkus/ts/spring/data/rest/additional/OpenShiftOpenAPIIT.java

Required for https://issues.redhat.com/browse/QUARKUS-2787
This is backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/1038 (https://github.com/quarkus-qe/quarkus-test-suite/pull/1041) which is made separately due to differences between 2.13 and main

[2.13] Cover OpenAPI together with Spring Data

---

http/http-minimum-reactive/src/main/java/io/quarkus/ts/http/minimum/reactive/HelloResource.java
http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/HttpMinimumReactiveIT.java
http/http-minimum/src/main/java/io/quarkus/ts/http/minimum/HelloResource.java
http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/HttpMinimumIT.java

backport:
[Verify that Transfer-Encoding and Content-Length doesn´t goes together in the same http response](https://github.com/quarkus-qe/quarkus-test-suite/pull/1046)

[2.13] Verify that Transfer-Encoding and Content-Length doesn´t goes together in the same http response

---

http/http-minimum-reactive/src/main/java/io/quarkus/ts/http/minimum/reactive/HelloResource.java
http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/HttpMinimumReactiveIT.java
http/http-minimum/src/main/java/io/quarkus/ts/http/minimum/HelloResource.java
http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/HttpMinimumIT.java
messaging/kafka-confluent-avro-reactive-messaging/pom.xml
pom.xml

- [Move Confluent repository definition into relevant module](https://github.com/quarkus-qe/quarkus-test-suite/pull/1032) rsvoboda
- [Coverage for Path Param group name containing a dash](https://github.com/quarkus-qe/quarkus-test-suite/pull/1031) rsvoboda

[2.7] re-location of Confluent maven repository and coverage of pathParams groupName with slash

---

pom.xml

Because of move to jakarta, our CI broke on 999-SNAPSHOT.
While we adapt our TS to jakarta, it makes sense to temporarily switch to 2.16.1.Final

Temporary fix for failing CI

---

.github/workflows/ci.yml
http/hibernate-validator/pom.xml
http/rest-client-reactive/pom.xml
http/rest-client/pom.xml
pom.xml
security/keycloak-oidc-client-extended/pom.xml
super-size/many-extensions/pom.xml
test-tooling/pact/src/test/java/io/quarkus/ts/http/pact/ProviderPactTest.java

- Right now our test suite does not compile at all thanks to https://github.com/quarkus-qe/quarkus-test-suite/pull/1025 that was never rebased on current main - that is fixed by commenting out kamelet module.
- Native build of multiple modules is fixed by commenting out Camel BOM - https://github.com/quarkusio/quarkus/issues/31105.
- Pact failure goes down to class loading changes in Quarkus 3, IMO we should migrate to Quarkus Pact once it's adapted to Quarkus 3. Comment has been added.

Fix Test Suite compilation by removing Kamelet module and fix native build and adjust Pact comment

---

security/keycloak-oidc-client-extended/pom.xml

https://github.com/quarkusio/quarkus/pull/31188 is merged and Jakarta activation exclusion is no longer needed for native build.

Remove 'jakarta.activation' exclusion from Keycloak OIDC Client extended

---

config/src/test/java/io/quarkus/ts/configmap/api/server/OpenShiftBaseConfigIT.java
config/src/test/java/io/quarkus/ts/configmap/api/server/OpenShiftConfigSourcePriorityIT.java
config/src/test/java/io/quarkus/ts/configmap/api/server/OpenShiftFailOnMissingConfigIT.java
funqy/knative-events/src/test/java/io/quarkus/ts/funqy/knativeevents/ServerlessExtensionOpenShiftFunqyKnEventsIT.java
http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/OpenShiftUsingExtensionDockerBuildStrategyHttpMinimumReactiveIT.java
http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/OpenShiftUsingExtensionHttpMinimumReactiveIT.java
http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/ServerlessExtensionDockerBuildStrategyOpenShiftHttpMinimumReactiveIT.java
http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/ServerlessExtensionOpenShiftHttpMinimumReactiveIT.java
http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/OpenShiftUsingExtensionDockerBuildStrategyHttpMinimumIT.java
http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/OpenShiftUsingExtensionHttpMinimumIT.java
http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/ServerlessExtensionDockerBuildStrategyOpenShiftHttpMinimumIT.java
http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/ServerlessExtensionOpenShiftHttpMinimumIT.java
http/jaxrs-reactive/src/test/java/io/quarkus/ts/http/jaxrs/reactive/OpenShiftCompressionHandlerIT.java
http/jaxrs-reactive/src/test/java/io/quarkus/ts/http/jaxrs/reactive/OpenShiftHttpCachingIT.java
http/vertx/src/test/java/io/quarkus/ts/vertx/OpenShiftUsingExtensionDockerBuildStrategyVertxIT.java
http/vertx/src/test/java/io/quarkus/ts/vertx/OpenShiftUsingExtensionVertxIT.java
http/vertx/src/test/java/io/quarkus/ts/vertx/ServerlessExtensionDockerBuildStrategyOpenShiftVertxIT.java
http/vertx/src/test/java/io/quarkus/ts/vertx/ServerlessExtensionOpenShiftVertxIT.java
infinispan-client/src/test/java/io/quarkus/ts/infinispan/client/OperatorOpenShiftInfinispanCountersIT.java
infinispan-client/src/test/java/io/quarkus/ts/infinispan/client/OperatorOpenShiftInfinispanObjectsIT.java
lifecycle-application/src/test/java/io/quarkus/ts/lifecycle/OpenShiftLifecycleApplicationIT.java
monitoring/micrometer-prometheus/src/test/java/io/quarkus/ts/micrometer/prometheus/OpenShiftCustomMetricsIT.java
pom.xml
service-discovery/stork/pom.xml
super-size/many-extensions/src/test/java/io/quarkus/ts/many/extensions/OpenShiftUsingExtensionDockerBuildStrategyManyExtensionsIT.java
super-size/many-extensions/src/test/java/io/quarkus/ts/many/extensions/OpenShiftUsingExtensionManyExtensionsIT.java
super-size/many-extensions/src/test/java/io/quarkus/ts/many/extensions/ServerlessExtensionDockerBuildStrategyOpenShiftManyExtensionsIT.java
super-size/many-extensions/src/test/java/io/quarkus/ts/many/extensions/ServerlessExtensionOpenShiftManyExtensionsIT.java

- Disable tests that use Quarkus Openshift extension due to https://github.com/quarkusio/quarkus/issues/31228
- Bump Quarkus Test Framework version to 1.3.0.Beta6, which fixes NPE for tests that enrich OpenShift template
- Dependency `org.bouncycastle:bcpkix-jdk15on` is no longer managed by Quarkus, therefore I went with `jdk18on`
- Disable Hibernate Reactive, PostgreSQL Service binding reactive and Spring Web Reactive modules due to https://github.com/quarkusio/quarkus/pull/31217

Bump Quarkus Test Framework to 1.3.0.Beta6 and disable OpenShift tests and Hibernate Reactive

---

config/src/test/java/io/quarkus/ts/configmap/api/server/OpenShiftApiServerConfigMapConfigIT.java
config/src/test/java/io/quarkus/ts/configmap/api/server/OpenShiftApiServerConfigSecretConfigIT.java
config/src/test/java/io/quarkus/ts/configmap/api/server/OpenShiftFileSystemConfigMapConfigIT.java
config/src/test/java/io/quarkus/ts/configmap/api/server/OpenShiftFileSystemConfigSecretConfigIT.java

Disables test in config module due to https://github.com/quarkusio/quarkus/issues/31228. I intentionally do not run OC CI (`run tests`) as 
1. disabling can't break anything 
2. loads of OC tests are failing over `NoClassDefFoundError`, which is unrelated and debugging is WIP.

Disable OpenShift config module tests due to upstream issue

---

sql-db/panache-flyway/src/main/java/io/quarkus/ts/sqldb/panacheflyway/ApplicationEntity.java
sql-db/reactive-rest-data-panache/src/main/java/io/quarkus/ts/reactive/rest/data/panache/ApplicationEntity.java

https://github.com/quarkusio/quarkus/pull/31235 upgraded Hibernate to version 6.2. `org.hibernate.annotations.ParamDef#type` now accepts `Class` instead of plain string. Because of that, TS don't compile.

Fix Test Suite compilation broken by bump to Hibernate 6.2 in Quarkus

---

sql-db/multiple-pus/src/main/resources/import-fruits.sql
sql-db/multiple-pus/src/main/resources/import-vegetables.sql
sql-db/multiple-pus/src/test/java/io/quarkus/ts/sqldb/multiplepus/AbstractMultiplePersistenceIT.java
sql-db/narayana-transactions/src/main/resources/import.sql
sql-db/narayana-transactions/src/test/resources/mariadb_import.sql
sql-db/narayana-transactions/src/test/resources/mssql_import.sql
sql-db/narayana-transactions/src/test/resources/mysql.properties
sql-db/narayana-transactions/src/test/resources/mysql_import.sql
sql-db/narayana-transactions/src/test/resources/oracle_import.sql
sql-db/sql-app/src/main/java/io/quarkus/ts/sqldb/sqlapp/Book.java
sql-db/sql-app/src/main/resources/import.sql
sql-db/sql-app/src/test/resources/db2_app.properties
sql-db/sql-app/src/test/resources/db2_import.sql
sql-db/sql-app/src/test/resources/mariadb_import.sql
sql-db/sql-app/src/test/resources/mssql_import.sql
sql-db/sql-app/src/test/resources/mysql.properties
sql-db/sql-app/src/test/resources/mysql_import.sql
sql-db/sql-app/src/test/resources/oracle_import.sql

Quarkus main branch is using Hibernate 6 now (please see https://github.com/quarkusio/quarkus/pull/31235 ). Unless we use legacy behavior, Hibernate entities are supposed to use dedicated sequence, instead of Hibernate ones. Test failure dailys are currently failing because of this. Further details in https://github.com/quarkusio/quarkus/issues/31256.
Changes:
- MySQL can't use `org.hibernate.dialect.MariaDB102Dialect` as commands handling next sequel value differ
- Default Hibernate increment by 50 is fine with `multiple-plus` and `naryana-transactions` modules due to how tests are written (don't expected certain id for entities not inserted via sql init script), however SQL app need increment by 1 therefore I skipped there to PanacheEntityBase and set sequence allocation and increment …

Hibernate 6 migration - use dedicated sequence for each table

---

pom.xml
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java

- backport: https://github.com/quarkus-qe/quarkus-test-suite/commit/1f1eec0267337c3855a5dbdb258bdd8012608fed
- Bump `impsort-maven-plugin` to 1.8.0

[2.13] Explicitly use maven local repo for gradle build (#1064)

---

quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
sql-db/hibernate-reactive/src/main/java/io/quarkus/ts/hibernate/reactive/http/PanacheEndpoint.java
sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/AbstractDatabaseHibernateReactiveIT.java

[Add coverage for new lines in HQL queries](https://github.com/quarkus-qe/quarkus-test-suite/pull/1056) fedinskiy
[Make jbang use the same repository as maven](https://github.com/quarkus-qe/quarkus-test-suite/pull/1058) fedinskiy

[2.13] jbang + HQL queries backports

---

README.md
infinispan-client/src/main/resources/application.properties
infinispan-client/src/test/resources/infinispan_cluster_configmap.yaml
messaging/infinispan-grpc-kafka/src/main/resources/application.properties
messaging/infinispan-grpc-kafka/src/test/java/io/quarkus/ts/messaging/infinispan/grpc/kafka/InfinispanKafkaIT.java
messaging/infinispan-grpc-kafka/src/test/java/io/quarkus/ts/messaging/infinispan/grpc/kafka/InfinispanKafkaSaslIT.java
nosql-db/infinispan/src/main/resources/application.properties
nosql-db/infinispan/src/test/java/io/quarkus/ts/infinispan/DevModeInfinispanIT.java
nosql-db/infinispan/src/test/java/io/quarkus/ts/infinispan/InfinispanIT.java
nosql-db/infinispan/src/test/resources/infinispan-it.properties

Currently we don't have any DEV mode test for Infinispan using Dev Services for Infinispan. There was a test at DEV mode that actually didn't start Dev Services as it set `server-list`. Now we use Dev Services to have this covered. Also some deprecated properties are migrated.

Make DEV mode Infinispan test use Dev Services for Infinispan

---

pom.xml
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/PostgresqlDatabaseIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/XAPostgresIT.java
sql-db/sql-app/src/test/resources/test.properties

Removes workaround for a failure reported in
https://github.com/quarkus-qe/quarkus-test-framework/issues/641 and observed in https://github.com/quarkus-qe/quarkus-test-suite/pull/971.

Remove PostgreSQL image workaround

---

sql-db/narayana-transactions/src/main/java/io.quarkus.ts.transactions/LegacyTransferTopUpService.java
sql-db/narayana-transactions/src/main/java/io.quarkus.ts.transactions/TransferResource.java
sql-db/narayana-transactions/src/main/resources/import.sql
sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/TransactionCommons.java
sql-db/narayana-transactions/src/test/resources/mariadb_import.sql
sql-db/narayana-transactions/src/test/resources/mssql_import.sql
sql-db/narayana-transactions/src/test/resources/mysql_import.sql
sql-db/narayana-transactions/src/test/resources/oracle_import.sql

Migrate old transaction API references to the new API
Motivation: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.16#quarkustransactionrunquarkustransactioncall-are-deprecated

Transaction API migration

---

spring/spring-web/src/main/java/io/quarkus/ts/spring/web/reactive/boostrap/web/RestExceptionHandler.java

Persistence exception is now wrapped with `ArcUndeclaredThrowableException`, so exception is never caught by exception handler and 500 is thrown instead of 400. Previously (tried 2.13), the top-most cost was `PersistenceException`.

Fix Spring Web test as ex. thrown for constraint violation is wrapped

---

scheduling/quartz/src/main/java/io/quarkus/ts/scheduling/quartz/basic/ManuallyScheduledCounter.java
scheduling/quartz/src/main/java/io/quarkus/ts/scheduling/quartz/basic/services/CounterService.java
scheduling/quartz/src/main/java/io/quarkus/ts/scheduling/quartz/failover/AnnotationScheduledJob.java
scheduling/quartz/src/main/java/io/quarkus/ts/scheduling/quartz/failover/ExecutionEntity.java
scheduling/quartz/src/main/resources/application.properties
scheduling/quartz/src/test/java/io/quarkus/ts/scheduling/quartz/BasicMySqlQuartzIT.java

Fix Quartz jobs:
- with Hibernate 6, identity wasn't used as strategy for PK, so there was sometimes duplicate keys exception (and sometimes I experienced table not found :-/)
- I mentioned that `init` method of the `io.quarkus.ts.scheduling.quartz.basic.ManuallyScheduledCounter.CountingJob` was called every single time job was executed. Also job is started way before job result is tested. It doesn't really make sense to have there 2 second waiting and test sequence (greater than 0 and greater than 1), I rewrote that test
- manually scheduled job was running even when it wasn't tested (when other `@QuarkusScenario` test classes where running), I adjusted the condition
- `AnnotationScheduledJob` tried to save results to database before application started (depending on a moment when job …

Fix Quartz job tests by adjusting Hibernate entity id, job scope and job start-up

---

http/graphql-telemetry/src/test/java/io/quarkus/ts/http/graphql/telemetry/GraphQLTelemetryIT.java
http/vertx-web-client/src/test/java/io/quarkus/ts/http/vertx/webclient/VertxWebClientIT.java
monitoring/opentelemetry/src/test/java/io/quarkus/ts/opentelemetry/OpentelemetryIT.java
sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/TransactionCommons.java

https://github.com/quarkusio/quarkus/pull/31356 bumped OpenTelemetry to 1.23.1 and we need to update traces operation names.

Fix OpenTelemetry traces operation names as they changed when OpenTelemetry was bumped to 1.23.1

---

monitoring/opentelemetry-reactive/src/test/java/io/quarkus/ts/opentelemetry/reactive/OpentelemetryReactiveIT.java

https://github.com/quarkusio/quarkus/pull/31356 bumped OpenTelemetry to 1.23.1 and we need to update traces operation names. Fixes daily run failure.

Fix OpenTelemetryReactiveIT expected trace operations and their names

---

http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/MultipleResponseSerializersResource.java
http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/PremierLeagueContainerRequestFilter.java
http/http-advanced/src/main/java/io/quarkus/ts/http/advanced/PremierLeagueContainerRequestFilter.java
http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/json/JsonParamConverterProvider.java
monitoring/opentelemetry-reactive/src/main/java/io/quarkus/ts/opentelemetry/reactive/sse/ServerSentEventsPingResource.java
security/basic/src/main/java/io/quarkus/ts/openshift/security/basic/AdminResource.java

[It is now possible](https://github.com/gsmet/quarkus/commit/2d4332267a81ec49b9d950c44790a44327c8c6f0) to use `@Inject` on field injection points in RESTEasy Classic providers instead of `@Context`. RESTEasy Reactive has already supported this approach. [There is a plan to drop support](https://github.com/quarkusio/quarkus/issues/29240) of `@Context` on method parameters too, however this is not supported by RESTEasy (classic) yet. RESTEasy Reactive already supports this method parameter injection.
Changes done by this PR:
- module HTTP advanced:
- `UriInfo` is newly injected with `@Inject`, however legacy `@Context` is stll used for `HttpRequest` injection
- module HTTP advanced reactive:
- in `PremierLeagueContainerRequestFilter`, `UriInfo` is newly injected with `@Inject`, however …

Use RESTEasy CDI to inject beans with `@Inject` instead of `@Context`

---

security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/OpenApiStoreSchemaIT.java
security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/OpenApiStoreSchemaIT.java
spring/spring-data/src/test/java/io/quarkus/ts/spring/data/rest/additional/OpenAPIIT.java

With https://github.com/quarkusio/quarkus/pull/31671 expected behavior of Smallrye OpenAPI has changed (torwards the specification) in regards to expected security scheme for basic authentication. We can't expect any value for 'basic' auth in Spring Data module now, therefore I added additional tests to Keycloak OIDC client extended modules so that we have tested scenarios when security scheme is not empty.

Fix OpenAPI test failure and extend test coverage for security schemes

---

http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/CookiesResource.java
http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/CookiesIT.java
http/http-advanced-reactive/src/test/resources/cookies.properties

https://github.com/quarkusio/quarkus/issues/31122 added support for a 'sameSite' attribute to 'NewCookie'. This change is possible as Jakarta 3.1 added support for the 'sameSite'. In short, it means that `Response` and `RestResponse` or anything that uses `RuntimeDelegate` for `NewCookie` map `sameSite` attribute when parsing the cookie and transforming `NewCookie` to `String`. In past, cookie would not contain `sameSite` attribute added to the `Response`. I also added test for `same-site-cookie` as we don't test it anywhere and I wanted a smoke test to ensure they can work together. `same-site-cookie` is tested in upstream, but I didn't find integration test with RESTEasy Reactive.
TD is done according to the TP [QUARKUS-2736](https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUA …

Test RESTEasy Reactive  support for a 'NewCookie' 'sameSite' attribute

---

security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/OpenApiStoreSchemaIT.java
security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/OpenApiStoreSchemaIT.java

Sometimes security scheme is empty (contains no roles). It only happens in CI, or in circumstances I'm not aware of. I run it locally about 100 times without single failure. I need to add extra logging that will show me generated OpenAPI definition in situation when test is failing. Now we also return for required role `null` instead of NPE, which means assertion will still fail.

Add debug logging to flaky `OpenApiStoreSchemaIT` tests

---

sql-db/multiple-pus/src/main/resources/application.properties
sql-db/narayana-transactions/src/test/resources/mariadb_app.properties
sql-db/reactive-rest-data-panache/src/test/resources/mariadb_app.properties
sql-db/reactive-rest-data-panache/src/test/resources/mysql.properties

Fixes DB-related daily failures. Migration guide https://docs.jboss.org/hibernate/orm/6.2/migration-guide/migration-guide.html suggest we should use `MariaDBDialect` unless we need to support legacy databases (which we don't). Quarkus guide suggest we don't need to specify dialect as Quarkus identifies the right dialect based on database kind (autoresolution). So I kinda combined it to have tested both.
Tests started to fail after https://github.com/quarkusio/quarkus/pull/31947 identified by @rsvoboda .

Migrate from legacy (and missing) MariaDB dialect to `MariaDBDialect`

---

spring/spring-web/src/main/resources/application.properties

Spring Web module succeeds in JVM mode, but native build fails over missing class
```
Caused by: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported type org.hibernate.boot.xsd.ConfigXsdSupport is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
```
It's just demonstration of incorrect dialect (as legacy dialect needs extra dependency - see https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0:-Hibernate-ORM-5-to-6-migration#dialect-configuration-changes).
Spring Web Reactive will need similar change, but it's disabled now. As https://github.com/quarkusio/quarkus/pull/31454 is merged now, I'll enable it in a separate PR.
Please …

Fix Spring Web native module build - Hibernate ORM shouldn't use legacy dialect as it fails in native

---

security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/OpenApiStoreSchemaIT.java

Disable flaky assertion till upstream issue is fixed - https://github.com/quarkusio/quarkus/issues/32112

Disable OpenAPI security scheme check in classic OIDC client

---

quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateExtensionIT.java
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateNativeApplicationIT.java
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliExtensionsIT.java
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliHelpIT.java
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliSpecialCharsIT.java

Expected text for version help has changed due to https://github.com/quarkusio/quarkus/commit/4af1c06e173316ed3bcb4629a1b72ddb67b8ed75#diff-28dd2b5fee9f9be1f967d404cde0b820f215e2fe6d9ead6579ecdcc8912efb60L194, now it shows `io.quarkus.cli.Version` _header_. Couple of CLI tests are disabled due to the https://github.com/quarkusio/quarkus/issues/32219.

Update expected Quarkus CLI text for command 'version' and disable failing CLI tests

---

funqy/knative-events/src/test/java/io/quarkus/ts/funqy/knativeevents/ServerlessExtensionOpenShiftFunqyKnEventsIT.java
http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/OpenShiftUsingExtensionDockerBuildStrategyHttpMinimumReactiveIT.java
http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/OpenShiftUsingExtensionHttpMinimumReactiveIT.java
http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/ServerlessExtensionDockerBuildStrategyOpenShiftHttpMinimumReactiveIT.java
http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/ServerlessExtensionOpenShiftHttpMinimumReactiveIT.java
http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/OpenShiftUsingExtensionDockerBuildStrategyHttpMinimumIT.java
http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/OpenShiftUsingExtensionHttpMinimumIT.java
http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/ServerlessExtensionDockerBuildStrategyOpenShiftHttpMinimumIT.java
http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/ServerlessExtensionOpenShiftHttpMinimumIT.java
http/jakarta-rest-reactive/src/test/java/io/quarkus/ts/http/jakartarest/reactive/OpenShiftCompressionHandlerIT.java
http/jakarta-rest-reactive/src/test/java/io/quarkus/ts/http/jakartarest/reactive/OpenShiftHttpCachingIT.java
http/vertx/src/test/java/io/quarkus/ts/vertx/OpenShiftUsingExtensionVertxIT.java
http/vertx/src/test/java/io/quarkus/ts/vertx/ServerlessExtensionDockerBuildStrategyOpenShiftVertxIT.java
http/vertx/src/test/java/io/quarkus/ts/vertx/ServerlessExtensionOpenShiftVertxIT.java
infinispan-client/src/test/java/io/quarkus/ts/infinispan/client/OperatorOpenShiftInfinispanCountersIT.java
infinispan-client/src/test/java/io/quarkus/ts/infinispan/client/OperatorOpenShiftInfinispanObjectsIT.java
lifecycle-application/pom.xml
lifecycle-application/src/test/java/io/quarkus/ts/lifecycle/OpenShiftLifecycleApplicationIT.java
pom.xml
super-size/many-extensions/src/test/java/io/quarkus/ts/many/extensions/OpenShiftUsingExtensionDockerBuildStrategyManyExtensionsIT.java
super-size/many-extensions/src/test/java/io/quarkus/ts/many/extensions/OpenShiftUsingExtensionManyExtensionsIT.java
super-size/many-extensions/src/test/java/io/quarkus/ts/many/extensions/ServerlessExtensionDockerBuildStrategyOpenShiftManyExtensionsIT.java
super-size/many-extensions/src/test/java/io/quarkus/ts/many/extensions/ServerlessExtensionOpenShiftManyExtensionsIT.java
websockets/quarkus-websockets/src/test/java/io/quarkus/ts/websockets/producer/WebSocketsProducerConsumerIT.java

- Enable tests using Quarkus OpenShift extension as https://github.com/quarkusio/quarkus/issues/31228 is resolved.
- Funqy Knative test is disabled in native as it is flaky and I need more time to understand it
- Websockets producer test is adjusted as message is sent asynchronously and sometimes it takes a little longer before we can assert it. I saw it several times in OC failures, however I also saw it last week in dailys https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/4537518462 - flaky
- Disabled `OperatorOpenShiftInfinispanCountersIT` as it sometimes expects 200 status and receives 503, flaky method changes, so I disabled whole class
- tests in config module using OC extensions are enabled in a separate PR https://github.com/quarkus-qe/quarkus-test-suite/pull/1140 in …

Enable tests with Quarkus OpenShift extension as upstream issue is fixed

---

security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/OpenApiStoreSchemaIT.java

Disables assertion of roles allowed to access path in generated OpenAPI definition. We already had to [disable same check for OIDC classic](https://github.com/quarkus-qe/quarkus-test-suite/pull/1129) and now that [daily build # 779 failed](https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/4585690826/jobs/8098110705), we know it is also affected by https://github.com/quarkusio/quarkus/issues/32112

Disable OpenAPI definition check for allowed roles in security scheme

---

spring/spring-web-reactive/src/test/java/io/quarkus/ts/spring/web/reactive/reactive/MariaDBConstants.java
spring/spring-web-reactive/src/test/java/io/quarkus/ts/spring/web/reactive/reactive/boostrap/SpringWebQuteReactiveIT.java
spring/spring-web-reactive/src/test/java/io/quarkus/ts/spring/web/reactive/reactive/boostrap/SpringWebRestReactiveIT.java
spring/spring-web-reactive/src/test/java/io/quarkus/ts/spring/web/reactive/reactive/openapi/SpringWebOpenApiReactiveIT.java

Enable spring-web-reactive module for GitHub Actions
MariaDB 10.5 image is tested in OpenShift scenarios, using public `mariadb.10.image` for bare metal scenarios

Enable spring-web-reactive module for GitHub Actions

---

spring/spring-web/src/main/java/io/quarkus/ts/spring/web/reactive/boostrap/web/RestExceptionHandler.java

Revert "Fix Spring Web test as ex. thrown for constraint violation is wrapped"
This fixes the recent CI failures after Hibernate 6.2.0.Final merge into Quarkus main, some details in https://github.com/quarkusio/quarkus/issues/32397#issuecomment-1495887017.
https://docs.jboss.org/hibernate/orm/6.2/javadocs/org/hibernate/PropertyValueException.html extends  jakarta.persistence.PersistenceException  
Also aligning with https://github.com/quarkus-qe/quarkus-test-suite/blob/main/spring/spring-web-reactive/src/main/java/io/quarkus/ts/spring/web/reactive/boostrap/web/RestExceptionHandler.java

Revert "Fix Spring Web test as ex. thrown for constraint violation is wrapped"

---

messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DevModeRedPandaDevServiceUserExperienceIT.java
messaging/kafka-strimzi-avro-reactive-messaging/src/main/resources/docker-compose-strimzi.yaml
messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/DevModeApicurioDevServiceUserExperienceIT.java

Updates Red Panda, Strimzi Kafka and Apicurio registry docker images. There is opened follow-up MR in Jenkins job project.

Update Red Panda, Strimzi Kafka and Apicurio registry image version

---

http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/DevModeGrpcIntegrationReactiveIT.java
http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/DevModeGrpcIntegrationIT.java
http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/DevModeHttpMinimumReactiveIT.java
http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/DevModeHttpMinimumIT.java

Disabled DEV mode tests using continuous testing. Currently there is no button to enable continuous testing, new dedicated page is expected in next days, then we need to adapt FW, release it and enable tests here.

Disable DEV mode continuous testing scenarios due to upstream re-working

---

spring/spring-data/pom.xml
spring/spring-data/src/test/java/io/quarkus/ts/spring/data/rest/additional/OpenAPIIT.java

Enable native test scenario for OpenAPIIT as https://github.com/quarkusio/quarkus/issues/30919 was resolved.

Enable native test scenario for OpenAPIIT

---

spring/spring-data/src/test/java/io/quarkus/ts/spring/data/rest/secured/SecuredRepositoryRestResourcesIT.java

rolesAllowedResourcePermitAllMethodWithoutRestResourceAnnotation test was enabled, because actual Quarkus project version is 3.0.0.CR2

Enable test in SecuredRepositoryRestResourcesIT

---

sql-db/panache-flyway/src/test/java/io/quarkus/ts/sqldb/panacheflyway/dbpool/AgroalPoolTest.java

Enable Agroal idle timeout test. Add quarkus.datasource.jdbc.background-validation-interval property that defines the interval at which idle connections has been validated in the background

Enable Agroal idleTimeoutTest

---

http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/BaseHttpAdvancedReactiveIT.java
http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientIT.java
monitoring/micrometer-prometheus-oidc/src/test/java/io/quarkus/ts/micrometer/oidc/BaseMicrometerOidcSecurityIT.java
monitoring/micrometer-prometheus/src/test/java/io/quarkus/ts/micrometer/prometheus/MicroProfileApiIT.java
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliExtensionsIT.java
spring/spring-data/src/test/java/io/quarkus/ts/spring/data/primitivetypes/SpringDataCompositeEntityIT.java

Enable tests previously disabled on specific Quarkus versions (2.*) as current Quarkus version is 3.0.0.CR2

Enable tests previously disabled on specific Quarkus versions

---

websockets/quarkus-websockets/src/test/java/io/quarkus/ts/websockets/producer/WebSocketsProducerConsumerIT.java

This test is flaky and every couple of days daily build fails, however even after Pablo's addition we still don't have any useful information for debugging failure. As I can't really reproduce it locally, I need 2 things:
1. would it succeed eventually? (=> enlarge waiting period)
3. how long does it take for asynchronously sent message to arrive

Debug websockets producer with additional time and logging

---

sql-db/sql-app-compatibility/pom.xml
sql-db/sql-app/pom.xml

closes: #373
Today, daily build (number 793) got cancelled in native as sql-modules take too long to execute. We recently added sql-app-compatibility module that added to already packaged Maven profile. All tests in `sql-app` and `sql-app-compatibility` modules use custom build, therefore we can spare couple of minutes by skipping `quarkus-maven-build` in native mode.

Skip native executable build for sql-app modules as tests use custom one

---

funqy/knative-events/src/test/java/io/quarkus/ts/funqy/knativeevents/ServerlessExtensionOpenShiftFunqyKnEventsIT.java
http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/ServerlessExtensionDockerBuildStrategyOpenShiftHttpMinimumReactiveIT.java
http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/ServerlessExtensionOpenShiftHttpMinimumReactiveIT.java
http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/ServerlessExtensionDockerBuildStrategyOpenShiftHttpMinimumIT.java
http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/ServerlessExtensionOpenShiftHttpMinimumIT.java
http/vertx/src/test/java/io/quarkus/ts/vertx/ServerlessExtensionDockerBuildStrategyOpenShiftVertxIT.java
http/vertx/src/test/java/io/quarkus/ts/vertx/ServerlessExtensionOpenShiftVertxIT.java
messaging/amqp-reactive/src/test/java/io/quarkus/ts/messaging/amqpreactive/OpenShiftProdAmqpReactiveIT.java
messaging/cloud-events/amqp-binary/src/test/java/io/quarkus/ts/messaging/cloudevents/amqpbinary/OpenShiftBinaryCloudEventsOverProdAmqpIT.java
messaging/cloud-events/amqp-json/src/test/java/io/quarkus/ts/messaging/cloudevents/amqpjson/OpenShiftJSONCloudEventsOverProdAmqpIT.java
messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftAmqStreamsKafkaStreamIT.java
messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OperatorOpenShiftAmqStreamsKafkaStreamIT.java
messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/OpenShiftAmqStreamsKafkaAvroIT.java
monitoring/micrometer-prometheus-kafka-reactive/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/reactive/OpenShiftAmqStreamsAlertEventsReactiveIT.java
monitoring/micrometer-prometheus-kafka/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/OpenShiftAmqStreamsAlertEventsIT.java
nosql-db/mongodb-reactive/src/test/java/io/quarkus/ts/nosqldb/mongodb/reactive/OpenShiftMongoClientReactiveIT.java
nosql-db/mongodb/src/test/java/io/quarkus/ts/nosqldb/mongodb/OpenShiftMongoClientIT.java
pom.xml
security/keycloak-authz-classic/src/test/java/io/quarkus/ts/security/keycloak/authz/OpenShiftRhSsoAuthzSecurityIT.java
security/keycloak-authz-reactive/src/test/java/io/quarkus/ts/security/keycloak/authz/reactive/OpenShiftRhSsoAuthzSecurityReactiveIT.java
security/keycloak-jwt/src/test/java/io/quarkus/ts/security/keycloak/jwt/OpenShiftRhSsoOidcJwtSecurityIT.java
security/keycloak-multitenant/src/test/java/io/quarkus/ts/security/keycloak/multitenant/OpenShiftRhSsoMultiTenantSecurityIT.java
security/keycloak-oauth2/src/test/java/io/quarkus/ts/security/keycloak/oauth2/OpenShiftRhSsoOauth2SecurityIT.java
security/keycloak-oidc-client-basic/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/basic/OpenShiftRhSsoOidcClientSecurityIT.java
security/keycloak-oidc-client-reactive-basic/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/basic/OpenShiftRhSsoOidcClientSecurityIT.java
security/keycloak-webapp/src/test/java/io/quarkus/ts/security/keycloak/webapp/OpenShiftRhSsoWebappSecurityIT.java
security/keycloak/src/test/java/io/quarkus/ts/security/keycloak/OpenShiftRhSsoOidcSecurityIT.java
security/oidc-client-mutual-tls/src/test/java/io/quarkus/ts/security/oidcclient/mtls/OpenShiftRhSsoOidcMtlsIT.java
super-size/many-extensions/src/test/java/io/quarkus/ts/many/extensions/ServerlessExtensionDockerBuildStrategyOpenShiftManyExtensionsIT.java
super-size/many-extensions/src/test/java/io/quarkus/ts/many/extensions/ServerlessExtensionOpenShiftManyExtensionsIT.java

This PR contains a new profile for ARM running on OpenShift; updates to containers running test services to multiarch version and exclusion for tests that do not have required test services running on aarch64.
Issues that will need to be addressed for complete coverage:
* https://github.com/quarkus-qe/quarkus-test-suite/issues/1142
* https://github.com/quarkus-qe/quarkus-test-suite/issues/1144
* https://github.com/quarkus-qe/quarkus-test-suite/issues/1145
* https://github.com/quarkus-qe/quarkus-test-suite/issues/1146
* https://github.com/quarkus-qe/quarkus-test-suite/issues/1147
Test run with the profile: https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/job/quarkus-main-rhel8-jdk11-openshift-weekly-ts-jvm-ocp-4-stable/14/
- [] Bug fix …

Profile for OpenShift running on aarch64

---

pom.xml

Faster build when using -DskipTests
Fixes https://github.com/quarkus-qe/quarkus-test-suite/issues/107
BEFORE: `[INFO] Total time:  06:49 min`
AFTER: `[INFO] Total time:  02:29 min`

Faster build when using -DskipTests

---

pom.xml

* Multiarch software collection container images are available only with
terms enabled registry. This commig is moving the RHEL8 SCL multiarch image
usage to openshift-arm profile.
ARM OpenShift test run: https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/job/quarkus-main-rhel8-jdk11-openshift-weekly-ts-jvm-ocp-4-stable/17/

Use multiarch MySQL just for openshift-arm

---

.github/workflows/ci.yml
.github/workflows/daily.yaml

Add retention-days for storing maven repo artifact (1GB)
The default retention policy is 90 days - https://github.com/actions/upload-artifact#retention-period

Add retention-days for storing maven repo artifact

---

infinispan-client/src/test/java/io/quarkus/ts/infinispan/client/OperatorOpenShiftInfinispanCountersIT.java

Enables `OperatorOpenShiftInfinispanCountersIT`. Failures were caused by old Infinispan cluster that hung in datagrid-cluster project.

Enable OperatorOpenShiftInfinispanCountersIT test

---

lifecycle-application/pom.xml
pom.xml

Fixes failure in lifecycle-application module. Looks like I didn't realize this needs to be done when bumping framework https://github.com/quarkus-qe/quarkus-test-suite/pull/1175 and CI was green as this test didn't run.

Fix lifecycle-application failure by syncing Quarkus version

---

service-binding/postgresql-crunchy-classic/src/main/resources/application.properties
service-binding/postgresql-crunchy-classic/src/main/resources/import.sql
service-binding/postgresql-crunchy-classic/src/test/java/io/quarkus/ts/sb/postgresql/OpenShiftPostgreSqlSbIT.java
service-binding/postgresql-crunchy-classic/src/test/resources/pg-cluster.yml
service-binding/postgresql-crunchy-reactive/src/main/resources/application.properties
service-binding/postgresql-crunchy-reactive/src/main/resources/import.sql
service-binding/postgresql-crunchy-reactive/src/test/java/io/quarkus/ts/sb/reactive/OpenShiftPostgreSqlReactiveSbIT.java
service-binding/postgresql-crunchy-reactive/src/test/resources/pg-cluster.yml

closes: #993
According to https://github.com/quarkusio/quarkus/issues/32773#issuecomment-1515786557 the issue was fixed by https://github.com/quarkusio/quarkus/pull/32651.
- sequence change goes down to Hibernate 6
- `hippo` -> `postgresql`: it doesn't work with hippo, I think that's because the name is also used for named datasource (so it looks for hippo ds), it is documented at the very end of this page https://quarkus.io/guides/deploying-to-kubernetes#customizing-automatic-service-binding (full disclosure: I'm not sure here. Do you read it same way I do?)

Enable PG service binding tests as upstream issue is fixed

---

service-binding/postgresql-crunchy-classic/src/main/resources/application.properties
service-binding/postgresql-crunchy-classic/src/test/resources/pg-cluster.yml
service-binding/postgresql-crunchy-reactive/src/main/resources/application.properties
service-binding/postgresql-crunchy-reactive/src/test/resources/pg-cluster.yml

Partially reverts https://github.com/quarkus-qe/quarkus-test-suite/pull/1164, I was convinced it didn't work for me before with `hippo`, but  I made mistake, this puts back original setup.

Revert service binding key back to hippo

---

http/management/src/test/java/io/quarkus/qe/extension/OpenShiftBaseDeploymentIT.java
http/management/src/test/java/io/quarkus/qe/extension/OpenShiftDockerBuildIT.java
http/management/src/test/java/io/quarkus/qe/extension/OpenShiftExtensionIT.java
http/management/src/test/java/io/quarkus/qe/extension/OpenShiftRegistryIT.java
monitoring/micrometer-prometheus/src/test/java/io/quarkus/ts/micrometer/prometheus/OpenShiftCustomMetricsIT.java
monitoring/micrometer-prometheus/src/test/resources/service-monitor.yaml
pom.xml

Follow-up to 2b483fa2165907e5d0f18687896915ccab05e07c
Apps with separate management interface can now be deployed by quarkus openshift-extension
Test plans for the change: https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-2738.md Related links:
https://github.com/quarkusio/quarkus/pull/30506
https://issues.redhat.com/browse/QUARKUS-2738
Depends on https://github.com/quarkus-qe/quarkus-test-framework/pull/747

Cover separate management interface deployed by openshift-extension

---

pom.xml

- we don't use `io.jsonwebtoken` anywhere
- we use different version of Quarkus IDE Config then Quarkus version that we test. Quarkus IDE Config is independent project inside Quarkus main repo and AFAICT it has same release versions as Quarkus have, let see https://mvnrepository.com/artifact/io.quarkus/quarkus-ide-config Also this way, we don't have dependabot to raise version and we spare CI runs

Dependency management cleanup: drop unused JJWT and use Quarkus IDE config version matching tested Quarkus

---

external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftQuickstartIT.java
external-applications/src/test/java/io/quarkus/ts/external/applications/QuickstartIT.java

`getting-started` quickstart migrated to Quarkus 3 in https://github.com/quarkusio/quarkus-quickstarts/commit/cf3ad53b03c2ab2d1df904382e21d8c77118035a.

Enable external application quickstart test

---

external-applications/src/test/java/io/quarkus/ts/external/applications/QuickstartIT.java

Add 2.13 branch specification to the `getting-started` quickstart app. The quickstart `main` has been upgraded to Quarkus 3 in https://github.com/quarkusio/quarkus-quickstarts/commit/cf3ad53b03c2ab2d1df904382e21d8c77118035a.
Related to https://github.com/quarkus-qe/quarkus-test-suite/pull/1198.

[2.13] Fix external application test - quickstart branch

---

sql-db/vertx-sql/src/main/resources/application.properties

Fixes daily build by explicitly setting `migrate-at-start=false`, see https://github.com/quarkusio/quarkus/issues/33058 for more info.

Explicitly disable Flyway migration for Oracle datasource at start

---

sql-db/vertx-sql/src/main/resources/application.properties

Reverts quarkus-qe/quarkus-test-suite#1208 due to https://github.com/quarkusio/quarkus/pull/33078.

Revert "Explicitly disable Flyway migration for Oracle datasource at start" as upstream PR is now reverted too

---

sql-db/panache-flyway/src/test/java/io/quarkus/ts/sqldb/panacheflyway/dbpool/AgroalPoolTest.java

Lately we enabled this test https://github.com/quarkus-qe/quarkus-test-suite/pull/1159 with idea that idle connections should be removed after idle timeout and removal  is executed when validation timeout expires (based on https://agroal.github.io/docs.html `validationTimeout` and `reapTimeout`). I'm not sure whether I read Agroal docs correctly, but one thing is clear - locally test never fails, while in CI it failed couple of days in row now (check daily build), so it must be down to resources.
My thinking is that we should give Agroal time to find out + execute (close connections) and we need to do something as failing test cancel execution of others (we are losing information).

Give AgroalPoolTest#idleTimeoutTest more time to succeed

---

lifecycle-application/pom.xml

Quarkus Test Framework is now using Quarkus 3.0.1.Final and we should keep versions as close as possible considering latest issues https://github.com/quarkus-qe/quarkus-test-suite/pull/1185.

Bump Quarkus version used by Lifecycle app to 3.0.1.Final

---

security/keycloak-oidc-client-extended/src/main/resources/application.properties
security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/BaseOidcIT.java
security/keycloak-oidc-client-reactive-extended/src/main/resources/application.properties
security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/BaseOidcIT.java

`quarkus.http.auth.basic` is a build-time option and is not effective via run-time parameters set using `withProperty`. The earlier PR #1217 was verified using the debugger which seemingly has different behavior around build-time/run-time property setting.

Disable HTTP Basic authentication at build time for extended OIDC ITs

---

sql-db/reactive-vanilla/src/main/java/io/quarkus/ts/reactive/db/clients/CommonResource.java
sql-db/reactive-vanilla/src/main/java/io/quarkus/ts/reactive/db/clients/HardCoverBookResource.java
sql-db/reactive-vanilla/src/main/java/io/quarkus/ts/reactive/db/clients/NoteBookResource.java
sql-db/reactive-vanilla/src/main/java/io/quarkus/ts/reactive/db/clients/SoftCoverBookResource.java
sql-db/reactive-vanilla/src/main/resources/mssql-init-script.sql
sql-db/reactive-vanilla/src/main/resources/mysql-init-script.sql
sql-db/reactive-vanilla/src/main/resources/postgresql-init-script.sql
sql-db/reactive-vanilla/src/test/java/io/quarkus/ts/reactive/db/clients/DevModeMultipleReactiveSqlClientsIT.java

We discussed with @gtroitsk this TODO https://github.com/quarkus-qe/quarkus-test-suite/blob/main/sql-db/reactive-vanilla/src/main/java/io/quarkus/ts/reactive/db/clients/CommonResource.java#L15 and IMO https://github.com/quarkusio/quarkus/issues/19766 is not going to be fixed anytime soon. So when I looked at this, I can't see a point why we should use Flyway at all as these tests are only concerned with Dev Services and if you look to tickets https://issues.redhat.com/browse/QUARKUS-1080 https://issues.redhat.com/browse/QUARKUS-1408 I can't see relation to Flyway either. IMO running this manual init is not a good pattern as your tests don't wait for queries to finish, you just hope they finish before the first test query was triggered. I checked Flyway extension docs and code and while …

Let Dev Services run database init for reactive vanilla clients

---

sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModePostgresqlDevServiceUserExperienceIT.java

Literally every dependabot bump I've reviewed in past weeks had failed `DevModePostgresqlDevServiceUserExperienceIT`. Here https://github.com/quarkus-qe/quarkus-test-suite/pull/1196 I experimentally verified that removing of PG images from Docker works in Github CI and also that test only fails when full CI is running, when just selected modules (those combinations I tested) are run in CI, test passes. Locally it's impossible to reproduce (at least for me).
Only idea I have is to try to use image that no other test is using and see if the test is still flaky. It only "covers" flakyness, but failing test is doing us no good as other runs are cancelled. I do't have better solution, but if there is one, please go ahead.

Use Alpine image for flaky DevModePostgresqlDevServiceUserExperienceIT to mitigate possible causes of failure

---

README.md
monitoring/opentelemetry-reactive/README.md
monitoring/opentelemetry-reactive/pom.xml
monitoring/opentelemetry-reactive/src/main/java/io/quarkus/ts/opentelemetry/reactive/SchedulerResource.java
monitoring/opentelemetry-reactive/src/main/java/io/quarkus/ts/opentelemetry/reactive/SchedulerService.java
monitoring/opentelemetry-reactive/src/test/java/io/quarkus/ts/opentelemetry/reactive/OpentelemetryReactiveIT.java
monitoring/opentelemetry-reactive/src/test/resources/pong.properties
monitoring/opentelemetry/src/main/java/io/quarkus/ts/opentelemetry/MicroProfileTelemetryDIResource.java
monitoring/opentelemetry/src/test/java/io/quarkus/ts/opentelemetry/OpenShiftOpenTelemetryIT.java
monitoring/opentelemetry/src/test/java/io/quarkus/ts/opentelemetry/OpenTelemetryIT.java
monitoring/opentelemetry/src/test/resources/pong.properties
sql-db/narayana-transactions/pom.xml
sql-db/narayana-transactions/src/main/java/io.quarkus.ts.transactions/SpanAsyncService.java
sql-db/narayana-transactions/src/main/java/io.quarkus.ts.transactions/SpanResource.java
sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/DevModeOpenTelemetryIT.java
sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/MssqlTransactionGeneralUsageIT.java
sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/OpenShiftMysqlTransactionGeneralUsageIT.java
sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/OracleTransactionGeneralUsageIT.java
sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/PostgresqlTransactionGeneralUsageIT.java
sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/TransactionCommons.java
sql-db/narayana-transactions/src/test/resources/mariadb_app.properties
sql-db/narayana-transactions/src/test/resources/mssql.properties
sql-db/narayana-transactions/src/test/resources/mysql.properties
sql-db/narayana-transactions/src/test/resources/oracle.properties

- OpenTelemetry JDBC instrumentation added to Narayana Transactions module as we already test there REST traces and start Jaeger:
- tests https://github.com/quarkusio/quarkus/pull/31567, covers scenarios missing in upstream test coverage:
- works in native (also) for MySQL and MSSQL datasource, important for we need to verify their drivers in native
- use actual Jaeger container, upstream uses InMemorySpanExporter or mocks everywhere
- test instrumentation in OpenShift environment with Red Hat registry images
- tests https://github.com/quarkusio/quarkus/pull/28792 as upstream doesn't test this at all
- in order to verify this issue, module `sql-db/narayana-transactions` is now using RESTEasy Reactive, which is preferred REST stack anyway and not relevant for Narayana tests
- [Smallrye …

Quarkus 3 OpenTelemetry hardening

---

http/http-advanced-reactive/src/test/resources/test.properties
lifecycle-application/pom.xml
pom.xml
security/keycloak-jwt/src/test/resources/test.properties
security/keycloak-multitenant/src/test/resources/test.properties
security/keycloak-oidc-client-extended/src/test/resources/test.properties
security/keycloak-oidc-client-reactive-extended/src/test/resources/test.properties
security/keycloak-webapp/src/test/resources/test.properties

https://github.com/quarkus-qe/quarkus-test-framework/pull/781 follow up. Bumps FW, manages HTMLUnit dependency itself and sets is logging to off level

Bump FW to 1.3.0.Beta16, manage HTMLUnit dependency and silent its logging

---

sql-db/hibernate-fulltext-search/src/test/java/io/quarkus/ts/hibernate/search/OpenShiftMysqlMultitenantHibernateSearchIT.java
sql-db/hibernate-fulltext-search/src/test/resources/test.properties

Enables `OpenShiftMysqlMultitenantHibernateSearchIT`. I use env variable for max allowed packets according to container file (basically previous `--max-allowed-packed` is not supported by current image) and enable internal service as URL as for some reason we use HTTP port only for non-internal services https://github.com/quarkus-qe/quarkus-test-framework/blob/c4aa750f09e09e5b69060a285f220d1ac09bf97a/quarkus-test-openshift/src/main/java/io/quarkus/test/services/containers/OpenShiftContainerManagedResource.java#L74. But after all, we already use internal service for PG test in the same module and I don't see anything wrong about that.

Enable and fix OpenShiftMysqlMultitenantHibernateSearchIT

---

pom.xml

Fix corrupted channel trouble with native binary build
Details in https://github.com/quarkus-qe/quarkus-test-framework/issues/785
Relates to https://github.com/quarkus-qe/quarkus-test-framework/pull/786
Example command: `mvn clean verify -Dit.test=WebSocketsClientIT -f websockets/websockets-client -Dnative -Dquarkus.native.container-build=false`

Fix corrupted channel trouble with native binary build

---

external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftQuickstartIT.java

It is now possible to run `OpenShiftQuickstartIT` with Quarkus `999-SNAPSHOT` - https://github.com/quarkus-qe/quarkus-test-framework/pull/768

Enable OpenShiftQuickstartIT with Quarkus 999-SNAPSHOT

---

sql-db/vertx-sql/src/test/java/io/quarkus/ts/vertx/sql/dbpool/PostgresPoolTest.java

Remove magical constant in PostgresPoolTest.
Run this test 10 times, no errors occurred.

Remove magical constant in PostgresPoolTest

---

monitoring/micrometer-prometheus/src/test/java/io/quarkus/ts/micrometer/prometheus/HttpServerMetricsIT.java

Micrometer Prometheus now uses new format without trailing comma.
https://github.com/quarkusio/quarkus/issues/30343

Trailing comma is no longer present in Micrometer Prometheus

---

monitoring/micrometer-prometheus-kafka-reactive/src/main/java/io/quarkus/ts/micrometer/prometheus/kafka/reactive/AlertConsumer.java

* Updating test app to use RestStreamElementType rather than the deprecated RestSseElementType. This also fixes failure of the Kafka tests running with the test app.
Note: I've also opened https://github.com/quarkusio/quarkus/issues/33652 as the deprecated SSE endpoint annotation is broken. Not sure if we want to keep tests for deprecated stuff in main.

Update deprecated usage of RestSseElementType

---

.github/workflows/ci.yml

There has been 21 merged PR for `tj-actions/changed-files` since 11/14/22 when we introduced them. And that's not counting superseded PRs. I analyzed previous major version v35 https://github.com/tj-actions/changed-files/releases/tag/v35 and there are not breaking changes in minor/micro releases. Breaking changes were introduced in v36.0.0 https://github.com/tj-actions/changed-files/releases/tag/v36. IMO we should not waste resources and time for bumps and simply use major version.
```
1a9c138d Bump tj-actions/changed-files from 36.0.8 to 36.0.10
aa33c540 Bump tj-actions/changed-files from 35.9.2 to 36.0.8
856c9350 Bump tj-actions/changed-files from 35.9.1 to 35.9.2
efa1736a Bump tj-actions/changed-files from 35.9.0 to 35.9.1
47c97208 Bump tj-actions/changed-files from 35.8.0 to 35.9.0 …
```

Use only major version tj-actions/changed-files to limit number of bump PRs

---

http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/DevModeHttpMinimumReactiveIT.java
http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/DevModeHttpMinimumIT.java

Daily build is failing (also) because logged message in DEV mode changed, not there is no signature. Caused by https://github.com/quarkusio/quarkus/pull/33685

Fix failing HTTP minimum DEV mode tests as logged message changed

---

http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/DomainSocketIT.java

I don't think https://github.com/quarkusio/quarkus/issues/33679 is getting fixed without next Vert.X release and so far there was no signal that they will revert Vert.X bump. Daily build is failing because of this test.

Disable DomainSocketIT due to upstream bug

---

.github/workflows/quarkus-snapshot.yaml

Fail fast as Ecosystem CI can't handle matrix status update
We have cases when on module fails, GH issue gets reopened and once another module finishes, the issue gets closed. And thus https://status.quarkus.io/ status is always green.

Fail fast as Ecosystem CI can't handle matrix status update

---

http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/DomainSocketIT.java

Enables `DomainSocketIT` as https://github.com/quarkusio/quarkus/issues/33679 was fixed.

Enable DomainSocketIT as upstream issue was fixed

---

security/bouncycastle-fips/bcFipsJsse/src/main/java/io/quarkus/ts/security/bouncycastle/fips/jsse/SecretProvider.java
security/keycloak-oidc-client-extended/src/test/resources/logout.properties
security/keycloak-oidc-client-reactive-extended/src/test/resources/logout.properties
spring/spring-web-reactive/src/main/java/io/quarkus/ts/spring/web/reactive/bootstrap/web/BookController.java
spring/spring-web-reactive/src/test/java/io/quarkus/ts/spring/web/reactive/MariaDBConstants.java

- As you can see in our Jenkins job rhbq-2.13-rhel8-jdk11-baremetal-ts-jvm/jdk=openjdk-11,label=RHEL8%20&&%20large,scenario=security-modules/23/#showFailuresLink branch 2.13 is failing over wrong CORS origin. This change goes down to https://issues.redhat.com/browse/QUARKUS-3159.
- Fixes imports and missing constants as project does not compile. I did poor job when solving merge conflicts of  https://github.com/quarkus-qe/quarkus-test-suite/pull/1270.

[2.13] Fix LogoutSinglePageAppFlowIT.singlePageAppLogoutFlow reactive and classic tests failing over missing CORS origin

---

security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/LogoutSinglePageAppFlowIT.java
security/keycloak-oidc-client-extended/src/test/resources/logout.properties
security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/LogoutSinglePageAppFlowIT.java
security/keycloak-oidc-client-reactive-extended/src/test/resources/logout.properties

Both reactive and classic `OpenShiftOidcSinglePageAppLogoutFlowIT#singlePageAppLogoutFlow` fails in OCP due to incorrect origin as inside OCP no port is used for communication.

[2.13] Fix wrong CORS Keycloak origin in OpenShift

---

README.md
docker-build/src/test/java/io/quarkus/ts/docker/DockerBuildIT.java
messaging/kafka-confluent-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/ConfluentKafkaAvroGroupIdIT.java
messaging/kafka-confluent-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/ConfluentKafkaAvroIT.java
sql-db/sql-app-compatibility/src/test/java/io/quarkus/ts/sqldb/compatibility/DB2DatabaseIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DB2DatabaseIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMariadbDevServicesUserExperienceIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMariadbIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMssqlDevServicesUserExperienceIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMssqlIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMysqlDevServiceUserExperienceIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMysqlIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeOracleDevServiceUserExperienceIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeOracleIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModePostgresqlDevServiceUserExperienceIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModePostgresqlIT.java

Prepare test suite to be runned with podman

---

security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/LogoutSinglePageAppFlowIT.java
security/keycloak-oidc-client-reactive-extended/src/test/resources/logout.properties

Cherry-picked from 32a86701f30a26c10f8322f9269cb283ab2f6542. See related PR
https://github.com/quarkus-qe/quarkus-test-suite/pull/1280.

Fix wrong CORS Keycloak origin in OpenShift

---

security/keycloak-webapp/src/test/java/io/quarkus/ts/security/keycloak/webapp/BaseWebappSecurityIT.java

There was failure in keycloak-webapp module because of typo in BaseWebappSecurityIT appUrl method from https://github.com/quarkus-qe/quarkus-test-suite/pull/1274

Fix app URL parsing bug in BaseWebappSecurityIT

---

messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/SslAlertMonitorIT.java

This test was enabled https://github.com/quarkus-qe/quarkus-test-suite/pull/869 due to upstream issue being fixed https://github.com/quarkusio/quarkus/issues/23964, however I believe that is only the client side as I tested Quarkus Integration test both with and without `kafka.ssl.engine.factory.class` (and so I did with our test) and fact is that Strimzi container won't start as `PBE AlgorithmParameters not available` (when SSL engine factory is set on our TS, ex. is little different but signals provider doesn't know the algorithm).
It should be possible with 0.33+ (by default in 2.13 we are using 0.31) https://strimzi.io/blog/2023/01/25/running-apache-kafka-on-fips-enabled-kubernetes-cluster/ but only thing that I did experienced was different exception. If we want it to work, we need …

[2.13] Disable SslAlertMonitorIT on FIPS compatible machines

---

sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/MsSQLDatabaseHibernateReactiveIT.java
sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/OracleDatabaseIT.java

The Hibernate Reactive bump to 2.0.1.Final solves issue https://github.com/quarkusio/quarkus/issues/32102#issuecomment-1482523629
Upstream PR https://github.com/quarkusio/quarkus/pull/34211 fixes error with MsSQL dialect

Enable Hibernate Reactive tests for Oracle and MsSQL

---

javaee-like-getting-started/pom.xml
javaee-like-getting-started/src/main/resources/application.properties
javaee-like-getting-started/src/test/java/io/quarkus/ts/javaee/gettingstarted/OpenAPITracingIT.java

Tests OpenTelemetry tracing of OpenAPI endpoints `/q/openapi` and `/q/swagger-ui/`.
Follow-up to https://github.com/quarkus-qe/quarkus-test-suite/pull/1265.

Add OTel + OpenAPI test scenario

---

security/jwt/src/test/java/io/quarkus/ts/security/jwt/CookieJwtSecurityIT.java
security/jwt/src/test/java/io/quarkus/ts/security/jwt/Oauth2JwtSecurityIT.java

Backports https://github.com/quarkus-qe/quarkus-test-suite/pull/1296

[2.13] Backport Enable tests from security JWT module on FIPS compatible machines

---

nosql-db/infinispan/pom.xml
nosql-db/infinispan/src/test/java/io/quarkus/ts/infinispan/InfinispanIT.java
quarkus-cli/pom.xml
quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java

First change enables back temporarily disabled test.
The second one disables CLI on native runs (it should be disabled in java code, but that doesn't currenctly work, see commit description for details).
The last one enables back test, which was temporarily disabled on native.

Fix daily runs

---

javaee-like-getting-started/src/test/java/io/quarkus/ts/javaee/gettingstarted/OpenAPITracingIT.java

See resolved issue: https://github.com/quarkusio/quarkus/issues/34376.
Related to https://github.com/quarkus-qe/quarkus-test-suite/pull/1295.

Enable disabled test of OTel + OpenAPI

---

sql-db/vertx-sql/pom.xml

Flyway has been bumped https://github.com/quarkusio/quarkus/pull/34262 to 9.20.0 and our daily build fails over `org.flywaydb.core.api.FlywayException: Unsupported Database: Oracle 21.3`. In order to pass this condition https://github.com/flyway/flyway/blob/5bda08d4b101b30ad6eb9c7ffd6b10a416d5f6ef/flyway-core/src/main/java/org/flywaydb/core/internal/database/DatabaseTypeRegister.java#L100C71-L100C71 we need https://github.com/flyway/flyway/blob/5bda08d4b101b30ad6eb9c7ffd6b10a416d5f6ef/flyway-database-oracle/src/main/java/org/flywaydb/database/oracle/OracleDatabaseType.java#L99 from `flyway-database-oracle` dependency.

Fix Oracle Flyway migration by adding `org.flywaydb:flyway-database-oracle` to Vert.X SQL module

---

messaging/kafka-streams-reactive-messaging/src/main/resources/application.properties
messaging/kafka-streams-reactive-messaging/src/test/resources/kafka.grateful.shutdown.application.properties
scaling/src/main/resources/application.properties
security/jwt/src/main/resources/application.properties
sql-db/hibernate-reactive/src/main/resources/application.properties
super-size/many-extensions/src/main/resources/application.properties

Resolution of this [issue](https://github.com/quarkus-qe/quarkus-test-suite/pull/1299)
Splitting the previous PR into two, this one is about Artemis URL, kafka-streams, and openshift. 
`kafka-streams` and `smallrye.jwt` are migrated. 
`quarkus.openshift.*` are deleted, because openshift is not in the maven profile.
According to [Migration guide](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0#using-persistence-xml-files-and-quarkus-hibernate-orm-configuration-properties-in-the-same-application-will-fail) is `quarkus.hibernate-orm.provider` deleted.
`quarkus.artemis.url` is deprecated, so it is deleted.

Migrate deprecated configuration properties for Artemis URL and kafka

---

pom.xml

Issue was https://github.com/quarkus-qe/quarkus-test-suite/issues/609 was closed.
Docker image naming strategy is clear and documented.

Remove todo with resolved issue from pom - Docker image naming strategy

---

external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftWorkshopHeroesIT.java
external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftWorkshopVillainsIT.java

- `OpenShiftWorkshopHeroesIT` is using specific commit `5bb433fb7a2c8d80dda88dac9dcabc50f7494dc3` from Quarkus 2.x, therefore tests failed when run with Quarkus 3.x over Jakarta imports. Pablo insisted here https://github.com/quarkus-qe/quarkus-test-suite/pull/547#discussion_r826789844 it was necessary and opened https://github.com/quarkus-qe/quarkus-test-framework/issues/432, however import issue only affects `OpenShiftWorkshopVillainsIT` now
- removing metrics scenarios because it is unclear to me why it should work - there is no Micrometer or Smallrye Metrics dependency in https://github.com/quarkusio/quarkus-workshops/blob/main/quarkus-workshop-super-heroes/super-heroes/rest-heroes/pom.xml or parent, it probably changed
- Enables the test for snapshot as now we support that in our FW …

Fix OpenShiftWorkshopHeroesIT so that it does not fail with RHBQ Ghost

---

http/graphql-telemetry/src/test/java/io/quarkus/ts/http/graphql/telemetry/GraphQLTelemetryIT.java
http/vertx-web-client/src/test/java/io/quarkus/ts/http/vertx/webclient/VertxWebClientIT.java
monitoring/opentelemetry-reactive/src/test/java/io/quarkus/ts/opentelemetry/reactive/OpenTelemetryGrpcIT.java
monitoring/opentelemetry-reactive/src/test/java/io/quarkus/ts/opentelemetry/reactive/OpenTelemetrySseIT.java
monitoring/opentelemetry-reactive/src/test/java/io/quarkus/ts/opentelemetry/reactive/OpentelemetryReactiveIT.java
monitoring/opentelemetry/src/test/java/io/quarkus/ts/opentelemetry/OpenTelemetryGrpcIT.java
monitoring/opentelemetry/src/test/java/io/quarkus/ts/opentelemetry/OpenTelemetryIT.java
monitoring/opentelemetry/src/test/java/io/quarkus/ts/opentelemetry/OpenTelemetrySseIT.java
sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/MariaDbTransactionGeneralUsageIT.java
sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/MssqlTransactionGeneralUsageIT.java
sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/MysqlTransactionGeneralUsageIT.java
sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/OpenShiftMariaDbTransactionGeneralUsageIT.java
sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/OpenShiftMysqlTransactionGeneralUsageIT.java
sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/OracleTransactionGeneralUsageIT.java
sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/PostgresqlTransactionGeneralUsageIT.java
sql-db/narayana-transactions/src/test/resources/mariadb_app.properties
sql-db/narayana-transactions/src/test/resources/mssql.properties
sql-db/narayana-transactions/src/test/resources/mysql.properties
sql-db/narayana-transactions/src/test/resources/oracle.properties
sql-db/narayana-transactions/src/test/resources/postgresql.properties

Resolution of this [issue](https://github.com/quarkus-qe/quarkus-test-suite/pull/1304)
According to [Migration Guide](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0#opentelemetry), we need to migrate `quarkus.opentelemetry.enabled` on `quarkus.otel.enabled`.
Then we migrate `quarkus.otel.tracer.exporter.otlp.endpoint` on `quarkus.otel.exporter.otlp.traces.endpoint`.  
We don't use `quarkus.otel.exporter.otlp.traces.legacy-endpoint` from the  [Migration Guide](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0#opentelemetry) because of the reasons mentioned in the previous  [PR](https://github.com/quarkus-qe/quarkus-test-suite/pull/1299#pullrequestreview-1510535072).
The property `quarkus.otel.enabled` must be in ` postgresql.properties` and applied in …

Migrate deprecated configuration properties for OpenTelemtry

---

pom.xml

Issue https://github.com/docker-library/mysql/issues/844 was closed

Bump MySQL Docker image to 5.7.42

---

pom.xml
sql-db/hibernate-fulltext-search/src/test/java/io/quarkus/ts/hibernate/search/MysqlMultitenantHibernateSearchIT.java
sql-db/hibernate-fulltext-search/src/test/java/io/quarkus/ts/hibernate/search/OpenShiftMysqlMultitenantHibernateSearchIT.java
sql-db/hibernate-fulltext-search/src/test/java/io/quarkus/ts/hibernate/search/OpenShiftPostgresqlMultitenantHibernateSearchIT.java
sql-db/hibernate-fulltext-search/src/test/java/io/quarkus/ts/hibernate/search/PostgresqlMultitenantHibernateSearchIT.java

Use official docker image for Elasticsearch and bump it to 7.17.10
Limit resources to use at max 1 GB as Elasticsearch official docker image use be default half of available RAM

Use official docker image for Elasticsearch

---

http/management/src/test/java/io/quarkus/qe/extension/OpenShiftDockerBuildIT.java
http/management/src/test/java/io/quarkus/qe/extension/OpenShiftExtensionIT.java
monitoring/micrometer-prometheus/src/test/java/io/quarkus/ts/micrometer/prometheus/OpenShiftCustomMetricsIT.java

Disable tests which use management interface, since [1] does not seem to be fixed soon and we need working weeklies
[1] https://github.com/quarkusio/quarkus/issues/34645

Disable tests which use management interface

---

config/src/main/resources/application.properties
config/src/test/resources/config-source-priority.properties
config/src/test/resources/secret.api-server.properties

Our openshift builds now fail with error`java.lang.StringIndexOutOfBoundsException: begin 34, end -1, length 41`.
Bisection shows, that this is caused by parameter `quarkus.kubernetes-config.secrets.enabled=true`.
It seems, that the Framework changes this parameter into some kind of environment variable (or even two) and thus breaks Smallrye.
Since this option is fixed[1] at build time anyway, I suggest to simply move it into application.properties.
[1] https://quarkus.io/guides/kubernetes-config#quarkus-kubernetes-config_quarkus.kubernetes-config.secrets.enabled

Fix for Openshift builds

---

spring/spring-data/src/main/java/io/quarkus/ts/spring/data/nameddatasource/AlternativeArticle.java
spring/spring-data/src/main/java/io/quarkus/ts/spring/data/nameddatasource/AlternativeArticleJpaRepository.java
spring/spring-data/src/main/resources/application.properties
spring/spring-data/src/main/resources/named-ds-import.sql
spring/spring-data/src/test/java/io/quarkus/ts/spring/data/di/SpringDiIT.java
spring/spring-data/src/test/java/io/quarkus/ts/spring/data/rest/JpaRepositoryRestResourceIT.java
sql-db/hibernate/src/main/java/io/quarkus/qe/hibernate/analyze/Analyze.java
sql-db/hibernate/src/main/java/io/quarkus/qe/hibernate/analyze/AnalyzeResource.java
sql-db/hibernate/src/main/java/io/quarkus/qe/hibernate/items/Account.java
sql-db/hibernate/src/main/java/io/quarkus/qe/hibernate/items/Customer.java
sql-db/hibernate/src/main/java/io/quarkus/qe/hibernate/items/Item.java
sql-db/hibernate/src/main/java/io/quarkus/qe/hibernate/items/Role.java
sql-db/hibernate/src/main/resources/application.properties
sql-db/hibernate/src/main/resources/import.sql
sql-db/hibernate/src/test/java/io/quarkus/qe/hibernate/BaseHibernateIT.java
sql-db/multiple-pus/src/main/java/io/quarkus/ts/sqldb/multiplepus/FungiTenantResolver.java
sql-db/multiple-pus/src/main/java/io/quarkus/ts/sqldb/multiplepus/FungusResource.java
sql-db/multiple-pus/src/main/java/io/quarkus/ts/sqldb/multiplepus/model/fungus/Fungus.java
sql-db/multiple-pus/src/main/resources/application.properties
sql-db/multiple-pus/src/main/resources/import-fungi.sql
sql-db/multiple-pus/src/test/java/io/quarkus/ts/sqldb/multiplepus/AbstractMultiplePersistenceIT.java

Verifies:
- https://github.com/quarkusio/quarkus/issues/28593 - allows setting quotation strategy
- https://github.com/quarkusio/quarkus/issues/28644 - multitennancy with discriminator column (as so far, we only tested db and scheme)
- https://github.com/quarkusio/quarkus/issues/24075 - Spring Data JPA repositories should support named datasources
Refactor:
- move `SpringDiIT` from `io.quarkus.ts.spring.data.rest` to `io.quarkus.ts.spring.data.di` package

Modest Hibernate hardening

---

config/src/main/resources/application.properties
config/src/test/java/io/quarkus/ts/configmap/api/server/OpenShiftConfigSourcePriorityIT.java

Quarkus 3 allows making K8s manifests more Git-friendly [1]
We cover them with these changes, with a single exception[2]
[1] https://github.com/quarkusio/quarkus/pull/31373
[2] https://github.com/quarkusio/quarkus/issues/34673

Cover GitOps friendly Kubernetes additions

---

http/management/src/main/resources/application.properties

Due to a change[1] made upstream  OpenAPI is now deployed on management interface by default. This breaks our tests, so we should use an option to disable this behavior (and verify, that this option works).
[1] https://github.com/quarkusio/quarkus/issues/34353

Force Openapi to use non-management interface

---

.github/workflows/daily.yaml
service-binding/postgresql-crunchy-classic/src/test/java/io/quarkus/ts/sb/postgresql/OpenShiftPostgreSqlSbIT.java

- Disable test with a known bug
- Distribute the load of native runs of sql-db module between two actions

Fix daily and weekly runs

---

infinispan-client/src/test/java/io/quarkus/ts/infinispan/client/OperatorOpenShiftInfinispanCountersIT.java

Attempt to solve weekly failure, when app can not found the cluster while running on Openshift
Fixes fails in `testRestartInfinispanCluster` method. Occasional failure in logger while closing should be addressed in the FW.

Attempt to solve weekly failure, when app can not found the cluster while running on Openshift

---

.gitignore
README.md
build-time-analytics/README.md
build-time-analytics/pom.xml
build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/AbstractAnalyticsIT.java
build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/AnalyticsFilesUtils.java
build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/AnalyticsUtils.java
build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/DevModeIT.java
build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/PayloadExtension.java
build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/ProdModeJvmIT.java
build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/ProdModeNativeIT.java
build-time-analytics/src/test/resources/local-config-disabled.json
build-time-analytics/src/test/resources/local-config-enabled.json
build-time-analytics/src/test/resources/remote-config-disabled.json
build-time-analytics/src/test/resources/remote-config-enabled.json
build-time-analytics/src/test/resources/remote-config-refreshable.json
build-time-analytics/src/test/resources/test.properties
pom.xml

Add test coverage for build analytics
- JIRA: https://issues.redhat.com/browse/QUARKUS-2812
- Test plan: https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-2812.md
- Introduce 3 new scenarios: dev mode, JVM, native.
- Uses Quarkus CLI to create/build/run applications and inspects the build analytics behavior.
Add .quarkus directory to .gitignore
- `.quarkus` directory is created by Quarkus CLI, which stores catalog information in `.quarkus/cli/plugins/quarkus-cli-catalog.json`.

Add test coverage for build analytics

---

sql-db/narayana-transactions/src/main/resources/application.properties
sql-db/narayana-transactions/src/test/resources/postgresql.properties

I changed expected build time property from `quarkus.opentelemetry.enabled` to `quarkus.otel.enabled` for former is deprecated and latter didn't trigger customized build https://github.com/quarkus-qe/quarkus-test-framework/pull/829. Here https://github.com/quarkus-qe/quarkus-test-suite/pull/1326 I didn't realize failure is related. Now we use `quarkus.otel.enabled` which triggers custom build and therefore, runs PG test with enabled OpenTelemetry.

Fix PostgresqlTransactionGeneralUsageIT traces by migrating to otel config property

---

build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/DevModeIT.java

Daily build failed over build time analytics https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/5687247780. I can't reproduce it, so I am guessing (therefore let see CI). Here is my conclusion:
- service didn't start fast enough because it tried to pull and start several containers (Keycloak, Infinispan, k8s.gcr.io/etcd, k8s.gcr.io/kube-apiserver, vectorized/redpanda
- this is right step anyway (fix or not) as we can save execution time and it has no effect on collected analytics.

Fix flaky build time analytics failure due to slow app startup

---

websockets/quarkus-websockets/src/main/java/io/quarkus/ts/websockets/producer/Pusher.java
websockets/quarkus-websockets/src/test/java/io/quarkus/ts/websockets/producer/WebSocketsProducerConsumerIT.java
websockets/websockets-client/src/main/java/io/quarkus/ts/websockets/client/Pusher.java

Quarkus WebSockets session handling working as expected. I prove it with debug prints.
Client onMessage: Several identical messages are sent asynchronously to all connected clients through broadcast. Each client has own session opened once and closed at the end. 
Pusher onOpen: In debug helpful prints I see all messages

Remove todos from WebSockets modules

---

README.md
pom.xml

Rename properties, which were removed[1] two years ago and use recommended image[2] as a base for s2i
[1] https://github.com/quarkus-qe/quarkus-test-framework/pull/309
[2] https://github.com/quarkusio/quarkus-images#quarkus-images-1:
```
ubi-quarkus-native-binary-s2i - S2I builder image for OpenShift taking a pre-built native executable as input
```

Rename outdated properties

---

.github/workflows/daily.yaml

Daily build is failing several days in row over native build timeout (mostly) and sometimes over OOM when building build time analytics executable for tests of many extensions together. I went couple of builds back and messaging/websockets are always by far the fastest both in native and JVM. By moving monitoring modules and testing tooling module we should have load spread better over runs. Just the fact that it times out after 6 hours is a bad sign when messaging/websockets takes about hour and half.

Fix daily build by re-coupling modules run together so that we don't timeout and avoid OOM

---

pom.xml

Here https://github.com/quarkus-qe/quarkus-test-suite/pull/1338. we saw failure in modules `SQL Database: Narayana-transactions`, `Hibernate Reactive`, `Vert.x SQL`, `RESTEasy Reactive + Rest Data Panache` as Oracle image run out of space In fact, we already saw it few times in past (I'm only going to find it on demand) and we also saw the same thing in Test Framework https://github.com/quarkus-qe/quarkus-test-suite/pull/1338. I think it is super suspicious that 4 modules run out of space when pulling and starting the very same image. My proposal is to use newer Oracle image also used by dev services as we don't have specific reason to use Oracle 21 (and the reason to use `oracle-xe` instead of `oracle-free`). So far I didn't see the same failure there and it is worth trying.
Please …

Use same Oracle image as dev services

---

websockets/quarkus-websockets/src/test/java/io/quarkus/ts/websockets/producer/WebSocketsProducerConsumerIT.java

Client's session must be opened just once, onOpen method is called only once. This PR adds assert to all existing tests that checks that.

Add client session single opening assert to WebSockets tests

---

lifecycle-application/pom.xml

Use 2.13.8 from Red Hat maven repository. Also adds plugin repository as Quarkus Maven plugin requires it.
Related to https://issues.redhat.com/browse/QUARKUS-3101

[2.13] Use Red Hat maven repository for lifecycle application

---

sql-db/vertx-sql/src/test/java/io/quarkus/ts/vertx/sql/handlers/OracleHandlerIT.java

After https://github.com/quarkus-qe/quarkus-test-suite/pull/1339 we experience https://github.com/eclipse-vertx/vertx-sql-client/issues/1343. We didn't run full CI there I think for it cancelled, that is worked on in https://github.com/quarkus-qe/quarkus-test-suite/pull/1340. Daily build fails also because of this issue.
You can reproduce failure on main in `sql-db/vertx-sql` module with `mvn clean verify -Dit.test=OracleHandlerIT`.

Workaround Oracle Vert.x issue with auto-generated ids

---

pom.xml

* Bump Quarkus Platform to 3.2.3.Final
Note: There's two issues that are supposedly fixed - https://github.com/quarkusio/quarkus/issues/31117 and https://github.com/quarkusio/quarkus/issues/13660 ; but the tests are still failing:
* `GrpcTraceIT` is disabled because of https://github.com/quarkusio/quarkus/issues/13660
* `AbstractDatabaseHibernateReactiveIT#newLineInQuery` is disabled because of https://github.com/quarkusio/quarkus/issues/31117

Bump to Quarkus 3.2.3.Final

---

.github/workflows/ci.yml

Any PR that makes changes in POM or a file that is not specific for some module (like dependabot often does) has run full test coverage. Our 4 hours timeout is not enough, this PR makes sure that when the full test coverage is run, we divide it into 2 runners in JVM. Native is not an issue as we don't run there full test coverage.

PR CI workflow for JVM snapshot needs to be divided when full test coverage is required

---

.github/workflows/ci.yml
.github/workflows/daily.yaml

Daily build in native is failing for several days in row as 
```
2023-08-04T04:57:17.3514775Z 04:40:29,705 INFO  [org.inf.HOTROD] ISPN004074: Native Epoll transport not available, using NIO instead: io.netty.channel.epoll.Epoll
2023-08-04T04:57:17.3515138Z 04:40:29,709 INFO  [org.inf.HOTROD] ISPN004108: Native IOUring transport not available, using NIO instead: io.netty.incubator.channel.uring.IOUring
2023-08-04T04:57:17.3515380Z Terminating due to java.lang.OutOfMemoryError: GC overhead limit exceeded
```
GraalVM GC use max 80% of physical memory https://www.graalvm.org/latest/reference-manual/native-image/optimizations-and-performance/MemoryManagement/ by default. Not sure that setting `MaximumHeapSizePercent` is great idea though, for we can't really tell how much memory is available …

Limit Java heap used during native image generation to fix build time analytics native failures

---

build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/ProdModeNativeIT.java

Native build fails with OOM as Github CI runners don't have that much of a memory. So we set maximum here https://github.com/quarkus-qe/quarkus-test-suite/pull/1346 but I didn't realize it is not propagated down to the application.

Propagate max Java heap used during native image generation down to build time analytics app builder

---

http/rest-client-reactive/pom.xml
http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/LargeFileHandlingIT.java
http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientIT.java
http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientProxyIT.java

Hi, this PR remove the disabled annotation on tests affected by by quarkus-qe/quarkus-test-framework#584.
It can be merged after the quarkus-qe/quarkus-test-framework#842 is merged and new version of framework is released and updated.

Enable tests after fixing quarkus-qe/quarkus-test-framework#584.

---

pom.xml

Make IDE config version independent from Quarkus platform version, since extension `quarkus-ide-config` is not productised.
This change partially reverts https://github.com/quarkus-qe/quarkus-test-suite/pull/1194

Make IDE config version independent from Quarkus platform version

---

http/vertx/src/test/java/io/quarkus/ts/vertx/AbstractVertxIT.java

- Tweak vertx http client request in the test cases.
- Added http2 protocol and request with name parameter test cases.

Add http vertx client test cases to http/vertx scenario

---

README.md
sql-db/narayana-transactions/src/main/java/io/quarkus/ts/transactions/recovery/TransactionExecutor.java
sql-db/narayana-transactions/src/main/java/io/quarkus/ts/transactions/recovery/TransactionLogsResource.java
sql-db/narayana-transactions/src/main/java/io/quarkus/ts/transactions/recovery/TransactionRecoveryService.java
sql-db/narayana-transactions/src/main/java/io/quarkus/ts/transactions/recovery/driver/CrashingXAConnection.java
sql-db/narayana-transactions/src/main/java/io/quarkus/ts/transactions/recovery/driver/CrashingXADataSource.java
sql-db/narayana-transactions/src/main/java/io/quarkus/ts/transactions/recovery/driver/CrashingXAResource.java
sql-db/narayana-transactions/src/main/java/io/quarkus/ts/transactions/recovery/service/AnnotationTransactionRecoveryService.java
sql-db/narayana-transactions/src/main/java/io/quarkus/ts/transactions/recovery/service/InjectedTransactionManagerRecoveryService.java
sql-db/narayana-transactions/src/main/java/io/quarkus/ts/transactions/recovery/service/InjectedUserTransactionRecoveryService.java
sql-db/narayana-transactions/src/main/java/io/quarkus/ts/transactions/recovery/service/QuarkusTransactionCallRecoveryService.java
sql-db/narayana-transactions/src/main/java/io/quarkus/ts/transactions/recovery/service/QuarkusTransactionRecoveryService.java
sql-db/narayana-transactions/src/main/java/io/quarkus/ts/transactions/recovery/service/StaticTransactionManagerRecoveryService.java
sql-db/narayana-transactions/src/main/java/io/quarkus/ts/transactions/recovery/service/StaticUserTransactionRecoveryService.java
sql-db/narayana-transactions/src/main/resources/application.properties
sql-db/narayana-transactions/src/main/resources/import.sql
sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/MariaDbTransactionGeneralUsageIT.java
sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/MssqlTransactionGeneralUsageIT.java
sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/MysqlTransactionGeneralUsageIT.java
sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/OpenShiftMariaDbTransactionGeneralUsageIT.java
sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/OpenShiftMysqlTransactionGeneralUsageIT.java
sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/OpenShiftPostgresqlTransactionGeneralUsageIT.java
sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/OracleTransactionGeneralUsageIT.java
sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/PostgresqlTransactionGeneralUsageIT.java
sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/TransactionCommons.java
sql-db/narayana-transactions/src/test/resources/mariadb_import.sql
sql-db/narayana-transactions/src/test/resources/mssql_import.sql
sql-db/narayana-transactions/src/test/resources/mysql_import.sql
sql-db/narayana-transactions/src/test/resources/oracle_import.sql

Adds transaction recovery test coverage for native and JVM. OpenShift will require changes in Test Framework that I didn't really explore yet. IMHO there is plenty of changes already and we should wait for OCP. DEV mode is something that is worth to do (especially due to https://github.com/quarkusio/quarkus/issues/34576#event-10010650889), but not part of original test plan here https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-2739.md and I didn't get to it yet.

Add JDBC transaction recovery for JVM and native scenarios

---

http/http-advanced-reactive/pom.xml
http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/MultipartResource.java

Move to MultipartFormDataInput from RESTEasy Reactive for `http/http-advanced-reactive` module
https://github.com/quarkusio/quarkus/pull/30307 introduced MultipartFormDataInput for RESTEasy Reactive in Quarkus 3.0.0.
resteasy-multipart-provider causes troubles in native as it pulls in several RESTEasy Classic dependencies.
`jakarta.validation` dependency needs to defined explicitly (needed by io.quarkus.ts.http.advanced.reactive.Hello), before it was pulled in transitively by RESTEasy Classic.
Fixes https://issues.redhat.com/browse/QUARKUS-3308 issue, needs to be backported to 3.2 branch.

Move to MultipartFormDataInput from RESTEasy Reactive

---

build-time-analytics/pom.xml

Build-time analytics can be disabled by `CI` environment variable. This fix explicitly sets the value of the variable to `false` for both surefire and failsafe executions in the analytics module, so that it gets executed in every environment.
The module itself works around the reasons this feature has been added to Quarkus, which is the fact that the initial analytics user prompt cannot be acted upon in CI environments.
See https://github.com/quarkusio/quarkus/pull/35456.

Fix analytics disabled by CI

---

monitoring/opentracing-reactive-grpc/pom.xml
monitoring/opentracing-reactive-grpc/src/test/java/io/quarkus/ts/monitoring/opentracing/reactive/grpc/ServerSentEventsTraceOpentracingIT.java

Move fully to RESTEasy Reactive, disable SSE scenario
Quarkus main now detects mixture of RESTEasy Reactive and RESTEasy Classic. Thus the build fails for monitoring/opentracing-reactive-grpc which used Mutiny on top of RESTEasy Classic.
Example: https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/5950642487/job/16140058276?pr=1372
I had to disable SSE scenario because of https://github.com/quarkusio/quarkus/issues/29539 which was closed as won't fix

Move fully to RESTEasy Reactive for opentracing-reactive-grpc, disable SSE scenario

---

.github/ci-init.sh
.github/quarkus-ecosystem-test

Install the command in a custom init script (provided by https://github.com/quarkusio/quarkus-ecosystem-ci/pull/140).
The custom script uses `jbang` to install Quarkus CLI from most recently built Quarkus artifacts.
This should ensure that tests which use the CLI don't fail in the Quarkus ecosystem GH environment.
See an example of such a failure at
https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/5947272576/job/16129106765.

Install Quarkus CLI in Quarkus Ecosystem GH action

---

sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMariadbDevServicesUserExperienceIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMariadbIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMssqlDevServicesUserExperienceIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMssqlIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMysqlDevServiceUserExperienceIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMysqlIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeOracleDevServiceUserExperienceIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeOracleIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModePostgresqlDevServiceUserExperienceIT.java
sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModePostgresqlIT.java

Enable tests which were disabled on outdated Podman 4.5.1

---

http/http-advanced-reactive/pom.xml
http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/AbstractDevModeIT.java
http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/BaseHttpAdvancedReactiveIT.java
http/http-advanced-reactive/src/test/resources/test.properties
pom.xml
security/keycloak-jwt/pom.xml
security/keycloak-jwt/src/test/java/io/quarkus/ts/security/keycloak/jwt/BaseOidcJwtSecurityIT.java
security/keycloak-jwt/src/test/resources/test.properties
security/keycloak-multitenant/pom.xml
security/keycloak-multitenant/src/test/java/io/quarkus/ts/security/keycloak/multitenant/BaseMultiTenantSecurityIT.java
security/keycloak-multitenant/src/test/resources/test.properties
security/keycloak-oidc-client-extended/pom.xml
security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/LogoutSinglePageAppFlowIT.java
security/keycloak-oidc-client-extended/src/test/resources/test.properties
security/keycloak-oidc-client-reactive-extended/pom.xml
security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/LogoutSinglePageAppFlowIT.java
security/keycloak-oidc-client-reactive-extended/src/test/resources/test.properties
security/keycloak-webapp/pom.xml
security/keycloak-webapp/src/test/java/io/quarkus/ts/security/keycloak/webapp/BaseWebappSecurityIT.java
security/keycloak-webapp/src/test/resources/test.properties

* Updating htmlunit to 3.5.0, along with relocations required by the htmlunit migration guide (https://www.htmlunit.org/migration.html).

[3.2] Bump htmlunit to 3.5.0

---

http/management/src/test/java/io/quarkus/qe/extension/OpenShiftRegistryIT.java

* It is currently impossible to run registry tests on aarch64. The test builds the application container on machine where the test is ran, pushes it to quay.io and deploys the container to OpenShift. So, in in our case it means the container is built for x86_64 arch, but we need aarch64.

Disabling registry tests on OCP on aarch64

---

http/management/src/test/java/io/quarkus/qe/extension/OpenShiftRegistryIT.java

* It is currently impossible to run registry tests on aarch64. The test builds the application container on machine where the test is ran, pushes it to quay.io and deploys the container to OpenShift. So, in in our case it means the container is built for x86_64 arch, but we need aarch64.
Backport of #1390 

[3.2] Disabling registry tests on OCP on aarch64

---

http/vertx/src/main/java/io/quarkus/ts/vertx/GreetingService.java
http/vertx/src/main/java/io/quarkus/ts/vertx/HelloResource.java
http/vertx/src/main/java/io/quarkus/ts/vertx/SecondGreetingService.java
http/vertx/src/test/java/io/quarkus/ts/vertx/AbstractVertxIT.java
http/vertx/src/test/java/io/quarkus/ts/vertx/Metric.java
monitoring/opentelemetry-reactive/pom.xml
monitoring/opentelemetry-reactive/src/test/java/io/quarkus/ts/opentelemetry/reactive/OpenTelemetryGrpcIT.java
sql-db/vertx-sql/pom.xml
sql-db/vertx-sql/src/test/java/io/quarkus/ts/vertx/sql/handlers/CommonTestCases.java
sql-db/vertx-sql/src/test/java/io/quarkus/ts/vertx/sql/handlers/MssqlHandlerIT.java
sql-db/vertx-sql/src/test/java/io/quarkus/ts/vertx/sql/handlers/MysqlHandlerIT.java
sql-db/vertx-sql/src/test/java/io/quarkus/ts/vertx/sql/handlers/OracleHandlerIT.java
sql-db/vertx-sql/src/test/java/io/quarkus/ts/vertx/sql/handlers/PostgresqlHandlerIT.java

Coverage for Full support of Vertx metrics, see https://issues.redhat.com/browse/QUARKUS-2830 for details.
Test plan: https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-2830.md

Verify, that VertX pool metrics are being collected

---

sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/OpenShiftMariaDbTransactionGeneralUsageIT.java
sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/OpenShiftMysqlTransactionGeneralUsageIT.java
sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/OpenShiftPostgresqlTransactionGeneralUsageIT.java
sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/TransactionCommons.java

Fixes Postgres and MariaDB OpenShift test coverage for transaction recovery. MySQL doesn't work and I'm perplexed why. As for Oracle & MsSQL, I'm working on baremetal fixes, but it's either not as trivial as it is described here https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.1/html/configuration_guide/datasource_management#vendor_specific_xa_recovery or I'm making some mistakes. Shall see.

Fix Narayana transaction recovery tests for Postgres and MariaDB in OpenShift

---

quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateNativeApplicationIT.java

The `QuarkusCliCreateNativeApplicationIT` is a native app test but comment says it's only for JVM verification. Technically I added the comment here https://github.com/quarkus-qe/quarkus-test-suite/pull/1230/files#diff-13508bdf64e26bd4341b3f69c458f8ca4a0839cc266ff95fcf11aee3cc181c6a but I only replaced original `@DisabledIfSystemProperty(named = "profile.id", matches = "native", disabledReason = "Only for JVM verification")` so I think it is there for a long time and can't tell why.

Only enable native CLI test in native

---

README.md
nosql-db/elasticsearch/pom.xml
nosql-db/elasticsearch/src/main/java/io/quarkus/ts/elasticsearch/DataTypes.java
nosql-db/elasticsearch/src/main/java/io/quarkus/ts/elasticsearch/DataTypesResource.java
nosql-db/elasticsearch/src/main/java/io/quarkus/ts/elasticsearch/DataTypesService.java
nosql-db/elasticsearch/src/main/java/io/quarkus/ts/elasticsearch/Fruit.java
nosql-db/elasticsearch/src/main/java/io/quarkus/ts/elasticsearch/FruitResource.java
nosql-db/elasticsearch/src/main/java/io/quarkus/ts/elasticsearch/FruitService.java
nosql-db/elasticsearch/src/test/java/io/quarkus/ts/elasticsearch/DevModeElasticsearchIT.java
nosql-db/elasticsearch/src/test/java/io/quarkus/ts/elasticsearch/ElasticsearchIT.java
pom.xml
sql-db/hibernate-fulltext-search/src/test/java/io/quarkus/ts/hibernate/search/MysqlMultitenantHibernateSearchIT.java
sql-db/hibernate-fulltext-search/src/test/java/io/quarkus/ts/hibernate/search/OpenShiftMysqlMultitenantHibernateSearchIT.java
sql-db/hibernate-fulltext-search/src/test/java/io/quarkus/ts/hibernate/search/OpenShiftPostgresqlMultitenantHibernateSearchIT.java
sql-db/hibernate-fulltext-search/src/test/java/io/quarkus/ts/hibernate/search/PostgresqlMultitenantHibernateSearchIT.java

- Test coverage for elasticsearch-rest-client (https://issues.redhat.com/browse/QUARKUS-3260)
- Rename elastic.71.image property to elastic.7x.image, use the latest 7.x version
`DevModeElasticsearchIT` uses devservices with Elasticsearch 8, `ElasticsearchIT` uses `elastic.7x.image`
Future AIs (tracked in GH issue https://github.com/quarkus-qe/quarkus-test-suite/issues/1402):
- Move to Elasticsearch 8, focus on `sql-db/hibernate-fulltext-search`
- Introduce quarkus-test-service-elasticsearch in https://github.com/quarkus-qe/quarkus-test-framework and use it here

Test coverage for elasticsearch-rest-client

---

quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java

`QuarkusCliCreateJvmApplicationIT` is failing on Windows for we try to delete service folder while still working with pom and other files. This fixed issue.
There is remaining issue with deleting `quarkus-cli-command.out`, but it can't be fixed only from here. I'm also not sure how to fix it at all.

Fix most of QuarkusCliCreateJvmApplicationIT file handling (but not all) on Windows

---

quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliSpecialCharsIT.java

- Separating `--output-directory` and `folder` fixes `shouldCreateApplicationOnJvmWithSpaces`
- Enclosing folder name inside double quotes helped to get further in `shouldCreateApplicationOnJvmWithSpecialChars`, but it later fails on `whenBuildOnJvmAppAt` (unrelated to changes here). I guess it needs fixing in FW, but won't know until I understand what is causing it.
- `[ERROR]   QuarkusCliSpecialCharsIT.shouldCreateApplicationOnJvmWithSpecialChars:55->assertCreateJavaApplicationAtFolder:123->thenBuildOutputIsSuccessful:151->thenResultIsSuccessful:147 Something failed, output: 'C:\Users\hudson\quarkus-test-suite\quarkus-cli\target\' is not recognized as an internal or external command,`

Test Suite part of the QuarkusCliSpecialCharsIT fixes for Windows - ensure proper folder name escaping

---

quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliSpecialCharsIT.java

backports https://github.com/quarkus-qe/quarkus-test-suite/pull/1414

[3.2] Disable special chars CLI test on Windows due to upstream bug

---

pom.xml

Quarkus Quickstarts are using this extension for their Github actions and I find it very useful to detect which base dirs should contains reports, especially for multiple submodules.

Collect and generate build reports used by AWS Windows instanced to analyze reports

---

quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java

Disable shouldCreateApplicationWithGradleOnJvm
Disable the test in 3.2 because of [QUARKUS-3439](https://issues.redhat.com/browse/QUARKUS-3439)

Disable shouldCreateApplicationWithGradleOnJvm

---

quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java

Disable the test in 3.2 because of [QUARKUS-3371](https://issues.redhat.com/browse/QUARKUS-3371)

Disable shouldCreateApplicationWithJbangOnJvm

---

security/keycloak-oidc-client-reactive-extended/src/test/resources/logout.properties

* Updating CORS policy for app in keycloak-oidc-client-reactive-extended module. Currently, the policy in test app only allows for access from the same domain where the test Keycloak is setup. This setup will not work in scenarios where the test is ran on domain different than that (e.g. our Aarch64 testing).
Note: this CORS wildcard is also used in the keycloak-oidc-client-extended module. I am not sure if this is the most correct solution, but it should work for the purposes of this test.

[3.2] Updating CORS policy for app in oidc reactive

---

security/keycloak-oidc-client-reactive-extended/src/test/resources/logout.properties

* Updating CORS policy for app in keycloak-oidc-client-reactive-extended module. Currently, the policy in test app only allows for access from the same domain where the test Keycloak is setup. This setup will not work in scenarios where the test is ran on domain different than that (e.g. our Aarch64 testing).

Updating CORS policy for app in oidc reactive

---

sql-db/panache-flyway/src/test/java/io/quarkus/ts/sqldb/panacheflyway/dbpool/AgroalPoolTest.java
sql-db/vertx-sql/src/test/java/io/quarkus/ts/vertx/sql/dbpool/PostgresPoolTest.java

Tested 5 times in row didn't fail with this.
You can see that `PostgresPoolTest` and `AgroalPoolTest` always fail on Windows (you can reproduce it anytime, please refer to our Jenkins jobs), but I can't reproduce it with WebClient. With RestAssured, something like this happen:
```
[ERROR] io.quarkus.ts.vertx.sql.dbpool.PostgresPoolTest.checkDbPoolTurnover  Time elapsed: 28.145 s  <<< ERROR!
java.net.BindException: Address already in use: no further information
at java.base/sun.nio.ch.Net.pollConnect(Native Method)
at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:547)
at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) …
```

Fix PostgresPoolTest and AgroalPoolTest on Windows by using WebClient as RestAssured doesn't close connection correctly

---

http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/OpenShiftHttpAdvancedReactiveIT.java
http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/OpenShiftHttpAdvancedIT.java
http/management/src/test/java/io/quarkus/qe/extension/OpenShiftRegistryIT.java
messaging/amqp-reactive/src/test/java/io/quarkus/ts/messaging/amqpreactive/ProdAmqpReactiveIT.java
messaging/cloud-events/amqp-binary/src/test/java/io/quarkus/ts/messaging/cloudevents/amqpbinary/BinaryCloudEventsOverProdAmqpIT.java
messaging/cloud-events/amqp-json/src/test/java/io/quarkus/ts/messaging/cloudevents/amqpjson/JSONCloudEventsOverProdAmqpIT.java
messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftAmqStreamsKafkaStreamIT.java
messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftStrimziKafkaStreamIT.java
messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/OpenShiftAmqStreamsKafkaAvroIT.java
messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/OpenShiftStrimziKafkaAvroIT.java
messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/StrimziKafkaAvroIT.java
messaging/qpid/src/test/java/io/quarkus/ts/messaging/qpid/QpidIT.java
monitoring/micrometer-prometheus-kafka-reactive/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/reactive/OpenShiftAmqStreamsAlertEventsReactiveIT.java
monitoring/micrometer-prometheus-kafka-reactive/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/reactive/OpenShiftKafkaAlertEventsReactiveIT.java
monitoring/micrometer-prometheus-kafka/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/OpenShiftAmqStreamsAlertEventsIT.java
monitoring/micrometer-prometheus-kafka/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/OpenShiftKafkaAlertEventsIT.java
nosql-db/mongodb-reactive/src/test/java/io/quarkus/ts/nosqldb/mongodb/reactive/OpenShiftMongoClientReactiveIT.java
nosql-db/mongodb/src/test/java/io/quarkus/ts/nosqldb/mongodb/OpenShiftMongoClientIT.java
pom.xml
properties/src/test/java/io/quarkus/ts/properties/consul/OpenShiftConsulConfigSourceIT.java
security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/OpenShiftOidcRestClientIT.java
security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/OpenShiftOidcSinglePageAppLogoutFlowIT.java
security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/OpenShiftOidcRestClientIT.java
security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/OpenShiftOidcSinglePageAppLogoutFlowIT.java
sql-db/hibernate-fulltext-search/src/test/java/io/quarkus/ts/hibernate/search/OpenShiftMysqlMultitenantHibernateSearchIT.java
sql-db/hibernate-fulltext-search/src/test/java/io/quarkus/ts/hibernate/search/OpenShiftPostgresqlMultitenantHibernateSearchIT.java

Similar to the new arm profile, I have created a s390x profile to run tests on OpenShift on IBM Z and have skipped some arch specific tests. 
Skipping some tests due to the following images not available on s390x:
- keycloak
- debezium/zookeeper
- bitnami/mongodb
- consul
- elasticsearch
Latest test runs with new profile:
- https://master-jenkins-csb-runtimes-ibmzqe.apps.ocp-c1.prod.psi.redhat.com/view/RHOAR/job/rhbq-3.x-ocp4-rhel8-jdk11/
- https://master-jenkins-csb-runtimes-ibmzqe.apps.ocp-c1.prod.psi.redhat.com/view/RHOAR/job/rhbq-3.x-ocp4-rhel8-jdk17/

[3.2] Add s390x profile and skip appropriate tests

---

sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/DevModeOpenTelemetryIT.java

`DevModeOpenTelemetryIT` always fails on Windows (see respective Jenkins job), strange thing I can reproduce it 6 times of 10 on Linux, while in our CI it doesn't fail. Anyway, the root cause is that we don't wait till live reload is finished. That's what this PR does.

Fix flaky DevModeOpenTelemetryIT especially on Windows with waiting till live reload has finished
