quarkus-qe/quarkus-test-suite

- OPENSHIFT_TS_MIGRATION_STATUS.md
- pom.xml
- scaling/pom.xml
- scaling/src/main/java/io/quarkus/ts/openshift/scaling/ScalingResource.java
- scaling/src/main/resources/application.properties
- scaling/src/test/java/io/quarkus/ts/openshift/scaling/OpenShiftScalingIT.java
* scaling -> scaling
Depends on: https://github.com/Sgitario/quarkus-test-framework/pull/7
> Add scaling module

- OPENSHIFT_TS_MIGRATION_STATUS.md
- config/pom.xml
- config/src/main/java/io/quarkus/ts/configmap/api/server/Hello.java
- config/src/main/java/io/quarkus/ts/configmap/api/server/HelloResource.java
- config/src/test/java/io/quarkus/ts/configmap/api/server/ApiServerConfigMapOpenShiftIT.java
- config/src/test/java/io/quarkus/ts/configmap/api/server/ApiServerConfigSecretOpenShiftIT.java
- config/src/test/java/io/quarkus/ts/configmap/api/server/BaseConfigOpenShiftIT.java
- config/src/test/java/io/quarkus/ts/configmap/api/server/FileSystemConfigMapOpenShiftIT.java
- config/src/test/java/io/quarkus/ts/configmap/api/server/FileSystemConfigSecretOpenShiftIT.java
- config/src/test/resources/configmap-broken.yaml
- config/src/test/resources/configmap-update.yaml
- config/src/test/resources/configmap.api-server.properties
- config/src/test/resources/configmap.file-system.properties
- config/src/test/resources/configmap.yaml
- config/src/test/resources/secret-broken.yaml
- config/src/test/resources/secret-update.yaml
- config/src/test/resources/secret.api-server.properties
- config/src/test/resources/secret.file-system.properties
- config/src/test/resources/secret.yaml
- config/src/test/resources/test.properties
- pom.xml
| Original Modules  | Second Header |
| ------------- | ------------- |
| configmap/api-server | config |
| configmap/file-system | config |
| config-secret/api-server | config |
| config-secret/file-system | config |
> configmap and config-secret migrated

- OPENSHIFT_TS_MIGRATION_STATUS.md
- micrometer/prometheus-kafka/pom.xml
- micrometer/prometheus-kafka/src/main/java/io/quarkus/ts/micrometer/prometheus/kafka/AlertBroadcast.java
- micrometer/prometheus-kafka/src/main/java/io/quarkus/ts/micrometer/prometheus/kafka/AlertConsumer.java
- micrometer/prometheus-kafka/src/main/java/io/quarkus/ts/micrometer/prometheus/kafka/AlertProducer.java
- micrometer/prometheus-kafka/src/main/java/io/quarkus/ts/micrometer/prometheus/kafka/Channels.java
- micrometer/prometheus-kafka/src/main/resources/application.properties
- micrometer/prometheus-kafka/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/AmqStreamsOpenShiftAlertEventsIT.java
- micrometer/prometheus-kafka/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/BaseOpenShiftAlertEventsIT.java
- micrometer/prometheus-kafka/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/KafkaOpenShiftAlertEventsIT.java
- micrometer/prometheus-kafka/src/test/resources/service-monitor.yaml
- micrometer/prometheus-kafka/src/test/resources/test.properties
- micrometer/prometheus/pom.xml
- micrometer/prometheus/src/main/java/io/quarkus/ts/micrometer/prometheus/PrimeNumberResource.java
- micrometer/prometheus/src/main/resources/application.properties
- micrometer/prometheus/src/test/java/io/quarkus/ts/micrometer/prometheus/PrimeNumberResourceOpenShiftIT.java
- micrometer/prometheus/src/test/resources/service-monitor.yaml
- pom.xml
| micrometer/prometheus | micrometer/prometheus |
| micrometer/prometheus-kafka | micrometer/prometheus-kafka |
> Migrated micrometer modules

- OPENSHIFT_TS_MIGRATION_STATUS.md
- microprofile/.dockerignore
- microprofile/pom.xml
- microprofile/src/main/java/io/quarkus/ts/openshift/microprofile/ClientResource.java
- microprofile/src/main/java/io/quarkus/ts/openshift/microprofile/HelloClient.java
- microprofile/src/main/java/io/quarkus/ts/openshift/microprofile/HelloResource.java
- microprofile/src/main/java/io/quarkus/ts/openshift/microprofile/HelloService.java
- microprofile/src/main/resources/application.properties
- microprofile/src/test/java/io/quarkus/ts/openshift/microprofile/MicroProfileIT.java
- microprofile/src/test/java/io/quarkus/ts/openshift/microprofile/OpenShiftMicroProfileIT.java
- microprofile/src/test/resources/test.properties
- pom.xml
Depends on: https://github.com/Sgitario/quarkus-test-framework/pull/8
> Add microprofile module

- .github/workflows/daily.yaml
- pom.xml
https://github.com/quarkusio/quarkus/releases/tag/1.13.3.Final
> Upgrade quarkus

- sql-db/sql-app/src/test/java/io/quarkus/ts/openshift/sqldb/DevModePostgresqlIT.java
- Add `sql-db/sql-app` devServices scenario
> Add sql-db/sql-app devServices scenario

- README.md
- http/http-minimum/src/main/resources/application.properties
- http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/DevModeHttpMinimumIT.java
- http/http-minimum/src/test/resources/HelloResourceTest.java.template
Basic coverage of Continuous testing feature with:
- Detection of new tests
- Detection of changes on existing sources
> Cover Continuous Testing

- .github/workflows/ci.yml
- .github/workflows/daily.yaml
This issue has been fixed in https://github.com/quarkus-qe/quarkus-test-framework/pull/79
> Remove installation of test suite parent in workflows

- micrometer/oidc/pom.xml
- micrometer/oidc/src/main/java/io/quarkus/ts/micrometer/oidc/UserResource.java
- micrometer/oidc/src/main/resources/application.properties
- micrometer/oidc/src/test/java/io/quarkus/ts/micrometer/oidc/BaseMicrometerOidcSecurityIT.java
- micrometer/oidc/src/test/java/io/quarkus/ts/micrometer/oidc/DevMicrometerOidcSecurityIT.java
- micrometer/oidc/src/test/java/io/quarkus/ts/micrometer/oidc/ProdMicrometerOidcSecurityIT.java
- micrometer/oidc/src/test/resources/keycloak-realm.json
- micrometer/oidc/src/test/resources/test.properties
- pom.xml
Added some basic coverage around Micrometer ++ OIDC (including DEV mode test).
No OpenShift related tests have been implemented.
> Adding Micrometer + OIDC Modules

- .github/workflows/ci.yml
- .github/workflows/daily.yaml
- pom.xml
Use released test framework, makes it easier to use this testsuite.
Test framework has quick release process when new feature is needed from it.
> Use released test framework

- messaging/amqp-reactive/src/test/java/io/quarkus/ts/messaging/amqpreactive/AmqpIT.java
- messaging/artemis-jta/src/test/java/io/quarkus/ts/messaging/artemisjta/ArtemisJtaIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/openshift/sqldb/AbstractSqlDatabaseIT.java
Misc cleanup in the code
- Fix JavaDoc link
- Drop unnecessary .toString()
- Use long to avoid Long.valueOf() method call
> Misc cleanup in the code

- BEEFY_TS_MIGRATION_STATUS.md
| Original Modules  | Second Header |
| ------------- | ------------- |
| 012-quarkus-kafka-streams | messaging/kafka-streams-reactive-messaging |
| 013-quarkus-oidc-restclient | security/keycloak-oidc-client |
| 020-quarkus-http-non-application-endpoints | http/http-advanced |
| 021-quarkus-panache-multiple-pus | sql-db/multiple-pus |
> Beefy TS migration status - initial commit

- BEEFY_TS_MIGRATION_STATUS.md
- README.md
- http/reactive-routes/pom.xml
- http/reactive-routes/src/main/java/io/quarkus/ts/BasicsRouteHandler.java
- http/reactive-routes/src/main/java/io/quarkus/ts/ReactiveRoutesTracing.java
- http/reactive-routes/src/main/java/io/quarkus/ts/validation/Request.java
- http/reactive-routes/src/main/java/io/quarkus/ts/validation/Response.java
- http/reactive-routes/src/main/java/io/quarkus/ts/validation/ValidationOnRequestBodyRouteHandler.java
- http/reactive-routes/src/main/java/io/quarkus/ts/validation/ValidationOnRequestParamsRouteHandler.java
- http/reactive-routes/src/main/java/io/quarkus/ts/validation/ValidationOnResponseRouteHandler.java
- http/reactive-routes/src/main/java/io/quarkus/ts/validation/annotations/Uppercase.java
- http/reactive-routes/src/main/java/io/quarkus/ts/validation/annotations/UppercaseService.java
- http/reactive-routes/src/main/java/io/quarkus/ts/validation/annotations/UppercaseValidator.java
- http/reactive-routes/src/main/resources/application.properties
- http/reactive-routes/src/test/java/io/quarkus/ts/BasicsRouteHandlerIT.java
- http/reactive-routes/src/test/java/io/quarkus/ts/validation/ValidationOnRequestBodyRouteHandlerIT.java
- http/reactive-routes/src/test/java/io/quarkus/ts/validation/ValidationOnRequestParamRouteHandlerIT.java
- http/reactive-routes/src/test/java/io/quarkus/ts/validation/ValidationOnResponseRouteHandlerIT.java
- http/reactive-routes/src/test/java/io/quarkus/ts/validation/utils/ValidationAssertions.java
- http/reactive-routes/src/test/java/io/quarkus/ts/validation/utils/ValidationError.java
- http/reactive-routes/src/test/java/io/quarkus/ts/validation/utils/ValidationErrorResponse.java
- pom.xml
Reactive routes migration
Migrate Reactive routes from [Beefy-ts ](https://github.com/quarkus-qe/beefy-scenarios) to quarkus-test-suite
FIX GH-96
> Add http/reactive_routes modules

- BEEFY_TS_MIGRATION_STATUS.md
- README.md
- kamelet/pom.xml
- kamelet/src/main/java/io/quarkus/ts/kamelet/KameletResource.java
- kamelet/src/main/java/io/quarkus/ts/kamelet/KameletRoutes.java
- kamelet/src/main/resources/application.properties
- kamelet/src/main/resources/kamelets/fresh-beer-integration-example.groovy
- kamelet/src/main/resources/kamelets/fresh-beer.Kamelet.yaml
- kamelet/src/main/resources/kamelets/logger.kamelet.yaml
- kamelet/src/test/java/io/quarkus/ts/kamelet/KameletIT.java
- pom.xml
Kamelet migration
Migrate Kamelet from [Beefy-ts ](https://github.com/quarkus-qe/beefy-scenarios/tree/main/023-quarkus-kamelet)to quarkus-test-suite
Fix GH-89
> Add Kamelet module from Beefy-ts

- BEEFY_TS_MIGRATION_STATUS.md
- README.md
- http/vertx-web-client/README.md
- http/vertx-web-client/pom.xml
- http/vertx-web-client/src/main/java/io/quarkus/qe/vertx/webclient/config/ChuckEndpointValue.java
- http/vertx-web-client/src/main/java/io/quarkus/qe/vertx/webclient/config/ChuckEndpointValueConverter.java
- http/vertx-web-client/src/main/java/io/quarkus/qe/vertx/webclient/config/VertxWebClientConfig.java
- http/vertx-web-client/src/main/java/io/quarkus/qe/vertx/webclient/handler/ChuckNorrisResource.java
- http/vertx-web-client/src/main/java/io/quarkus/qe/vertx/webclient/handler/FailureHandler.java
- http/vertx-web-client/src/main/java/io/quarkus/qe/vertx/webclient/handler/TracingExampleResource.java
- http/vertx-web-client/src/main/java/io/quarkus/qe/vertx/webclient/model/Joke.java
- http/vertx-web-client/src/main/java/io/quarkus/qe/vertx/webclient/service/PongService.java
- http/vertx-web-client/src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.Converter
- http/vertx-web-client/src/main/resources/application.properties
- http/vertx-web-client/src/test/java/io/quarkus/qe/vertx/webclient/ChuckNorrisResourceIT.java
- http/vertx-web-client/src/test/resources/application.properties
- pom.xml
https://github.com/quarkus-qe/quarkus-test-suite/issues/92
> Move vertx-web clint from beefy TS

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCompletionIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateApplicationIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliExtensionsIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliHelpIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliSpecialCharsIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliVersionIT.java
The coverage should fulfill the test plan in https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-960.md
> Finish coverage of CLI functionality

- messaging/kafka-avro-reactive-messaging/README.md
- messaging/kafka-avro-reactive-messaging/pom.xml
- messaging/kafka-avro-reactive-messaging/src/main/resources/application.properties
- messaging/kafka-avro-reactive-messaging/src/main/resources/docker-compose-strimzi.yaml
- messaging/kafka-avro-reactive-messaging/src/test/java/io/quarkus/ts/openshift/messaging/kafka/ConfluentKafkaAvroIT.java
- messaging/kafka-avro-reactive-messaging/src/test/resources/confluent-application.properties
- messaging/kafka-avro-reactive-messaging/src/test/resources/strimzi-application.properties
- messaging/kafka-avro-reactive-messaging/src/test/resources/test.properties
- pom.xml
- Add Kafka confluent scenario
- Add docker-compose in order to run it manually
- Pending: Confluent Openshift scenario due to some PSI issues
Fix #93
> Add messaging confluent scenario

- sql-db/panache-flyway/src/test/java/io/quarkus/qe/sqldb/panacheflyway/dbpool/AgroalPoolTest.java
Migrate PR from beefy: https://github.com/quarkus-qe/beefy-scenarios/pull/249
> Fix a statement leak resulting in a ton of warnings in the logs

- http/http-advanced/pom.xml
- http/http-advanced/src/main/java/io/quarkus/ts/http/advanced/GrpcStreamingService.java
- http/http-advanced/src/main/java/io/quarkus/ts/http/advanced/GrpcWebSocketListener.java
- http/http-advanced/src/main/proto/helloworld.proto
- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/DevModeGrpcIntegrationIT.java
quarkus-qe/quarkus-test-plans#33
Please message me to present the logic (if needed)
> Add gRPC devui test into http-advanced module

- external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftQuickstartUsingS2iIT.java
- external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftTodoDemoIT.java
- external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftWorkshopHeroesIT.java
- external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftWorkshopVillainsIT.java
- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/HttpAdvancedIT.java
- logging/jboss/src/test/java/io/quarkus/ts/logging/jboss/LogResourceIT.java
- pom.xml
All the changes in https://github.com/quarkus-qe/quarkus-test-framework/releases/tag/v0.0.7
> Upgrade Quarkus Test Framework to 0.0.7

- messaging/amqp-reactive/src/test/java/io/quarkus/ts/messaging/amqpreactive/DevModeAmqpDevServiceUserExperienceIT.java
- messaging/amqp-reactive/src/test/java/io/quarkus/ts/messaging/amqpreactive/DevModeAmqpIT.java
- messaging/amqp-reactive/src/test/java/io/quarkus/ts/messaging/amqpreactive/DockerUtils.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/DevModeKafkaStreamIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/DevModeRedPandaDevServiceUserExperienceIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/DockerUtils.java
- security/keycloak/src/test/java/io/quarkus/ts/security/DevModeKeycloakDevServiceUserExperienceIT.java
- security/keycloak/src/test/java/io/quarkus/ts/security/DevModeOidcSecurityIT.java
- security/keycloak/src/test/java/io/quarkus/ts/security/DockerUtils.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMariadbDevServicesUserExperienceIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMariadbIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMssqlDevServicesUserExperienceIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMssqlIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMysqlDevServiceUserExperienceIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMysqlIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModePostgresqlDevServiceUserExperienceIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DockerUtils.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/OpenShiftMssqlDatabaseIT.java
- sql-db/sql-app/src/test/resources/container-license-acceptance.txt
- sql-db/sql-app/src/test/resources/mssql.properties
Verified dev services:
* Keycloak
* Kafka/RedPanda
* amqp
* Postgresql
* Mysql
* Mariadb
* Mssql
> Verify messaging,keycloack and datasources devService logs

- security/keycloak/src/test/java/io/quarkus/ts/security/DevModeKeycloakDevServiceUserExperienceIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMariadbDevServicesUserExperienceIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMssqlDevServicesUserExperienceIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMysqlDevServiceUserExperienceIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModePostgresqlDevServiceUserExperienceIT.java
DevService inconsistencies related to logs have been fixed. 
Original Issue: https://github.com/quarkusio/quarkus/issues/19485
> Check that all Dev services logs messages are consistent with each other

- README.md
- http/jaxrs-reactive/src/main/java/io/quarkus/ts/jaxrs/reactive/ExecutionModelResource.java
- http/jaxrs-reactive/src/test/java/io/quarkus/ts/jaxrs/reactive/ExecutionModelResourceIT.java
- http/jaxrs-reactive/src/test/java/io/quarkus/ts/jaxrs/reactive/OpenShiftExecutionModelResourceIT.java
- http/jaxrs-reactive/src/test/resources/execution-model.properties
Related to https://github.com/quarkusio/quarkus/pull/18923.
> Add coverage of execution model

- README.md
- http/jaxrs-reactive/src/main/java/io/quarkus/ts/jaxrs/reactive/ExecutionModelResource.java
- http/jaxrs-reactive/src/test/java/io/quarkus/ts/jaxrs/reactive/ExecutionModelResourceIT.java
- http/jaxrs-reactive/src/test/java/io/quarkus/ts/jaxrs/reactive/OpenShiftExecutionModelResourceIT.java
- http/jaxrs-reactive/src/test/resources/execution-model.properties
Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/198/.
> [2.2] Add coverage of execution model

- README.md
- pom.xml
- sql-db/reactive-postgresql/pom.xml
- sql-db/reactive-postgresql/src/main/java/io/quarkus/qe/model/Book.java
- sql-db/reactive-postgresql/src/main/java/io/quarkus/qe/model/Record.java
- sql-db/reactive-postgresql/src/main/java/io/quarkus/qe/resources/BookResource.java
- sql-db/reactive-postgresql/src/main/resources/application.properties
- sql-db/reactive-postgresql/src/test/java/io/quarkus/qe/resources/DevModeReactivePostgresqlDevServiceUserExperienceIT.java
- sql-db/reactive-postgresql/src/test/java/io/quarkus/qe/resources/DevModeReactivePostgresqlIT.java
- sql-db/reactive-postgresql/src/test/java/io/quarkus/qe/resources/DockerUtils.java
- sql-db/reactive-postgresql/src/test/resources/test.properties
Reactive Postgresql / Dev services scenario
> Reactive DevServices postgresql

- http/jaxrs-reactive/pom.xml
- http/jaxrs-reactive/src/main/java/io/quarkus/ts/jaxrs/reactive/HttpCachingResource.java
- http/jaxrs-reactive/src/main/resources/application.properties
- http/jaxrs-reactive/src/test/java/io/quarkus/ts/jaxrs/reactive/HttpCachingResourceIT.java
- http/jaxrs-reactive/src/test/java/io/quarkus/ts/jaxrs/reactive/OpenShiftHttpCachingResourceIT.java
Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/209 and https://github.com/quarkus-qe/quarkus-test-suite/pull/213.
> [2.2] Add HTTP Caching scenario to jaxrs-reactive

- README.md
- pom.xml
- sql-db/reactive-postgresql/pom.xml
- sql-db/reactive-postgresql/src/main/java/io/quarkus/qe/model/Book.java
- sql-db/reactive-postgresql/src/main/java/io/quarkus/qe/model/Record.java
- sql-db/reactive-postgresql/src/main/java/io/quarkus/qe/resources/BookResource.java
- sql-db/reactive-postgresql/src/main/resources/application.properties
- sql-db/reactive-postgresql/src/test/java/io/quarkus/qe/resources/DevModeReactivePostgresqlDevServiceUserExperienceIT.java
- sql-db/reactive-postgresql/src/test/java/io/quarkus/qe/resources/DevModeReactivePostgresqlIT.java
- sql-db/reactive-postgresql/src/test/java/io/quarkus/qe/resources/DockerUtils.java
- sql-db/reactive-postgresql/src/test/resources/test.properties
> [2.2] Reactive DevServices postgresql

- README.md
- http/jaxrs-reactive/pom.xml
- http/jaxrs-reactive/src/main/java/io/quarkus/ts/jaxrs/reactive/json/JsonResource.java
- http/jaxrs-reactive/src/main/java/io/quarkus/ts/jaxrs/reactive/json/UnquotedFields.java
- http/jaxrs-reactive/src/main/java/io/quarkus/ts/jaxrs/reactive/json/User.java
- http/jaxrs-reactive/src/main/java/io/quarkus/ts/jaxrs/reactive/json/Views.java
- http/jaxrs-reactive/src/test/java/io/quarkus/ts/jaxrs/reactive/AsciiMultipartResourceIT.java
- http/jaxrs-reactive/src/test/java/io/quarkus/ts/jaxrs/reactive/ExecutionModelResourceIT.java
- http/jaxrs-reactive/src/test/java/io/quarkus/ts/jaxrs/reactive/HttpCachingResourceIT.java
- http/jaxrs-reactive/src/test/java/io/quarkus/ts/jaxrs/reactive/MultipartResourceIT.java
- http/jaxrs-reactive/src/test/java/io/quarkus/ts/jaxrs/reactive/OpenShiftHttpCachingResourceIT.java
- http/jaxrs-reactive/src/test/java/io/quarkus/ts/jaxrs/reactive/json/JsonResourceIT.java
- http/jaxrs-reactive/src/test/java/io/quarkus/ts/jaxrs/reactive/json/OpenShiftJsonResourceIT.java
Part of test development to QUARKUS-1075.
Covers one of the advanced topics of the test plan.
https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-1075.md
> Add JSON serialization scenario

- README.md
- http/jaxrs-reactive/pom.xml
- http/jaxrs-reactive/src/main/java/io/quarkus/ts/jaxrs/reactive/client/ClientMultipartBody.java
- http/jaxrs-reactive/src/main/java/io/quarkus/ts/jaxrs/reactive/client/MultipartClientResource.java
- http/jaxrs-reactive/src/main/java/io/quarkus/ts/jaxrs/reactive/client/MultipartService.java
- http/jaxrs-reactive/src/main/java/io/quarkus/ts/jaxrs/reactive/client/PojoData.java
- http/jaxrs-reactive/src/main/resources/application.properties
- http/jaxrs-reactive/src/test/java/io/quarkus/ts/jaxrs/reactive/client/MultipartClientResourceIT.java
Based on https://github.com/quarkusio/quarkus/issues/19892.
Serves as a verification for related JIRA:
https://issues.redhat.com/browse/QUARKUS-1225
> Add REST Client Reactive multipart scenario

- .github/workflows/ci.yml
- lifecycle-application/pom.xml
- pom.xml
- spring/spring-cloud-config/src/main/java/io/quarkus/ts/spring/cloud/config/ConfigMappingGreetingResource.java
- spring/spring-cloud-config/src/main/java/io/quarkus/ts/spring/cloud/config/CustomMessageConfig.java
- spring/spring-cloud-config/src/test/java/io/quarkus/ts/spring/cloud/config/SpringCloudConfigIT.java
Back port of https://github.com/quarkus-qe/quarkus-test-suite/pull/236
> [2.2] Upgrade Quarkus to 2.2.2.Final

- README.md
- http/jaxrs-reactive/pom.xml
- http/jaxrs-reactive/src/main/java/io/quarkus/ts/jaxrs/reactive/json/JsonResource.java
- http/jaxrs-reactive/src/main/java/io/quarkus/ts/jaxrs/reactive/json/UnquotedFields.java
- http/jaxrs-reactive/src/main/java/io/quarkus/ts/jaxrs/reactive/json/User.java
- http/jaxrs-reactive/src/main/java/io/quarkus/ts/jaxrs/reactive/json/Views.java
- http/jaxrs-reactive/src/test/java/io/quarkus/ts/jaxrs/reactive/AsciiMultipartResourceIT.java
- http/jaxrs-reactive/src/test/java/io/quarkus/ts/jaxrs/reactive/ExecutionModelResourceIT.java
- http/jaxrs-reactive/src/test/java/io/quarkus/ts/jaxrs/reactive/HttpCachingResourceIT.java
- http/jaxrs-reactive/src/test/java/io/quarkus/ts/jaxrs/reactive/MultipartResourceIT.java
- http/jaxrs-reactive/src/test/java/io/quarkus/ts/jaxrs/reactive/OpenShiftHttpCachingResourceIT.java
- http/jaxrs-reactive/src/test/java/io/quarkus/ts/jaxrs/reactive/json/JsonResourceIT.java
- http/jaxrs-reactive/src/test/java/io/quarkus/ts/jaxrs/reactive/json/OpenShiftJsonResourceIT.java
Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/221.
> [2.2] Add JSON serialization scenario

- README.md
- pom.xml
- sql-db/hibernate/pom.xml
- sql-db/hibernate/src/main/java/io/quarkus/qe/hibernate/items/Account.java
- sql-db/hibernate/src/main/java/io/quarkus/qe/hibernate/items/Customer.java
- sql-db/hibernate/src/main/java/io/quarkus/qe/hibernate/items/Item.java
- sql-db/hibernate/src/main/java/io/quarkus/qe/hibernate/items/ItemsResource.java
- sql-db/hibernate/src/main/java/io/quarkus/qe/hibernate/items/Role.java
- sql-db/hibernate/src/main/java/io/quarkus/qe/hibernate/transaction/TransactionScopeBean.java
- sql-db/hibernate/src/main/java/io/quarkus/qe/hibernate/transaction/TransactionScopeBeanResource.java
- sql-db/hibernate/src/main/java/io/quarkus/qe/hibernate/validator/Hello.java
- sql-db/hibernate/src/main/java/io/quarkus/qe/hibernate/validator/Human.java
- sql-db/hibernate/src/main/java/io/quarkus/qe/hibernate/validator/JpaAndHibernateValidatorResource.java
- sql-db/hibernate/src/main/java/io/quarkus/qe/hibernate/validator/SomeChildEntity.java
- sql-db/hibernate/src/main/java/io/quarkus/qe/hibernate/validator/SomeEntity.java
- sql-db/hibernate/src/main/resources/META-INF/resources/index.html
- sql-db/hibernate/src/main/resources/application.properties
- sql-db/hibernate/src/main/resources/import.sql
- sql-db/hibernate/src/test/java/io/quarkus/qe/hibernate/items/ItemsResourceIT.java
- sql-db/hibernate/src/test/java/io/quarkus/qe/hibernate/transaction/TransactionScopeBeanResourceIT.java
- sql-db/hibernate/src/test/java/io/quarkus/qe/hibernate/validator/JpaAndHibernateValidatorResourceIT.java
* Migrating 004-quarkus-HHH-and-HV from beefy-scenarios
> [#77] Quarkus Hibernate and Hibernate Validator

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
Test for JaCoCo extension
Using CLI to generate the project and to invoke the build.
> Test for JaCoCo extension

- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/RemoteDevModeHttpAdvancedIT.java
This PR is to verify https://issues.redhat.com/browse/QUARKUS-834
> RemoteDev scenario to check DEV ui is not found

- .github/workflows/ci.yml
Example of run when there is a change in a module: https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/1216700602
> Github CI: Run only changed modules in JVM for Linux and Windows

- messaging/kafka-avro-reactive-messaging/pom.xml
- messaging/kafka-avro-reactive-messaging/src/main/resources/application.properties
- messaging/kafka-avro-reactive-messaging/src/main/resources/docker-compose-strimzi.yaml
- messaging/kafka-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/OpenShiftAmqStreamsKafkaAvroIT.java
- messaging/kafka-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/StrimziKafkaAvroIT.java
- messaging/kafka-avro-reactive-messaging/src/test/resources/strimzi-application.properties
- pom.xml
> [2.2] Move on to new Quarkus apicurio registry library

- pom.xml
- sql-db/sql-app/pom.xml
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/OpenShiftOracleDatabaseIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/OracleDatabaseIT.java
- sql-db/sql-app/src/test/resources/oracle.properties
- sql-db/sql-app/src/test/resources/oracle_import.sql
Part of test development for QUARKUS-1164.
> Add Oracle DB scenario

- .github/workflows/ci.yml
Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/247
> [2.2] Github CI: Run only changed modules in JVM for Linux and Windows

- pom.xml
- sql-db/sql-app/pom.xml
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/OpenShiftOracleDatabaseIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/OracleDatabaseIT.java
- sql-db/sql-app/src/test/resources/oracle.properties
- sql-db/sql-app/src/test/resources/oracle_import.sql
Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/254.
> [2.2] Add Oracle DB scenario

- pom.xml
Swap quay.io/pjgg/db2:11.5.5.0 to quay.io/quarkusqeteam/db2:11.5.5.0
> Swap quay.io/pjgg/db2:11.5.5.0 to quay.io/quarkusqeteam/db2:11.5.5.0

- README.md
- external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftWorkshopHeroesIT.java
- external-applications/src/test/java/io/quarkus/ts/external/applications/TodoDemoIT.java
- pom.xml
Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/269
> [2.2] Fix external applications: Missing S2i props + Wrong artifact in Todo

- .github/workflows/ci.yml
- super-size/many-extensions/pom.xml
This is to let the test framework to build the parent correctly
> Fix Many Extensions relative path

- .github/workflows/ci.yml
- super-size/many-extensions/pom.xml
This is to let the test framework to build the parent correctly
Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/278
> [2.2] Fix Many Extensions relative path

- .github/workflows/daily.yaml
- .github/workflows/quarkus-snapshot.yaml
- monitoring/micrometer-prometheus-kafka/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/BaseOpenShiftAlertEventsIT.java
- monitoring/micrometer-prometheus/src/test/java/io/quarkus/ts/micrometer/prometheus/OpenShiftPrimeNumberResourceIT.java
Issue on fabric8 side, related to https://github.com/quarkus-qe/quarkus-test-framework/issues/270 and reported in https://github.com/fabric8io/kubernetes-client/issues/3473
> Workaround to fix OpenShiftClient.execOnPod issue

- pom.xml
> [2.2] Swap quay.io/pjgg/db2:11.5.5.0 to quay.io/quarkusqeteam/db2:11.5.5.0

- sql-db/vertx-sql/src/main/resources/application.properties
- sql-db/vertx-sql/src/test/java/io/quarkus/qe/vertx/sql/handlers/Db2HandlerIT.java
- sql-db/vertx-sql/src/test/java/io/quarkus/qe/vertx/sql/handlers/MysqlHandlerIT.java
- sql-db/vertx-sql/src/test/java/io/quarkus/qe/vertx/sql/handlers/PostgresqlHandlerIT.java
Reported in https://github.com/IBM/Db2/issues/43
> Tag DB2 Handler IT as incompatible with FIPS

- .github/workflows/ci.yml
- .github/workflows/daily.yaml
> [2.2] Adopt OpenJDK got moved to Eclipse Temurin

- spring/spring-web/pom.xml
- spring/spring-web/src/main/java/io/quarkus/ts/spring/web/boostrap/web/SimpleController.java
- super-size/many-extensions/pom.xml
Close #297
Related to: https://github.com/quarkusio/quarkus/issues/20278
> Fix Conflicts between reactive and non-reactive libraries

- README.md
- infinispan-client/pom.xml
- infinispan-client/src/main/java/io/quarkus/ts/infinispan/client/InfinispanClientApp.java
- infinispan-client/src/main/java/io/quarkus/ts/infinispan/client/serialized/ShopItem.java
- infinispan-client/src/main/java/io/quarkus/ts/infinispan/client/serialized/ShopItemResource.java
- infinispan-client/src/main/java/io/quarkus/ts/infinispan/client/serialized/ShopItemSchema.java
- infinispan-client/src/test/java/io/quarkus/ts/infinispan/client/OperatorOpenShiftInfinispanCountersIT.java
- infinispan-client/src/test/java/io/quarkus/ts/infinispan/client/OperatorOpenShiftInfinispanObjectsIT.java
TD https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-803.md
Finally, cache.clear() was used and it behaves stable on OpenShift.
> Add Data Grid Serialization and cache eviction test

- .github/workflows/daily.yaml
- .github/workflows/quarkus-snapshot.yaml
- README.md
- pom.xml
- websockets/quarkus-websockets/pom.xml
- websockets/quarkus-websockets/src/main/java/io/quarkus/ts/Chat.java
- websockets/quarkus-websockets/src/main/java/io/quarkus/ts/Pusher.java
- websockets/quarkus-websockets/src/main/resources/META-INF/resources/index.html
- websockets/quarkus-websockets/src/test/java/io/quarkus/ts/ChatIT.java
- websockets/quarkus-websockets/src/test/java/io/quarkus/ts/OpenShiftChatIT.java
- websockets/quarkus-websockets/src/test/resources/test.properties
- websockets/websockets-client/pom.xml
- websockets/websockets-client/src/main/java/io/quarkus/ts/Chat.java
- websockets/websockets-client/src/main/java/io/quarkus/ts/Pusher.java
- websockets/websockets-client/src/main/java/io/quarkus/ts/RemoteClient.java
- websockets/websockets-client/src/main/resources/application.properties
- websockets/websockets-client/src/test/java/io/quarkus/ts/ClientIT.java
- websockets/websockets-client/src/test/java/io/quarkus/ts/OpenShiftClientIT.java
- websockets/websockets-client/src/test/resources/test.properties
Coverage of sending messages over WebSocket in our new TS.
> [2.2] Websockets coverage

- .github/workflows/ci.yml
- monitoring/micrometer-prometheus-kafka/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/BaseOpenShiftAlertEventsIT.java
- monitoring/micrometer-prometheus/src/test/java/io/quarkus/ts/micrometer/prometheus/OpenShiftPrimeNumberResourceIT.java
- pom.xml
- scheduling/quartz/pom.xml
- spring/spring-data/pom.xml
- spring/spring-web/pom.xml
- sql-db/panache-flyway/pom.xml
- websockets/websockets-client/pom.xml
- websockets/websockets-client/src/test/java/io/quarkus/ts/ClientIT.java
++ quarkus-hibernate-orm-rest-data-panache ++ spring web no longer reactive
Related to https://github.com/quarkusio/quarkus/commit/5054ba11db07d7d2a538a989d707ae90bf6ddd36
> Bump to Quarkus Test Framework 0.0.12 ++ Refactor Websockets ++ Fix reactive issues

- monitoring/micrometer-prometheus-kafka/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/BaseOpenShiftAlertEventsIT.java
- monitoring/micrometer-prometheus/src/test/java/io/quarkus/ts/micrometer/prometheus/OpenShiftPrimeNumberResourceIT.java
- pom.xml
- websockets/websockets-client/pom.xml
- websockets/websockets-client/src/test/java/io/quarkus/ts/ClientIT.java
Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/303
> [2.2] Bump to Quarkus Test Framework 0.0.12 ++ Refactor Websockets

- README.md
- messaging/kafka-producer/pom.xml
- messaging/kafka-producer/src/main/java/io/quarkus/ts/messaging/kafka/Application.java
- messaging/kafka-producer/src/main/java/io/quarkus/ts/messaging/kafka/FailureHandler.java
- messaging/kafka-producer/src/main/java/io/quarkus/ts/messaging/kafka/KafkaBlockingProducer.java
- messaging/kafka-producer/src/main/resources/application.properties
- messaging/kafka-producer/src/test/java/io/quarkus/ts/messaging/kafka/BlockingProducerIT.java
- messaging/kafka-producer/src/test/java/io/quarkus/ts/messaging/kafka/CustomStrimziKafkaContainer.java
- messaging/kafka-producer/src/test/resources/test.properties
- pom.xml
> [2.2] Add blocking Kafka producer scenario

- README.md
- messaging/kafka-avro-reactive-messaging/src/main/java/io/quarkus/ts/messaging/kafka/KStockPriceProducer.java
- messaging/kafka-avro-reactive-messaging/src/main/java/io/quarkus/ts/messaging/kafka/StockPriceDto.java
- messaging/kafka-avro-reactive-messaging/src/main/java/io/quarkus/ts/messaging/kafka/StockPriceEndpoint.java
- messaging/kafka-avro-reactive-messaging/src/main/resources/application.properties
- messaging/kafka-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/BaseKafkaAvroGroupIdIT.java
- messaging/kafka-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/ConfluentKafkaAvroGroupIdIT.java
- messaging/kafka-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/StrimziKafkaAvroGroupIdIT.java
- messaging/kafka-avro-reactive-messaging/src/test/resources/confluent-application.properties
- messaging/kafka-avro-reactive-messaging/src/test/resources/strimzi-application.properties
> [2.2] Add auto generated group ID scenario

- README.md
- messaging/kafka-streams-reactive-messaging/src/main/resources/application.properties
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/KafkaGratefulShutdownIT.java
> [2.2] Auto-detect serializers and deserializers 

- messaging/kafka-producer/src/main/resources/application.properties
- messaging/kafka-producer/src/test/java/io/quarkus/ts/messaging/kafka/BlockingProducerIT.java
> [2.2] Improve Kafka-producer resilience

- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/KafkaGratefulShutdownIT.java
- messaging/kafka-streams-reactive-messaging/src/test/resources/kafka.grateful.shutdown.application.properties
Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/327
> [2.2] Remove workaround for auto serializers in KafkaGratefulShutdownIT

- scaling/src/test/java/io/quarkus/ts/openshift/scaling/OpenShiftScalingIT.java
This is a test framework issue reported in https://github.com/quarkus-qe/quarkus-test-framework/issues/290
> Fix OpenShift scaling test

- scaling/src/test/java/io/quarkus/ts/openshift/scaling/OpenShiftScalingIT.java
This is a test framework issue reported in https://github.com/quarkus-qe/quarkus-test-framework/issues/290
Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/331
> [2.2] Fix OpenShift scaling test

- infinispan-client/src/test/java/io/quarkus/ts/infinispan/client/BaseOpenShiftInfinispanIT.java
- infinispan-client/src/test/java/io/quarkus/ts/infinispan/client/OperatorOpenShiftInfinispanCountersIT.java
- infinispan-client/src/test/java/io/quarkus/ts/infinispan/client/OperatorOpenShiftInfinispanObjectsIT.java
++ To move all the common functionality into a base class.
> Refactor Infinispan to delete cluster when startup failures

- README.md
- pom.xml
- sql-db/sql-app-oracle/pom.xml
- sql-db/sql-app-oracle/src/main/java/io/quarkus/ts/sqldb/sqlapp/oracle/ApplicationExceptionMapper.java
- sql-db/sql-app-oracle/src/main/java/io/quarkus/ts/sqldb/sqlapp/oracle/Book.java
- sql-db/sql-app-oracle/src/main/java/io/quarkus/ts/sqldb/sqlapp/oracle/BookResource.java
- sql-db/sql-app-oracle/src/main/java/io/quarkus/ts/sqldb/sqlapp/oracle/NotFoundExceptionMapper.java
- sql-db/sql-app-oracle/src/main/java/io/quarkus/ts/sqldb/sqlapp/oracle/ValidationExceptionMapper.java
- sql-db/sql-app-oracle/src/main/resources/application.properties
- sql-db/sql-app-oracle/src/main/resources/oracle_import.sql
- sql-db/sql-app-oracle/src/test/java/io/quarkus/ts/sqldb/sqlapp/oracle/AbstractSqlDatabaseIT.java
- sql-db/sql-app-oracle/src/test/java/io/quarkus/ts/sqldb/sqlapp/oracle/OpenShiftOracleDatabaseIT.java
- sql-db/sql-app-oracle/src/test/java/io/quarkus/ts/sqldb/sqlapp/oracle/OracleDatabaseIT.java
- sql-db/sql-app-oracle/src/test/resources/test.properties
- sql-db/sql-app/pom.xml
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/AbstractSqlDatabaseIT.java
Original RFE: https://issues.redhat.com/browse/QUARKUS-1164.
Related bug: https://issues.redhat.com/browse/QUARKUS-1305.
> Add separate SQL module for Oracle

- README.md
- pom.xml
- sql-db/sql-app-oracle/pom.xml
- sql-db/sql-app-oracle/src/main/java/io/quarkus/ts/sqldb/sqlapp/oracle/ApplicationExceptionMapper.java
- sql-db/sql-app-oracle/src/main/java/io/quarkus/ts/sqldb/sqlapp/oracle/Book.java
- sql-db/sql-app-oracle/src/main/java/io/quarkus/ts/sqldb/sqlapp/oracle/BookResource.java
- sql-db/sql-app-oracle/src/main/java/io/quarkus/ts/sqldb/sqlapp/oracle/NotFoundExceptionMapper.java
- sql-db/sql-app-oracle/src/main/java/io/quarkus/ts/sqldb/sqlapp/oracle/ValidationExceptionMapper.java
- sql-db/sql-app-oracle/src/main/resources/application.properties
- sql-db/sql-app-oracle/src/main/resources/oracle_import.sql
- sql-db/sql-app-oracle/src/test/java/io/quarkus/ts/sqldb/sqlapp/oracle/AbstractSqlDatabaseIT.java
- sql-db/sql-app-oracle/src/test/java/io/quarkus/ts/sqldb/sqlapp/oracle/OpenShiftOracleDatabaseIT.java
- sql-db/sql-app-oracle/src/test/java/io/quarkus/ts/sqldb/sqlapp/oracle/OracleDatabaseIT.java
- sql-db/sql-app-oracle/src/test/resources/test.properties
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/AbstractSqlDatabaseIT.java
Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/362.
> [2.2] Add separate SQL module for Oracle

- pom.xml
Disable Kafka confluent test due to issue: https://github.com/quarkusio/quarkus/issues/21412
> Rollback kafka-avro-serializer dependency version due to issue #21412

- messaging/infinispan-grpc-kafka/src/test/resources/test.properties
- messaging/kafka-avro-reactive-messaging/src/main/java/io/quarkus/ts/messaging/kafka/KStockPriceProducer.java
- messaging/kafka-avro-reactive-messaging/src/test/resources/test.properties
- messaging/kafka-producer/src/main/java/io/quarkus/ts/messaging/kafka/Application.java
- messaging/kafka-producer/src/test/resources/test.properties
- Reduce kafka and kafka-apps amount of logs, when logs are not required
> Kafka scenarios: Reduce the amount of logs

- README.md
Issue Ref: #118 
Improve README.md in order to cover some basic topics as:
- Compile and verify scenarios in native mode (baremetal and openshift)
- Compile and verify scenarios in JVM mode (baremetal and openshift)
> Upgrade README.md documentation,basic compilation usages

- sql-db/vertx-sql/src/test/java/io/quarkus/qe/vertx/sql/handlers/MssqlHandlerIT.java
Related issue: https://github.com/quarkusio/quarkus/issues/21826
> Disable mssql scenario because is Flyway doesn't support this DB on upstream

- http/reactive-routes/src/test/java/io/quarkus/ts/validation/utils/ValidationAssertions.java
- http/reactive-routes/src/test/java/io/quarkus/ts/validation/utils/ValidationErrorResponse.java
Issue Ref: https://github.com/quarkusio/quarkus/pull/21970
> details attribute has been renamed to detail

- .github/workflows/ci.yml
Increase timeout for JVM runs in CI
> Increase timeout for JVM runs in CI

- .github/workflows/ci.yml
- lifecycle-application/pom.xml
- pom.xml
Upgrade 2.2 branch to 2.2.4 release
> [2.2] Upgrade to Quarkus 2.2.4.Final

- sql-db/sql-app/pom.xml
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/OracleDatabaseIT.java
Related issue: https://github.com/quarkusio/quarkus/issues/22476
> Disable Oracle native scenario in combination with other datasources

- http/vertx-web-client/pom.xml
- monitoring/opentelemetry-reactive/pom.xml
- monitoring/opentelemetry/pom.xml
issue Ref: https://github.com/quarkusio/quarkus/issues/22275
> Enable quarkus-opentelemetry-exporter-jaeger scenarios in native mode

- monitoring/micrometer-prometheus/src/main/java/io/quarkus/ts/micrometer/prometheus/UsingMicroProfilePingPongResource.java
- monitoring/micrometer-prometheus/src/test/java/io/quarkus/ts/micrometer/prometheus/UsingMicroProfilePingPongResourceIT.java
Original issue: https://github.com/quarkusio/quarkus/issues/20047
Related issue: https://github.com/quarkusio/quarkus/issues/22662
> Gauge annotation is not registered or showing up

- .github/workflows/daily.yaml
- pom.xml
- sql-db/sql-app/pom.xml
Update sql-db/sql-app and GraalVM / Mandrel
> Update sql-db/sql-app and GraalVM / Mandrel

- http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/RemoteDevWithoutPasswordIT.java
> [2.2] RemoteDevMode without password scenario

- spring/spring-data/src/main/java/io/quarkus/ts/spring/data/primitivetypes/BookResource.java
- spring/spring-data/src/main/java/io/quarkus/ts/spring/data/primitivetypes/BookStore.java
- spring/spring-data/src/test/java/io/quarkus/ts/spring/data/primitivetypes/BookResourceIT.java
Coverage for this issue: https://github.com/quarkusio/quarkus/pull/20568
> Coverage for serialization of PageImpl

- README.md
- http/http-minimum-reactive/pom.xml
- http/http-minimum-reactive/src/main/java/io/quarkus/ts/http/minimum/reactive/Hello.java
- http/http-minimum-reactive/src/main/java/io/quarkus/ts/http/minimum/reactive/HelloResource.java
- http/http-minimum-reactive/src/main/resources/application.properties
- http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/DevModeHttpMinimumReactiveIT.java
- http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/HttpMinimumReactiveIT.java
- http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/OpenShiftHttpMinimumReactiveIT.java
- http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/OpenShiftUsingExtensionDockerBuildStrategyHttpMinimumReactiveIT.java
- http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/OpenShiftUsingExtensionHttpMinimumReactiveIT.java
- http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/ServerlessExtensionDockerBuildStrategyOpenShiftHttpMinimumReactiveIT.java
- http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/ServerlessExtensionOpenShiftHttpMinimumReactiveIT.java
- http/http-minimum-reactive/src/test/resources/HelloResourceTest.java.template
- http/http-minimum-reactive/src/test/resources/NoFunctionalTest.java.template
- pom.xml
backport of [this](https://github.com/quarkus-qe/quarkus-test-suite/pull/388/commits/9d347de6129bc815da04bbfe3213d5afd1227733) commit
> [2.2] Add reactive counterpart of http/http-minimum

- spring/spring-data/src/main/java/io/quarkus/ts/spring/data/primitivetypes/BookResource.java
- spring/spring-data/src/main/java/io/quarkus/ts/spring/data/primitivetypes/BookStore.java
- spring/spring-data/src/test/java/io/quarkus/ts/spring/data/primitivetypes/BookResourceIT.java
Backport for https://github.com/quarkus-qe/quarkus-test-suite/pull/452
> [2.2] Coverage for serialization of PageImpl

- README.md
- http/graphql/pom.xml
- http/graphql/src/main/java/io/quarkus/ts/http/graphql/Person.java
- http/graphql/src/main/java/io/quarkus/ts/http/graphql/PersonsEndpoint.java
- http/graphql/src/main/resources/application.properties
- http/graphql/src/test/java/io/quarkus/ts/http/graphql/GraphQLIT.java
- http/graphql/src/test/java/io/quarkus/ts/http/graphql/OpenShiftGraphQLIT.java
- pom.xml
Coverage for https://github.com/quarkusio/quarkus/issues/20293
TODOs:
> Graphql coverage

- monitoring/micrometer-prometheus/src/main/java/io/quarkus/ts/micrometer/prometheus/UsingMicroProfilePingPongResource.java
- monitoring/micrometer-prometheus/src/test/java/io/quarkus/ts/micrometer/prometheus/UsingMicroProfilePingPongResourceIT.java
> [2.2] Gauge annotation is not registered or showing up

- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/IdBeanParam.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/ReactiveClientBookResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestInterface.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/json/BookAsJsonResource.java
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ClientBookResourceIT.java
Rest Client Reactive: Support PathParam from BeanParam scenario
> Add pathParam as BeanParam scenario

- http/jaxrs/pom.xml
- http/jaxrs/src/main/java/io/quarkus/ts/security/core/GreetingResource.java
- http/jaxrs/src/main/java/io/quarkus/ts/security/core/SerializationConfig.java
- http/jaxrs/src/test/java/io/quarkus/ts/security/core/BaseQuarkusBundleIT.java
- http/jaxrs/src/test/java/io/quarkus/ts/security/core/SerializationIT.java
original issue Ref: https://github.com/quarkusio/quarkus/issues/19711
A new issue was created: https://github.com/quarkusio/quarkus/issues/22654
> native coverage: reflections registration of constructors

- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/IdBeanParam.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/ReactiveClientBookResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestInterface.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/json/BookAsJsonResource.java
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ClientBookResourceIT.java
> [2.2] Add pathParam as BeanParam scenario

- .github/workflows/ci.yml
- .github/workflows/daily.yaml
- README.md
- docker-build/pom.xml
- docker-build/src/main/docker/Dockerfile.jvm
- docker-build/src/main/docker/Dockerfile.legacy-jar
- docker-build/src/main/docker/Dockerfile.native
- docker-build/src/main/docker/Dockerfile.native-distroless
- docker-build/src/main/java/io/quarkus/ts/docker/HelloResource.java
- docker-build/src/main/resources/application.properties
- docker-build/src/test/java/io/quarkus/ts/docker/DockerBuildIT.java
- pom.xml
> [2.2] Add docker image name with empty spaces scenario

- docker-build/src/main/resources/application.properties
- docker-build/src/test/java/io/quarkus/ts/docker/NativeConfigurationIT.java
> [2.2] Add gdb debugging sources scenario

- README.md
- pom.xml
- qute/multimodule/pom.xml
- qute/multimodule/qute-api/pom.xml
- qute/multimodule/qute-api/src/main/java/io/quarkus/qe/qute/api/AlertMessages.java
- qute/multimodule/qute-api/src/main/java/io/quarkus/qe/qute/api/AppMessagesProvider.java
- qute/multimodule/qute-api/src/main/java/io/quarkus/qe/qute/api/ExampleResource.java
- qute/multimodule/qute-api/src/main/resources/messages/alert_el.properties
- qute/multimodule/qute-api/src/main/resources/messages/alert_en.properties
- qute/multimodule/qute-test/pom.xml
- qute/multimodule/qute-test/src/test/java/io/quarkus/qe/qute/ExampleResourceTest.java
- qute/multimodule/qute-test/src/test/resources/messages/alert_el.properties
- qute/multimodule/qute-test/src/test/resources/messages/alert_en.properties
> [2.2] Coverage for Qute template engine and regression test for QUARKUS-1547

- cache/caffeine/src/main/java/io/quarkus/ts/cache/caffeine/ReactiveWithCacheResource.java
- cache/caffeine/src/test/java/io/quarkus/ts/cache/caffeine/cache/caffeine/ServiceWithCacheResourceIT.java
Revert "Disable reactive tests in `cache/caffeine`"
This reverts commit 50d90aad7867dbe05d5bbf2ed698a0b3155d869b.
https://github.com/quarkusio/quarkus/pull/22271 got merged
> Revert "Disable reactive tests in `cache/caffeine`"

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
Scenarios for: 
- `quarkus create app --gradle`
- `quarkus create app --jbang`
> Add Quarkus-cli create app gradle/jbang scenario

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
> [2.2] Add Quarkus-cli create app gradle/jbang scenario

- external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftWorkshopHeroesIT.java
- external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftWorkshopVillainsIT.java
- pom.xml
- security/keycloak-authz-classic/src/test/java/io/quarkus/ts/security/keycloak/authz/OpenShiftRhSso75AuthzSecurityIT.java
- security/keycloak-authz-reactive/src/test/java/io/quarkus/ts/security/keycloak/authz/OpenShiftRhSso75AuthzSecurityIT.java
- security/keycloak-jwt/src/test/java/io/quarkus/ts/security/keycloak/jwt/OpenShiftRhSso75OidcJwtSecurityIT.java
- security/keycloak-multitenant/src/test/java/io/quarkus/ts/security/keycloak/multitenant/OpenShiftRhSso75MultiTenantSecurityIT.java
- security/keycloak-oauth2/src/test/java/io/quarkus/ts/security/OpenShiftRhSso75Oauth2SecurityIT.java
- security/keycloak-oidc-client-basic/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/basic/OpenShiftRhSso75OidcClientSecurityIT.java
- security/keycloak-webapp/src/test/java/io/quarkus/ts/security/keycloak/webapp/OpenShiftRhSso75WebappSecurityIT.java
- security/keycloak/src/test/java/io/quarkus/ts/security/OpenShiftRhSso75OidcSecurityIT.java
- sql-db/multiple-pus/src/test/java/io/quarkus/ts/sqldb/multiplepus/OpenShiftMultiplePersistenceIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/MariaDB10DatabaseIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/OpenShiftPostgresql13DatabaseIT.java
* Removing microrelease version numbers from image tags to pick up
latest minors
* Bumping RHSSO 7.4 to 7.5
* Bumping RHSCL PostgreSQL to 13
* Bumping Oracle XE to 21
> Container version update

- http/jaxrs/pom.xml
- http/jaxrs/src/main/java/io/quarkus/ts/security/core/GreetingResource.java
- http/jaxrs/src/main/java/io/quarkus/ts/security/core/SerializationConfig.java
- http/jaxrs/src/test/java/io/quarkus/ts/security/core/BaseQuarkusBundleIT.java
- http/jaxrs/src/test/java/io/quarkus/ts/security/core/SerializationIT.java
> [2.2] native coverage: reflections registration of constructors

- docker-build/src/test/java/io/quarkus/ts/docker/NativeConfigurationIT.java
- http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/HttpCustomHeadersIT.java
- http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/HttpHostDisabledIT.java
- http/jaxrs/src/test/java/io/quarkus/ts/security/core/SerializationIT.java
- spring/spring-data/src/test/java/io/quarkus/ts/spring/data/primitivetypes/OpenShiftBookResourceIT.java
- spring/spring-data/src/test/java/io/quarkus/ts/spring/data/primitivetypes/OpenShiftCatResourceIT.java
- spring/spring-data/src/test/java/io/quarkus/ts/spring/data/primitivetypes/SpringDataBookResourceIT.java
- spring/spring-data/src/test/java/io/quarkus/ts/spring/data/primitivetypes/SpringDataCatResourceIT.java
- sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/reactive/AbstractReactiveDatabaseIT.java
> [2.2] Rename some customer cases test names in order to improve readability

- messaging/kafka-confluent-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/BaseKafkaAvroGroupIdIT.java
- messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/BaseKafkaAvroGroupIdIT.java
This change should fix github CI failures
> Increase timeout to 10 sec waiting for kafka reactive events

- http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/HttpMinimumReactiveIT.java
- http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/ServerlessExtensionDockerBuildStrategyOpenShiftHttpMinimumReactiveIT.java
- http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/ServerlessExtensionOpenShiftHttpMinimumReactiveIT.java
- http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/HttpMinimumIT.java
- http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/ServerlessExtensionDockerBuildStrategyOpenShiftHttpMinimumIT.java
- http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/ServerlessExtensionOpenShiftHttpMinimumIT.java
- super-size/many-extensions/src/test/java/io/quarkus/ts/many/extensions/ManyExtensionsIT.java
- super-size/many-extensions/src/test/java/io/quarkus/ts/many/extensions/ServerlessExtensionDockerBuildStrategyOpenShiftManyExtensionsIT.java
- super-size/many-extensions/src/test/java/io/quarkus/ts/many/extensions/ServerlessExtensionOpenShiftManyExtensionsIT.java
Trust all serverless hosts regardless if the SSL certificate is invalid on serverless scenarios
> Knative operator service is running by default over HTTPS

- pom.xml
- security/keycloak-jwt/src/test/java/io/quarkus/ts/security/keycloak/jwt/BaseOidcJwtSecurityIT.java
* Bumping io.quarkus.qe:io.quarkus.qe to 1.0.2.Final.
> [2.2] Quarkus QE test framework update

- .github/workflows/quarkus-snapshot.yaml
Set mandatory input for distribution
Fail example: https://github.com/quarkus-qe/quarkus-test-suite/runs/5032197826?check_suite_focus=true
> Set mandatory input for distribution

- pom.xml
* Bumping Quarkus QE test framework to 1.1.0.Beta.1.
> Quarkus QE test framework 1.1.0.Beta.1

- .github/quarkus-cli-config.yaml
- .github/workflows/ci.yml
- pom.xml
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliExtensionsIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliHelpIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliVersionIT.java
Framework bump to 1.0.3.Final + CLI fixes
> [2.2] Framework bump to 1.0.3.Final + CLI fixes

- http/vertx-web-client/src/test/java/io/quarkus/qe/vertx/webclient/ChuckNorrisResourceIT.java
Use default Jaeger image specified in test-framework
> Use default Jaeger image specified in test-framework

- logging/jboss/src/main/java/io/quarkus/ts/logging/jboss/LogResource.java
- logging/jboss/src/main/resources/application.properties
- logging/jboss/src/test/java/io/quarkus/ts/logging/jboss/DefaultMinLogLevelIT.java
backport: e5087ceb49995aef51156a03722df758ff69b814
> [2.2] Log min level coverage

- qute/multimodule/qute-api/pom.xml
- qute/multimodule/qute-test/pom.xml
> [2.2] Add qute multimodule maven modules names

- .github/workflows/ci.yml
- .github/workflows/daily.yaml
- .github/workflows/quarkus-snapshot.yaml
- pom.xml
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliExtensionsIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliVersionIT.java
Move main to Quarkus 2.7
Revert excludes applicable just for Quarkus 2.8+/main
Adjust CI scripts
Adjust modules used in Ecosystem CI
> Move main to Quarkus 2.7

- pom.xml
Remove qute module, tests are disabled, it has no value
> Remove qute module, tests are disabled, it has no value

- lifecycle-application/pom.xml
- pom.xml
Upgrade Quarkus platform version to the latest one.
> Upgrade Quarkus platform version to 2.7.4.Final

- sql-db/hibernate-fulltext-search/pom.xml
- sql-db/hibernate-fulltext-search/src/main/java/io/quarkus/qe/hibernate/search/FruitResource.java
Moves all resteasy method to a blocking thread model, in order to use `quarkus-resteasy-reactive` with blocking `quarkus-hibernate-orm-panache`
> Use quarkus-resteasy-reactive in hibernate-fulltext-search scenario

- service-discovery/stork/src/test/java/io/quarkus/ts/stork/AbstractCommonTestCases.java
- service-discovery/stork/src/test/java/io/quarkus/ts/stork/NativeStorkServiceDiscoveryIT.java
- service-discovery/stork/src/test/java/io/quarkus/ts/stork/OpenShiftStorkServiceDiscoveryIT.java
- service-discovery/stork/src/test/java/io/quarkus/ts/stork/StorkLoadBalancerIT.java
The current native scenario is too heavy in terms of memory and CPU usage.
This commit disables the current scenario for native mode and also create a new simpler scenario
in order to validate native execution
> Native Stork refactor

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
Quarkus-cli should be able to select which java version to target. This PR verifies this behavior
> quarkus-cli should allow you to select which java version to target

- sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/reactive/openshift/OpenShiftMySqlIT.java
- sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/reactive/openshift/OpenShiftPostgresql10IT.java
- sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/reactive/openshift/OpenShiftPostgresqlIT.java
Enable tests, which were disabled because of already fixed bugs
> Enable tests, which were disabled because of already fixed bugs

- lifecycle-application/pom.xml
> Solve the conflict between Red Hat repository defined for lifecycle application and the one, defined for CLI

- pom.xml
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/MariaDB10DatabaseIT.java
Image from bitnami was restarting after notifying that it is ready to accept connections
> Use upstream MariaDB docker image

- http/rest-client/src/test/java/io/quarkus/ts/http/restclient/ClientBookResourceIT.java
Fails: 
```
cd http/rest-client
mvn clean verify -Dquarkus.platform.version=2.2.5.Final
```
Success: `mvn clean verify -Dall-modules -pl http/rest-client`
> NotFound RestEasy resources should not return any internal impl details

- pom.xml
Required to solve porblems with podman and windows.
See https://github.com/testcontainers/testcontainers-java/issues/5275
for details
> Use fully-qualified names of docker images

- security/keycloak/src/test/java/io/quarkus/ts/security/DevModeOidcSecurityIT.java
Add missing keycloak + devservice + FIPS workaround
> Disable FIPS on Keycloak devservice container

- pom.xml
Workaround for issue reported in
https://github.com/quarkusio/quarkus/issues/25171.
> Add workaround for Quarkus hamcrest dependency collision

- pom.xml
Bump FW from 1.1.0.Beta3 to 1.1.0.Beta4
> Bump FW from 1.1.0.Beta3 to 1.1.0.Beta4

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateExtensionIT.java
Test coverage for extension creation and build
> Test coverage for extension creation and build

- pom.xml
> Bump quarkus-test-framework from 1.1.0.Beta4 to 1.1.0.Beta5

- security/keycloak/src/main/resources/application.properties
Disable FIPS on keycloak devService
> Disable FIPS on keycloak devservices

- pom.xml
Move to quarkus-test-framework 1.1.0.Final
> Move to quarkus-test-framework 1.1.0.Final

- http/rest-client-reactive/src/main/resources/modern.properties
Enlarge timeout for successful handling of large files on IO-bounded machines
> Enlarge timeout

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
When "resteasy" and "resteasy-reactive" are added as extensions an error should be thrown.
This PR covers the above scenario.
> Add scenario for resteasy extension collisions

- http/rest-client-reactive/pom.xml
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/BookClient.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/PlainBookResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/ReactiveClientBookResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/files/FileClientResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/files/FileResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/files/OsUtils.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/json/IdBeanParam.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/json/JsonRestInterface.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/proxy/ProxyClient.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/proxy/ProxyResource.java
- http/rest-client-reactive/src/main/resources/classic.properties
- http/rest-client-reactive/src/main/resources/modern.properties
- http/rest-client-reactive/src/main/resources/proxy.properties
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ClassicPropertiesIT.java
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/LargeFileHandlingIT.java
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ProxyIT.java
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientIT.java
- http/rest-client-reactive/src/test/resources/proxy/Dockerfile
- http/rest-client-reactive/src/test/resources/proxy/README.md
- http/rest-client-reactive/src/test/resources/proxy/deploy.sh
- http/rest-client-reactive/src/test/resources/proxy/nginx.conf
- http/rest-client-reactive/src/test/resources/proxy/run.sh
Follow-up on https://github.com/quarkus-qe/quarkus-test-suite/pull/580, adds coverage for sub-resources and proxies as well as some refactoring in a separate commit.
Test plan: https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-1415.md
> Reactive REST client, part2

- monitoring/micrometer-prometheus/src/main/java/io/quarkus/ts/micrometer/prometheus/UsingMicroProfilePingPongResource.java
- monitoring/micrometer-prometheus/src/test/java/io/quarkus/ts/micrometer/prometheus/UsingMicroProfilePingPongResourceIT.java
Define multiple `@Gauge` metrics in a class and verify that all of them
are being recorded.
> Extend test of annotated Gauge metrics

- .github/pull_request_template.md
Add refactoring option into PR template
> Add refactoring option into PR template

- http/http-advanced/pom.xml
- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/DomainSocketIT.java
Scenario for Unix Domain Socket usage
> Scenario for Unix Domain Socket usage

- README.md
- pom.xml
- security/keycloak-oidc-client-reactive/pom.xml
- security/keycloak-oidc-client-reactive/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/RequestHeadersClient.java
- security/keycloak-oidc-client-reactive/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/RequestHeadersClientResource.java
- security/keycloak-oidc-client-reactive/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/RequestHeadersResource.java
- security/keycloak-oidc-client-reactive/src/main/resources/application.properties
- security/keycloak-oidc-client-reactive/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/RequestHeadersIT.java
- security/keycloak-oidc-client-reactive/src/test/resources/keycloak-realm.json
- security/keycloak-oidc-client-reactive/src/test/resources/test.properties
Covers reported bug: https://github.com/quarkusio/quarkus/issues/25029.
> Test OIDC client request reactive filter

- security/jwt/src/main/resources/application.properties
> [2.7] Keep PEM files in native mode

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateExtensionIT.java
Related to: https://github.com/quarkusio/quarkus/pull/25880#issuecomment-1149671224
Fixes https://github.com/quarkus-qe/quarkus-test-suite/issues/693
> Disable Quarkus-cli create extension scenario on Quarkus upstream

- sql-db/reactive-vanilla/src/test/java/io/quarkus/ts/reactive/db/clients/DevModeMultipleReactiveSqlClientsIT.java
- sql-db/reactive-vanilla/src/test/java/io/quarkus/ts/reactive/db/clients/DevModeReactiveMysqlDevServiceUserExperienceIT.java
- sql-db/reactive-vanilla/src/test/java/io/quarkus/ts/reactive/db/clients/DevModeReactivePostgresqlDevServiceUserExperienceIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMssqlIT.java
Related to: https://github.com/quarkusio/quarkus/issues/26042
> Disable Mssql devservice scenarios due to a missing configuration

- sql-db/reactive-vanilla/src/main/resources/container-license-acceptance.txt
- sql-db/reactive-vanilla/src/test/java/io/quarkus/ts/reactive/db/clients/DevModeMultipleReactiveSqlClientsIT.java
- sql-db/reactive-vanilla/src/test/java/io/quarkus/ts/reactive/db/clients/DevModeReactiveMysqlDevServiceUserExperienceIT.java
- sql-db/reactive-vanilla/src/test/java/io/quarkus/ts/reactive/db/clients/DevModeReactivePostgresqlDevServiceUserExperienceIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMssqlIT.java
- sql-db/sql-app/src/test/resources/container-license-acceptance.txt
Mssql requires you to accept a license agreement for each version. This PR add license agreement for `mcr.microsoft.com/mssql/server:2019-latest`
> Enable Mssql devservice scenarios

- http/vertx-web-client/src/test/java/io/quarkus/ts/http/vertx/webclient/VertxWebClientIT.java
From this PR [Fix `VertxWebClientIT` condition assertion & correct Span operation name](https://github.com/quarkus-qe/quarkus-test-suite/pull/706) was backported the following commit:
* [Filter traces by operation name and correct VertxWebClientIT assertion](https://github.com/quarkus-qe/quarkus-test-suite/pull/706/commits/a2bf694025da1b937118fca27d3b11efda83efd3)
> [2.7] backport RHBQ 2.7.6 part 3

- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/BookClient.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/ReactiveClientBookResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/files/FileClient.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/files/FileClientResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/files/FileResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/files/FileWrapper.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/files/OsUtils.java
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/LargeFileHandlingIT.java
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientIT.java
Add checks for the following issues:
https://github.com/quarkusio/quarkus/issues/24402
https://github.com/quarkusio/quarkus/issues/24405
https://github.com/quarkusio/quarkus/issues/24415
https://github.com/quarkusio/quarkus/issues/25028
Additionally: delete temporary files to speed up local execution and use java tools instead of OS-specific ones
> Coverage for 2.7.6 backports

- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/BookClient.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/ReactiveClientBookResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/files/FileClient.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/files/FileClientResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/files/FileResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/files/FileWrapper.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/files/OsUtils.java
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/LargeFileHandlingIT.java
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientIT.java
[Coverage for 2.7.6 backports](https://github.com/quarkus-qe/quarkus-test-suite/pull/685)
> [2.7] Backport 2.7.6 several scenarios

- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/DomainSocketIT.java
Simplify DomainSocketIT and use Awaitility
CountDownLatch looks a bit too complex for the scenario
> Simplify DomainSocketIT and use Awaitility

- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/LargeFileHandlingIT.java
> Use upstream issue number for the bug

- http/vertx-web-client/src/main/java/io/quarkus/ts/http/vertx/webclient/handler/ChuckNorrisResource.java
- http/vertx-web-client/src/main/java/io/quarkus/ts/http/vertx/webclient/handler/FailureHandler.java
- service-discovery/stork-custom/src/main/java/io/quarkus/ts/stork/custom/PongReplicaResource.java
- service-discovery/stork-custom/src/main/java/io/quarkus/ts/stork/custom/PongResource.java
- sql-db/vertx-sql/src/main/java/io/quarkus/ts/vertx/sql/handlers/AirlineHandler.java
- sql-db/vertx-sql/src/main/java/io/quarkus/ts/vertx/sql/handlers/AirportsHandler.java
- sql-db/vertx-sql/src/main/java/io/quarkus/ts/vertx/sql/handlers/FailureHandler.java
- sql-db/vertx-sql/src/main/java/io/quarkus/ts/vertx/sql/handlers/FlightsHandler.java
- sql-db/vertx-sql/src/main/java/io/quarkus/ts/vertx/sql/handlers/PricingRulesHandler.java
Path expression "/" is not supported any longer as a subpath. This PR replaces this regexp with a proper one that fits each case.
> Fix reactive routes path regexp

- pom.xml
- properties/pom.xml
Remove Consul extension workaround
Update Consul extension to 1.1.0 which includes fix for https://github.com/quarkiverse/quarkus-config-extensions/issues/70
> Remove Consul extension workaround

- .github/workflows/ci.yml
- .github/workflows/daily.yaml
Use batch mode in CI runs to reduce size of the logs and make searching faster
> Use batch mode in CI runs

- pom.xml
Remove hamcrest-core workaround
https://github.com/quarkusio/quarkus/issues/25171 was fixed for 2.9/2.10
> Remove hamcrest-core workaround

- sql-db/vertx-sql/src/main/java/io/quarkus/ts/vertx/sql/handlers/FailureHandler.java
Unify the path with other occurences.
See also 0b360080beecc2c344b2d5a380e4a298ce6200d6.
Follow-up to https://github.com/quarkus-qe/quarkus-test-suite/pull/740.
> Fix Vert.x route path in vertx-sql

- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/SslAlertMonitorIT.java
cherry picked from commit 3e57d244beee3d3e8eb382fbbac13b4e04cabca5
> [2.7] Disable KafkaSSL on FIPS builds

- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/ContainerRequestFilterReactiveIT.java
- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/ContainerRequestFilterIT.java
- scheduling/quartz/src/test/java/io/quarkus/ts/scheduling/quartz/AnnotationScheduledJobsMySqlQuartzIT.java
- scheduling/quartz/src/test/java/io/quarkus/ts/scheduling/quartz/BasicMySqlQuartzIT.java
- security/bouncycastle-fips/bcfips/src/test/java/io/quarkus/ts/security/bouncycastle/fips/BouncyCastleFipsIT.java
- security/https/src/test/java/io/quarkus/ts/security/https/enabled/UnixEnabledHttpsSecurityIT.java
- security/https/src/test/java/io/quarkus/ts/security/https/redirect/UnixRedirectHttpsSecurityIT.java
- security/https/src/test/java/io/quarkus/ts/security/https/secured/UnixAuthzHttpsSecurityIT.java
- security/keycloak-jwt/src/test/java/io/quarkus/ts/security/keycloak/jwt/KeycloakOidcJwtSecurityIT.java
- security/keycloak-multitenant/src/test/java/io/quarkus/ts/security/keycloak/multitenant/KeycloakMultiTenantSecurityIT.java
- security/keycloak-oidc-client-basic/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/basic/BaseOidcClientSecurityIT.java
- security/vertx-jwt/src/test/java/io/quarkus/ts/security/vertx/BladeRunnerHandlerIT.java
- security/vertx-jwt/src/test/java/io/quarkus/ts/security/vertx/NoSecuredResourceIT.java
- security/vertx-jwt/src/test/java/io/quarkus/ts/security/vertx/ReplicantHandlerIT.java
- security/vertx-jwt/src/test/java/io/quarkus/ts/security/vertx/SecuredResourceIT.java
- security/vertx-jwt/src/test/java/io/quarkus/ts/security/vertx/jwt/JwtIT.java
- sql-db/hibernate-fulltext-search/src/test/java/io/quarkus/ts/hibernate/search/MysqlMultitenantHibernateSearchIT.java
- sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/MySQLDatabaseHibernateReactiveIT.java
- sql-db/panache-flyway/src/test/java/io/quarkus/ts/sqldb/panacheflyway/CRUDAllInPanacheWithFlywayIT.java
- sql-db/panache-flyway/src/test/java/io/quarkus/ts/sqldb/panacheflyway/CRUDPanacheWithFlywayIT.java
- sql-db/panache-flyway/src/test/java/io/quarkus/ts/sqldb/panacheflyway/DataSourceConfigPanacheWithFlywayIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/MySqlDatabaseIT.java
- sql-db/vertx-sql/src/test/java/io/quarkus/ts/vertx/sql/handlers/MysqlHandlerIT.java
There are several modules that doesn't work on FIPS + native mode. This PR will disable these scenarios until do a further investigation.
> fips incompatible (Native mode)

- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/ContainerRequestFilterReactiveIT.java
- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/ContainerRequestFilterIT.java
- scheduling/quartz/src/test/java/io/quarkus/ts/scheduling/quartz/AnnotationScheduledJobsMySqlQuartzIT.java
- scheduling/quartz/src/test/java/io/quarkus/ts/scheduling/quartz/BasicMySqlQuartzIT.java
- security/bouncycastle-fips/bcfips/src/test/java/io/quarkus/ts/security/bouncycastle/fips/BouncyCastleFipsIT.java
- security/https/src/test/java/io/quarkus/ts/security/https/enabled/UnixEnabledHttpsSecurityIT.java
- security/https/src/test/java/io/quarkus/ts/security/https/redirect/UnixRedirectHttpsSecurityIT.java
- security/https/src/test/java/io/quarkus/ts/security/https/secured/UnixAuthzHttpsSecurityIT.java
- security/keycloak-jwt/src/test/java/io/quarkus/ts/security/keycloak/jwt/KeycloakOidcJwtSecurityIT.java
- security/keycloak-multitenant/src/test/java/io/quarkus/ts/security/keycloak/multitenant/KeycloakMultiTenantSecurityIT.java
- security/keycloak-oidc-client-basic/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/basic/BaseOidcClientSecurityIT.java
- security/vertx-jwt/src/test/java/io/quarkus/ts/security/vertx/BladeRunnerHandlerIT.java
- security/vertx-jwt/src/test/java/io/quarkus/ts/security/vertx/NoSecuredResourceIT.java
- security/vertx-jwt/src/test/java/io/quarkus/ts/security/vertx/ReplicantHandlerIT.java
- security/vertx-jwt/src/test/java/io/quarkus/ts/security/vertx/SecuredResourceIT.java
- security/vertx-jwt/src/test/java/io/quarkus/ts/security/vertx/jwt/JwtIT.java
- sql-db/hibernate-fulltext-search/src/test/java/io/quarkus/ts/hibernate/search/MysqlMultitenantHibernateSearchIT.java
- sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/MySQLDatabaseHibernateReactiveIT.java
- sql-db/panache-flyway/src/test/java/io/quarkus/ts/sqldb/panacheflyway/CRUDAllInPanacheWithFlywayIT.java
- sql-db/panache-flyway/src/test/java/io/quarkus/ts/sqldb/panacheflyway/CRUDPanacheWithFlywayIT.java
- sql-db/panache-flyway/src/test/java/io/quarkus/ts/sqldb/panacheflyway/DataSourceConfigPanacheWithFlywayIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/MySqlDatabaseIT.java
- sql-db/vertx-sql/src/test/java/io/quarkus/ts/vertx/sql/handlers/MysqlHandlerIT.java
(cherry picked from commit ff77c41770753b7371038388f00f8c6f863afd2f)
backport: #757 
> [2.7] Disable several scenarios in FIPS mode

- http/http-advanced-reactive/src/main/resources/application.properties
- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/BaseHttpAdvancedReactiveIT.java
- http/http-advanced/src/main/resources/application.properties
- monitoring/micrometer-prometheus-kafka-reactive/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/reactive/BaseOpenShiftAlertEventsReactiveIT.java
- monitoring/micrometer-prometheus-kafka/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/BaseOpenShiftAlertEventsIT.java
- monitoring/micrometer-prometheus/src/test/java/io/quarkus/ts/micrometer/prometheus/OpenShiftCustomMetricsIT.java
- service-discovery/stork/pom.xml
- service-discovery/stork/src/main/resources/application.properties
- service-discovery/stork/src/test/java/io/quarkus/ts/stork/OpenShiftStorkServiceDiscoveryIT.java
Some amendments in order to run weekly build over upstream
> OCP Ustream stability

- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/HttpAdvancedReactiveIT.java
- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/HttpAdvancedIT.java
- security/bouncycastle-fips/bcFipsJsse/src/test/java/io/quarkus/ts/security/bouncycastle/fips/jsse/BouncyCastleFipsJsseIT.java
- spring/spring-data/src/test/java/io/quarkus/ts/spring/data/di/SpringDiTest.java
- sql-db/panache-flyway/src/test/java/io/quarkus/ts/sqldb/panacheflyway/dbpool/AgroalPoolTest.java
- super-size/many-extensions/src/test/java/io/quarkus/ts/many/extensions/ManyExtensionsIT.java
(cherry picked from commit 6775c5f30e730917974d1213d903b18e65b8ac09)
> [2.7] Disable FIPS native failures

- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/BookClient.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/PlainBookResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/ReactiveClientBookResource.java
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientIT.java
Provides coverage for https://issues.redhat.com/browse/QUARKUS-2098
Test plans: https://github.com/quarkus-qe/quarkus-test-plans/pull/85
> Add coverage for QUARKUS-2098: Fix support of media types with suffixes

- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/BookClient.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/PlainBookResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/ReactiveClientBookResource.java
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientIT.java
Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/775
> [backport 2.7]Add coverage for QUARKUS-2098: Fix support of media types with suffixes

- security/keycloak-authz-classic/src/test/resources/keycloak-realm.json
(Add uma_protection scope to module "Keycloak + Authorization + Classic"
> Keycloak 18 requires uma_protection scope on Keycloak + Authorization + Classic

- security/keycloak-authz-classic/src/test/resources/keycloak-realm.json
- security/keycloak-authz-reactive/src/test/resources/keycloak-realm.json
- security/keycloak-oidc-client-basic/src/test/resources/keycloak-realm.json
- security/keycloak/src/test/resources/keycloak-realm.json
Some daily scenarios are failing because are missing scope uma_protection. This PR add uma_protection to these scenarios
> Add to Keycloak 18,  `uma_protection` scope to realm test-admin-user

- sql-db/vertx-sql/src/main/resources/application.properties
Related to: https://github.com/quarkusio/quarkus/issues/27101
> Fix daily issues: Oracle native compilation error

- properties/src/test/java/io/quarkus/ts/properties/bulk/ConfigValueIT.java
Update test expectation in native mode
Related to: https://github.com/quarkusio/quarkus/issues/27231#issuecomment-1211783882
> Update upstream scenario due to an upstream changes

- sql-db/vertx-sql/pom.xml
Revert: https://github.com/quarkus-qe/quarkus-test-suite/pull/789
> Revert Disable native compilation on Vertx-sql due to an open issue

- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DevModeKafkaStreamIT.java
Related to: https://github.com/quarkusio/quarkus/issues/27352
> Disable DevService Kafka streams due to an upstream issue

- pom.xml
- security/keycloak/src/test/java/io/quarkus/ts/security/keycloak/DevModeKeycloakDevServiceUserExperienceIT.java
> Use Keycloak 19 instead of 16

- messaging/kafka-confluent-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/BaseKafkaAvroIT.java
Extends Kafka batch Strimzi patch to Kafka confluent
Ref: https://github.com/quarkus-qe/quarkus-test-suite/pull/799/files
> Fix flaky Kafka confluent Batch scenario (Flaky test)

- messaging/kafka-confluent-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/BaseKafkaAvroIT.java
- messaging/kafka-strimzi-avro-reactive-messaging/src/main/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/KStockPriceProducer.java
- messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/BaseKafkaAvroIT.java
- messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/StrimziKafkaAvroGroupIdIT.java
Backport the following commits:
9f849619623aca8820bba1919aea0c15487498fc 
d086ccc75a7fdc46987c37d90e0829eb8168704f 
ca0119edfb2d4ed77c1cb8e893f71cde2ac50464 
> [2.7] Backport Kafka facky test patches

- http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/Hello.java
- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/BaseHttpAdvancedReactiveIT.java
- http/http-advanced/src/main/java/io/quarkus/ts/http/advanced/Hello.java
- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/BaseHttpAdvancedIT.java
Openapi should add content from javax.validation.constraints.Pattern to opeapi yaml file. Implemented in https://issues.redhat.com/browse/QUARKUS-2004
> Check, that openapi process @Pattern annotation

- sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/openshift/OpenShiftHibernateReactiveMsSQLIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/OpenShiftMssqlDatabaseIT.java
Similar to https://github.com/quarkus-qe/quarkus-test-suite/pull/802, but for the main branch
> Disable MSSQL tests on openshift due to a known issue

- env-info/README.md
- env-info/pom.xml
- env-info/src/main/java/io/quarkus/ts/envinfo/OsJvmEnvInfoLogger.java
- pom.xml
New module runs a simple class which outputs info about OS, architecture
and JVM into a file given by an argument.
The module must be called separately.
Parent POM contains a dedicated maven profile for the module.
> Add environment logging module

- javaee-like-getting-started/pom.xml
- messaging/infinispan-grpc-kafka/pom.xml
- messaging/kafka-producer/pom.xml
- messaging/kafkaSSL/pom.xml
- service-binding/postgresql-crunchy/pom.xml
- sql-db/vertx-sql/pom.xml
- super-size/many-extensions/pom.xml
- Remove some duplicated dependencies
> remove some duplicate dependencies

- service-discovery/stork-custom/src/test/java/io/quarkus/ts/stork/custom/StorkCustomServiceDiscoveryAndLoadBalancerIT.java
Related to: https://github.com/quarkusio/quarkus/issues/27870
This PR fix daily issues: https://github.com/quarkus-qe/quarkus-test-suite/runs/8296152260?check_suite_focus=true
> Set Stork custom service discovery host

- service-discovery/stork/pom.xml
Related to: https://github.com/quarkusio/quarkus/issues/27886
> Disable stork native build due to an upstream issue

- service-discovery/stork-custom/src/test/java/io/quarkus/ts/stork/custom/StorkCustomServiceDiscoveryAndLoadBalancerIT.java
Related to: https://github.com/quarkusio/quarkus/pull/27891
> Rollback workaround for stork default host #828

- env-info/src/main/java/io/quarkus/ts/envinfo/OsJvmEnvInfoLogger.java
Provide info about Maven
Example:
```
Mac OS X 12.5.1
Architecture
x86_64
JVM
OpenJDK 64-Bit Server VM GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05, mixed mode, sharing)
11
MVN
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /Users/rsvoboda/.sdkman/candidates/maven/current
Java version: 11.0.13, vendor: GraalVM Community, runtime: /Users/rsvoboda/.sdkman/candidates/java/21.3.0.r11-grl
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "12.5.1", arch: "x86_64", family: "mac"
```
> Provide info about Maven

- pom.xml
Quarkus stork has been updated to 1.2.0
> Bump Stork to 1.2.0

- service-discovery/stork/pom.xml
Related to: https://github.com/quarkusio/quarkus/issues/27886
Native errors are fixed by Stork 1.2.0
> Add required K8s_client to Stork scenario

- pom.xml
New TS release with fixes of OpenShiftClient issues.
Disable kamelet module
- https://github.com/quarkusio/quarkus/issues/28007
> Bump Quarkus QE TF from 1.2.0.Beta9 to 1.2.0.Beta11

- sql-db/hibernate-reactive/src/main/java/io/quarkus/ts/hibernate/reactive/database/Author.java
- sql-db/hibernate-reactive/src/main/java/io/quarkus/ts/hibernate/reactive/http/PanacheEndpoint.java
- sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/AbstractDatabaseHibernateReactiveIT.java
Covers https://issues.redhat.com/browse/QUARKUS-1220
> Verify, that Multi is serialized into JSON properly

- .github/workflows/ci.yml
- .github/workflows/daily.yaml
- .github/workflows/quarkus-snapshot.yaml
Update JDK install action to the latest version
> Update JDK install action to the latest version

- spring/spring-data/README.md
- spring/spring-data/src/main/java/io/quarkus/ts/spring/data/rest/ArticleJpaRepository.java
- spring/spring-data/src/main/java/io/quarkus/ts/spring/data/rest/ArticleRepository.java
- spring/spring-data/src/test/java/io/quarkus/ts/spring/data/rest/AbstractPagingAndSortingRepositoryRestResourceIT.java
- spring/spring-data/src/test/java/io/quarkus/ts/spring/data/rest/AbstractRepositoryRestResourceIT.java
- spring/spring-data/src/test/java/io/quarkus/ts/spring/data/rest/CrudRepositoryRestResourceIT.java
- spring/spring-data/src/test/java/io/quarkus/ts/spring/data/rest/JpaRepositoryRestResourceIT.java
- spring/spring-data/src/test/java/io/quarkus/ts/spring/data/rest/PagingAndSortingRepositoryRestResourceIT.java
Based on https://issues.redhat.com/browse/QUARKUS-2388 - Promote Spring Data REST from TP to full support.
Test plan:
https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-2388.md.
> Add more tests of spring-data-rest

- docker-build/src/main/docker/Dockerfile.jvm
- docker-build/src/main/docker/Dockerfile.native
- helm/helm-minimum/src/main/docker/Dockerfile.jvm
Sync of changes in Dockerfiles with upstream
- https://github.com/quarkusio/quarkus/pull/28362
- https://github.com/quarkusio/quarkus/commit/f335f7e084429d2744ff839e6273d64f017948eb
- https://github.com/quarkusio/quarkus/commit/79d7ed54b396fc045c5313a8fecd0175209bcec7
> Sync of changes in Dockerfiles with upstream

- README.md
- funqy/knative-events/pom.xml
- funqy/knative-events/src/main/java/io/quarkus/ts/funqy/knativeevents/BrokerClient.java
- funqy/knative-events/src/main/java/io/quarkus/ts/funqy/knativeevents/Constants.java
- funqy/knative-events/src/main/java/io/quarkus/ts/funqy/knativeevents/FunctionValidationChain.java
- funqy/knative-events/src/main/java/io/quarkus/ts/funqy/knativeevents/ValidationResult.java
- funqy/knative-events/src/main/java/io/quarkus/ts/funqy/knativeevents/ValidationResultRepository.java
- funqy/knative-events/src/main/resources/application.properties
- funqy/knative-events/src/test/java/io/quarkus/ts/funqy/knativeevents/FunqyKnEventsIT.java
- funqy/knative-events/src/test/java/io/quarkus/ts/funqy/knativeevents/ServerlessExtensionOpenShiftFunqyKnEventsIT.java
- pom.xml
Adds Funqy Knative Events test coverage according to the [test plan](https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-2284.md).
> Test Funqy Knative Events functions

- http/rest-client-reactive/src/test/resources/proxy/Dockerfile
- http/rest-client-reactive/src/test/resources/proxy/deploy.sh
> Update to the latest docker version

- http/jaxrs-reactive/src/test/java/io/quarkus/ts/http/jaxrs/reactive/client/MultipartClientIT.java
Related to: https://github.com/quarkusio/quarkus/issues/28782
> Disable MultipartClientIT#testMultipartDataIsSent scenario due to an upstream issue

- README.md
- http/jaxrs-reactive/src/main/java/io/quarkus/ts/http/jaxrs/reactive/CompressionResource.java
- http/jaxrs-reactive/src/main/resources/application.properties
- http/jaxrs-reactive/src/test/java/io/quarkus/ts/http/jaxrs/reactive/CompressionHandlerIT.java
- http/jaxrs-reactive/src/test/java/io/quarkus/ts/http/jaxrs/reactive/OpenShiftCompressionHandlerIT.java
- http/jaxrs-reactive/src/test/java/io/quarkus/ts/http/jaxrs/reactive/OpenShiftExecutionModelIT.java
- http/reactive-routes/src/main/java/io/quarkus/ts/http/reactiveroutes/CompressionHandler.java
- http/reactive-routes/src/main/resources/application.properties
- http/reactive-routes/src/test/java/io/quarkus/ts/http/reactiveroutes/CompressionHandlerIT.java
TP: https://github.com/quarkus-qe/quarkus-test-plans
> Compression support for Reactive Routes and RESTEasy Reactive

- test-tooling/pact/pom.xml
- test-tooling/pact/src/test/java/io/quarkus/ts/http/pact/ProviderPactTest.java
* c4accd0a1f1047487feb13378096f19447af39f2 - Update Pact to supported 4.1
> [2.13] Backport - Update Pact to supported 4.1

- http/jaxrs-reactive/src/test/java/io/quarkus/ts/http/jaxrs/reactive/client/MultipartClientIT.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/files/FileResource.java
- http/rest-client-reactive/src/main/resources/modern.properties
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/LargeFileHandlingIT.java
Related to: 
- https://github.com/quarkusio/quarkus/issues/28920
- https://github.com/quarkusio/quarkus/issues/25909
> Re-enable some Multipart test that was previously disabled

- sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/openshift/OpenShiftHibernateReactiveMsSQLIT.java
- sql-db/reactive-rest-data-panache/src/test/java/io/quarkus/ts/reactive/rest/data/panache/OpenShiftMssqlPanacheResourceIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/OpenShiftMssqlDatabaseIT.java
Reverts quarkus-qe/quarkus-test-suite#866 as the workaround on clusters broken operators
> Revert "Re-enable mssql scenario"

- config/src/main/resources/application.properties
Fixes OpenShift tests, which were failing due to https://github.com/quarkus-qe/quarkus-test-suite/pull/886
> Fix failing OpenShift tests

- README.md
- http/jaxrs-reactive/src/main/java/io/quarkus/ts/http/jaxrs/reactive/CompressionResource.java
- http/jaxrs-reactive/src/main/resources/application.properties
- http/jaxrs-reactive/src/test/java/io/quarkus/ts/http/jaxrs/reactive/CompressionHandlerIT.java
- http/jaxrs-reactive/src/test/java/io/quarkus/ts/http/jaxrs/reactive/OpenShiftCompressionHandlerIT.java
- http/jaxrs-reactive/src/test/java/io/quarkus/ts/http/jaxrs/reactive/OpenShiftExecutionModelIT.java
- http/jaxrs-reactive/src/test/java/io/quarkus/ts/http/jaxrs/reactive/client/MultipartClientIT.java
- http/reactive-routes/src/main/java/io/quarkus/ts/http/reactiveroutes/CompressionHandler.java
- http/reactive-routes/src/main/resources/application.properties
- http/reactive-routes/src/test/java/io/quarkus/ts/http/reactiveroutes/CompressionHandlerIT.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/files/FileResource.java
- http/rest-client-reactive/src/main/resources/modern.properties
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/LargeFileHandlingIT.java
This PR contains the following commits:
- 9b45fe25935788ddb4e0a1471799bbdbabae7721 
- f006c18e8aa6bccfbf3b04689ecfca23cfc729bd 
-  f83c32a18092d0985947f3ea932dc75f578fc76b 
-  0e5a85cb9e720cf3a5e1adbad74010f51a2f15d6 
> [2.13] Backport: RestEasy Compression scenario and Multipart scenario issues

- README.md
- security/keycloak-oidc-client-extended/pom.xml
- security/keycloak-oidc-client-extended/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/tokens/LogoutFlow.java
- security/keycloak-oidc-client-extended/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/tokens/LogoutTenantResolver.java
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/LogoutSinglePageAppFlowIT.java
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/OpenShiftOidcSinglePageAppLogoutFlowIT.java
- security/keycloak-oidc-client-extended/src/test/resources/kc-logout-realm.json
- security/keycloak-oidc-client-extended/src/test/resources/logout.properties
- security/keycloak-oidc-client-reactive-extended/pom.xml
- security/keycloak-oidc-client-reactive-extended/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/tokens/LogoutFlow.java
- security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/LogoutSinglePageAppFlowIT.java
- security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/OpenShiftOidcSinglePageAppLogoutFlowIT.java
- security/keycloak-oidc-client-reactive-extended/src/test/resources/kc-logout-realm.json
- security/keycloak-oidc-client-reactive-extended/src/test/resources/logout.properties
Add OIDC single page application logout flow coverage
> Add single page app logout flow coverage

- pom.xml
Upgrade Quarkus.platform to the latest Quarkus platform version
> [2.13] Bump Quarkus platform to 2.13.4.Final

- security/keycloak-oidc-client-reactive-extended/src/test/resources/logout.properties
Currently this scenario is covering a single logout. This PR is removing a missconfiguration on the logs.
> Remove a logout debug log that was leftover

- http/graphql/src/main/java/io/quarkus/ts/http/graphql/Person.java
- http/graphql/src/main/java/io/quarkus/ts/http/graphql/PersonsEndpoint.java
- http/graphql/src/main/java/io/quarkus/ts/http/graphql/PersonsEndpointBase.java
- http/graphql/src/main/java/io/quarkus/ts/http/graphql/PersonsReactiveEndpoint.java
- http/graphql/src/main/java/io/quarkus/ts/http/graphql/PhilosophyEra.java
- http/graphql/src/main/java/io/quarkus/ts/http/graphql/PhilosophyException.java
- http/graphql/src/main/resources/application.properties
- http/graphql/src/test/java/io/quarkus/ts/http/graphql/GraphQLDisabledGetIT.java
- http/graphql/src/test/java/io/quarkus/ts/http/graphql/GraphQLIT.java
- http/graphql/src/test/java/io/quarkus/ts/http/graphql/GraphQLTracingIT.java
- http/graphql/src/test/java/io/quarkus/ts/http/graphql/OpenShiftGraphQLDisabledGetIT.java
- http/graphql/src/test/java/io/quarkus/ts/http/graphql/Utils.java
Adds test coverage for SmallRye GraphQL:
- reactive queries
- GET queries (GraphQL over HTTP)
- `@AdaptToScalar`
- Maps support
- `@ErrorCode`
> SmallRye GraphQL non-blocking support

- http/jaxrs-reactive/src/main/resources/application.properties
backports https://github.com/quarkus-qe/quarkus-test-suite/pull/937
> [2.13] Fix OpenShiftHttpCachingIT in native mode

- pom.xml
> Fix a possible cause of failed interop tests

- lifecycle-application/pom.xml
- pom.xml
> [2.13] Bump Quarkus to 2.13.6.Final

- .github/workflows/daily.yaml
Use github-token for graalvm/setup-graalvm to reduce rate limiting issues
Resources:
- https://github.com/graalvm/setup-graalvm#options
- https://github.com/graalvm/setup-graalvm#templates
- https://docs.github.com/en/actions/security-guides/automatic-token-authentication
Type:
> Use github-token for graalvm/setup-graalvm to reduce rate limiting issues

- lifecycle-application/src/test/java/io/quarkus/ts/lifecycle/OpenShiftLifecycleApplicationIT.java
- pom.xml
Update the framework to the new version[1]. This is required to solve bugs in interop tests and to fix several failures in OCP
[1] https://github.com/quarkus-qe/quarkus-test-framework/releases/tag/1.3.0.Beta1
> Bump the version of the framework

- external-applications/src/test/java/io/quarkus/ts/external/applications/TodoDemoIT.java
- pom.xml
Required for coverage of https://issues.redhat.com/browse/QUARKUS-2777
Will be in draft stage until new version of the Framework is released.
> Verify, that uberjar can be built even with empty suffix

- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/DevModeHttpsIT.java
- http/jaxrs-reactive/src/test/java/io/quarkus/ts/http/jaxrs/reactive/RESTEasyReactiveMultipartIT.java
- pom.xml
- Bump Quarkus to 2.13.7.Final
> [2.13] Bump Quarkus to 2.13.7.Final

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliSpecialCharsIT.java
* Updating description in QuarkusCliSpecialCharsIT# shouldCreateApplicationOnJvmWithSpaces as this is an issue in upstream Quarkus rather than in test suite.
Issue: https://github.com/quarkusio/quarkus/issues/30642
> Updating issue in disabled whitespace CLI test

- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DB2DatabaseIT.java
https://github.com/quarkusio/quarkus/issues/30176 is fixed now.
> Enable DB2DatabaseIT as upstream issue is fixed

- external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftWorkshopHeroesIT.java
- external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftWorkshopVillainsIT.java
- external-applications/src/test/java/io/quarkus/ts/external/applications/QuickstartIT.java
- external-applications/src/test/java/io/quarkus/ts/external/applications/TodoDemoIT.java
- pom.xml
Bump Quarkus QE framework version from 1.2.1.Final to 1.2.3.Final
> [2.13] Bump Quarkus QE framework version from 1.2.1.Final to 1.2.3.Final

- pom.xml
Depends on https://github.com/quarkus-qe/quarkus-test-framework/pull/671
> Updating Quarkus QE framework version to 1.1.5

- pom.xml
> [2.7] Bump to Quarkus 2.7.7.Final

- sql-db/panache-flyway/src/test/resources/test.properties
Backport
[Expose DB endpoint on OCP / flyway scenario](https://github.com/quarkus-qe/quarkus-test-suite/commit/170baaf222e9636eb501a034cab3781e62194e66)
> [2.13] Expose DB endpoint on OCP / flyway scenario

- sql-db/panache-flyway/src/test/resources/test.properties
I am getting a timeout on Mysql flyway scenario because the DB endpoint can´t be reached.
This PR exposes this database endpoint to the application.
> Expose DB endpoint on OCP / flyway scenario

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
Fixes https://issues.redhat.com/browse/QUARKUS-2707 for production
> Make jbang use the same repository as maven

- sql-db/hibernate-reactive/src/main/java/io/quarkus/ts/hibernate/reactive/http/PanacheEndpoint.java
- sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/AbstractDatabaseHibernateReactiveIT.java
Required for https://issues.redhat.com/browse/QUARKUS-2846
> Add coverage for new lines in HQL queries

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
Fixes https://issues.redhat.com/browse/QUARKUS-2709
> Explicitly use maven local repo for gradle build

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliHelpIT.java
Fixes Quarkus CLI failing test. https://github.com/quarkusio/quarkus/pull/29558 updated help for 'version' command.
> Update expected CLI help for command 'version'

- security/bouncycastle-fips/bcFipsJsse/src/main/java/io/quarkus/ts/security/bouncycastle/fips/jsse/SecretProvider.java
- security/bouncycastle-fips/bcFipsJsse/src/main/resources/application.properties
- security/bouncycastle-fips/bcFipsJsse/src/test/java/io/quarkus/ts/security/bouncycastle/fips/jsse/BouncyCastleFipsJsseIT.java
This PR inject keystore and truststore password through a custom credential provider.
JiraIssue: https://issues.redhat.com/browse/QUARKUS-2749
> Add coverage for credential provider

- http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/GrpcReflectionResponse.java
- http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/GrpcResource.java
- http/http-advanced-reactive/src/main/resources/application.properties
- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/BaseHttpAdvancedReactiveIT.java
Coverage for gRPC reflection services
> Add coverage for gRPC reflection services

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliSpecialCharsIT.java
Enabling tests as following Quarkus issues are now fixed:
- https://github.com/quarkusio/quarkus/issues/32266
- https://github.com/quarkusio/quarkus/issues/30642
> Enable Quarkus CLI tests disabled due to upstream issue that is fixed now

- websockets/quarkus-websockets/src/main/java/io/quarkus/ts/websockets/producer/Chat.java
- websockets/quarkus-websockets/src/test/java/io/quarkus/ts/websockets/producer/WebSocketsProducerConsumerIT.java
There is a flaky error on daily GH actions that are under investigation. This PR adds more logs in case of a failure. 
Also, the WebSocket broadcast implementation has been updated with the latest Doc recommendations. 
> Websocket: Improve websocket logs on failures 

- pom.xml
fixes: #1143
Previous AMQ Kafka Streams link is not valid anymore.
> Upgrade AMQ Kafka Streams to 2.3.0

- sql-db/sql-app-compatibility/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeOracleIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeOracleIT.java
Tests fails following https://github.com/quarkusio/quarkus/pull/32489 as used Docker image changed.
> Update expected docker image used by Dev Services for Oracle

- messaging/qpid/src/main/java/io/quarkus/ts/messaging/qpid/PriceConsumer.java
- messaging/qpid/src/main/java/io/quarkus/ts/messaging/qpid/PriceProducer.java
- pom.xml
Activate qpid module as quarkus-qpid-jms 2.1.0 now uses Quarkus 3
> Enable qpid module

- README.md
fixes https://github.com/quarkus-qe/quarkus-test-suite/issues/552
> Document test groups and current branches

- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/BaseOidcIT.java
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/OpenApiStoreSchemaIT.java
- security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/BaseOidcIT.java
- security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/OpenApiStoreSchemaIT.java
> Disable HTTP Basic authentication for OpenAPI OIDC tests

- http/graphql-telemetry/src/test/java/io/quarkus/ts/http/graphql/telemetry/GraphQLTelemetryIT.java
Adjust GraphQLTelemetryIT to reflect latest updates
GraphQL and OpenTelemetry now produces 2 spans with more details in it:
Fixes daily runs, aligns with https://github.com/quarkus-qe/quarkus-jdkspecifics/commit/4a88109acae44de083746dcabf9a228f1ad3dc9c
> Adjust GraphQLTelemetryIT to reflect latest updates

- README.md
- pom.xml
> Add option to debug Quarkus Test Suite

- sql-db/sql-app-compatibility/src/test/java/io/quarkus/ts/sqldb/compatibility/PostgresqlDatabaseIT.java
- sql-db/sql-app-compatibility/src/test/resources/test.properties
Extends https://github.com/quarkus-qe/quarkus-test-suite/pull/1240
> Rename PostgreSQL image instances

- security/keycloak/src/test/java/io/quarkus/ts/security/keycloak/DevModeKeycloakDevServiceUserExperienceIT.java
Before https://github.com/quarkusio/quarkus/pull/33476, encryption key was generated for all OIDC application types, even though it wasn't used for service application. When no encryption secret, client secret, client secret value or `client_jwt_secret` was set, warning message was logged. This is purely user experience issue and functionality is not affected, therefore we can only check logs.
fail: `mvn clean verify -Dit.test=DevModeKeycloakDevServiceUserExperienceIT -Dquarkus.oidc.application-type=hybrid`
pass: `mvn clean verify -Dit.test=DevModeKeycloakDevServiceUserExperienceIT`
backport PR to 2.13 needs to be adjusted as logged message lately changed https://github.com/quarkusio/quarkus/pull/33550
> Verify encryption key is not generated for OIDC service application

- http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/DevModeHttpMinimumReactiveIT.java
- http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/DevModeHttpMinimumIT.java
Reverts quarkus-qe/quarkus-test-suite#1256 as today fix was merged to upstream.
> Revert "Fix failing HTTP minimum DEV mode tests as logged message changed"

- pom.xml
- spring/spring-data/pom.xml
- spring/spring-data/src/test/java/io/quarkus/ts/spring/data/rest/additional/OpenAPIIT.java
Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/1158
> Enable native test scenario for OpenAPIIT

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
Disable a test until upstream issue is fixed
> Disable a test until upstream issue is fixed

- .openshift-interop/Dockerfile
- .openshift-interop/oc_login.sh
- .openshift-interop/run.sh
- .openshift-interop/settings.xml
This is mostly a draft, and maybe we should put these files into separate repo.
> Dockerfile and scripts for running interop tests

- pom.xml
> Bump test framework to 1.3.0.Beta21

- service-binding/postgresql-crunchy-reactive/src/test/java/io/quarkus/ts/sb/reactive/OpenShiftPostgreSqlReactiveSbIT.java
> Disable failing Postgres test

- .openshift-interop/README.md
> Documentation for Openshift CI tests

- http/vertx/src/test/java/io/quarkus/ts/vertx/AbstractVertxIT.java
> Adding vertx HttpClient test to http/vertx scenario

- build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/AnalyticsUtils.java
RHBQ platform version may differ in the number suffix from the RHBQ extensions version.
> Fix RHBQ version bug in build-time-analytics

- build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/AnalyticsUtils.java
RHBQ platform version may differ in the number suffix from the RHBQ extensions version.
Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/1359.
> [3.2] Fix RHBQ version bug in build-time-analytics

- http/http-advanced-reactive/src/test/resources/keycloak-realm.json
- http/http-advanced/src/test/resources/keycloak-realm.json
- pom.xml
- security/keycloak-authz-classic/src/test/resources/keycloak-realm.json
- security/keycloak-authz-reactive/src/test/resources/keycloak-realm.json
Bumps quarkus.qe.framework.version from 1.3.0.Beta23 to 1.3.0.Beta24
> Bump quarkus.qe.framework.version from 1.3.0.Beta23 to 1.3.0.Beta24

- http/jakarta-rest-reactive/src/test/java/io/quarkus/ts/http/jakartarest/reactive/OpenShiftCompressionHandlerIT.java
- http/jakarta-rest-reactive/src/test/java/io/quarkus/ts/http/jakartarest/reactive/OpenShiftExecutionModelIT.java
- http/jakarta-rest-reactive/src/test/java/io/quarkus/ts/http/jakartarest/reactive/OpenShiftHttpCachingIT.java
- http/jakarta-rest-reactive/src/test/java/io/quarkus/ts/http/jakartarest/reactive/OpenShiftRESTEasyReactiveMultipartIT.java
- http/jakarta-rest-reactive/src/test/java/io/quarkus/ts/http/jakartarest/reactive/json/OpenShiftJsonIT.java
Link to the [Issue](https://github.com/quarkusio/quarkus/issues/35344).
> Disable test affected by issue 35344

- http/jakarta-rest-reactive/src/test/java/io/quarkus/ts/http/jakartarest/reactive/OpenShiftRESTEasyReactiveMultipartIT.java
- http/jakarta-rest-reactive/src/test/java/io/quarkus/ts/http/jakartarest/reactive/json/OpenShiftJsonIT.java
Fixes code format errors after https://github.com/quarkus-qe/quarkus-test-suite/pull/1363
> Fix code style imports errors

- lifecycle-application/pom.xml
- pom.xml
> Bump Quarkus version to 3.2.4.Final

- pom.xml
> Update mandrel to version 23.0

- infinispan-client/src/test/java/io/quarkus/ts/infinispan/client/OperatorOpenShiftInfinispanCountersIT.java
To fix races when reaching to app, which not stopped/started
> Add wait in infinispan tests

- .github/workflows/ci.yml
- .github/workflows/daily.yaml
Same fix as [https://github.com/quarkus-qe/quarkus-jdkspecifics/pull/94](https://github.com/quarkus-qe/quarkus-jdkspecifics/pull/94)
> Add instalation of pigz to gh action definition.

- http/vertx-web-client/pom.xml
- pom.xml
put wiremock-jre8 under dependency management
> put wiremock-jre8 under dependency management

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
Run Gradle Daemon to avoid file lock on quarkus-cli-command.out when the daemon is started as part of the build
> Run Gradle Daemon to avoid file lock on quarkus-cli-command.out when the daemon is started as part of the build

- README.md
Windows Prerequisites for quarkus-cli
> Windows Prerequisites for quarkus-cli

- README.md
- nosql-db/elasticsearch/pom.xml
- nosql-db/elasticsearch/src/main/java/io/quarkus/ts/elasticsearch/DataTypes.java
- nosql-db/elasticsearch/src/main/java/io/quarkus/ts/elasticsearch/DataTypesResource.java
- nosql-db/elasticsearch/src/main/java/io/quarkus/ts/elasticsearch/DataTypesService.java
- nosql-db/elasticsearch/src/main/java/io/quarkus/ts/elasticsearch/Fruit.java
- nosql-db/elasticsearch/src/main/java/io/quarkus/ts/elasticsearch/FruitResource.java
- nosql-db/elasticsearch/src/main/java/io/quarkus/ts/elasticsearch/FruitService.java
- nosql-db/elasticsearch/src/test/java/io/quarkus/ts/elasticsearch/DevModeElasticsearchIT.java
- nosql-db/elasticsearch/src/test/java/io/quarkus/ts/elasticsearch/ElasticsearchIT.java
- pom.xml
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliSpecialCharsIT.java
- sql-db/hibernate-fulltext-search/src/test/java/io/quarkus/ts/hibernate/search/MysqlMultitenantHibernateSearchIT.java
- sql-db/hibernate-fulltext-search/src/test/java/io/quarkus/ts/hibernate/search/OpenShiftMysqlMultitenantHibernateSearchIT.java
- sql-db/hibernate-fulltext-search/src/test/java/io/quarkus/ts/hibernate/search/OpenShiftPostgresqlMultitenantHibernateSearchIT.java
- sql-db/hibernate-fulltext-search/src/test/java/io/quarkus/ts/hibernate/search/PostgresqlMultitenantHibernateSearchIT.java
Backports:
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1410
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1409
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1407
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1401
> [3.2] Backport Quarkus CLI Windows fixes and Elasticsearch Rest Client test development

- .github/workflows/daily.yaml
Switch GitHub Actions to Mandrel 23 and relevant GraalVM.
> Switch GitHub Actions to Mandrel 23 and relevant GraalVM

- sql-db/narayana-transactions/src/main/java/io/quarkus/ts/transactions/recovery/driver/CrashingXADataSource.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/MssqlTransactionGeneralUsageIT.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/TransactionCommons.java
Adds test for Narayana Microsoft SQL server on bare metal.
> Test Narayana MSSQL transaction log recovery on bare metal

- lifecycle-application/pom.xml
- pom.xml
> [3.2] Bump Quarkus version used by Test Suite in Github actions to 3.2.6

- .github/workflows/daily.yaml
I think we should test NoSQL modules as part of daily build. I added it to profiles set that lasts the least of all to run.
> Run NoSQL module as part of daily build

- infinispan-client/src/test/java/io/quarkus/ts/infinispan/client/OperatorOpenShiftInfinispanCountersIT.java
To fix races when reaching to app, which not stopped/started. Backporting #1371
> [3.2] Add wait in infinispan tests

- sql-db/panache-flyway/src/test/java/io/quarkus/ts/sqldb/panacheflyway/dbpool/AgroalPoolTest.java
- sql-db/vertx-sql/src/test/java/io/quarkus/ts/vertx/sql/dbpool/PostgresPoolTest.java
backports https://github.com/quarkus-qe/quarkus-test-suite/pull/1435
> [3.2] Backport `@QuarkusTest` DB Web client fixes for Windows

- build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/AbstractAnalyticsIT.java
backports https://github.com/quarkus-qe/quarkus-test-suite/pull/1439
> [3.2] Fix some build-time analytics failures on Windows by closing file reader

- external-applications/src/test/java/io/quarkus/ts/external/applications/QuickstartIT.java
> Enable external app QuickstartIT on Windows

- build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/AbstractAnalyticsIT.java
I have 10 tests failing on Windows in Build Analytics (see respective Jenkins job) and I think I tracked it down (at least some of them) to `JsonPath.from(File file)`. There is a chance it is not closing resources correctly.
1. https://github.com/rest-assured/rest-assured/blob/master/json-path/src/main/java/io/restassured/path/json/JsonPath.java#L952
2. https://github.com/rest-assured/rest-assured/blob/master/json-path/src/main/groovy/io/restassured/internal/path/json/ConfigurableJsonSlurper.groovy#L95
3. https://docs.groovy-lang.org/2.4.7/html/gapi/groovy/json/JsonLexer.html
I don't see it closed anywhere, though I'm not sure whether there exists some Groovy magic.
> Fix closing of resource usage on Windows by passing RestAssured JsonPath file reader which we close

- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/OpenShiftHttpAdvancedReactiveIT.java
- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/OpenShiftHttpAdvancedIT.java
- http/management/src/test/java/io/quarkus/qe/extension/OpenShiftRegistryIT.java
- messaging/amqp-reactive/src/test/java/io/quarkus/ts/messaging/amqpreactive/ProdAmqpReactiveIT.java
- messaging/cloud-events/amqp-binary/src/test/java/io/quarkus/ts/messaging/cloudevents/amqpbinary/BinaryCloudEventsOverProdAmqpIT.java
- messaging/cloud-events/amqp-json/src/test/java/io/quarkus/ts/messaging/cloudevents/amqpjson/JSONCloudEventsOverProdAmqpIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftAmqStreamsKafkaStreamIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/OpenShiftStrimziKafkaStreamIT.java
- messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/OpenShiftAmqStreamsKafkaAvroIT.java
- messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/OpenShiftStrimziKafkaAvroIT.java
- messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/StrimziKafkaAvroIT.java
- messaging/qpid/src/test/java/io/quarkus/ts/messaging/qpid/QpidIT.java
- monitoring/micrometer-prometheus-kafka-reactive/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/reactive/OpenShiftAmqStreamsAlertEventsReactiveIT.java
- monitoring/micrometer-prometheus-kafka-reactive/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/reactive/OpenShiftKafkaAlertEventsReactiveIT.java
- monitoring/micrometer-prometheus-kafka/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/OpenShiftAmqStreamsAlertEventsIT.java
- monitoring/micrometer-prometheus-kafka/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/OpenShiftKafkaAlertEventsIT.java
- nosql-db/mongodb-reactive/src/test/java/io/quarkus/ts/nosqldb/mongodb/reactive/OpenShiftMongoClientReactiveIT.java
- nosql-db/mongodb/src/test/java/io/quarkus/ts/nosqldb/mongodb/OpenShiftMongoClientIT.java
- pom.xml
- properties/src/test/java/io/quarkus/ts/properties/consul/OpenShiftConsulConfigSourceIT.java
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/OpenShiftOidcRestClientIT.java
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/OpenShiftOidcSinglePageAppLogoutFlowIT.java
- security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/OpenShiftOidcRestClientIT.java
- security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/OpenShiftOidcSinglePageAppLogoutFlowIT.java
- sql-db/hibernate-fulltext-search/src/test/java/io/quarkus/ts/hibernate/search/OpenShiftMysqlMultitenantHibernateSearchIT.java
- sql-db/hibernate-fulltext-search/src/test/java/io/quarkus/ts/hibernate/search/OpenShiftPostgresqlMultitenantHibernateSearchIT.java
Cherry-picking commit from https://github.com/quarkus-qe/quarkus-test-suite/pull/1431 to main branch.
> Add s390x profile and skip appropriate tests

- build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/AbstractAnalyticsIT.java
- external-applications/src/test/java/io/quarkus/ts/external/applications/QuickstartIT.java
- lifecycle-application/src/test/java/io/quarkus/ts/lifecycle/HelloMainTest.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
- security/oidc-client-mutual-tls/src/test/java/io/quarkus/ts/security/oidcclient/mtls/JksOidcMtlsIT.java
- security/oidc-client-mutual-tls/src/test/java/io/quarkus/ts/security/oidcclient/mtls/LocalHostKeycloakContainerManagedResourceBuilder.java
- security/oidc-client-mutual-tls/src/test/java/io/quarkus/ts/security/oidcclient/mtls/MutualTlsKeycloakService.java
- security/oidc-client-mutual-tls/src/test/java/io/quarkus/ts/security/oidcclient/mtls/Pkcs12OidcMtlsIT.java
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1441
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1444
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1443
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1442
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1446
> [3.2] Backport Windows fixes pro Ghost

- .github/workflows/ci.yml
- fixes CLI failures that was demonstrated here #1447
- I mentioned that all the runs are using Java 11, so I switched all 17 in 2 runs
> [3.2] GH workflow adjustments - fix CLI tests by upgrading Quarkus to 3.2.6 and use also Java 17 for some of runs

- messaging/infinispan-grpc-kafka/src/test/java/io/quarkus/ts/messaging/infinispan/grpc/kafka/InfinispanKafkaSaslIT.java
- messaging/infinispan-grpc-kafka/src/test/java/io/quarkus/ts/messaging/infinispan/grpc/kafka/LocalHostInfinispanManagedResourceBuilder.java
- messaging/infinispan-grpc-kafka/src/test/java/io/quarkus/ts/messaging/infinispan/grpc/kafka/LocalHostKafkaContainerManagedResourceBuilder.java
- messaging/infinispan-grpc-kafka/src/test/java/io/quarkus/ts/messaging/infinispan/grpc/kafka/LocalHostManagedResourceUtil.java
> [3.2] Fix InfinispanKafkaSaslIT by proxying localhost port to Docker host as certs are generated for localhost

- messaging/kafkaSSL/src/test/java/io/quarkus/qe/messaging/ssl/KafkaSslIT.java
- messaging/kafkaSSL/src/test/java/io/quarkus/qe/messaging/ssl/LocalHostKafkaContainerManagedResourceBuilder.java
> [3.2] Fix KafkaSslIT on Windows by forwarding localhost port

- messaging/kafkaSSL/src/test/java/io/quarkus/qe/messaging/ssl/KafkaSslIT.java
- messaging/kafkaSSL/src/test/java/io/quarkus/qe/messaging/ssl/LocalHostKafkaContainerManagedResourceBuilder.java
Fixes same kind of a problem as in #1454 and #1446, tested on Win, fixes the issue.
> Fix KafkaSslIT on Windows by forwarding localhost port

- http/servlet-undertow/pom.xml
- http/servlet-undertow/src/main/java/io/quarkus/ts/http/undertow/security/ServletBasicAuthIdentityProvider.java
- http/servlet-undertow/src/main/java/io/quarkus/ts/http/undertow/servlets/SecuredWorld.java
- http/servlet-undertow/src/main/resources/application.properties
- http/servlet-undertow/src/test/java/io/quarkus/ts/http/undertow/HttpServletWithSessionListenerIT.java
> [3.2] Verify Undertow allows activation of req scope during auth

- http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/ServerlessExtensionDockerBuildStrategyOpenShiftHttpMinimumReactiveIT.java
- http/http-minimum-reactive/src/test/java/io/quarkus/ts/http/minimum/reactive/ServerlessExtensionOpenShiftHttpMinimumReactiveIT.java
- http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/ServerlessExtensionDockerBuildStrategyOpenShiftHttpMinimumIT.java
- http/http-minimum/src/test/java/io/quarkus/ts/http/minimum/ServerlessExtensionOpenShiftHttpMinimumIT.java
- super-size/many-extensions/src/test/java/io/quarkus/ts/many/extensions/ServerlessExtensionDockerBuildStrategyOpenShiftManyExtensionsIT.java
- super-size/many-extensions/src/test/java/io/quarkus/ts/many/extensions/ServerlessExtensionOpenShiftManyExtensionsIT.java
Enabling the the tests affected by https://github.com/quarkusio/quarkus/issues/35288. Tested it locally and it worked so seems that the issue is resolved.
> Enable the disable test affected by quarkusio/quarkus#35288

- sql-db/reactive-vanilla/src/main/resources/container-license-acceptance.txt
- sql-db/sql-app/src/test/resources/container-license-acceptance.txt
Needed due to the https://github.com/quarkusio/quarkus/pull/36259, daily's fail.
> Fix DEV mode MS SQL tests by accepting license

- pom.xml
* This is needed to make the Kafka Operator tests pass with new Kafka
> Bump quarkus-test-framework to 1.2.5.Final

- external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftWorkshopHeroesIT.java
- external-applications/src/test/java/io/quarkus/ts/external/applications/OpenShiftWorkshopVillainsIT.java
* Pinning source S2I super hero workshop tests to last working 3.2 commit.
> [3.2] Pinning OpenShiftWorkshop*ITs to 3.2 branch

- README.md
Details for activities related to the branch creation
> Details for activities related to the branch creation

- lifecycle-application/pom.xml
Use RHBQ 3.2 bits in lifecycle-application to ensure the original intention of the module. There was no RHBQ 3 release till now.
> Use RHBQ 3.2 bits in lifecycle-application

- cache/redis/src/test/java/io/quarkus/ts/cache/redis/RedisCacheIT.java
- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/BaseHttpAdvancedReactiveIT.java
- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/CookiesIT.java
> Add tags to RH Quarkus jira

- http/vertx/src/main/java/io/quarkus/ts/vertx/HelloResource.java
- http/vertx/src/test/java/io/quarkus/ts/vertx/AbstractVertxIT.java
- http/vertx/src/test/java/io/quarkus/ts/vertx/Metric.java
- http/vertx/src/test/java/io/quarkus/ts/vertx/ThreadPoolIT.java
backports https://github.com/quarkus-qe/quarkus-test-suite/pull/1551
> [3.2] Test Vert.x pool metric for rejected submissions to the pool

- nosql-db/mongodb/src/test/java/io/quarkus/ts/nosqldb/mongodb/OpenShiftMongoClientIT.java
- pom.xml
https://github.com/quarkus-qe/quarkus-test-suite/pull/1554
Cherry-picking to main branch.
> Enable mongodb tests on s390x

- monitoring/opentelemetry-reactive/src/test/java/io/quarkus/ts/opentelemetry/reactive/OpentelemetryReactiveIT.java
Failures go down to https://github.com/quarkusio/quarkus/pull/35989#issuecomment-1835979200, let see if that was intentional, I guess not. But we should fix tests and eventually revert it with upstream fixes.
> Fix OpentelemetryReactiveIT#testSchedulerTracing by updating operation name

- security/bouncycastle-fips/bcFipsJsse/pom.xml
Daily build is failing due to https://github.com/quarkusio/quarkus/issues/37500.
> Disable Bouncy Castle FIPS JSSE native executable build due to upstream issue

- lifecycle-application/pom.xml
> Bump lifecycle app to 3.2.9.Final-redhat-00002

- pom.xml
- Bumps test framework to 1.4.0.Beta4
> Bump QE Test Framework to 1.4.0.Beta4

- README.md
- javaee-like-getting-started/pom.xml
- javaee-like-getting-started/src/main/java/io/quarkus/ts/javaee/gettingstarted/MapperResource.java
- javaee-like-getting-started/src/main/java/io/quarkus/ts/javaee/gettingstarted/data/ChitChat.java
- javaee-like-getting-started/src/main/java/io/quarkus/ts/javaee/gettingstarted/data/ChitChatTopic.java
- javaee-like-getting-started/src/main/java/io/quarkus/ts/javaee/gettingstarted/data/Farewell.java
- javaee-like-getting-started/src/main/java/io/quarkus/ts/javaee/gettingstarted/data/FarewellPartOne.java
- javaee-like-getting-started/src/main/java/io/quarkus/ts/javaee/gettingstarted/data/FarewellPartOneDefaultMethod.java
- javaee-like-getting-started/src/main/java/io/quarkus/ts/javaee/gettingstarted/data/FarewellPartOneHappyImpl.java
- javaee-like-getting-started/src/main/java/io/quarkus/ts/javaee/gettingstarted/data/FarewellPartOneSadImpl.java
- javaee-like-getting-started/src/main/java/io/quarkus/ts/javaee/gettingstarted/data/FarewellPartTwo.java
- javaee-like-getting-started/src/main/java/io/quarkus/ts/javaee/gettingstarted/data/Greeting.java
- javaee-like-getting-started/src/main/java/io/quarkus/ts/javaee/gettingstarted/data/SeriousTalk.java
- javaee-like-getting-started/src/main/java/io/quarkus/ts/javaee/gettingstarted/dto/ChitChatDTO.java
- javaee-like-getting-started/src/main/java/io/quarkus/ts/javaee/gettingstarted/dto/FarewellDTO.java
- javaee-like-getting-started/src/main/java/io/quarkus/ts/javaee/gettingstarted/dto/FarewellPartOneDTO.java
- javaee-like-getting-started/src/main/java/io/quarkus/ts/javaee/gettingstarted/dto/GreetingDTO.java
- javaee-like-getting-started/src/main/java/io/quarkus/ts/javaee/gettingstarted/dto/SeriousTalkDTO.java
- javaee-like-getting-started/src/main/java/io/quarkus/ts/javaee/gettingstarted/mapper/ChitChatDtoFactory.java
- javaee-like-getting-started/src/main/java/io/quarkus/ts/javaee/gettingstarted/mapper/ChitChatMapper.java
- javaee-like-getting-started/src/main/java/io/quarkus/ts/javaee/gettingstarted/mapper/ChitChatTopicMapper.java
- javaee-like-getting-started/src/main/java/io/quarkus/ts/javaee/gettingstarted/mapper/FarewellMapper.java
- javaee-like-getting-started/src/main/java/io/quarkus/ts/javaee/gettingstarted/mapper/FarewellMapperDecorator.java
- javaee-like-getting-started/src/main/java/io/quarkus/ts/javaee/gettingstarted/mapper/FarewellPartOneHappyImplMapper.java
- javaee-like-getting-started/src/main/java/io/quarkus/ts/javaee/gettingstarted/mapper/FarewellPartOneSadImplMapper.java
- javaee-like-getting-started/src/main/java/io/quarkus/ts/javaee/gettingstarted/mapper/GreetingMapper.java
- javaee-like-getting-started/src/main/java/io/quarkus/ts/javaee/gettingstarted/mapper/SeriousTalkMapper.java
- javaee-like-getting-started/src/test/java/io/quarkus/ts/javaee/gettingstarted/MapStructIT.java
Add test coverage for basic MapStruct features used with Quarkus. Integration point with Quarkus is mostly about CDI, as all other should work from annotation processor, but it's good to test common stuff because you never know.
> Test MapStruct together with Quarkus

- .github/workflows/daily.yaml
Fix typo (missing version) in GH action
> Fix typo in daily pipeline

- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/LogoutSinglePageAppFlowIT.java
- security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/LogoutSinglePageAppFlowIT.java
Keycloak "q_session" cookies got too big and they don't fit into one cookie (cookie is milited to 4096B). So they might be split into multiple chunks. Old code searched only for cookie with exact name, new one can work with chunks too.
I tried to find out why is the cookie suddenly bigger, but content is encrypted and I cannot pinpoint exact change that caused it.
> Change Keycloak logout test to support multichunk cookies

- config/src/test/java/io/quarkus/ts/configmap/api/server/OpenShiftApiServerConfigMapConfigIT.java
- config/src/test/java/io/quarkus/ts/configmap/api/server/OpenShiftApiServerConfigSecretConfigIT.java
- config/src/test/java/io/quarkus/ts/configmap/api/server/OpenShiftConfigSourcePriorityIT.java
- config/src/test/java/io/quarkus/ts/configmap/api/server/OpenShiftFailOnMissingConfigIT.java
- config/src/test/java/io/quarkus/ts/configmap/api/server/OpenShiftFileSystemConfigMapConfigIT.java
- config/src/test/java/io/quarkus/ts/configmap/api/server/OpenShiftFileSystemConfigSecretConfigIT.java
- funqy/knative-events/src/test/java/io/quarkus/ts/funqy/knativeevents/ServerlessExtensionOpenShiftFunqyKnEventsIT.java
- infinispan-client/src/test/java/io/quarkus/ts/infinispan/client/OperatorOpenShiftInfinispanCountersIT.java
- infinispan-client/src/test/java/io/quarkus/ts/infinispan/client/OperatorOpenShiftInfinispanObjectsIT.java
Issue https://github.com/quarkusio/quarkus/issues/38018 is making all these test fail. Disabling affected the tests until issue is fixed.
> Disable test failing on issue 38018

- pom.xml
Bumps Quarkus to 3.2.10.Final.
> [3.2] Bump Quarkus to 3.2.10.Final

- pom.xml
Backports https://github.com/quarkus-qe/quarkus-test-suite/pull/1633.
> [3.2] Re-run failing tests to limit flakiness

- http/jakarta-rest-reactive/src/test/java/io/quarkus/ts/http/jakartarest/reactive/OpenShiftExecutionModelIT.java
> Disable test affected by QQE-465

- README.md
- messaging/kafka-producer/src/test/java/io/quarkus/ts/messaging/kafka/producer/BlockingProducerIT.java
- pom.xml
> Update images versions

- .github/workflows/ci.yml
- lifecycle-application/pom.xml
- pom.xml
> [3.2] Bump Quarkus to 3.2.10

- pom.xml
Bump test framework to 1.4.2.Beta8. Include recent changes
> Bump test framework to 1.4.2.Beta8

- lifecycle-application/pom.xml
> [3.2] Bump Lifecycle dependency RHBQ to `3.2.10.Final-redhat-00003`

- lifecycle-application/pom.xml
ports https://github.com/quarkus-qe/quarkus-test-suite/pull/1673
> Bump Lifecycle RHBQ to 3.2.10.Final-redhat-00003

- pom.xml
Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/1662 but not bumping version of db2
> [3.2] Update db2 image

- .github/workflows/ci.yml
- pom.xml
> Update Quarkus 3.7 to 3.8

- pom.xml
- spring/spring-cloud-config/README.md
New image is based on https://github.com/quarkus-qe/spring-cloud-config-server
> Bump Spring Cloud Config Server to 4.1

- sql-db/narayana-transactions/src/main/java/io/quarkus/ts/service/ServiceResource.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/OpenShiftMysqlTransactionGeneralUsageIT.java
https://issues.redhat.com/browse/QQE-492
Fixes https://github.com/quarkus-qe/quarkus-test-suite/issues/1397
> Add ability to grants rights on OpenShift

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
> Disable Jbang tests on product, since Jbang is not supported

- README.md
- sql-db/panache-flyway/pom.xml
- sql-db/panache-flyway/src/test/java/io/quarkus/ts/sqldb/panacheflyway/init/CustomYaml.java
- sql-db/panache-flyway/src/test/java/io/quarkus/ts/sqldb/panacheflyway/init/OpenShiftDefaultInitContainerIT.java
- sql-db/panache-flyway/src/test/java/io/quarkus/ts/sqldb/panacheflyway/init/OpenShiftFlywayInitContainerIT.java
- sql-db/panache-flyway/src/test/resources/Dockerfile
https://issues.redhat.com/browse/QQE-507
> Cover custom init containers

- sql-db/hibernate-fulltext-search/pom.xml
- sql-db/vertx-sql/pom.xml
Triggered by the https://github.com/quarkusio/quarkus/pull/39509 as tests are failing.
> Fix missing Flyway dependencies after Flyway bump to the 10.10.0 version

- .github/workflows/ci.yml
- pom.xml
Bump default quarkus version to 3.2.11.Final
> [3.2] Bump Quarkus version to 3.2.11.Final

- .github/workflows/ci.yml
I merged #1727 and release notes explained this change in the breaking change section. It should help with detection of changed files and fix some bug.
> Specify the fork repo explicitly in checkout step GH Action

- README.md
- pom.xml
- security/jpa/README.md
- security/jpa/pom.xml
- security/jpa/src/main/java/io/quarkus/ts/security/jpa/AdminResource.java
- security/jpa/src/main/java/io/quarkus/ts/security/jpa/PublicResource.java
- security/jpa/src/main/java/io/quarkus/ts/security/jpa/UserResource.java
- security/jpa/src/main/resources/application.properties
- security/jpa/src/test/java/io/quarkus/ts/security/jpa/BaseJpaSecurityRealmIT.java
- security/jpa/src/test/java/io/quarkus/ts/security/jpa/CreateUserWithMD5PassResource.java
- security/jpa/src/test/java/io/quarkus/ts/security/jpa/CreateUserWithSHA256PassResource.java
- security/jpa/src/test/java/io/quarkus/ts/security/jpa/CreateUserWithSHA512PassResource.java
- security/jpa/src/test/java/io/quarkus/ts/security/jpa/MD5PasswordProvider.java
- security/jpa/src/test/java/io/quarkus/ts/security/jpa/MD5UserEntity.java
- security/jpa/src/test/java/io/quarkus/ts/security/jpa/MariaDbMd5JpaIT.java
- security/jpa/src/test/java/io/quarkus/ts/security/jpa/MySqlSha256JpaIT.java
- security/jpa/src/test/java/io/quarkus/ts/security/jpa/OraclePlaintextExternalRolesJpaIT.java
- security/jpa/src/test/java/io/quarkus/ts/security/jpa/OracleSha512JpaIT.java
- security/jpa/src/test/java/io/quarkus/ts/security/jpa/PlaintextExternalRolesUserEntity.java
- security/jpa/src/test/java/io/quarkus/ts/security/jpa/RoleEntity.java
- security/jpa/src/test/java/io/quarkus/ts/security/jpa/SHA256PasswordProvider.java
- security/jpa/src/test/java/io/quarkus/ts/security/jpa/SHA256UserEntity.java
- security/jpa/src/test/java/io/quarkus/ts/security/jpa/SHA512PasswordProvider.java
- security/jpa/src/test/java/io/quarkus/ts/security/jpa/SHA512UserEntity.java
- security/jpa/src/test/resources/import.sql
- security/jpa/src/test/resources/mariadb_app.properties
- security/jpa/src/test/resources/mysql.properties
- security/jpa/src/test/resources/oracle.properties
- security/jpa/src/test/resources/test.properties
Backports https://github.com/quarkus-qe/quarkus-test-suite/pull/1741 as I need to verify QUARKUS-3866 against RHBQ 3.8.
> [3.8] Add coverage for Quarkus Security JPA extension

- external-applications/src/test/java/io/quarkus/ts/external/applications/QuickstartIT.java
> Use branch 3.8 in quickstarts

- README.md
> Update branching strategy to include QuickstartsIT

- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DevModeKafkaStreamIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DevModeRedPandaDevServiceUserExperienceIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DevModeStrimziKafkaStreamIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DisabledOnRHBQWindowsConditions.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DisabledOnRHBQandWindows.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/KafkaGratefulShutdownIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/SslAlertMonitorIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/StrimziKafkaStreamIT.java
For reasons see:
- https://issues.redhat.com/browse/QUARKUS-600
- https://issues.redhat.com/browse/QUARKUS-3434
- https://issues.redhat.com/browse/QUARKUS-4321
> Disable kafka tests on RHBQ and Windows

- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DevModeKafkaStreamIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DevModeRedPandaDevServiceUserExperienceIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DevModeStrimziKafkaStreamIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DisabledOnRHBQWindowsConditions.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DisabledOnRHBQandWindows.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/KafkaGratefulShutdownIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/SslAlertMonitorIT.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/StrimziKafkaStreamIT.java
backports https://github.com/quarkus-qe/quarkus-test-suite/pull/1758
> [3.8] Disable kafka tests on RHBQ and Windows

- .github/workflows/ci.yml
- external-applications/src/test/java/io/quarkus/ts/external/applications/QuickstartIT.java
- pom.xml
Update Quarkus and Quarkus config version to 3.2.12.Final
> [3.2] Bump Quarkus and Quarkus config version to 3.2.12.Final

- .github/workflows/ci.yml
- pom.xml
Update Quarkus and Quarkus config version to 3.8.4
> [3.8] Bump Quarkus and Quarkus config version to 3.8.4

- build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/CliDevModeIT.java
- build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/CliProdModeJvmIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateNativeApplicationIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliSpecialCharsIT.java
Enable CLI test as the Quarkus 3.9 is released
> Enable CLI tests as 3.9 is released

- lifecycle-application/pom.xml
Run lifecycle-application against RHBQ 3.8 dependencies
> Run lifecycle-application against RHBQ 3.8 dependencies

- lifecycle-application/pom.xml
Update of lifecycle-app rhbq versions 
> [3.2] Update lifecycle-application RHBQ version to 3.2.12

- security/keycloak-jwt/src/test/java/io/quarkus/ts/security/keycloak/jwt/KeycloakOidcJwtSecurityIT.java
- security/keycloak-multitenant/src/test/java/io/quarkus/ts/security/keycloak/multitenant/KeycloakMultiTenantSecurityIT.java
Both tests succeeds in JVM and native mode without any modification when run in FIPS-enabled environment.
> Run `KeycloakMultiTenantSecurityIT` and `KeycloakOidcJwtSecurityIT` in FIPS-enabled environment

- security/keycloak-oidc-client-basic/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/basic/BaseOidcClientSecurityIT.java
- security/keycloak-oidc-client-reactive-basic/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/basic/BaseOidcClientSecurityIT.java
They just work, so let's run them.
> Run OIDC client tests in FIPS-enabled environment

- super-size/many-extensions/src/test/java/io/quarkus/ts/many/extensions/ManyExtensionsIT.java
Works without modification in FIPS-enabled environment both in JVM and native mode.
> Run ManyExtensionsIT in FIPS-enabled env

- http/graphql/src/test/java/io/quarkus/ts/http/graphql/GraphQLDisabledGetIT.java
- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/DomainSocketIT.java
There is an issue in test-FW, that causes several of our tests to fail: https://github.com/quarkus-qe/quarkus-test-framework/issues/1149
Disable tests affected by this.
> Disable tests affected by test-FW issue 1149

- http/graphql/src/test/java/io/quarkus/ts/http/graphql/OpenShiftGraphQLDisabledGetIT.java
Follows up https://github.com/quarkus-qe/quarkus-test-suite/pull/1811
> Disable OpenShiftGraphQLDisabledGetIT affected by FW issue 1149

- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/failures/FailingClientResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/failures/FailingResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/failures/FailureClient.java
- http/rest-client-reactive/src/main/resources/modern.properties
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliCreateJvmApplicationIT.java
- security/basic/pom.xml
- security/basic/src/main/java/io/quarkus/ts/openshift/security/basic/SecurityFilter.java
The issues:
- https://github.com/quarkusio/quarkus/pull/40718
- https://github.com/quarkusio/quarkus/issues/37323
- https://github.com/quarkusio/quarkus/issues/40307
> Coverage for several issues, which will be fixed in 3.8.5 via backporting

- security/basic/pom.xml
Follow-up to https://github.com/quarkus-qe/quarkus-test-suite/pull/1818#issuecomment-2151830369
> Use renamed extension

- spring/spring-data/src/main/java/io/quarkus/ts/spring/data/rest/ArticleRepository.java
- spring/spring-data/src/main/java/io/quarkus/ts/spring/data/rest/secured/PublicRepository.java
After https://github.com/quarkusio/quarkus/pull/40344 compilation of this project fails. This is expected as described in the PR description. This PR does not fix all the test failures, just `SpringDataCompositeEntityIT` and compilation.
> Fix Spring Data compilation after Spring bump upstream

- spring/spring-data/src/test/java/io/quarkus/ts/spring/data/primitivetypes/SpringDataCompositeEntityIT.java
As spring data tests failing for sometime and  we didn't see all the CI run. Almost all of them were fixed, just this one wasn't fixed/was not detected before fix.
> Disable ensureFieldPageableIsSerialized test

- .github/workflows/ci.yml
- http/rest-client-reactive/pom.xml
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/multipart/EncoderModeRestClient.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/multipart/Html5EncoderModeRestClient.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/multipart/Item.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/multipart/MyMultipartDTO.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/multipart/Rfc1738EncoderModeRestClient.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/multipart/Rfc3986EncoderModeRestClient.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/MultipartPostEncoderModeResource.java
- http/rest-client-reactive/src/main/resources/application.properties
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/HttpMultipartEncodeModeAndContentIT.java
- http/rest-client-reactive/src/test/resources/sampl'eñ.txt
- http/rest-client-reactive/src/test/resources/sample.txt
This is back port of #1853 as this development targeted RHBQ 3.8.5 by [QUARKUS-4540](https://issues.redhat.com/browse/QUARKUS-4540)
> [3.8] Backport of `Add test coverage for improvement multipart encoded mode in rest-client`

- websockets/quarkus-websockets/pom.xml
Was added here by mistake: https://github.com/quarkus-qe/quarkus-test-suite/pull/1875
> [3.2] Remove dependency which was added erroneusly

- pom.xml
> [3.8] Update/framework 1.4.8

- pom.xml
Part of https://issues.redhat.com/browse/QQE-823
The version update upstream is a part of this PR: https://github.com/quarkusio/quarkus/pull/42078
> QQE-823 | Update image versions

- pom.xml
> Bump framework version to 1.5.0.Beta13

- .github/workflows/ci.yml
- .github/workflows/daily.yaml
`nosql-db-modules` are missing in CI workflows
> Run nosql-db-modules in JVM mode as part of PR and daily CI

- pom.xml
Bump framework to 1.4.9. Required by quarkus CLI update tests.
> [3.8] Bump test framework version to 1.4.9

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliConfigEncryptIT.java
Reverts quarkus-qe/quarkus-test-suite#1918
> Revert "Fix secretFormat on QuarkusCliConfigEncryptIT for Windows job"

- logging/jboss/src/main/java/io/quarkus/ts/logging/jboss/LogResource.java
- logging/jboss/src/main/resources/application.properties
- logging/jboss/src/test/java/io/quarkus/ts/logging/jboss/DefaultMinLogLevelIT.java
Backports https://github.com/quarkus-qe/quarkus-test-suite/pull/1946
> [3.15] Verify log file rotation for periods longer than day

- logging/jboss/src/main/java/io/quarkus/ts/logging/jboss/LogResource.java
- logging/jboss/src/main/resources/application.properties
- logging/jboss/src/test/java/io/quarkus/ts/logging/jboss/DefaultMinLogLevelIT.java
Backports https://github.com/quarkus-qe/quarkus-test-suite/pull/1946
> [3.8] Verify log file rotation for periods longer than day

- pom.xml
> [3.8] Bump test framework version to 1.4.10

- spring/spring-data/src/main/java/io/quarkus/ts/spring/data/rest/Magazine.java
- spring/spring-data/src/main/java/io/quarkus/ts/spring/data/rest/MagazineJpaRepository.java
- spring/spring-data/src/main/java/io/quarkus/ts/spring/data/rest/MagazineListCrudRepository.java
- spring/spring-data/src/main/java/io/quarkus/ts/spring/data/rest/MagazineListPagingAndSortingRepository.java
- spring/spring-data/src/main/java/io/quarkus/ts/spring/data/rest/MagazineResource.java
- spring/spring-data/src/main/resources/application.properties
- spring/spring-data/src/main/resources/import.sql
- spring/spring-data/src/test/java/io/quarkus/ts/spring/data/rest/CrudRepositoryRestResourceIT.java
- spring/spring-data/src/test/java/io/quarkus/ts/spring/data/rest/JpaRepositoryRestResourceIT.java
- spring/spring-data/src/test/java/io/quarkus/ts/spring/data/rest/PagingAndSortingRepositoryRestResourceIT.java
This PR consist of TD for https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-4958.md.
> Test newly supported interfaces in  Quarkus Spring Data JPA and getReferencedBy as replacement for deprecated methods

- monitoring/micrometer-prometheus-kafka/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/BaseOpenShiftAlertEventsIT.java
This test checks kafka metrics for being non-zero
At the moment, kafka-proudcer sends 3 metrics, and we only check first, but since they are ordered randomly, sometimes we check metric `kafka-consumer-dead-letter-topic-undeliverable-target` which is is always 0.0 (as expected).
To avoid that, now we only check metric for `alerts` topic (since we run other tests on it), and we check, that it is the only such metric, to avoid such kerfuffle in the future.
> Check kafka metrics independently from their order

- pom.xml
Bump test framework to 1.6.0.Beta11
> Bump test framework to 1.6.0.Beta11

- build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/AbstractAnalyticsIT.java
Do not mix --platform and --stream options for CLI, since they are not compatible
> Do not mix --platform and --stream options for CLI

- cache/infinispan/src/main/resources/application.properties
- cache/infinispan/src/test/resources/test.properties
- lifecycle-application/src/test/java/io/quarkus/ts/lifecycle/LifecycleApplicationIT.java
- messaging/kafka-confluent-avro-reactive-messaging/src/main/java/io/quarkus/ts/messaging/kafka/KStockPriceProducer.java
- messaging/kafka-strimzi-avro-reactive-messaging/src/main/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/KStockPriceProducer.java
- monitoring/opentelemetry-reactive/src/test/java/io/quarkus/ts/opentelemetry/reactive/OpentelemetryReactiveIT.java
- sql-db/vertx-sql/src/test/java/io/quarkus/ts/vertx/sql/handlers/OracleHandlerIT.java
> Remove outdated FIXMEs and add recommended properties for a test on FIPS

- security/bouncycastle-fips/bcfips/src/test/java/io/quarkus/ts/security/bouncycastle/fips/BouncyCastleFipsIT.java
- security/bouncycastle-fips/bcfips/src/test/java/io/quarkus/ts/security/bouncycastle/fips/DisabledOnFipsAndNative.java
- security/bouncycastle-fips/bcfips/src/test/java/io/quarkus/ts/security/bouncycastle/fips/DisabledOnFipsAndNativeCondition.java
Talked to Severin and this is not expected to work. I have opened docs ticket for it as well `https://github.com/quarkusio/quarkus/issues/43935`.
> Disable BCFIPS in native in FIPS-enabled env as not supported

- config/src/test/java/io/quarkus/ts/configmap/api/server/ConfigIT.java
- config/src/test/java/io/quarkus/ts/configmap/api/server/DisabledOnFipsAndNative.java
- config/src/test/java/io/quarkus/ts/configmap/api/server/DisabledOnFipsAndNativeCondition.java
- security/bouncycastle-fips/bcfips/src/test/java/io/quarkus/ts/security/bouncycastle/fips/BouncyCastleFipsIT.java
- security/bouncycastle-fips/bcfips/src/test/java/io/quarkus/ts/security/bouncycastle/fips/DisabledOnFipsAndNative.java
- security/bouncycastle-fips/bcfips/src/test/java/io/quarkus/ts/security/bouncycastle/fips/DisabledOnFipsAndNativeCondition.java
- sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/MsSQLDatabaseHibernateReactiveIT.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/MssqlTransactionGeneralUsageIT.java
- sql-db/reactive-rest-data-panache/src/test/java/io/quarkus/ts/reactive/rest/data/panache/MssqlPanacheResourceIT.java
- sql-db/reactive-vanilla/src/test/java/io/quarkus/ts/reactive/db/clients/DevModeReactiveMssqlDevServiceUserExperienceIT.java
- sql-db/sql-app-compatibility/src/test/java/io/quarkus/ts/sqldb/compatibility/MssqlDatabaseIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMssqlDevServicesUserExperienceIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/MssqlDatabaseIT.java
- sql-db/vertx-sql/src/main/java/io/quarkus/ts/vertx/sql/Application.java
- sql-db/vertx-sql/src/test/java/io/quarkus/ts/vertx/sql/handlers/MssqlHandlerIT.java
Backports:
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2097
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2098
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2099
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2100
> [3.15] Backport FIPS fixes and disables

- build/podman/pom.xml
Cherry pick from https://github.com/quarkus-qe/quarkus-test-suite/pull/2103
> [3.15] Set podman disabled true by default

- pom.xml
Follow #2113 and add suffix ":latest" to docker images added in #2127 .
> Add :latest tag to images defined in surefire

- http/http-advanced-reactive/pom.xml
- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/Brotli4JHttpIT.java
- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/DevModeBrotli4JHttpIT.java
- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/brotli4j/Brotli4JHttpServerConfig.java
- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/brotli4j/Brotli4JResource.java
- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/brotli4j/Brotli4JRestMock.java
- pom.xml
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/annotations/EnabledIfPostgresImageCommunity.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/annotations/EnabledIfPostgresImageCommunityCondition.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/annotations/EnabledIfPostgresImageProduct.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/annotations/EnabledIfPostgresImageProductCondition.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/PostgresqlCommunityTransactionGeneralUsageIT.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/PostgresqlProductTransactionGeneralUsageIT.java
* Adding a missing commit from https://github.com/quarkus-qe/quarkus-test-suite/pull/2072/
* https://github.com/quarkus-qe/quarkus-test-suite/pull/2134
* https://github.com/quarkus-qe/quarkus-test-suite/pull/2135
> 3.15 backports bulk

- super-size/many-extensions/src/test/java/io/quarkus/ts/many/extensions/ManyExtensionsIT.java
https://github.com/quarkus-qe/quarkus-test-suite/pull/2150 follow-up, I have updated linked product tracker with details.
> Disable ManyExtensionsIT on FIPS in native mode

- super-size/many-extensions/src/test/java/io/quarkus/ts/many/extensions/ManyExtensionsIT.java
Backports:
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2165
> [3.15]  Disable ManyExtensionsIT on FIPS in native mode

- infinispan-client/src/main/java/io/quarkus/ts/infinispan/client/InfinispanClientApp.java
- infinispan-client/src/main/java/io/quarkus/ts/infinispan/client/serialized/ShopItemResource.java
- infinispan-client/src/main/java/io/quarkus/ts/infinispan/client/serialized/ShopItemSchema.java
- infinispan-client/src/test/java/io/quarkus/ts/infinispan/client/BaseOpenShiftInfinispanIT.java
- infinispan-client/src/test/java/io/quarkus/ts/infinispan/client/OperatorOpenShiftInfinispanCountersIT.java
- infinispan-client/src/test/java/io/quarkus/ts/infinispan/client/OperatorOpenShiftInfinispanObjectsIT.java
- javaee-like-getting-started/src/main/java/io/quarkus/ts/javaee/gettingstarted/data/Greeting.java
- javaee-like-getting-started/src/main/java/io/quarkus/ts/javaee/gettingstarted/dto/SeriousTalkDTO.java
- lifecycle-application/src/main/java/io/quarkus/ts/lifecycle/ArgsResource.java
- lifecycle-application/src/main/java/io/quarkus/ts/lifecycle/Main.java
- lifecycle-application/src/test/java/io/quarkus/ts/lifecycle/LifecycleApplicationIT.java
- lifecycle-application/src/test/java/io/quarkus/ts/lifecycle/OpenShiftLifecycleApplicationIT.java
- logging/jboss/src/test/java/io/quarkus/ts/logging/jboss/AccessLoggingIT.java
- logging/jboss/src/test/java/io/quarkus/ts/logging/jboss/DefaultMinLogLevelIT.java
- logging/thirdparty/src/main/resources/application.properties
- logging/thirdparty/src/test/java/io/quarkus/ts/logging/jboss/SyslogIT.java
Changes from IDEA code analysis. Mostly refactor into simpler code constructions. Also replacing some deprecated APIs in infinispan client.
> Apply idea code analysis suggestions I-L

- messaging/infinispan-grpc-kafka/README.md
- messaging/infinispan-grpc-kafka/src/main/java/io/quarkus/ts/messaging/infinispan/grpc/kafka/InfinispanPopulated.java
- messaging/infinispan-grpc-kafka/src/main/java/io/quarkus/ts/messaging/infinispan/grpc/kafka/books/BookCacheInitializer.java
- messaging/infinispan-grpc-kafka/src/main/java/io/quarkus/ts/messaging/infinispan/grpc/kafka/books/BookContextInitializer.java
- messaging/infinispan-grpc-kafka/src/main/java/io/quarkus/ts/messaging/infinispan/grpc/kafka/books/BookResource.java
- messaging/infinispan-grpc-kafka/src/main/java/io/quarkus/ts/messaging/infinispan/grpc/kafka/prices/PriceGenerator.java
- messaging/infinispan-grpc-kafka/src/main/java/io/quarkus/ts/messaging/infinispan/grpc/kafka/quickstart/KafkaEndpoint.java
- messaging/kafka-confluent-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/BaseKafkaAvroGroupIdIT.java
- messaging/kafka-producer/src/main/java/io/quarkus/ts/messaging/kafka/producer/Application.java
- messaging/kafka-producer/src/main/java/io/quarkus/ts/messaging/kafka/producer/FailureHandler.java
- messaging/kafka-producer/src/main/java/io/quarkus/ts/messaging/kafka/producer/KafkaBlockingProducer.java
- messaging/kafka-streams-reactive-messaging/src/main/java/io/quarkus/ts/messaging/kafka/reactive/streams/aggregator/streams/WindowedLoginDeniedStream.java
- messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/reactive/streams/DevModeRedPandaDevServiceUserExperienceIT.java
- messaging/kafka-strimzi-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/strimzi/kafka/reactive/BaseKafkaAvroGroupIdIT.java
- messaging/kafkaSSL/src/main/java/io/quarkus/qe/messaging/ssl/quickstart/KafkaEndpoint.java
- messaging/qpid/src/main/java/io/quarkus/ts/messaging/qpid/PriceConsumer.java
- monitoring/micrometer-prometheus-kafka-reactive/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/reactive/BaseOpenShiftAlertEventsReactiveIT.java
- monitoring/micrometer-prometheus-kafka-reactive/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/reactive/KafkaAndMetricsIT.java
- monitoring/micrometer-prometheus-kafka/src/test/java/io/quarkus/ts/micrometer/prometheus/kafka/BaseOpenShiftAlertEventsIT.java
- monitoring/micrometer-prometheus/src/test/java/io/quarkus/ts/micrometer/prometheus/OpenShiftCustomMetricsIT.java
- monitoring/opentelemetry-reactive/src/test/java/io/quarkus/ts/opentelemetry/reactive/OpenTelemetryGrpcIT.java
- monitoring/opentelemetry-reactive/src/test/java/io/quarkus/ts/opentelemetry/reactive/OpenTelemetrySseIT.java
- monitoring/opentelemetry/src/test/java/io/quarkus/ts/opentelemetry/OpenTelemetryGrpcIT.java
- monitoring/opentelemetry/src/test/java/io/quarkus/ts/opentelemetry/OpenTelemetrySseIT.java
- nosql-db/elasticsearch/src/main/java/io/quarkus/ts/elasticsearch/DataTypesService.java
- nosql-db/elasticsearch/src/test/java/io/quarkus/ts/elasticsearch/DevModeElasticsearchIT.java
- nosql-db/elasticsearch/src/test/java/io/quarkus/ts/elasticsearch/ElasticsearchIT.java
- nosql-db/infinispan/src/main/java/io/quarkus/ts/infinispan/client/InfinispanClientApp.java
- nosql-db/mongodb-reactive/src/main/java/io/quarkus/ts/nosqldb/mongodb/reactive/Fruit.java
- nosql-db/mongodb/src/main/java/io/quarkus/ts/nosqldb/mongodb/Fruit.java
Apply idea code suggestions. Mostly grammar fixes, updating deprecated API usage and some code simplyfication.
> Apply idea code analysis suggestions M-N

- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/BaseHttpAdvancedReactiveIT.java
- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/Http2IT.java
- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/BaseHttpAdvancedIT.java
- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/DomainSocketIT.java
- http/vertx-web-client/src/main/java/io/quarkus/ts/http/vertx/webclient/handler/ChuckNorrisResource.java
- http/vertx-web-client/src/main/java/io/quarkus/ts/http/vertx/webclient/service/PongService.java
- http/vertx-web-client/src/test/java/io/quarkus/ts/http/vertx/webclient/PureVertxHttpClientTest.java
- http/vertx/src/test/java/io/quarkus/ts/vertx/AbstractVertxIT.java
- security/oidc-client-mutual-tls/src/test/java/io/quarkus/ts/security/oidcclient/mtls/MutualTlsKeycloakService.java
- security/webauthn/src/test/java/io/quarkus/ts/security/webauthn/AbstractWebAuthnTest.java
- sql-db/narayana-transactions/src/main/java/io.quarkus.ts.transactions/LegacyTransferTopUpService.java
> Remove usage of deprecated APIs

- http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/MultipartResource.java
- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/MultipartInputstreamIT.java
- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/OpenShiftMultipartInputstreamIT.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/BookClient.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/multipart/FileUploadClient.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/multipart/MultipartBodyWithMediaType.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/multipart/MultipartBodyWithoutMediaType.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/FileUploadClientTestResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/FileUploadResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/PlainBookResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/ReactiveClientBookResource.java
- http/rest-client-reactive/src/main/resources/modern.properties
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientIT.java
- http/vertx/src/test/java/io/quarkus/ts/vertx/PortConflictIT.java
Backport bulk for the following merge requests: 
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2183
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2188
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2209
> [3.15.2] backports bulk set1

- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/HeadersIT.java
Adding test to check http 1.0 request work correctly without headers. Checked request with wireshart and the request is same as expected.
Motivated by https://github.com/quarkusio/quarkus/discussions/42636
> Add coverage for HTTP 1.0 request with no host header

- .github/workflows/ci.yml
Our PR CI was configured to skip tests annotated `@Tag("long-running")` even if they were changed. This PR detects changed long running test classes and runs them separately
Example run: https://github.com/gtroitsk/quarkus-test-suite/pull/4/checks
> Detect changed long-running tagged tests to run in CI

- http/servlet-undertow/src/test/java/io/quarkus/ts/http/undertow/UndertowMissingServletClassIT.java
- http/servlet-undertow/src/test/resources/test.properties
See https://github.com/quarkus-qe/quarkus-test-suite/pull/2218#issuecomment-2504957745.
> Make UndertowMissingServletClassIT reproduce linked upstream issue

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/update/AbstractQuarkusCliUpdateIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/update/QuarkusCli35to315UpdateIT.java
This is a backport from https://github.com/quarkus-qe/quarkus-test-suite/pull/2238/commits
> [3.15] Fix QuarkusCli35to315UpdateIT

- javaee-like-getting-started/src/test/java/io/quarkus/ts/javaee/gettingstarted/OpenAPITracingIT.java
The paths were changed in https://github.com/quarkusio/quarkus/pull/45300
See https://github.com/quarkusio/quarkus/issues/45754 for details
> Use new paths to system resources in traces

- pom.xml
> [3.15] Update to 3.15.3

- security/keycloak-oidc-client-reactive-extended/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/ping/FilterLogMessagesResource.java
- security/keycloak-oidc-client-reactive-extended/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/ping/UserinfoResource.java
- security/keycloak-oidc-client-reactive-extended/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/ping/filters/JWKSResponseFilter.java
- security/keycloak-oidc-client-reactive-extended/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/ping/filters/TokenResponseFilter.java
- security/keycloak-oidc-client-reactive-extended/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/ping/filters/UserinfoResponseFilter.java
- security/keycloak-oidc-client-reactive-extended/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/tokens/TokenRefreshResource.java
- security/keycloak-oidc-client-reactive-extended/src/main/resources/application.properties
- security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/OidcResponseFilterIT.java
- security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/OpenShiftOidcResponseFilterIT.java
- security/keycloak-oidc-client-reactive-extended/src/test/resources/test-realm-realm.json
This PR introduces new tests covering for [QUARKUS-5613](https://issues.redhat.com/browse/QUARKUS-5613 )
Following the TP--> [QUARKUS-5613](https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-5613.md )
> Add test coverage for OIDC response filters

- spring/spring-properties/src/test/java/io/quarkus/ts/spring/properties/SpringPropertiesIT.java
SpringPropertiesIT - Update GH issue for DisabledOnNative
Original issue was fixed but further experiments revealed another issue (https://github.com/quarkusio/quarkus/issues/46341), thus updating the reason for disable.
> SpringPropertiesIT - Update GH issue for DisabledOnNative

- README.md
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/BookClient.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/json/Book.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/MetaResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/PlainBookResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/ReactiveClientBookResource.java
- http/rest-client-reactive/src/main/resources/application.properties
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientIT.java
- qute/reactive/pom.xml
- qute/reactive/src/main/java/io/quarkus/ts/qute/Application.java
- qute/reactive/src/main/java/io/quarkus/ts/qute/Client.java
- qute/reactive/src/main/java/io/quarkus/ts/qute/Proxy.java
- qute/reactive/src/main/resources/application.properties
- qute/reactive/src/test/java/io/quarkus/ts/qute/QuteReactiveIT.java
Required for QUARKUS-5615.
Changes are in Qute and RestClient modules
Test Plans: https://github.com/quarkus-qe/quarkus-test-plans/pull/195
> Verify, that reflection-free serialization doesn't break anything

- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/update/AbstractQuarkusCliUpdateIT.java
Error message was formatted wrong, add space to fix it.
> Add space to fix wrong message formatting

- qute/reactive/src/main/java/io/quarkus/ts/qute/Application.java
- qute/reactive/src/main/java/io/quarkus/ts/qute/JsonReflection.java
- qute/reactive/src/test/java/io/quarkus/ts/qute/QuteReactiveIT.java
Workaround for this issue: https://github.com/quarkusio/quarkus/issues/46508
Follow-up to https://github.com/quarkus-qe/quarkus-test-suite/pull/2315
> Fix native test in Qute

- README.md
- http/graphql-client/pom.xml
- http/graphql-client/src/main/java/io/quarkus/ts/http/graphql/DateEndpoint.java
- http/graphql-client/src/main/java/io/quarkus/ts/http/graphql/client/ClientEndpoint.java
- http/graphql-client/src/main/java/io/quarkus/ts/http/graphql/client/GraphQLClient.java
- http/graphql-client/src/main/resources/application.properties
- http/graphql-client/src/test/java/io/quarkus/ts/http/graphql/SeparateDependenciesIT.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/MetaClient.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/MetaClientResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/MetaResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/PlainBookResource.java
- http/rest-client-reactive/src/main/resources/modern.properties
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/LocalProxyIT.java
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientIT.java
- pom.xml
The issues:
- https://github.com/quarkusio/quarkus/pull/46413
- https://github.com/quarkusio/quarkus/pull/46530
- https://github.com/quarkusio/quarkus/pull/45161
> Cover three fixes, which were backported to 3.15

- javaee-like-getting-started/src/test/java/io/quarkus/ts/javaee/gettingstarted/OpenAPITracingIT.java
- security/webauthn/src/main/resources/application.properties
Since https://github.com/quarkusio/quarkus/issues/46889 will not be fixed, I prepared a PR, which adapts our TS to breaking changes in it
> Adapt to changes in Quarkus 3.15.4

- README.md
- http/graphql-client/pom.xml
- http/graphql-client/src/main/java/io/quarkus/ts/http/graphql/DateEndpoint.java
- http/graphql-client/src/main/java/io/quarkus/ts/http/graphql/client/ClientEndpoint.java
- http/graphql-client/src/main/java/io/quarkus/ts/http/graphql/client/GraphQLClient.java
- http/graphql-client/src/main/resources/application.properties
- http/graphql-client/src/test/java/io/quarkus/ts/http/graphql/SeparateDependenciesIT.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/MetaClient.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/MetaClientResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/MetaResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/PlainBookResource.java
- http/rest-client-reactive/src/main/resources/modern.properties
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/LocalProxyIT.java
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/ReactiveRestClientIT.java
- monitoring/opentelemetry-reactive/src/test/java/io/quarkus/ts/opentelemetry/reactive/MetricsIT.java
- monitoring/opentelemetry-reactive/src/test/java/io/quarkus/ts/opentelemetry/reactive/OpentelemetryReactiveIT.java
- pom.xml
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliTlsCommandIT.java
- sql-db/vertx-sql/src/test/java/io/quarkus/ts/vertx/sql/handlers/MssqlHandlerIT.java
Backports the following PRs
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2297
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2318
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2333
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2286 (this was not marked to for backporting, but fixes CI failure)
> [3.15] Backports with coverage for backported fixes

- pom.xml
TSIA; this should fix couple of issues with Strimzi, registry etc.
> [3.15] Bump Quarkus QE Test Framework from 1.5.10 to 1.5.11

- .github/pull_request_template.md
* Adding a checkbox advertising new option to run arm with OCP tests.
> Update template for arm tests

- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/fault/tolerance/RequestIdClientRequestFilter.java
Backport of https://github.com/quarkus-qe/quarkus-test-suite/pull/2350
> [3.15] Verify, that @Retry on failing RestClient is not executed in root context

- .github/workflows/ci.yml
- .github/workflows/daily.yaml
Use shorter names in GitHub Actions
Goal: to have a better overview in the left panel on the Actions page
New naming
```
Linux JVM
Linux Native
Windows JVM
Windows Native
Linux AArch64 JVM
Linux AArch64 Native
```
> Use shorter names in GitHub Actions

- .github/workflows/ci.yml
Use short name for PR GH Action
To be in sync with https://github.com/quarkus-qe/quarkus-test-framework/blob/main/.github/workflows/pr.yaml#L1 and to have more details about the executed modules combination in `Actions` view and on PR
> Use short name for PR GH Action

- sql-db/sql-app-compatibility/pom.xml
backports https://github.com/quarkus-qe/quarkus-test-suite/pull/2392
> [3.20] Fix Sql app native failures in FIPS-enabled env

- security/basic/src/main/java/io/quarkus/ts/openshift/security/basic/CustomPolicyResource.java
- security/basic/src/main/java/io/quarkus/ts/openshift/security/policy/NameContainsB.java
- security/basic/src/main/java/io/quarkus/ts/openshift/security/policy/NameStartsWithA.java
- security/basic/src/main/resources/application.properties
- security/basic/src/test/java/io/quarkus/ts/openshift/security/basic/BasicSecurityIT.java
Test plan:
https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-5620.md
> Coverage for @AuthorizationPolicy

- security/basic/src/main/java/io/quarkus/ts/openshift/security/basic/CustomPolicyResource.java
- security/basic/src/main/java/io/quarkus/ts/openshift/security/policy/NameContainsB.java
- security/basic/src/main/java/io/quarkus/ts/openshift/security/policy/NameStartsWithA.java
- security/basic/src/main/resources/application.properties
- security/basic/src/test/java/io/quarkus/ts/openshift/security/basic/BasicSecurityIT.java
- security/keycloak-oidc-client-reactive-extended/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/permissionChecker/PermissionCheckerResource.java
- security/keycloak-oidc-client-reactive-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/reactive/extended/OidcRestClientIT.java
- security/keycloak/pom.xml
- security/keycloak/src/test/java/io/quarkus/ts/security/keycloak/MultiMechanismAuthenticationIT.java
- security/keycloak/src/test/java/io/quarkus/ts/security/keycloak/OpenShiftMultiMechanismAuthenticationIT.java
- security/keycloak/src/test/resources/multi-mechanism.properties
Backports:
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2398
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2396
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2394
> [3.20] Backports as April 16th

- pom.xml
- security/jpa/src/test/java/io/quarkus/ts/security/jpa/MariaDbMd5JpaIT.java
- spring/spring-web-reactive/src/test/java/io/quarkus/ts/spring/web/reactive/MariaDBConstants.java
- spring/spring-web-reactive/src/test/java/io/quarkus/ts/spring/web/reactive/bootstrap/SpringWebQuteReactiveIT.java
- spring/spring-web-reactive/src/test/java/io/quarkus/ts/spring/web/reactive/bootstrap/SpringWebRestReactiveIT.java
- spring/spring-web-reactive/src/test/java/io/quarkus/ts/spring/web/reactive/openapi/SpringWebOpenApiReactiveIT.java
- spring/spring-web/src/test/java/io/quarkus/ts/spring/web/MariaDBConstants.java
- spring/spring-web/src/test/java/io/quarkus/ts/spring/web/bootstrap/OpenShiftSpringWebQuteIT.java
- spring/spring-web/src/test/java/io/quarkus/ts/spring/web/bootstrap/OpenShiftSpringWebRestIT.java
- spring/spring-web/src/test/java/io/quarkus/ts/spring/web/bootstrap/SpringWebQuteIT.java
- spring/spring-web/src/test/java/io/quarkus/ts/spring/web/bootstrap/SpringWebRestIT.java
- spring/spring-web/src/test/java/io/quarkus/ts/spring/web/openapi/OpenShiftSpringWebOpenApiIT.java
- spring/spring-web/src/test/java/io/quarkus/ts/spring/web/openapi/SpringWebOpenApiIT.java
- sql-db/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/MariaDbDatabaseHibernateReactiveIT.java
- sql-db/multiple-pus/src/test/java/io/quarkus/ts/sqldb/multiplepus/MultiplePersistenceIT.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/MariaDbTransactionGeneralUsageIT.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/OpenShiftMariaDbTransactionGeneralUsageIT.java
- sql-db/reactive-rest-data-panache/src/test/java/io/quarkus/ts/reactive/rest/data/panache/MariaDBPanacheResourceIT.java
- sql-db/reactive-rest-data-panache/src/test/java/io/quarkus/ts/reactive/rest/data/panache/OpenShiftMariaDBPanacheResourceIT.java
- sql-db/sql-app-compatibility/src/test/java/io/quarkus/ts/sqldb/compatibility/MariaDBDatabaseIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMariadbDevServicesUserExperienceIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/MariaDBDatabaseIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/OpenShiftMariaDBDatabaseIT.java
As requested https://issues.redhat.com/browse/QUARKUS-5471, TP https://github.com/quarkus-qe/quarkus-test-plans/pull/221.
> Switch tests from MariaDB 10.11 to 11.4

- websockets/websocket-next/src/test/java/io/quarkus/ts/websockets/next/WebSocketsNextMetricsIT.java
* Adding waits for messages to actually appear through websockets before checking the metrics for them.
> WS.next + metrics stabilization

- pom.xml
- security/jpa/src/test/java/io/quarkus/ts/security/jpa/MariaDbMd5JpaIT.java
- spring/spring-web-reactive/src/test/java/io/quarkus/ts/spring/web/reactive/MariaDBConstants.java
- spring/spring-web-reactive/src/test/java/io/quarkus/ts/spring/web/reactive/bootstrap/SpringWebQuteReactiveIT.java
- spring/spring-web-reactive/src/test/java/io/quarkus/ts/spring/web/reactive/bootstrap/SpringWebRestReactiveIT.java
- spring/spring-web-reactive/src/test/java/io/quarkus/ts/spring/web/reactive/openapi/SpringWebOpenApiReactiveIT.java
- spring/spring-web/src/test/java/io/quarkus/ts/spring/web/MariaDBConstants.java
- spring/spring-web/src/test/java/io/quarkus/ts/spring/web/bootstrap/SpringWebQuteIT.java
- spring/spring-web/src/test/java/io/quarkus/ts/spring/web/bootstrap/SpringWebRestIT.java
- spring/spring-web/src/test/java/io/quarkus/ts/spring/web/openapi/SpringWebOpenApiIT.java
- sql-db/multiple-pus/src/test/java/io/quarkus/ts/sqldb/multiplepus/CustomDatasourceProducerIT.java
- sql-db/multiple-pus/src/test/java/io/quarkus/ts/sqldb/multiplepus/MultiDatabaseActiveInactiveIT.java
- sql-db/multiple-pus/src/test/java/io/quarkus/ts/sqldb/multiplepus/MultiplePersistenceIT.java
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/MariaDbTransactionGeneralUsageIT.java
- sql-db/reactive-rest-data-panache/src/test/java/io/quarkus/ts/reactive/rest/data/panache/MariaDBPanacheResourceIT.java
- sql-db/sql-app-compatibility/src/test/java/io/quarkus/ts/sqldb/compatibility/MariaDBDatabaseIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/MariaDBDatabaseIT.java
- websockets/websocket-next/pom.xml
- websockets/websocket-next/src/test/java/io/quarkus/ts/websockets/next/BaseWebSocketIT.java
- websockets/websocket-next/src/test/java/io/quarkus/ts/websockets/next/Client.java
- websockets/websocket-next/src/test/java/io/quarkus/ts/websockets/next/OpenShiftWebSocketsNextOpenTelemetryIT.java
- websockets/websocket-next/src/test/java/io/quarkus/ts/websockets/next/WebSocketsNextMetricsIT.java
- websockets/websocket-next/src/test/java/io/quarkus/ts/websockets/next/WebSocketsNextOpenTelemetryIT.java
Backports:
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2426
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2427
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2412
> [3.20] Backports as of April 24

- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/BookClient.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/json/Author.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/PlainBookResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/resources/ReactiveClientBookResource.java
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/DevModeIT.java
https://issues.redhat.com/browse/QUARKUS-5616
> Verify, that Boolean can be used for reflection-free serialization

- lifecycle-application/pom.xml
This dependency version is provided by the latest RHBQ 3.20.0 platform release.
> Update Spring Core API

- sql-db/hibernate/pom.xml
- sql-db/hibernate/src/main/java/io/quarkus/qe/hibernate/items/JsonEntity.java
- sql-db/hibernate/src/main/java/io/quarkus/qe/hibernate/items/JsonEntityResource.java
- sql-db/hibernate/src/test/java/io/quarkus/qe/hibernate/BaseHibernateIT.java
- sql-db/hibernate/src/test/java/io/quarkus/qe/hibernate/DevModeHibernateIT.java
- sql-db/hibernate/src/test/java/io/quarkus/qe/hibernate/ProdHibernateIT.java
This PR adds test coverage for the fix implemented in PR  [46940](https://github.com/quarkusio/quarkus/pull/46940 ), which addresses issue #[43105](https://github.com/quarkusio/quarkus/discussions/43105) and #[43102](https://github.com/quarkusio/quarkus/discussions/43102 ). 
Original issue: https://github.com/quarkusio/quarkus/discussions/43102 
Upstream Fix: https://github.com/quarkusio/quarkus/pull/46940 
> TD Coverage for the fix ObjectMapper unremovable fix in Hibernate ORM #46940

- security/keycloak-multitenant/src/main/java/io/quarkus/ts/security/keycloak/multitenant/OidcTenantInitializer.java
- security/keycloak-multitenant/src/main/java/io/quarkus/ts/security/keycloak/multitenant/UserInfoResource.java
- security/keycloak-multitenant/src/test/java/io/quarkus/ts/security/keycloak/multitenant/AbstractStaticMultiTenantUserInfoIT.java
- security/keycloak-multitenant/src/test/java/io/quarkus/ts/security/keycloak/multitenant/KeycloakStaticMultiTenantUserInfoIT.java
- security/keycloak-multitenant/src/test/java/io/quarkus/ts/security/keycloak/multitenant/OpenShiftRhSsoStaticMultiTenantUserInfoIT.java
- security/keycloak-multitenant/src/test/resources/test-realm-realm.json
- security/keycloak-webapp/src/main/resources/empty.properties
- security/keycloak-webapp/src/test/java/io/quarkus/ts/security/keycloak/webapp/KeycloakStaticTenantWebappIT.java
- security/keycloak-webapp/src/test/java/io/quarkus/ts/security/keycloak/webapp/OidcTenantInitializer.java
TP: https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-5660.md
> Add test coverage for programmatic OIDC tenants configuration

- monitoring/opentelemetry/src/test/java/io/quarkus/ts/opentelemetry/OpenTelemetryProxyIT.java
The `OpenTelemetryProxyIT` keeps failing in GitHub daily builds steadily, but I can't reproduce it locally. The issue seems to be that Quarkus OTel gRPC client when trying to export traces communicates with a server using HTTP 1.1 instead of HTTP2. But at which point that happens (whether logged message comes from communication between Quarkus gRPC client and proxy or Quarkus gRPC client and something else or the proxy and Jaeger collector) is unclear. I will need more information to find a fix. This PR changes how proxy is created (making sure that when the server starts listening we have gRPC client ready and changes port where the proxy listens (in case there is something else listening on that port already). If that is not enough, we will at least know this wasn't the root cause. …
> Refactor OpenTelemetryProxyIT to gather more information about GitHub daily build failers and in theory, mitigate the failures

- pom.xml
Bump quarkus.ide.version  to 3.20.1
> Bump quarkus.ide.version  to 3.20.1

- .github/actions/use-docker-mirror/action.yml
- .github/workflows/ci.yml
- http/http-advanced-reactive/src/main/java/io/quarkus/ts/http/advanced/reactive/ResourcesFinderResource.java
- http/http-advanced-reactive/src/main/resources/application.properties
- http/http-advanced-reactive/src/main/resources/resource-finder-dir/resource_finder_dir.txt
- http/http-advanced-reactive/src/test/java/io/quarkus/ts/http/advanced/reactive/ResourceFinderIT.java
- monitoring/opentelemetry/src/test/java/io/quarkus/ts/opentelemetry/OpenTelemetryProxyIT.java
- pom.xml
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/QuarkusCliHelpIT.java
- quarkus-cli/src/test/java/io/quarkus/ts/quarkus/cli/update/QuarkusCli38to315UpdateIT.java
- sql-db/hibernate/src/main/java/io/quarkus/qe/hibernate/items/MyEntity.java
- sql-db/hibernate/src/main/java/io/quarkus/qe/hibernate/items/MyEntityId.java
- sql-db/hibernate/src/main/java/io/quarkus/qe/hibernate/items/MyEntityResource.java
- sql-db/hibernate/src/test/java/io/quarkus/qe/hibernate/BaseHibernateIT.java
- sql-db/narayana-transactions/src/main/java/io.quarkus.ts.transactions/ClientEntity.java
- sql-db/narayana-transactions/src/main/java/io.quarkus.ts.transactions/ClientResource.java
- sql-db/narayana-transactions/src/main/java/io.quarkus.ts.transactions/ClientService.java
- sql-db/narayana-transactions/src/main/resources/import.sql
- sql-db/narayana-transactions/src/test/java/io/quarkus/ts/transactions/TransactionCommons.java
- sql-db/narayana-transactions/src/test/resources/mariadb_import.sql
- sql-db/narayana-transactions/src/test/resources/mssql_import.sql
- sql-db/narayana-transactions/src/test/resources/mysql_import.sql
- sql-db/narayana-transactions/src/test/resources/oracle_import.sql
Bumps:
* Quarkus IDE to 3.15.5 (https://github.com/quarkus-qe/quarkus-test-suite/commit/1ad38413d7c86ebc16159f6f21439d36868f5974)
* QE FW to 1.5.12 (https://github.com/quarkus-qe/quarkus-test-suite/commit/90cc87626ea386dcbfed264378383e91a468250f)
Backports:
* https://github.com/quarkus-qe/quarkus-test-suite/pull/2462
* https://github.com/quarkus-qe/quarkus-test-suite/pull/2458
* https://github.com/quarkus-qe/quarkus-test-suite/pull/2370
* https://github.com/quarkus-qe/quarkus-test-suite/pull/2470
* https://github.com/quarkus-qe/quarkus-test-suite/pull/2302
* Done as I saw some docker hub timeouts/request limit reached
* https://github.com/quarkus-qe/quarkus-test-suite/pull/2466
* It seems that this also affected 3.15, even the old version have now same problem
Disable tests:
* …
> [3.15] Quarkus and FW bump + Backports 27.5.2025

- http/vertx/pom.xml
- http/vertx/src/main/java/io/quarkus/ts/vertx/ExternalHealthEndpoint.java
- http/vertx/src/main/java/io/quarkus/ts/vertx/InMemoryLogHandler.java
- http/vertx/src/main/java/io/quarkus/ts/vertx/InMemoryLogHandlerProducer.java
- http/vertx/src/main/java/io/quarkus/ts/vertx/MdcPropagationHealthCheck1.java
- http/vertx/src/main/java/io/quarkus/ts/vertx/MdcPropagationHealthCheck2.java
- http/vertx/src/main/java/io/quarkus/ts/vertx/MdcTestNativeConfiguration.java
- http/vertx/src/test/java/io/quarkus/ts/vertx/MdcContextPropagationIT.java
This test coverage verify the fix https://github.com/quarkusio/quarkus/pull/48057
Original issue: https://github.com/quarkusio/quarkus/discussions/47481
Test will fail with previous quarkus version, you can see executing:
` mvn clean verify -Dit.test=MdcContextPropagationIT -Dreruns=0 -Dquarkus.platform.version=3.19.3`
> Test coverage for the fix about correct duplicated context creation in SmallRye Health #48057 

- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMariadbComposeIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMysqlComposeIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModePostgresqlComposeIT.java
- sql-db/sql-app/src/test/resources/mariadb-compose-devservices.yml
- sql-db/sql-app/src/test/resources/mysql-compose-devservices.yml
- sql-db/sql-app/src/test/resources/postgresql-compose-devservices.yml
Compose Dev Services coverage for PostgreSQL, MariaDB, MySQL
First batch of the coverage for https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-6234.md#test-coverage to get initial feedback.
> Compose Dev Services coverage for PostgreSQL, MariaDB, MySQL

- README.md
- pom.xml
- security/jpa-reactive/pom.xml
- security/jpa-reactive/src/main/java/io/quarkus/ts/security/jpa/reactive/db/MyEntity.java
- security/jpa-reactive/src/main/java/io/quarkus/ts/security/jpa/reactive/db/TestRoleEntity.java
- security/jpa-reactive/src/main/java/io/quarkus/ts/security/jpa/reactive/db/TestUserEntity.java
- security/jpa-reactive/src/main/java/io/quarkus/ts/security/jpa/reactive/rest/CreateEntityRequestDto.java
- security/jpa-reactive/src/main/java/io/quarkus/ts/security/jpa/reactive/rest/CrudResource.java
- security/jpa-reactive/src/main/java/io/quarkus/ts/security/jpa/reactive/rest/UpdateEntityRequestDto.java
- security/jpa-reactive/src/main/java/io/quarkus/ts/security/jpa/reactive/security/HttpSecurityConfig.java
- security/jpa-reactive/src/main/resources/application.properties
- security/jpa-reactive/src/main/resources/import.sql
- security/jpa-reactive/src/test/java/io/quarkus/ts/security/jpa/reactive/AbstractSecurityJpaReactiveIT.java
- security/jpa-reactive/src/test/java/io/quarkus/ts/security/jpa/reactive/OpenShiftPostgreSqlSecurityJpaReactiveIT.java
- security/jpa-reactive/src/test/java/io/quarkus/ts/security/jpa/reactive/PostgreSqlSecurityJpaReactiveIT.java
- security/jpa-reactive/src/test/resources/test.properties
This PR implements test plan https://github.com/quarkus-qe/quarkus-test-plans/pull/245.
> Test Hibernate Reactive and Hibernate ORM used in one project

- security/keycloak/src/main/java/io/quarkus/ts/security/keycloak/OidcProviderClientResource.java
- security/keycloak/src/test/java/io/quarkus/ts/security/keycloak/BaseOidcSecurityIT.java
- security/keycloak/src/test/resources/test-realm-realm.json
Backports https://github.com/quarkus-qe/quarkus-test-suite/pull/2476
> [3.20] Backport - Test OIDC token revocation using OidcProviderClient

- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeMssqlComposeIT.java
- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeOracleComposeIT.java
- sql-db/sql-app/src/test/resources/mssql-compose-devservices.yml
- sql-db/sql-app/src/test/resources/oracle-compose-devservices.yml
Compose Dev Services for MS SQL and Oracle DB
> Compose Dev Services for MS SQL and Oracle DB

- sql-db/sql-app/src/test/java/io/quarkus/ts/sqldb/sqlapp/DevModeComposeLocationsIT.java
Different file naming check for Compose Dev Services
> Different file naming check for Compose Dev Services

- http/grpc/src/main/java/io/quarkus/ts/http/grpc/customizers/GrpcMetadataInterceptor.java
- http/grpc/src/main/java/io/quarkus/ts/http/grpc/customizers/GrpcServerCustomizer.java
- http/grpc/src/main/java/io/quarkus/ts/http/grpc/customizers/GrpcServerCustomizerHelper.java
- http/grpc/src/main/java/io/quarkus/ts/http/grpc/customizers/InterceptorInvocations.java
- http/grpc/src/main/java/io/quarkus/ts/http/grpc/customizers/LegacyGrpcServerCustomizer.java
- http/grpc/src/main/java/io/quarkus/ts/http/grpc/customizers/LegacyGrpcServerCustomizer2.java
- http/grpc/src/main/java/io/quarkus/ts/http/grpc/customizers/LegacyGrpcServerCustomizer3.java
- http/grpc/src/main/java/io/quarkus/ts/http/grpc/customizers/VertxGrpcServerCustomizer.java
- http/grpc/src/main/java/io/quarkus/ts/http/grpc/customizers/VertxGrpcServerCustomizer2.java
- http/grpc/src/main/java/io/quarkus/ts/http/grpc/customizers/VertxGrpcServerCustomizer3.java
- http/grpc/src/main/proto/metadata.proto
- http/grpc/src/test/java/io/quarkus/ts/http/grpc/GrpcMutualTlsSameServerIT.java
- http/grpc/src/test/java/io/quarkus/ts/http/grpc/GrpcSameServerCustomizationIT.java
- http/grpc/src/test/java/io/quarkus/ts/http/grpc/GrpcTlsSameServerIT.java
- http/grpc/src/test/java/io/quarkus/ts/http/grpc/OpenShiftExtensionGRPCIT.java
- http/grpc/src/test/java/io/quarkus/ts/http/grpc/OpenShiftGRPCIT.java
- http/grpc/src/test/java/io/quarkus/ts/http/grpc/SameServerIT.java
- http/grpc/src/test/java/io/quarkus/ts/http/grpc/SeparateServerIT.java
Implements https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-6246.MD. Renamed some incorrectly named tests.
> Test gRPC server customization options

- pom.xml
* Moving MariaDB to 11.8
* Moving MongoDB to 8
> Updating database containers for Quarkus 3.27 LTS

- http/http-advanced/src/main/resources/keycloakless.properties
- http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/DevModeWorkspaceIT.java
> Add coverage for Dev UI Workspace

- security/keycloak-oidc-client-extended/pom.xml
- security/keycloak-oidc-client-extended/src/main/resources/application.properties
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/AbstractHealthCheckIT.java
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/AbstractMultiTenantHealthCheckIT.java
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/AbstractOidcHealthCheckErrorStatusIT.java
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/MultiTenantHealthCheckIT.java
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/OidcHealthCheckErrorStatusIT.java
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/OidcHealthCheckIT.java
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/OpenShiftMultiTenantHealthCheckIT.java
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/OpenShiftOidcHealthCheckErrorStatusIT.java
- security/keycloak-oidc-client-extended/src/test/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/OpenShiftOidcHealthCheckIT.java
- security/keycloak-oidc-client-extended/src/test/resources/health-enabled.properties
- security/keycloak-oidc-client-extended/src/test/resources/health-management.properties
Implement test for OIDC Health Checks according to the test plan https://github.com/quarkus-qe/quarkus-test-plans/pull/254
JIRA: https://issues.redhat.com/browse/QUARKUS-6263
Upstream PR: https://github.com/quarkusio/quarkus/pull/47830
Extension/feature community status: supported
> Add test coverage for QUARKUS-6263 OIDC Health Checks

- messaging/kafka-confluent-avro-reactive-messaging/pom.xml
- messaging/kafka-confluent-avro-reactive-messaging/src/main/resources/application.properties
- messaging/kafka-confluent-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/ConfluentKafkaAvroGroupIdIT.java
- messaging/kafka-confluent-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/ConfluentKafkaAvroIT.java
- messaging/kafka-confluent-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/ConfluentKafkaRestClientTimeoutIT.java
- messaging/kafka-confluent-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/restclient/SignalRestResource.java
- messaging/kafka-confluent-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/restclient/UppercaseRestClient.java
- messaging/kafka-confluent-avro-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/restclient/UppercaseRestResource.java
Backports https://github.com/quarkus-qe/quarkus-test-suite/pull/2633
> [3.20] Add reproducer for #48983: Kafka consumer hangs on REST client call

- hibernate/hibernate-reactive/src/main/java/io/quarkus/ts/hibernate/reactive/database/XmlValidatedCustomer.java
- hibernate/hibernate-reactive/src/main/java/io/quarkus/ts/hibernate/reactive/http/ValidationResource.java
- hibernate/hibernate-reactive/src/main/resources/META-INF/validation.xml
- hibernate/hibernate-reactive/src/main/resources/META-INF/validation/constraints-customer.xml
- hibernate/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/AbstractHibernateValidatorIT.java
- hibernate/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/MultiDatabaseHibernateReactiveIT.java
- hibernate/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/MySQLHibernateValidatorDisabledIT.java
- hibernate/hibernate-reactive/src/test/java/io/quarkus/ts/hibernate/reactive/OracleHibernateValidatorDdlModeIT.java
- http/rest-client-reactive/pom.xml
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/validation/UserProcessingService.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/validation/UserProcessingServiceBean.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/validation/UserValidationResource.java
- http/rest-client-reactive/src/main/java/io/quarkus/ts/http/restclient/reactive/validation/ValidatedUser.java
- http/rest-client-reactive/src/main/resources/application.properties
- http/rest-client-reactive/src/test/java/io/quarkus/ts/http/restclient/reactive/UserProcessingValidationIT.java
Test coverage for acoording to [Test Plan](https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-6262.MD)
> Add coverage of QUARKUS-6262 - XML constraints and method overriding

- pom.xml
Backport of:
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2644
> [3.27] Ensure annotation processor respect depmgmt 

- build-time-analytics/src/test/java/io/quarkus/ts/buildtimeanalytics/AnalyticsUtils.java
- pom.xml
- super-size/many-extensions/pom.xml
Reverting the https://github.com/quarkus-qe/quarkus-test-suite/pull/2658 as it was fixed
> Enable tests which were disabled due to quarkus#50247

- properties/src/test/java/io/quarkus/ts/properties/consul/OpenShiftConsulConfigSourceIT.java
* See https://github.com/hashicorp/consul/issues/21762
> Disabling Consul on OCP tests due to bug in container

- hibernate/hibernate-orm/src/main/java/io/quarkus/qe/hibernate/hql/Address.java
- hibernate/hibernate-orm/src/main/java/io/quarkus/qe/hibernate/hql/DevUIJsonRpcClient.java
- hibernate/hibernate-orm/src/main/java/io/quarkus/qe/hibernate/hql/HQLConsoleClient.java
- hibernate/hibernate-orm/src/main/java/io/quarkus/qe/hibernate/hql/OrderItem.java
- hibernate/hibernate-orm/src/main/java/io/quarkus/qe/hibernate/hql/Orders.java
- hibernate/hibernate-orm/src/main/resources/application.properties
- hibernate/hibernate-orm/src/main/resources/test-hql-pu-import-script.sql
- hibernate/hibernate-orm/src/test/java/io/quarkus/qe/hibernate/AbstractHQLConsoleIT.java
- hibernate/hibernate-orm/src/test/java/io/quarkus/qe/hibernate/DevModeMySQLHQLConsoleIT.java
- hibernate/hibernate-orm/src/test/java/io/quarkus/qe/hibernate/DevModePostgresqlHQLConsoleIT.java
- hibernate/hibernate-orm/src/test/resources/mysql.properties
Test HQL in Quarkus dev mode according to the [test plan](https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-6243.md)
> Coverage for QUARKUS-6243 - execute HQL queries using DevUI

- cache/redis/src/main/java/io/quarkus/ts/cache/redis/TemplateCacheResource.java
- Fixes https://issues.redhat.com/browse/QQE-1870
> Test should handle `TemplateException` instead of `IllegalStateException`

- cache/infinispan/pom.xml
- cache/infinispan/src/main/java/io/quarkus/ts/cache/infinispan/BaseServiceWithCache.java
- cache/infinispan/src/main/java/io/quarkus/ts/cache/infinispan/cdi/request/context/CdiRequestContextResource.java
- cache/infinispan/src/main/java/io/quarkus/ts/cache/infinispan/cdi/request/context/CdiRequestContextResponse.java
- cache/infinispan/src/main/java/io/quarkus/ts/cache/infinispan/cdi/request/context/CdiRequestContextResponseFilter.java
- cache/infinispan/src/main/java/io/quarkus/ts/cache/infinispan/cdi/request/context/InterceptedRequestContextResponse.java
- cache/infinispan/src/main/java/io/quarkus/ts/cache/infinispan/cdi/request/context/RequestContextState.java
- cache/infinispan/src/test/java/io/quarkus/ts/cache/infinispan/InfinispanCacheIT.java
backports https://github.com/quarkus-qe/quarkus-test-suite/pull/2614
> [3.20] Test Infinispan cache CDI request ctx propagation
